import { describe, expect, it } from "vitest";

import {
  attachVerifiedFixtureSnapshots,
  candidateKey,
  findEquivalentCandidate,
  requireCandidateSnapshot,
  restoreStudioCandidates,
  type Candidate,
} from "./studio-candidates.js";
import {
  candidateIdentityKey,
  generatedCandidateIdentity,
  processedCandidateIdentity,
  uploadedCandidateIdentity,
} from "./candidate-identity.js";
import { candidateIdentityMatchesAsset } from "./studio-store-validation.js";
import type { StudioAsset } from "./studio-store.js";

const FIXTURE_HASH = "a".repeat(64);
const SECOND_HASH = "c".repeat(64);

const fixtureCandidate: Candidate = {
  id: "candidate-literal",
  label: "Valley witness",
  direction: "Literal landscape",
  sourceUrl: "/fixture.webp",
  hash: FIXTURE_HASH,
  origin: "generated",
  provenance: "generated",
  identity: generatedCandidateIdentity(FIXTURE_HASH, "candidate-literal"),
};
const secondFixture: Candidate = {
  ...fixtureCandidate,
  id: "candidate-symbolic",
  hash: SECOND_HASH,
  identity: generatedCandidateIdentity(SECOND_HASH, "candidate-symbolic"),
};

describe("Studio candidate source snapshots", () => {
  it("attaches and returns the verified Blob instead of consulting the display URL again", () => {
    const verifiedBlob = new Blob(["reviewed bytes"], { type: "image/webp" });
    const [candidate] = attachVerifiedFixtureSnapshots(
      [fixtureCandidate],
      [{ hash: fixtureCandidate.hash, blob: verifiedBlob }],
    );

    expect(candidate.blob).toBe(verifiedBlob);
    expect(requireCandidateSnapshot(candidate)).toBe(verifiedBlob);
  });

  it("fails closed when a selected candidate has no verified source snapshot", () => {
    expect(() => attachVerifiedFixtureSnapshots([fixtureCandidate], [])).toThrow(
      /candidate-literal.*verified source snapshot.*reload/i,
    );
    expect(() => requireCandidateSnapshot(fixtureCandidate)).toThrow(
      /candidate-literal.*verified source snapshot.*reload/i,
    );
  });

  it("does not collapse byte-identical candidates with different provenance", () => {
    const uploadIdentity = uploadedCandidateIdentity(FIXTURE_HASH);

    expect(findEquivalentCandidate([fixtureCandidate], uploadIdentity)).toBeUndefined();
  });

  it("reuses repeated equivalent uploads and treatments", async () => {
    const uploadIdentity = uploadedCandidateIdentity(FIXTURE_HASH);
    const uploadCandidate: Candidate = {
      ...fixtureCandidate,
      id: "upload-pinned-hash",
      origin: "uploaded",
      provenance: "uploaded",
      identity: uploadIdentity,
    };
    const treatmentIdentity = await processedCandidateIdentity(
      FIXTURE_HASH,
      "uploaded",
      uploadIdentity,
      "warm-mineral-treatment-v1",
    );
    const treatmentCandidate: Candidate = {
      ...uploadCandidate,
      id: "processed-pinned-hash",
      origin: "processed",
      identity: treatmentIdentity,
    };

    expect(findEquivalentCandidate([uploadCandidate], uploadedCandidateIdentity(FIXTURE_HASH))).toBe(
      uploadCandidate,
    );
    expect(findEquivalentCandidate([treatmentCandidate], treatmentIdentity)).toBe(treatmentCandidate);
  });

  it("restores an uploaded selection separately from generated bytes with the same hash", () => {
    const blob = new Blob(["same reviewed bytes"], { type: "image/webp" });
    const verifiedFixture = { ...fixtureCandidate, blob };
    const asset: StudioAsset = {
      schemaVersion: 1,
      kind: "original",
      hash: FIXTURE_HASH,
      blob,
      mimeType: "image/webp",
      byteLength: blob.size,
      createdAt: "2026-08-23T18:00:00.000Z",
    };
    const uploadedIdentity = uploadedCandidateIdentity(FIXTURE_HASH);
    const restored = restoreStudioCandidates({
      fixtureCandidates: [verifiedFixture],
      assets: [asset],
      selectedIdentity: uploadedIdentity,
      legacySelectedHash: FIXTURE_HASH,
      createSourceUrl: () => "blob:restored-upload",
    });

    expect(restored.candidates).toHaveLength(2);
    expect(new Set(restored.candidates.map(candidateKey)).size).toBe(2);
    expect(restored.selectedKey).toBe(candidateIdentityKey(uploadedIdentity));
    expect(
      restored.candidates.find((candidate) => candidateKey(candidate) === restored.selectedKey),
    ).toMatchObject({ provenance: "uploaded", origin: "uploaded" });
  });

  it("does not guess provenance for a legacy derivative rooted in fixture bytes", () => {
    const fixtureBlob = new Blob(["fixture"], { type: "image/webp" });
    const derivativeBlob = new Blob(["derivative"], { type: "image/png" });
    const derivativeHash = "b".repeat(64);
    const assets: StudioAsset[] = [
      {
        schemaVersion: 1,
        kind: "original",
        hash: FIXTURE_HASH,
        blob: fixtureBlob,
        mimeType: "image/webp",
        byteLength: fixtureBlob.size,
        createdAt: "2026-08-23T18:00:00.000Z",
      },
      {
        schemaVersion: 1,
        kind: "derivative",
        hash: derivativeHash,
        parentHash: FIXTURE_HASH,
        operation: "warm-mineral-treatment-v1",
        blob: derivativeBlob,
        mimeType: "image/png",
        byteLength: derivativeBlob.size,
        createdAt: "2026-08-23T18:00:00.000Z",
      },
    ];
    const restored = restoreStudioCandidates({
      fixtureCandidates: [{ ...fixtureCandidate, blob: fixtureBlob }],
      assets,
      selectedIdentity: null,
      legacySelectedHash: derivativeHash,
      createSourceUrl: () => "blob:should-not-be-created",
    });

    expect(restored.candidates).toHaveLength(1);
    expect(restored.selectedKey).toBeNull();
    expect(restored.selectionWarning).toMatch(/provenance.*not.*guess/i);
  });

  it("never relabels or selects a version-1 derivative from an operation-shaped identity", () => {
    const derivativeBlob = new Blob(["derivative"], { type: "image/png" });
    const derivativeHash = "b".repeat(64);
    const derivative: StudioAsset = {
      schemaVersion: 1,
      kind: "derivative",
      hash: derivativeHash,
      parentHash: FIXTURE_HASH,
      operation: "warm-mineral-treatment-v1",
      blob: derivativeBlob,
      mimeType: "image/png",
      byteLength: derivativeBlob.size,
      createdAt: "2026-08-23T18:00:00.000Z",
    };
    const relabeledIdentity = {
      version: 1 as const,
      hash: derivativeHash,
      provenance: "uploaded" as const,
      origin: "processed" as const,
      lineage: `processed:warm-mineral-treatment-v1:parent=${candidateIdentityKey(uploadedCandidateIdentity(FIXTURE_HASH))}`,
    };

    expect(candidateIdentityMatchesAsset(derivative, relabeledIdentity)).toBe(false);
    const restored = restoreStudioCandidates({
      fixtureCandidates: [fixtureCandidate],
      assets: [derivative],
      selectedIdentity: relabeledIdentity,
      legacySelectedHash: derivativeHash,
      createSourceUrl: () => "blob:must-not-be-created",
    });
    expect(restored.selectedKey).toBeNull();
    expect(restored.candidates.some((candidate) => candidate.hash === derivativeHash)).toBe(false);
    expect(restored.selectionWarning).toMatch(/cannot be selected, processed, or published/i);
  });

  it("keeps an unselected ambiguous version-1 derivative preserved but out of candidates", () => {
    const fixtureBlob = new Blob(["fixture"], { type: "image/webp" });
    const derivativeBlob = new Blob(["derivative"], { type: "image/png" });
    const derivativeHash = "b".repeat(64);
    const assets: StudioAsset[] = [
      {
        schemaVersion: 1,
        kind: "original",
        hash: FIXTURE_HASH,
        blob: fixtureBlob,
        mimeType: "image/webp",
        byteLength: fixtureBlob.size,
        createdAt: "2026-08-23T18:00:00.000Z",
      },
      {
        schemaVersion: 1,
        kind: "derivative",
        hash: derivativeHash,
        parentHash: FIXTURE_HASH,
        operation: "warm-mineral-treatment-v1",
        blob: derivativeBlob,
        mimeType: "image/png",
        byteLength: derivativeBlob.size,
        createdAt: "2026-08-23T18:00:00.000Z",
      },
    ];
    const restored = restoreStudioCandidates({
      fixtureCandidates: [fixtureCandidate, secondFixture],
      assets,
      selectedIdentity: secondFixture.identity,
      legacySelectedHash: SECOND_HASH,
      createSourceUrl: () => "blob:should-not-be-created",
    });

    expect(restored.selectedKey).toBe(candidateKey(secondFixture));
    expect(restored.candidates).toHaveLength(2);
    expect(restored.candidates.some((candidate) => candidate.hash === derivativeHash)).toBe(false);
    expect(restored.selectionWarning).toMatch(/older.*provenance.*not added/i);
  });

  it("restores an unselected derivative from its persisted exact lineage", async () => {
    const derivativeHash = "d".repeat(64);
    const fixtureBlob = new Blob(["fixture"], { type: "image/webp" });
    const derivativeBlob = new Blob(["derivative"], { type: "image/png" });
    const derivativeIdentity = await processedCandidateIdentity(
      derivativeHash,
      "generated",
      fixtureCandidate.identity,
      "warm-mineral-treatment-v1",
    );
    const assets: StudioAsset[] = [
      {
        schemaVersion: 2,
        kind: "original",
        hash: FIXTURE_HASH,
        blob: fixtureBlob,
        mimeType: "image/webp",
        byteLength: fixtureBlob.size,
        createdAt: "2026-08-23T18:00:00.000Z",
        candidateIdentities: [fixtureCandidate.identity],
      },
      {
        schemaVersion: 2,
        kind: "derivative",
        hash: derivativeHash,
        candidateLineages: [
          {
            parentHash: FIXTURE_HASH,
            operation: "warm-mineral-treatment-v1",
            parentCandidateIdentity: fixtureCandidate.identity,
            candidateIdentity: derivativeIdentity,
          },
        ],
        blob: derivativeBlob,
        mimeType: "image/png",
        byteLength: derivativeBlob.size,
        createdAt: "2026-08-23T18:00:00.000Z",
      },
    ];

    const restored = restoreStudioCandidates({
      fixtureCandidates: [
        { ...fixtureCandidate, blob: fixtureBlob },
        { ...secondFixture, blob: fixtureBlob },
      ],
      assets,
      selectedIdentity: secondFixture.identity,
      legacySelectedHash: SECOND_HASH,
      createSourceUrl: () => "blob:restored-derivative",
    });

    expect(restored.selectedKey).toBe(candidateKey(secondFixture));
    expect(findEquivalentCandidate(restored.candidates, derivativeIdentity)).toMatchObject({
      origin: "processed",
      provenance: "generated",
    });
    expect(new Set(restored.candidates.map(candidateKey)).size).toBe(restored.candidates.length);
  });
});
