import type { BookSeed } from "./book-authoring-record";

export const literaryAndNonfictionBookSeeds = [
  {
    slug: "the-remains-of-the-day",
    bookTitle: "The Remains of the Day",
    author: "Kazuo Ishiguro",
    category: "literary-fiction",
    forms: ["one long corridor", "a silver tray silhouette", "a garden-window glow"],
    relationship: "the tray remains precisely centered while the corridor recedes toward the fading garden",
    palette: ["smoke gray", "silver", "garden green", "late gold"],
    styles: ["aquatint-atmosphere", "monoprint-ink-wash", "wood-marquetry-landscape"],
  },
  {
    slug: "beloved",
    bookTitle: "Beloved",
    author: "Toni Morrison",
    category: "literary-fiction",
    forms: ["one open doorway", "a protective double silhouette", "one red ribbon"],
    relationship:
      "the joined silhouettes hold the threshold while the ribbon passes through memory and space",
    palette: ["ink black", "paper white", "deep red", "earth brown"],
    styles: ["monoprint-ink-wash", "woven-tapestry-field", "fresco-mineral-pigment"],
  },
  {
    slug: "the-road",
    bookTitle: "The Road",
    author: "Cormac McCarthy",
    category: "literary-fiction",
    forms: ["two large footprints", "one bare tree", "a pale horizon band"],
    relationship: "the footprints continue past the tree toward the only light on the horizon",
    palette: ["charcoal", "ash gray", "bone white", "faint amber"],
    styles: ["charcoal-pastel-weather", "scratchboard-nocturne", "aquatint-atmosphere"],
  },
  {
    slug: "a-gentleman-in-moscow",
    bookTitle: "A Gentleman in Moscow",
    author: "Amor Towles",
    category: "literary-fiction",
    forms: ["one tall hotel window", "a brass key", "a distant city band"],
    relationship: "the key rests inside the window frame while the city remains beyond it",
    palette: ["walnut", "maple cream", "brass", "winter blue"],
    styles: ["wood-marquetry-landscape", "aquatint-atmosphere", "matte-gouache-editorial"],
  },
  {
    slug: "the-kite-runner",
    bookTitle: "The Kite Runner",
    author: "Khaled Hosseini",
    category: "literary-fiction",
    forms: ["one red kite", "a broken curving string", "a single rooftop band"],
    relationship: "the kite pulls away from the rooftops as the severed string curls back",
    palette: ["sky blue", "pomegranate red", "sand", "deep brown"],
    styles: ["cut-paper-strata", "risograph-overprint", "luminous-ligne-claire"],
  },
  {
    slug: "pachinko",
    bookTitle: "Pachinko",
    author: "Min Jin Lee",
    category: "literary-fiction",
    forms: ["three ivory balls", "one bold brass peg arc", "an indigo basin"],
    relationship: "the three balls descend on different courses through the same arc into the shared basin",
    palette: ["porcelain white", "brass", "indigo", "persimmon"],
    styles: ["ceramic-underglaze", "mosaic-tesserae-field", "risograph-overprint"],
  },
  {
    slug: "thinking-fast-and-slow",
    bookTitle: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "modern-nonfiction",
    forms: ["one lightning path", "one meandering path", "a shared destination disk"],
    relationship: "the unequal paths begin apart and arrive at the same decision point",
    palette: ["deep navy", "electric yellow", "mineral teal", "warm white"],
    styles: ["prismatic-geometric-symbolism", "contour-atlas-ink", "monoprint-ink-wash"],
  },
  {
    slug: "atomic-habits",
    bookTitle: "Atomic Habits",
    author: "James Clear",
    category: "modern-nonfiction",
    forms: ["three ascending blocks", "one growing sun-seed", "a stable ground band"],
    relationship: "each block adds one measured step until the seed clears the horizon",
    palette: ["paper cream", "coral", "teal", "sun yellow"],
    styles: ["risograph-overprint", "cut-paper-strata", "pixel-cluster-landscape"],
  },
  {
    slug: "educated",
    bookTitle: "Educated",
    author: "Tara Westover",
    category: "modern-nonfiction",
    forms: ["one mountain ridge", "an open doorway", "a broad dawn band"],
    relationship: "the doorway opens away from the mountain interior into dawn",
    palette: ["mountain umber", "sky blue", "dawn peach", "snow white"],
    styles: ["plein-air-broken-color", "cyanotype-field-study", "charcoal-pastel-weather"],
  },
  {
    slug: "kitchen-confidential",
    bookTitle: "Kitchen Confidential",
    author: "Anthony Bourdain",
    category: "modern-nonfiction",
    forms: ["one chef's knife", "a swinging kitchen door", "a bold steam coil"],
    relationship: "the knife and steam cross before the door opens into the working room",
    palette: ["ink black", "paper cream", "tomato red", "steel gray"],
    styles: ["relief-blockprint", "ceramic-underglaze", "matte-gouache-editorial"],
  },
  {
    slug: "the-wager",
    bookTitle: "The Wager",
    author: "David Grann",
    category: "modern-nonfiction",
    forms: ["one broken ship hull", "a giant wave", "a compass star"],
    relationship: "the wave overtakes the hull while the star remains fixed above the wreck",
    palette: ["storm black", "sea green", "foam white", "restrained brass"],
    styles: ["aquatint-atmosphere", "relief-blockprint", "charcoal-pastel-weather"],
  },
  {
    slug: "the-anthropocene-reviewed",
    bookTitle: "The Anthropocene Reviewed",
    author: "John Green",
    category: "modern-nonfiction",
    forms: ["one Earth disk", "a branching flower", "a warm hand silhouette"],
    relationship: "the hand steadies the Earth while the flower crosses from human space into the blue field",
    palette: ["transparent blue", "leaf green", "warm ochre", "coral"],
    styles: ["watercolor-naturalist-study", "cyanotype-field-study", "fresco-mineral-pigment"],
  },
] as const satisfies readonly BookSeed[];
