import type { BookSeed } from "./book-authoring-record";

export const classicAndHistoryBookSeeds = [
  {
    slug: "nineteen-eighty-four",
    bookTitle: "1984",
    author: "George Orwell",
    category: "classic",
    forms: ["one observing aperture", "a lone doorway", "two red light beams"],
    relationship: "the doorway stands beneath the aperture while the paired beams divide the dark field",
    palette: ["charcoal black", "paper cream", "warning red"],
    styles: ["screenprint-night", "aquatint-atmosphere", "prismatic-geometric-symbolism"],
  },
  {
    slug: "to-kill-a-mockingbird",
    bookTitle: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "classic",
    forms: ["a broad oak branch", "one white feather", "a courthouse-step wedge"],
    relationship: "the feather settles between the sheltering branch and the severe ascending steps",
    palette: ["warm paper", "oak brown", "soft white", "deep courthouse gray"],
    styles: ["watercolor-naturalist-study", "ceramic-underglaze", "relief-blockprint"],
  },
  {
    slug: "the-great-gatsby",
    bookTitle: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "classic",
    forms: ["one green harbor light", "a black water arc", "a distant gold skyline"],
    relationship: "the unreachable green light glows across the water from the compressed skyline",
    palette: ["midnight blue", "harbor green", "antique gold", "black"],
    styles: ["stained-glass-field", "screenprint-night", "risograph-overprint"],
  },
  {
    slug: "pride-and-prejudice",
    bookTitle: "Pride and Prejudice",
    author: "Jane Austen",
    category: "classic",
    forms: ["two facing profiles", "one winding garden path", "paired hedge masses"],
    relationship: "the profiles remain apart while the path curves between their contrasting hedges",
    palette: ["parchment", "garden green", "mulberry", "ink brown"],
    styles: ["cut-paper-strata", "watercolor-naturalist-study", "wood-marquetry-landscape"],
  },
  {
    slug: "the-count-of-monte-cristo",
    bookTitle: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    category: "classic",
    forms: ["a dark island silhouette", "one oversized key", "a broken chain arc"],
    relationship: "the key rises from the island as the chain opens around it",
    palette: ["sea blue", "volcanic black", "aged brass", "foam white"],
    styles: ["mosaic-tesserae-field", "relief-blockprint", "aquatint-atmosphere"],
  },
  {
    slug: "the-odyssey",
    bookTitle: "The Odyssey",
    author: "Homer",
    category: "classic",
    forms: ["one black sail", "a single spiral wave", "one homeward star"],
    relationship: "the sail climbs the spiral wave toward the fixed star",
    palette: ["Aegean blue", "ink black", "sun-baked ochre", "star white"],
    styles: ["relief-blockprint", "mineral-line-engraving", "luminous-ligne-claire"],
  },
  {
    slug: "the-brothers-karamazov",
    bookTitle: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    category: "classic",
    forms: ["one four-branched path", "a dark dome", "a dawn disk"],
    relationship: "the divided path converges beneath the dome before opening toward dawn",
    palette: ["plaster white", "earth umber", "oxblood", "dawn gold"],
    styles: ["fresco-mineral-pigment", "monoprint-ink-wash", "aquatint-atmosphere"],
  },
  {
    slug: "guns-germs-and-steel",
    bookTitle: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    category: "history",
    forms: ["one grain stalk", "a circular cell form", "a spanning steel beam"],
    relationship: "the three forces meet without hierarchy at one geometric crossroads",
    palette: ["charcoal", "wheat gold", "oxidized teal", "steel gray"],
    styles: ["prismatic-geometric-symbolism", "relief-blockprint", "mosaic-tesserae-field"],
  },
  {
    slug: "the-dawn-of-everything",
    bookTitle: "The Dawn of Everything",
    author: "David Graeber and David Wengrow",
    category: "history",
    forms: ["one sunrise disk", "open earth strata", "a communal ring"],
    relationship: "the ring rests within exposed strata as sunrise widens the field above",
    palette: ["lime plaster", "clay red", "soil brown", "dawn yellow"],
    styles: ["fresco-mineral-pigment", "cut-paper-strata", "woven-tapestry-field"],
  },
  {
    slug: "the-silk-roads",
    bookTitle: "The Silk Roads",
    author: "Peter Frankopan",
    category: "history",
    forms: ["one continuous route band", "a mountain arch", "a broad sea arc"],
    relationship: "the route crosses the mountain opening and continues into the sea",
    palette: ["desert ochre", "lapis blue", "mulberry", "ink black"],
    styles: ["contour-atlas-ink", "luminous-ligne-claire", "risograph-overprint"],
  },
  {
    slug: "team-of-rivals",
    bookTitle: "Team of Rivals",
    author: "Doris Kearns Goodwin",
    category: "history",
    forms: ["four contrasting chair backs", "one oval table", "a shared light pool"],
    relationship: "the four chairs lean toward the table while the light holds the center",
    palette: ["walnut", "maple", "cherry wood", "lamplight gold"],
    styles: ["wood-marquetry-landscape", "matte-gouache-editorial", "relief-blockprint"],
  },
  {
    slug: "the-warmth-of-other-suns",
    bookTitle: "The Warmth of Other Suns",
    author: "Isabel Wilkerson",
    category: "history",
    forms: ["three broad migration streams", "one northern horizon", "a golden sun"],
    relationship: "the three streams rise separately toward the same warm horizon",
    palette: ["deep indigo", "rust", "warm gold", "cotton white"],
    styles: ["thread-painted-embroidery", "contour-atlas-ink", "risograph-overprint"],
  },
  {
    slug: "spqr",
    bookTitle: "SPQR",
    author: "Mary Beard",
    category: "history",
    forms: ["one broad Roman arch", "a laurel branch", "a river band"],
    relationship: "the branch crosses the arch while the river carries beneath it",
    palette: ["warm paper", "graphite", "iron red", "verdigris"],
    styles: ["mineral-line-engraving", "fresco-mineral-pigment", "ceramic-underglaze"],
  },
] as const satisfies readonly BookSeed[];
