import type { BookSeed } from "./book-authoring-record";

export const scienceAndPhilosophyBookSeeds = [
  {
    slug: "a-brief-history-of-time",
    bookTitle: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "science",
    forms: ["one black center", "two expanding rings", "a curved star ribbon"],
    relationship: "the rings expand from darkness while the star ribbon bends around them",
    palette: ["night black", "deep blue", "silver", "electric cyan"],
    styles: ["screenprint-night", "scratchboard-nocturne", "prismatic-geometric-symbolism"],
  },
  {
    slug: "the-selfish-gene",
    bookTitle: "The Selfish Gene",
    author: "Richard Dawkins",
    category: "science",
    forms: ["two thick helix ribbons", "three broad connecting bridges", "one cell disk"],
    relationship: "the paired ribbons twist through the cell with only three durable connections",
    palette: ["cobalt", "amber", "deep violet", "clear white"],
    styles: ["stained-glass-field", "mosaic-tesserae-field", "luminous-ligne-claire"],
  },
  {
    slug: "the-gene",
    bookTitle: "The Gene",
    author: "Siddhartha Mukherjee",
    category: "science",
    forms: ["one large chromosome silhouette", "a branching lineage form", "one luminous cell"],
    relationship: "the lineage grows from the chromosome and resolves inside the cell",
    palette: ["Prussian blue", "exposure white", "botanical green", "mineral gold"],
    styles: ["cyanotype-field-study", "watercolor-naturalist-study", "stained-glass-field"],
  },
  {
    slug: "the-emperor-of-all-maladies",
    bookTitle: "The Emperor of All Maladies",
    author: "Siddhartha Mukherjee",
    category: "science",
    forms: ["one dark cellular knot", "a clean white fork", "a gold horizon band"],
    relationship: "the white fork opens the knot toward the narrow horizon",
    palette: ["charcoal", "bone white", "muted crimson", "restrained gold"],
    styles: ["monoprint-ink-wash", "prismatic-geometric-symbolism", "mosaic-tesserae-field"],
  },
  {
    slug: "the-sixth-extinction",
    bookTitle: "The Sixth Extinction",
    author: "Elizabeth Kolbert",
    category: "science",
    forms: ["one ammonite silhouette", "a fading wing form", "an ash horizon"],
    relationship: "the wing thins into the horizon above the enduring fossil spiral",
    palette: ["charcoal black", "ash gray", "fossil cream", "warning coral"],
    styles: ["charcoal-pastel-weather", "aquatint-atmosphere", "cyanotype-field-study"],
  },
  {
    slug: "cosmos",
    bookTitle: "Cosmos",
    author: "Carl Sagan",
    category: "science",
    forms: ["one ringed planet", "an observatory dome", "a broad Milky Way arc"],
    relationship: "the observatory faces the planet beneath the immense stellar arc",
    palette: ["black", "star white", "indigo", "restrained copper"],
    styles: ["scratchboard-nocturne", "pixel-cluster-landscape", "screenprint-night"],
  },
  {
    slug: "meditations",
    bookTitle: "Meditations",
    author: "Marcus Aurelius",
    category: "philosophy",
    forms: ["one calm central flame", "two concentric stone arcs", "a surrounding storm band"],
    relationship: "the flame remains upright within the stone arcs as weather moves outside",
    palette: ["wool gray", "indigo", "ember gold", "stone cream"],
    styles: ["woven-tapestry-field", "wood-marquetry-landscape", "ceramic-underglaze"],
  },
  {
    slug: "the-republic",
    bookTitle: "The Republic",
    author: "Plato",
    category: "philosophy",
    forms: ["one cave arch", "a rising stair path", "one brilliant sun disk"],
    relationship: "the steps move from the enclosing arch into the unobstructed sun",
    palette: ["plaster white", "cave umber", "mineral blue", "sun gold"],
    styles: ["fresco-mineral-pigment", "aquatint-atmosphere", "cut-paper-strata"],
  },
  {
    slug: "mans-search-for-meaning",
    bookTitle: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    category: "philosophy",
    forms: ["one broken enclosure", "an upright human silhouette", "a horizon glow"],
    relationship: "the figure stands inside the opening and faces the distant light",
    palette: ["ink black", "warm gray", "paper white", "quiet amber"],
    styles: ["monoprint-ink-wash", "relief-blockprint", "risograph-overprint"],
  },
  {
    slug: "the-myth-of-sisyphus",
    bookTitle: "The Myth of Sisyphus",
    author: "Albert Camus",
    category: "philosophy",
    forms: ["one steep slope", "a monumental round stone", "a rising sun"],
    relationship: "the stone holds against the slope while dawn begins behind it",
    palette: ["ink black", "stone gray", "ochre", "paper cream"],
    styles: ["relief-blockprint", "charcoal-pastel-weather", "fresco-mineral-pigment"],
  },
  {
    slug: "justice",
    bookTitle: "Justice",
    author: "Michael J. Sandel",
    category: "philosophy",
    forms: ["two contrasting paths", "one central light", "a shared circular ground"],
    relationship: "the paths hold equal visual weight before meeting at the light",
    palette: ["deep navy", "rust", "clear teal", "warm white"],
    styles: ["prismatic-geometric-symbolism", "mosaic-tesserae-field", "matte-gouache-editorial"],
  },
  {
    slug: "nicomachean-ethics",
    bookTitle: "Nicomachean Ethics",
    author: "Aristotle",
    category: "philosophy",
    forms: ["one middle path", "two dark cliff masses", "an olive branch"],
    relationship: "the path keeps a deliberate course between extremes toward the branch",
    palette: ["clay cream", "olive green", "iron black", "warm terracotta"],
    styles: ["ceramic-underglaze", "fresco-mineral-pigment", "woven-tapestry-field"],
  },
] as const satisfies readonly BookSeed[];
