import type { BookSeed } from "./book-authoring-record";

export const technologyAndSpeculativeBookSeeds = [
  {
    slug: "the-innovators",
    bookTitle: "The Innovators",
    author: "Walter Isaacson",
    category: "technology",
    forms: ["three linked relay forms", "one bright spark", "an airy circuit path"],
    relationship: "the relays pass one continuous path into the spark",
    palette: ["clear white", "graphite", "copper", "electric blue"],
    styles: ["luminous-ligne-claire", "risograph-overprint", "pixel-cluster-landscape"],
  },
  {
    slug: "the-design-of-everyday-things",
    bookTitle: "The Design of Everyday Things",
    author: "Don Norman",
    category: "technology",
    forms: ["one simple door plane", "a clearly placed round handle", "an opening wedge of light"],
    relationship: "the handle explains the opening action before the light reveals the result",
    palette: ["matte cream", "charcoal", "rust", "clear yellow"],
    styles: ["matte-gouache-editorial", "cut-paper-strata", "ceramic-underglaze"],
  },
  {
    slug: "the-pragmatic-programmer",
    bookTitle: "The Pragmatic Programmer",
    author: "Andrew Hunt and David Thomas",
    category: "technology",
    forms: ["three modular blocks", "one bridged gap", "a glowing terminal tile"],
    relationship: "the modules form a practical bridge toward the clear final tile",
    palette: ["deep navy", "slate", "amber", "mint green"],
    styles: ["pixel-cluster-landscape", "risograph-overprint", "contour-atlas-ink"],
  },
  {
    slug: "code",
    bookTitle: "Code",
    author: "Charles Petzold",
    category: "technology",
    forms: ["one dark tile river", "one light tile river", "a golden pulse"],
    relationship: "the paired state rivers alternate and converge into the pulse",
    palette: ["cobalt", "porcelain white", "carbon black", "signal gold"],
    styles: ["ceramic-underglaze", "pixel-cluster-landscape", "mosaic-tesserae-field"],
  },
  {
    slug: "algorithms-to-live-by",
    bookTitle: "Algorithms to Live By",
    author: "Brian Christian and Tom Griffiths",
    category: "technology",
    forms: ["one branching route network", "a clear destination disk", "a boundary arc"],
    relationship: "the possible routes simplify as they approach the destination within the boundary",
    palette: ["warm paper", "graphite", "mineral teal", "route orange"],
    styles: ["contour-atlas-ink", "prismatic-geometric-symbolism", "luminous-ligne-claire"],
  },
  {
    slug: "the-phoenix-project",
    bookTitle: "The Phoenix Project",
    author: "Gene Kim, Kevin Behr, and George Spafford",
    category: "technology",
    forms: ["one rising firebird silhouette", "three server-like monoliths", "an ember arc"],
    relationship: "the firebird rises from the aligned monoliths as the ember arc reconnects them",
    palette: ["deep indigo", "ember orange", "gold", "smoke gray"],
    styles: ["stained-glass-field", "relief-blockprint", "screenprint-night"],
  },
  {
    slug: "chip-war",
    bookTitle: "Chip War",
    author: "Chris Miller",
    category: "technology",
    forms: ["one central silicon square", "two opposing wave bands", "a narrow circuit river"],
    relationship: "the wave bands press toward the square while the circuit river escapes between them",
    palette: ["silicon gray", "cobalt", "copper", "warning red"],
    styles: ["mosaic-tesserae-field", "prismatic-geometric-symbolism", "pixel-cluster-landscape"],
  },
  {
    slug: "dune",
    bookTitle: "Dune",
    author: "Frank Herbert",
    category: "speculative-fiction",
    forms: ["one giant sun", "two sweeping dune curves", "a blue oasis accent"],
    relationship: "the dunes eclipse part of the sun while the small oasis holds the cool counterpoint",
    palette: ["sand ochre", "burnt orange", "deep umber", "oasis blue"],
    styles: ["cut-paper-strata", "ceramic-underglaze", "relief-blockprint"],
  },
  {
    slug: "the-three-body-problem",
    bookTitle: "The Three-Body Problem",
    author: "Cixin Liu",
    category: "speculative-fiction",
    forms: ["three distinct sun disks", "one fractured planet", "a looping orbit band"],
    relationship: "the orbit band fails to settle as the three suns pull around the planet",
    palette: ["space black", "solar gold", "warning red", "icy blue"],
    styles: ["prismatic-geometric-symbolism", "screenprint-night", "mosaic-tesserae-field"],
  },
  {
    slug: "foundation",
    bookTitle: "Foundation",
    author: "Isaac Asimov",
    category: "speculative-fiction",
    forms: ["one fallen arch", "a luminous geometric seed", "a distant star disk"],
    relationship: "the seed remains intact beyond the fallen arch beneath the fixed star",
    palette: ["plaster gray", "night blue", "seed gold", "oxide red"],
    styles: ["fresco-mineral-pigment", "stained-glass-field", "aquatint-atmosphere"],
  },
  {
    slug: "neuromancer",
    bookTitle: "Neuromancer",
    author: "William Gibson",
    category: "speculative-fiction",
    forms: ["one neon data river", "twin tower canyons", "a pale moon disk"],
    relationship: "the data river cuts between the towers and bends toward the moon",
    palette: ["night black", "electric cyan", "acid magenta", "moon white"],
    styles: ["screenprint-night", "pixel-cluster-landscape", "luminous-ligne-claire"],
  },
  {
    slug: "the-left-hand-of-darkness",
    bookTitle: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    category: "speculative-fiction",
    forms: ["two interlocking profiles", "one snow ridge", "a divided sun disk"],
    relationship: "the profiles share one boundary above the ridge while the sun holds both tones",
    palette: ["snow white", "midnight blue", "violet", "cold gold"],
    styles: ["woven-tapestry-field", "charcoal-pastel-weather", "cut-paper-strata"],
  },
  {
    slug: "project-hail-mary",
    bookTitle: "Project Hail Mary",
    author: "Andy Weir",
    category: "speculative-fiction",
    forms: ["one seed-shaped craft", "two contrasting suns", "a single orbit arc"],
    relationship: "the small craft follows the arc through the space between the suns",
    palette: ["space black", "clear white", "solar yellow", "red-orange"],
    styles: ["stained-glass-field", "prismatic-geometric-symbolism", "screenprint-night"],
  },
] as const satisfies readonly BookSeed[];
