import {
  arc,
  circle,
  color,
  curve,
  ellipse,
  forms,
  palette,
  polygon,
  recipe,
  rect,
  star,
} from "./code-native-art-recipe-builders";

export const codeNativeTechnologySpeculativeRecipes = [
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-innovators",
    primaryStyleId: "luminous-ligne-claire",
    manufacturingLanguage: "ligne-claire-panels",
    styleComparison:
      "Preserves luminous-ligne-claire using three clear relay panels and one path without circuit clutter or glow effects.",
    forms: forms("three linked relay forms", "one bright spark", "one airy circuit path"),
    relationship: "Three relays pass one continuous path into the spark.",
    palette: palette(
      color("clear white", "#EFECDD"),
      color("graphite", "#32383D"),
      color("copper", "#B96E39"),
      color("electric blue", "#337DB4"),
    ),
    backgroundColor: 0,
    commands: [
      rect(1, 118, 354, 156, 156),
      rect(2, 370, 354, 156, 156),
      rect(3, 622, 354, 156, 156),
      curve(2, 42, [-40, 432], [202, 432], [514, 432], [818, 432]),
      star(3, 804, 432, 116, 48, 6),
    ],
    minimumFeaturePixels: 42,
    minimumNegativeGapPixels: 96,
    edgeStrategy:
      "The continuous path enters from left and the spark reaches right while white remains open at top and bottom.",
    sourceSpecificExclusions: [
      "exactly three relay forms",
      "no repeated circuit traces, labels, or terminal symbols",
      "no glow or thin outlines",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-pragmatic-programmer",
    primaryStyleId: "pixel-cluster-landscape",
    manufacturingLanguage: "large-pixel-clusters",
    styleComparison:
      "Preserves pixel-cluster-landscape using a handful of large square modules without low-resolution noise or terminal glyphs.",
    forms: forms("three modular blocks", "one bridged gap", "one glowing terminal tile"),
    relationship: "Three modules make one practical bridge toward the clear final tile.",
    palette: palette(
      color("deep navy", "#1C2C4A"),
      color("slate", "#66717A"),
      color("amber", "#D39835"),
      color("mint green", "#67B59A"),
    ),
    backgroundColor: 0,
    commands: [
      rect(1, 100, 566, 176, 176),
      rect(2, 322, 430, 176, 176),
      rect(1, 544, 294, 176, 176),
      polygon(2, 240, 570, 356, 454, 422, 520, 306, 636),
      rect(3, 658, 154, 176, 176),
    ],
    minimumFeaturePixels: 66,
    minimumNegativeGapPixels: 46,
    edgeStrategy:
      "Navy reaches all four edges; the rising modules stay open and never create an inset pixel frame.",
    sourceSpecificExclusions: [
      "exactly three modules and one destination tile",
      "no code, prompt, cursor, letters, or terminal marks",
      "no tiny pixels",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "algorithms-to-live-by",
    primaryStyleId: "contour-atlas-ink",
    manufacturingLanguage: "broad-map-bands",
    styleComparison:
      "Preserves contour-atlas-ink through three broad route branches without repeated contour lines, nodes, or labels.",
    forms: forms("one branching route network", "one destination disk", "one boundary arc"),
    relationship: "Three possible routes simplify toward one destination inside the boundary.",
    palette: palette(
      color("warm paper", "#E8D9BA"),
      color("graphite", "#3C4143"),
      color("mineral teal", "#397F78"),
      color("route orange", "#C86C3C"),
    ),
    backgroundColor: 0,
    commands: [
      arc(1, 448, 478, 350, 300, 190, 520),
      curve(2, 60, [-40, 260], [184, 278], [300, 400], [448, 478]),
      curve(3, 60, [-40, 474], [186, 460], [312, 462], [448, 478]),
      curve(1, 60, [-40, 708], [184, 660], [304, 548], [448, 478]),
      circle(3, 574, 478, 104),
      circle(0, 574, 478, 44),
    ],
    minimumFeaturePixels: 50,
    minimumNegativeGapPixels: 32,
    edgeStrategy:
      "All three routes enter from left, boundary remains open at right, and paper reaches top and bottom.",
    sourceSpecificExclusions: [
      "three route branches maximum",
      "no small nodes, arrows, map labels, or contour repetition",
      "destination must remain one disk",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-phoenix-project",
    primaryStyleId: "stained-glass-field",
    manufacturingLanguage: "large-stained-glass-cells",
    styleComparison:
      "Preserves stained-glass-field using one simplified firebird cell and three monolith cells without feathers or server detail.",
    forms: forms("one rising firebird silhouette", "three server-like monoliths", "one ember arc"),
    relationship: "The firebird rises from three aligned monoliths as one ember arc reconnects them.",
    palette: palette(
      color("deep indigo", "#202B57"),
      color("ember orange", "#D05A32"),
      color("gold", "#D5A13A"),
      color("smoke gray", "#7C8184"),
    ),
    backgroundColor: 0,
    commands: [
      rect(3, 144, 612, 154, 284),
      rect(3, 371, 560, 154, 336),
      rect(3, 598, 612, 154, 284),
      polygon(1, 448, 112, 514, 322, 686, 258, 548, 438, 448, 546, 348, 438, 210, 258, 382, 322),
      arc(2, 448, 724, 344, 286, 186, 354),
    ],
    minimumFeaturePixels: 58,
    minimumNegativeGapPixels: 44,
    edgeStrategy:
      "Indigo reaches all four edges and monoliths exit bottom; the ember arc remains open at both sides.",
    sourceSpecificExclusions: [
      "no feathers, eyes, beak detail, or flames",
      "exactly three blank monoliths",
      "no racks, cables, lights, or server vents",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "chip-war",
    primaryStyleId: "mosaic-tesserae-field",
    manufacturingLanguage: "large-prismatic-cells",
    styleComparison:
      "Translates mosaic-tesserae-field into four large prismatic cells without tesserae, repeated circuits, or relief.",
    forms: forms("one central silicon square", "two opposing wave bands", "one narrow circuit river"),
    relationship: "The wave bands press toward the square while one river escapes between them.",
    palette: palette(
      color("dark seam", "#252B35"),
      color("silicon gray", "#A8ADB4"),
      color("cobalt", "#244DA1"),
      color("copper", "#C77934"),
      color("warning red", "#A92D38"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(2, 0, 170, 0, 390, 260, 470, 340, 392, 252, 300),
      polygon(4, 896, 726, 896, 506, 636, 426, 556, 504, 644, 596),
      curve(3, 58, [470, 940], [470, 650], [426, 312], [470, -40]),
      rect(1, 326, 326, 244, 244),
    ],
    minimumFeaturePixels: 58,
    minimumNegativeGapPixels: 40,
    edgeStrategy:
      "Circuit river reaches top and bottom; opposing wave bands reach left and right, eliminating any inset boundary.",
    sourceSpecificExclusions: [
      "one circuit river only",
      "one solid silicon square with no inset square",
      "no repeated traces, tesserae, or faux relief",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-three-body-problem",
    primaryStyleId: "prismatic-geometric-symbolism",
    manufacturingLanguage: "prismatic-cells",
    styleComparison:
      "Preserves prismatic-geometric-symbolism through five large orbital cells without starfields, facets, or equation-like marks.",
    forms: forms("three distinct sun disks", "one fractured planet", "one looping orbit band"),
    relationship: "One orbit fails to settle as three suns pull around the fractured planet.",
    palette: palette(
      color("space black", "#11151B"),
      color("solar gold", "#D7A33B"),
      color("warning red", "#B13B3D"),
      color("icy blue", "#79AFC4"),
      color("orbit white", "#E9E8DC"),
    ),
    backgroundColor: 0,
    commands: [
      circle(1, 210, 214, 116),
      circle(2, 684, 196, 92),
      circle(3, 730, 650, 132),
      arc(4, 448, 448, 340, 296, 18, 338),
      circle(3, 448, 466, 146),
      polygon(0, 414, 320, 470, 448, 438, 486, 494, 612, 446, 612, 386, 492, 420, 452, 366, 320),
    ],
    minimumFeaturePixels: 44,
    minimumNegativeGapPixels: 32,
    edgeStrategy:
      "Space black reaches all four edges; the looping orbit has a broad opening and never becomes an outer frame.",
    sourceSpecificExclusions: [
      "exactly three suns and one planet",
      "one broad fracture only",
      "no stars, equations, numerals, or fine orbit lines",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "foundation",
    primaryStyleId: "fresco-mineral-pigment",
    manufacturingLanguage: "mineral-fresco-planes",
    styleComparison:
      "Preserves fresco-mineral-pigment through a fallen arch plane and two luminous symbols without plaster cracks or space texture.",
    forms: forms("one fallen arch", "one luminous geometric seed", "one distant star disk"),
    relationship: "The seed remains intact beyond the fallen arch beneath one fixed star.",
    palette: palette(
      color("plaster gray", "#A5A39A"),
      color("night blue", "#26385D"),
      color("seed gold", "#D4A13A"),
      color("oxide red", "#9C4A3B"),
    ),
    backgroundColor: 0,
    commands: [
      arc(3, 300, 650, 320, 220, 190, 340),
      polygon(3, -30, 620, 200, 660, 180, 790, -30, 820),
      polygon(2, 610, 572, 720, 682, 610, 792, 500, 682),
      circle(1, 698, 190, 116),
      circle(2, 698, 190, 56),
    ],
    minimumFeaturePixels: 56,
    minimumNegativeGapPixels: 44,
    edgeStrategy:
      "Fallen arch bleeds through left and bottom; plaster reaches top and right without an enclosing border.",
    sourceSpecificExclusions: [
      "no masonry blocks or cracks",
      "no city, people, or starfield",
      "seed must remain one diamond",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "neuromancer",
    primaryStyleId: "screenprint-night",
    manufacturingLanguage: "screenprint-masses",
    styleComparison:
      "Preserves screenprint-night through two canyon masses and one neon river without circuitry, windows, or glow gradients.",
    forms: forms("one neon data river", "twin tower canyons", "one pale moon disk"),
    relationship: "The data river cuts between twin canyons and bends toward the moon.",
    palette: palette(
      color("night black", "#111318"),
      color("electric cyan", "#24B8C7"),
      color("acid magenta", "#B52D79"),
      color("moon white", "#ECE9DA"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(2, 0, 0, 330, 0, 292, 210, 360, 352, 278, 512, 318, 896, 0, 896),
      polygon(2, 896, 0, 590, 0, 622, 238, 556, 388, 634, 550, 590, 896, 896, 896),
      curve(1, 120, [448, 940], [332, 720], [570, 526], [612, 230]),
      circle(3, 674, 162, 110),
    ],
    minimumFeaturePixels: 110,
    minimumNegativeGapPixels: 40,
    edgeStrategy:
      "Tower canyons bleed top, left, right, and bottom; data river exits bottom and the night remains open.",
    sourceSpecificExclusions: [
      "no windows, skyline, cables, grids, or circuit traces",
      "one river only",
      "no neon glow or gradient",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "project-hail-mary",
    primaryStyleId: "stained-glass-field",
    manufacturingLanguage: "large-stained-glass-cells",
    styleComparison:
      "Preserves stained-glass-field using four large orbital cells without spacecraft detail, stars, or luminous depth.",
    forms: forms("one seed-shaped craft", "two contrasting suns", "one orbit arc"),
    relationship: "The small craft follows one arc through the space between two suns.",
    palette: palette(
      color("space black", "#101419"),
      color("clear white", "#EEEBDD"),
      color("solar yellow", "#D9AA32"),
      color("red-orange", "#C94C32"),
    ),
    backgroundColor: 0,
    commands: [
      circle(2, 226, 236, 150),
      circle(3, 700, 622, 174),
      arc(1, 448, 448, 330, 288, 132, 390),
      ellipse(1, 472, 420, 70, 136),
      polygon(1, 434, 520, 510, 520, 472, 626),
    ],
    minimumFeaturePixels: 42,
    minimumNegativeGapPixels: 38,
    edgeStrategy:
      "Space black reaches all four edges; the orbit remains open and neither sun creates an inset enclosure.",
    sourceSpecificExclusions: [
      "exactly two suns and one craft",
      "no spacecraft panels, engines, windows, or stars",
      "one orbit arc only",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "code",
    primaryStyleId: "ceramic-underglaze",
    manufacturingLanguage: "ceramic-underglaze-fields",
    styleComparison:
      "Preserves ceramic-underglaze through broad alternating state rivers without tile grids, glaze shine, or circuit texture.",
    forms: forms("one dark tile river", "one light tile river", "one golden pulse"),
    relationship: "The paired state rivers alternate in broad steps and converge into one pulse.",
    palette: palette(
      color("cobalt", "#28558A"),
      color("porcelain white", "#EEE8D6"),
      color("carbon black", "#202427"),
      color("signal gold", "#D3A13A"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(2, 0, 206, 284, 206, 284, 304, 456, 304, 456, 404, 620, 404, 620, 506, 0, 506),
      polygon(1, 896, 690, 650, 690, 650, 586, 478, 586, 478, 482, 306, 482, 306, 378, 896, 378),
      circle(3, 468, 444, 104),
    ],
    minimumFeaturePixels: 98,
    minimumNegativeGapPixels: 34,
    edgeStrategy:
      "The dark and light rivers bleed through opposite side edges while cobalt remains open at top and bottom.",
    sourceSpecificExclusions: [
      "no binary digits, words, letters, numerals, or terminal glyphs",
      "no repeated tile grid or circuit traces",
      "one pulse disk only",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-left-hand-of-darkness",
    primaryStyleId: "woven-tapestry-field",
    manufacturingLanguage: "broad-woven-bands",
    styleComparison:
      "Preserves woven-tapestry-field through interlocking color silhouettes without threads, weave texture, or fringe.",
    forms: forms("two interlocking profiles", "one snow ridge", "one divided sun disk"),
    relationship:
      "Two complementary profiles share one boundary above the ridge while the sun holds both tones.",
    palette: palette(
      color("snow white", "#ECE9DA"),
      color("midnight blue", "#25375F"),
      color("violet", "#604879"),
      color("cold gold", "#C9A348"),
    ),
    backgroundColor: 2,
    commands: [
      polygon(
        0,
        0,
        0,
        448,
        0,
        448,
        100,
        520,
        200,
        480,
        260,
        540,
        320,
        478,
        350,
        510,
        430,
        448,
        510,
        480,
        620,
        448,
        700,
        0,
        700,
      ),
      polygon(
        1,
        896,
        0,
        448,
        0,
        448,
        100,
        520,
        200,
        480,
        260,
        540,
        320,
        478,
        350,
        510,
        430,
        448,
        510,
        480,
        620,
        448,
        700,
        896,
        700,
      ),
      polygon(0, 0, 896, 0, 704, 192, 620, 370, 716, 548, 634, 720, 724, 896, 650, 896, 896),
      arc(3, 710, 154, 104, 0, 90, 270),
      arc(2, 710, 154, 104, 0, -90, 90),
    ],
    minimumFeaturePixels: 62,
    minimumNegativeGapPixels: 34,
    edgeStrategy:
      "Profiles bleed left, right, and top while the ridge exits both sides and bottom; no woven border is present.",
    sourceSpecificExclusions: [
      "no eyes, hair, facial detail, hands, or author likeness",
      "no snowflakes, thread marks, weave texture, or fringe",
      "sun remains one disk divided into two broad halves",
    ],
  }),
] as const;
