import {
  arc,
  circle,
  color,
  curve,
  ellipse,
  forms,
  palette,
  polygon,
  recipe,
  rect,
  star,
} from "./code-native-art-recipe-builders";

export const codeNativeLiteraryMilestoneRecipes = [
  recipe({
    catalogueDirectory: "books-read",
    slug: "beloved",
    primaryStyleId: "monoprint-ink-wash",
    manufacturingLanguage: "monoprint-overlap",
    styleComparison:
      "Preserves monoprint-ink-wash through broad threshold overlap without wash gradients, texture, or tiny scenery.",
    forms: forms("one open doorway", "one protective double silhouette", "one red ribbon"),
    relationship: "The joined silhouettes hold the threshold while one ribbon crosses memory and space.",
    palette: palette(
      color("paper white", "#F0E2C7"),
      color("earth brown", "#7A4C35"),
      color("ink black", "#17191B"),
      color("deep red", "#A52D32"),
    ),
    backgroundColor: 0,
    commands: [
      rect(1, 250, 118, 396, 778),
      rect(2, 286, 158, 324, 738),
      curve(3, 72, [-50, 650], [190, 470], [650, 790], [950, 510]),
      circle(0, 390, 370, 58),
      circle(0, 514, 348, 72),
      polygon(0, 318, 774, 330, 486, 390, 438, 444, 480, 502, 430, 574, 476, 584, 774),
    ],
    minimumFeaturePixels: 40,
    minimumNegativeGapPixels: 36,
    edgeStrategy:
      "Ribbon bleeds left and right, threshold opens through bottom, and paper reaches top without an outer frame.",
    sourceSpecificExclusions: [
      "double silhouette must stay visible at 48 pixels",
      "no faces, rooms, furniture, or ghost effects",
      "no gradient-only rendering",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-road",
    primaryStyleId: "charcoal-pastel-weather",
    manufacturingLanguage: "charcoal-cut-masses",
    styleComparison:
      "Preserves charcoal-pastel-weather through broad ash and charcoal cuts without smudging, grain, or atmospheric gradients.",
    forms: forms("two large footprints", "one bare tree", "one pale horizon band"),
    relationship: "Two footprints continue past the tree toward the only light on the horizon.",
    palette: palette(
      color("charcoal", "#25282A"),
      color("ash gray", "#858783"),
      color("bone white", "#E8E1D0"),
      color("faint amber", "#C59A54"),
    ),
    backgroundColor: 1,
    commands: [
      rect(3, 0, 178, 896, 92),
      polygon(0, 596, 896, 616, 504, 552, 406, 628, 456, 700, 344, 652, 490, 692, 896),
      ellipse(2, 300, 672, 88, 154),
      ellipse(2, 260, 542, 62, 54),
      ellipse(2, 454, 458, 78, 138),
      ellipse(2, 420, 344, 58, 48),
    ],
    minimumFeaturePixels: 56,
    minimumNegativeGapPixels: 34,
    edgeStrategy:
      "Horizon crosses left and right, tree exits bottom, and ash reaches top; no weathered border is present.",
    sourceSpecificExclusions: [
      "exactly two footprints",
      "no toe microdetail beyond one broad toe mass",
      "no branches thinner than the recognition floor or charcoal grain",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "a-gentleman-in-moscow",
    primaryStyleId: "wood-marquetry-landscape",
    manufacturingLanguage: "marquetry-inlay",
    styleComparison:
      "Preserves wood-marquetry-landscape through broad window and key inlays without grain, depth, or miniature architecture.",
    forms: forms("one tall hotel window", "one brass key", "one distant city band"),
    relationship: "The key rests inside the window while the city remains beyond it.",
    palette: palette(
      color("maple cream", "#EEDDBD"),
      color("walnut", "#5B3528"),
      color("brass", "#C99735"),
      color("winter blue", "#7194A8"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(3, 204, 700, 204, 540, 330, 540, 330, 448, 520, 448, 520, 578, 692, 578, 692, 700),
      rect(1, 112, 0, 92, 896),
      rect(1, 692, 0, 92, 896),
      rect(1, 112, 0, 672, 92),
      rect(1, 112, 700, 672, 196),
      circle(2, 448, 315, 126),
      circle(0, 448, 315, 62),
      rect(2, 414, 408, 68, 238),
      polygon(2, 448, 610, 590, 610, 590, 676, 518, 676, 518, 724, 414, 724, 414, 610),
    ],
    minimumFeaturePixels: 64,
    minimumNegativeGapPixels: 44,
    edgeStrategy:
      "Window rails run through top and bottom, while maple remains open on left and right outside the window.",
    sourceSpecificExclusions: [
      "city band limited to three large steps",
      "no skyline spires, windows, wood grain, or inset depth",
      "key wholly inside window",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-kite-runner",
    primaryStyleId: "cut-paper-strata",
    manufacturingLanguage: "cut-paper-strata",
    styleComparison:
      "Preserves cut-paper-strata through three overlapping silhouette layers without skyline detail or paper fibers.",
    forms: forms("one red kite", "one broken curving string", "one rooftop band"),
    relationship: "The kite pulls away from the rooftops as the broken string curls back.",
    palette: palette(
      color("sky blue", "#6698B5"),
      color("pomegranate red", "#B6333F"),
      color("sand", "#DDC79D"),
      color("deep brown", "#49352D"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(
        3,
        0,
        896,
        0,
        700,
        176,
        700,
        176,
        630,
        356,
        630,
        356,
        716,
        566,
        716,
        566,
        648,
        736,
        648,
        736,
        716,
        896,
        716,
        896,
        896,
      ),
      polygon(1, 600, 160, 742, 310, 594, 462, 452, 310),
      curve(2, 42, [574, 446], [514, 518], [480, 570], [458, 632]),
      curve(2, 42, [420, 686], [350, 744], [286, 702], [220, 760]),
    ],
    minimumFeaturePixels: 42,
    minimumNegativeGapPixels: 38,
    edgeStrategy:
      "Rooftop band bleeds left, right, and bottom while sky reaches top; broken string remains open.",
    sourceSpecificExclusions: [
      "one kite only",
      "rooftop is one broad band with no windows or antennas",
      "string has one deliberate gap and no thin linework",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "pachinko",
    primaryStyleId: "ceramic-underglaze",
    manufacturingLanguage: "ceramic-underglaze-fields",
    styleComparison:
      "Preserves ceramic-underglaze through rounded flat fields without glaze highlights, peg repetition, or ceramic texture.",
    forms: forms("three ivory balls", "one bold brass peg arc", "one indigo basin"),
    relationship: "Three balls descend through one broad arc into a shared basin.",
    palette: palette(
      color("persimmon field", "#C96A3B"),
      color("porcelain white", "#EEE8D7"),
      color("brass", "#C69A3B"),
      color("indigo", "#273B68"),
    ),
    backgroundColor: 0,
    commands: [
      arc(2, 448, 410, 312, 256, 188, 352),
      circle(1, 282, 270, 86),
      circle(1, 448, 206, 86),
      circle(1, 614, 270, 86),
      arc(3, 448, 850, 400, 250, 180, 360),
    ],
    minimumFeaturePixels: 56,
    minimumNegativeGapPixels: 34,
    edgeStrategy:
      "Indigo basin exits left, right, and bottom while persimmon reaches top; no enclosing ceramic rim is drawn.",
    sourceSpecificExclusions: [
      "exactly three balls",
      "one continuous peg arc rather than repeated pegs",
      "no machine, pins, numbers, or glaze reflections",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "atomic-habits",
    primaryStyleId: "risograph-overprint",
    manufacturingLanguage: "risograph-overprint-planes",
    styleComparison:
      "Preserves risograph-overprint through large offset color planes without dot screens, ink noise, or typography.",
    forms: forms("three ascending blocks", "one growing sun-seed", "one stable ground band"),
    relationship: "Each block adds one measured step until the seed clears the horizon.",
    palette: palette(
      color("paper cream", "#EEE2C8"),
      color("coral", "#D05E51"),
      color("teal", "#34847C"),
      color("sun yellow", "#D9AC39"),
    ),
    backgroundColor: 0,
    commands: [
      rect(2, 0, 742, 896, 154),
      rect(1, 126, 584, 176, 158),
      rect(2, 360, 426, 176, 316),
      rect(1, 594, 268, 176, 474),
      circle(3, 682, 178, 100),
    ],
    minimumFeaturePixels: 100,
    minimumNegativeGapPixels: 58,
    edgeStrategy:
      "Ground band bleeds left, right, and bottom while paper reaches top; blocks remain separate without an inset frame.",
    sourceSpecificExclusions: [
      "exactly three blocks",
      "no checkmarks, arrows, letters, or progress labels",
      "no halftone dots or print grain",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "kitchen-confidential",
    primaryStyleId: "relief-blockprint",
    manufacturingLanguage: "relief-cut-spot-shapes",
    styleComparison:
      "Preserves relief-blockprint through three hard kitchen silhouettes without hatching, food detail, or metallic depth.",
    forms: forms("one chef knife", "one swinging kitchen door", "one bold steam coil"),
    relationship: "Knife and steam cross before the door opens into the working room.",
    palette: palette(
      color("paper cream", "#EDE0C3"),
      color("ink black", "#1D2022"),
      color("tomato red", "#B8403C"),
      color("steel gray", "#7C8488"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(1, 110, 896, 110, 190, 448, 118, 448, 896),
      polygon(0, 176, 250, 380, 222, 380, 896, 176, 896),
      polygon(3, 234, 588, 696, 330, 748, 420, 304, 680),
      rect(1, 696, 330, 76, 90),
      curve(2, 70, [564, 618], [420, 532], [704, 404], [548, 276]),
    ],
    minimumFeaturePixels: 52,
    minimumNegativeGapPixels: 36,
    edgeStrategy:
      "Door exits top and bottom, cream reaches right, and the composition stays open at both side edges.",
    sourceSpecificExclusions: [
      "no food, cookware, fire, blood, or people",
      "one knife and one steam coil only",
      "no steel highlights or carved hatching",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-wager",
    primaryStyleId: "aquatint-atmosphere",
    manufacturingLanguage: "aquatint-flat-silhouette",
    styleComparison:
      "Translates aquatint-atmosphere into broad storm silhouettes without tonal gradients, spray speckle, or etched texture.",
    forms: forms("one broken ship hull", "one giant wave", "one compass star"),
    relationship: "The giant wave overtakes the broken hull while the star remains fixed above.",
    palette: palette(
      color("storm black", "#191D20"),
      color("sea green", "#2E776F"),
      color("foam white", "#EDE8D7"),
      color("restrained brass", "#B8893D"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(3, 132, 330, 442, 308, 514, 454, 330, 494, 188, 462),
      polygon(3, 542, 324, 756, 286, 830, 430, 652, 476, 584, 448),
      curve(1, 230, [-100, 720], [246, 404], [558, 862], [996, 452]),
      star(2, 706, 170, 112, 44, 8),
    ],
    minimumFeaturePixels: 62,
    minimumNegativeGapPixels: 34,
    edgeStrategy:
      "Wave bleeds left and right, storm reaches top and bottom, and broken hull pieces never form an inset border.",
    sourceSpecificExclusions: [
      "one wave only",
      "hull limited to two broad broken pieces",
      "no rigging, crew, foam speckle, compass letters, or tonal wash",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-anthropocene-reviewed",
    primaryStyleId: "watercolor-naturalist-study",
    manufacturingLanguage: "cut-paper-naturalist",
    styleComparison:
      "Translates watercolor-naturalist-study into large natural cut shapes without washes, botanical veins, or realistic anatomy.",
    forms: forms("one Earth disk", "one branching flower", "one warm hand silhouette"),
    relationship: "The hand steadies Earth while the flower crosses into the blue field.",
    palette: palette(
      color("paper cream", "#EDE2C9"),
      color("Earth blue", "#337DA1"),
      color("leaf green", "#4C8856"),
      color("warm ochre", "#C38B4A"),
      color("coral", "#C95A55"),
    ),
    backgroundColor: 0,
    commands: [
      circle(1, 582, 360, 238),
      polygon(3, 76, 896, 102, 700, 204, 586, 306, 604, 386, 704, 512, 752, 526, 896),
      curve(3, 100, [222, 636], [244, 568], [284, 526], [338, 516]),
      curve(3, 100, [320, 664], [352, 594], [388, 540], [430, 506]),
      curve(2, 62, [270, 650], [258, 490], [252, 356], [248, 250]),
      curve(2, 54, [254, 438], [204, 392], [178, 340], [172, 286]),
      circle(4, 248, 224, 88),
      circle(4, 186, 272, 70),
      circle(4, 310, 272, 70),
    ],
    minimumFeaturePixels: 48,
    minimumNegativeGapPixels: 30,
    edgeStrategy:
      "Hand exits left and bottom, paper reaches top and right, and Earth remains an open central disk without a frame.",
    sourceSpecificExclusions: [
      "no detailed fingers, continents, coastlines, veins, or petals smaller than 70 pixels",
      "no rating stars or review glyphs",
      "one flower only",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "thinking-fast-and-slow",
    primaryStyleId: "prismatic-geometric-symbolism",
    manufacturingLanguage: "prismatic-cells",
    styleComparison:
      "Preserves prismatic-geometric-symbolism through two unequal route cells and one destination without facets or diagram labels.",
    forms: forms("one lightning path", "one meandering path", "one shared destination disk"),
    relationship: "The unequal paths begin apart and arrive together at the same decision point.",
    palette: palette(
      color("deep navy", "#1B2D4D"),
      color("electric yellow", "#E0B438"),
      color("mineral teal", "#36867E"),
      color("warm white", "#EEE5D0"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(
        1,
        -20,
        90,
        232,
        218,
        178,
        326,
        364,
        374,
        302,
        478,
        512,
        530,
        472,
        602,
        626,
        554,
        516,
        462,
        578,
        396,
        404,
        334,
        452,
        250,
        -20,
        -10,
      ),
      curve(2, 104, [-40, 812], [222, 756], [330, 612], [626, 554]),
      circle(3, 700, 554, 122),
    ],
    minimumFeaturePixels: 50,
    minimumNegativeGapPixels: 38,
    edgeStrategy:
      "Lightning and meandering paths enter from separate left edges while navy reaches top, right, and bottom.",
    sourceSpecificExclusions: [
      "no brain, face, arrows, checkmarks, words, or numerals",
      "one jagged path and one smooth path only",
      "destination remains one disk without diagram nodes",
    ],
  }),
] as const;
