import { defineLandscapeArtProfile, motif, palette } from "./code-native-landscape-profile";

export const codeNativeUsStateProfiles03 = [
  defineLandscapeArtProfile({
    slug: "massachusetts",
    sourceCue: "Cape Cod dunes curving around a lighthouse and broad Atlantic water",
    primaryStyleId: "ceramic-underglaze",
    palette: palette(
      ["dune cream", "#E2D2AE"],
      ["Atlantic blue", "#3F7292"],
      ["cranberry red", "#A13D49"],
      ["weathered gray", "#858680"],
    ),
    motifs: [
      motif(
        "Cape Cod dunes curving around a lighthouse and broad Atlantic water",
        "block",
        3,
        0.32,
        0.42,
        0.16,
        0.46,
      ),
      motif("a hooked shoreline holding centuries of ocean passage", "ribbon", 1, 0.56, 0.58, 0.64, 0.14),
      motif("rocky uplands, river valley, glacial ponds, and sandy cape", "horizon", 2, 0.5, 0.78, 0.82, 0.2),
    ],
    relationship:
      "One lighthouse tower stands inside a hooked shoreline above the cranberry-colored sandy cape.",
    edgeStrategy: "The sandy cape reaches the bottom edge while Atlantic water exits through the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "michigan",
    sourceCue: "Pictured Rocks cliffs glowing above the clear water of Lake Superior",
    primaryStyleId: "wood-marquetry-landscape",
    palette: palette(
      ["lake turquoise", "#3E8D96"],
      ["sandstone copper", "#B0663D"],
      ["pine green", "#355945"],
      ["ice blue", "#B9D5D8"],
    ),
    motifs: [
      motif(
        "Pictured Rocks cliffs glowing above the clear water of Lake Superior",
        "corner",
        1,
        0.46,
        0.4,
        0.62,
        0.46,
      ),
      motif("two peninsulas surrounded by freshwater horizons", "horizon", 3, 0.5, 0.62, 0.78, 0.22),
      motif(
        "Great Lakes shore, forest, dunes, wetlands, and glacial plain",
        "stripe",
        2,
        0.5,
        0.79,
        0.76,
        0.14,
      ),
    ],
    relationship: "One copper cliff stands over a single turquoise horizon and the pine-green glacial shore.",
    edgeStrategy: "The Great Lakes shore reaches the bottom edge and clear water opens along the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "minnesota",
    sourceCue: "Boundary Waters lakes reflecting boreal pines beneath northern light",
    primaryStyleId: "scratchboard-nocturne",
    palette: palette(
      ["lake black", "#182527"],
      ["pine green", "#345B49"],
      ["aurora teal", "#4EA49B"],
      ["granite gray", "#7C8583"],
      ["snow blue", "#B6D2D8"],
    ),
    motifs: [
      motif(
        "Boundary Waters lakes reflecting boreal pines beneath northern light",
        "triangle",
        1,
        0.3,
        0.4,
        0.28,
        0.42,
      ),
      motif("a chain of quiet water leading into wilderness", "ribbon", 2, 0.57, 0.56, 0.58, 0.14),
      motif(
        "lake country, boreal forest, prairie, and North Shore bedrock",
        "horizon",
        3,
        0.5,
        0.77,
        0.82,
        0.21,
      ),
    ],
    relationship: "One boreal pine form reflects into a single teal water chain above the granite shore.",
    edgeStrategy: "The North Shore bedrock meets the bottom edge and the aurora field opens at the top.",
  }),
  defineLandscapeArtProfile({
    slug: "mississippi",
    sourceCue: "cypress wetlands and an oxbow lake across the Mississippi Delta plain",
    primaryStyleId: "luminous-ligne-claire",
    palette: palette(
      ["cotton white", "#F1EBDD"],
      ["cypress green", "#315B45"],
      ["river brown", "#76503A"],
      ["mist blue", "#87AEB8"],
      ["journey gold", "#D4A23F"],
    ),
    motifs: [
      motif(
        "cypress wetlands and an oxbow lake across the Mississippi Delta plain",
        "triangle",
        1,
        0.23,
        0.4,
        0.24,
        0.36,
      ),
      motif("a slow river memory bending away from its former course", "arch", 2, 0.59, 0.48, 0.38, 0.28),
      motif("alluvial delta, loess bluffs, pine hills, and Gulf coast", "horizon", 3, 0.5, 0.77, 0.72, 0.18),
    ],
    accent: motif("one open delta journey", "ribbon", 4, 0.55, 0.3, 0.42, 0.12),
    relationship:
      "One cypress, one oxbow, and one low coast leave open sky around a single gold journey line.",
    edgeStrategy: "The delta rests on the bottom edge while the open journey line exits at the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "missouri",
    sourceCue: "a clear Ozark spring flowing beneath wooded limestone bluffs",
    primaryStyleId: "pixel-cluster-landscape",
    palette: palette(
      ["spring blue", "#4F8C9B"],
      ["limestone cream", "#D8CAAA"],
      ["oak green", "#486442"],
      ["river silt", "#816047"],
    ),
    motifs: [
      motif("a clear Ozark spring flowing beneath wooded limestone bluffs", "arch", 1, 0.5, 0.41, 0.62, 0.46),
      motif("two great rivers meeting beyond a maze of upland streams", "ribbon", 3, 0.5, 0.61, 0.68, 0.14),
      motif(
        "Ozark plateau, prairie plain, limestone caves, and broad rivers",
        "horizon",
        2,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship: "One limestone bluff shelters a single spring curve above the oak-green Ozark plateau.",
    edgeStrategy:
      "The prairie-and-river plane reaches the bottom edge and the spring opens at the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "montana",
    sourceCue: "glaciated peaks rising beyond open prairie beneath a vast sky",
    primaryStyleId: "thread-painted-embroidery",
    palette: palette(
      ["sky blue", "#6092B0"],
      ["snow white", "#EFF0E8"],
      ["prairie gold", "#C69D46"],
      ["pine green", "#315645"],
      ["stone gray", "#747A7B"],
    ),
    motifs: [
      motif(
        "glaciated peaks rising beyond open prairie beneath a vast sky",
        "triangle",
        1,
        0.5,
        0.38,
        0.56,
        0.48,
      ),
      motif("one clear river carrying mountain snow toward the plains", "ribbon", 4, 0.5, 0.61, 0.64, 0.14),
      motif(
        "northern Rockies, intermontane valleys, prairie, and badlands",
        "horizon",
        2,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship: "One glacier-white peak feeds a single stone river across the gold prairie.",
    edgeStrategy: "The prairie reaches the bottom edge while the vast sky stays open across the top.",
  }),
  defineLandscapeArtProfile({
    slug: "nebraska",
    sourceCue: "sandhill cranes gathering along the braided Platte River",
    primaryStyleId: "plein-air-broken-color",
    palette: palette(
      ["prairie gold", "#C99C3F"],
      ["river silver", "#9FAFB1"],
      ["crane gray", "#656F72"],
      ["dawn rose", "#C98379"],
    ),
    motifs: [
      motif("sandhill cranes gathering along the braided Platte River", "bird", 2, 0.6, 0.34, 0.48, 0.24),
      motif("a moving flock joining water, grass, and open sky", "ribbon", 3, 0.5, 0.55, 0.64, 0.14),
      motif(
        "Sandhills grassland, river valleys, loess plains, and High Plains",
        "horizon",
        1,
        0.5,
        0.76,
        0.82,
        0.23,
      ),
    ],
    relationship: "One broad crane form moves along a single rose braid above the Platte grassland.",
    edgeStrategy: "The Sandhills reach the bottom edge and the flock continues toward the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "nevada",
    sourceCue: "Basin and Range ridges repeating across a bright desert playa",
    primaryStyleId: "relief-blockprint",
    palette: palette(
      ["playa cream", "#DFD0A9"],
      ["sage green", "#71805B"],
      ["mountain violet", "#62516F"],
      ["rust red", "#A4553D"],
      ["cobalt sky", "#356A98"],
    ),
    motifs: [
      motif(
        "Basin and Range ridges repeating across a bright desert playa",
        "horizon",
        2,
        0.5,
        0.48,
        0.82,
        0.34,
      ),
      motif(
        "successive mountain silhouettes measuring immense dry distance",
        "stripe",
        3,
        0.5,
        0.63,
        0.72,
        0.14,
      ),
      motif(
        "parallel fault-block ranges, desert basins, playas, and alpine islands",
        "triangle",
        1,
        0.65,
        0.76,
        0.3,
        0.26,
      ),
    ],
    relationship:
      "One violet ridge, one rust silhouette, and one sage alpine island measure the bright basin.",
    edgeStrategy: "The playa reaches the bottom edge while cobalt sky stays open along both upper sides.",
  }),
  defineLandscapeArtProfile({
    slug: "new-hampshire",
    sourceCue: "Mount Washington above layered White Mountain forest in autumn",
    primaryStyleId: "stained-glass-field",
    palette: palette(
      ["maple red", "#A84836"],
      ["birch gold", "#D0A141"],
      ["granite gray", "#777B7B"],
      ["fir green", "#315640"],
      ["cloud blue", "#8AB0C1"],
    ),
    motifs: [
      motif(
        "Mount Washington above layered White Mountain forest in autumn",
        "triangle",
        2,
        0.48,
        0.38,
        0.54,
        0.48,
      ),
      motif("weather moving quickly across a high granite ridge", "stripe", 4, 0.5, 0.27, 0.62, 0.14),
      motif(
        "White Mountains, lake country, forested hills, and short Atlantic coast",
        "horizon",
        3,
        0.5,
        0.77,
        0.82,
        0.21,
      ),
    ],
    relationship: "One granite summit rises through a single moving cloud band above fir-green hills.",
    edgeStrategy: "The forested hills meet the bottom edge while weather exits through the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "new-jersey",
    sourceCue: "tea-dark Pine Barrens water flowing through Atlantic white cedar",
    primaryStyleId: "monoprint-ink-wash",
    palette: palette(
      ["cedar green", "#365B48"],
      ["tea brown", "#75513A"],
      ["sand cream", "#DFCEA7"],
      ["cranberry red", "#A33E48"],
    ),
    motifs: [
      motif(
        "tea-dark Pine Barrens water flowing through Atlantic white cedar",
        "triangle",
        1,
        0.28,
        0.4,
        0.3,
        0.42,
      ),
      motif("a quiet wild corridor held between coast and city", "ribbon", 3, 0.59, 0.55, 0.56, 0.14),
      motif(
        "ridge and valley, Piedmont, pine barrens, wetlands, and barrier shore",
        "horizon",
        2,
        0.5,
        0.77,
        0.82,
        0.21,
      ),
    ],
    relationship:
      "One tea-dark watercourse passes through a single cranberry corridor above the pale barrier shore.",
    edgeStrategy:
      "The barrier shore runs to the bottom edge and the wild corridor opens along the left side.",
  }),
] as const;
