import { defineLandscapeArtProfile, motif, palette } from "./code-native-landscape-profile";

export const codeNativeUsStateProfiles01 = [
  defineLandscapeArtProfile({
    slug: "alabama",
    sourceCue: "longleaf pines opening onto the braided wetlands of the Mobile-Tensaw Delta",
    primaryStyleId: "pixel-cluster-landscape",
    palette: palette(
      ["pine green", "#173F35"],
      ["river blue", "#4A8FA3"],
      ["marsh gold", "#D2A94F"],
      ["clay red", "#A9563F"],
    ),
    motifs: [
      motif(
        "longleaf pines opening onto the braided wetlands of the Mobile-Tensaw Delta",
        "triangle",
        3,
        0.26,
        0.38,
        0.24,
        0.38,
      ),
      motif("river channels gathering toward the Gulf", "ribbon", 1, 0.62, 0.55, 0.54, 0.14),
      motif("forested uplands descending through a broad coastal plain", "horizon", 2, 0.5, 0.76, 0.82, 0.22),
    ],
    relationship: "A lone pine mass opens into one braided river before the coastal plain settles below.",
    edgeStrategy: "The marsh plain reaches the bottom edge while open river color breaks the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "alaska",
    sourceCue: "Denali rising above braided tundra rivers and dark spruce",
    primaryStyleId: "thread-painted-embroidery",
    palette: palette(
      ["snow white", "#F1F2EA"],
      ["glacier blue", "#75AFC5"],
      ["spruce black", "#172D2B"],
      ["tundra russet", "#9A5438"],
      ["aurora green", "#72B58A"],
    ),
    motifs: [
      motif(
        "Denali rising above braided tundra rivers and dark spruce",
        "triangle",
        1,
        0.47,
        0.38,
        0.54,
        0.5,
      ),
      motif("immense northern distance held beneath a low luminous sky", "horizon", 4, 0.5, 0.2, 0.78, 0.16),
      motif("glaciated ranges, tundra, boreal forest, and braided water", "ribbon", 2, 0.5, 0.75, 0.74, 0.16),
    ],
    relationship:
      "Denali anchors the center, a low aurora spans above, and one braided watercourse crosses the tundra below.",
    edgeStrategy:
      "The tundra ribbon reaches the bottom edge and the sky stays open along both upper corners.",
  }),
  defineLandscapeArtProfile({
    slug: "arizona",
    sourceCue: "the Colorado River winding through the layered walls of the Grand Canyon",
    primaryStyleId: "plein-air-broken-color",
    palette: palette(
      ["sandstone red", "#A84E35"],
      ["ochre", "#D59B43"],
      ["violet shadow", "#5A4569"],
      ["river green", "#3F8274"],
      ["sky cobalt", "#32669A"],
    ),
    motifs: [
      motif(
        "the Colorado River winding through the layered walls of the Grand Canyon",
        "corner",
        2,
        0.5,
        0.39,
        0.66,
        0.48,
      ),
      motif("geologic time revealed as bands of desert color", "stripe", 1, 0.5, 0.57, 0.68, 0.15),
      motif("high plateau cut by immense canyons and dry tributaries", "ribbon", 3, 0.5, 0.76, 0.76, 0.16),
    ],
    relationship:
      "One canyon wall holds the upper field while a single color band and river cut through the plateau below.",
    edgeStrategy: "The plateau runs full-bleed across the bottom edge, leaving the sky open at the top.",
  }),
  defineLandscapeArtProfile({
    slug: "arkansas",
    sourceCue: "the Buffalo National River beneath pale Ozark limestone bluffs",
    primaryStyleId: "relief-blockprint",
    palette: palette(
      ["limestone cream", "#E3D2AE"],
      ["river teal", "#3D7F80"],
      ["oak copper", "#A96036"],
      ["moss green", "#486342"],
    ),
    motifs: [
      motif(
        "the Buffalo National River beneath pale Ozark limestone bluffs",
        "corner",
        2,
        0.5,
        0.39,
        0.62,
        0.46,
      ),
      motif("clear water carrying autumn color around a quiet bend", "ribbon", 1, 0.5, 0.62, 0.68, 0.14),
      motif("wooded plateaus, river valleys, springs, and folded ridges", "horizon", 3, 0.5, 0.77, 0.8, 0.2),
    ],
    relationship:
      "The limestone bluff crowns one clear bend, with a single wooded ridge supporting the river valley.",
    edgeStrategy: "The wooded ridge meets the bottom edge while the bluff opens into both side margins.",
  }),
  defineLandscapeArtProfile({
    slug: "california",
    sourceCue: "coastal redwoods framing Pacific light with Sierra granite beyond",
    primaryStyleId: "stained-glass-field",
    palette: palette(
      ["redwood umber", "#53382C"],
      ["Pacific blue", "#397BA0"],
      ["granite silver", "#B9B7AE"],
      ["poppy orange", "#E8752A"],
      ["chaparral green", "#557044"],
    ),
    motifs: [
      motif(
        "coastal redwoods framing Pacific light with Sierra granite beyond",
        "corner",
        4,
        0.48,
        0.39,
        0.64,
        0.48,
      ),
      motif("one long horizon joining forest, ocean, and mountain", "horizon", 1, 0.5, 0.65, 0.78, 0.22),
      motif(
        "coast ranges, central valleys, high granite, and desert basins",
        "triangle",
        2,
        0.68,
        0.39,
        0.32,
        0.34,
      ),
    ],
    relationship:
      "A redwood frame, one Pacific horizon, and one granite peak share a single uncluttered field.",
    edgeStrategy: "The ocean band reaches the bottom edge and the redwood frame touches the left edge only.",
  }),
  defineLandscapeArtProfile({
    slug: "colorado",
    sourceCue: "a snow-lined Rocky Mountain ridge above golden aspen",
    primaryStyleId: "monoprint-ink-wash",
    palette: palette(
      ["alpine blue", "#477FA2"],
      ["snow white", "#EFF1EC"],
      ["aspen gold", "#DAA43B"],
      ["granite gray", "#777A78"],
      ["spruce green", "#315344"],
    ),
    motifs: [
      motif("a snow-lined Rocky Mountain ridge above golden aspen", "triangle", 1, 0.48, 0.37, 0.56, 0.48),
      motif("a high pass opening into clear alpine distance", "arch", 3, 0.64, 0.53, 0.34, 0.3),
      motif(
        "continental-divide peaks, parks, mesas, and river headwaters",
        "horizon",
        2,
        0.5,
        0.76,
        0.8,
        0.21,
      ),
    ],
    relationship: "The snow ridge rises above one open pass and a single aspen-gold park at its base.",
    edgeStrategy:
      "The mountain park runs to the bottom edge while alpine blue remains open at the upper right.",
  }),
  defineLandscapeArtProfile({
    slug: "connecticut",
    sourceCue: "the Connecticut River passing autumn hardwoods and old fieldstone walls",
    primaryStyleId: "contour-atlas-ink",
    palette: palette(
      ["maple red", "#A14836"],
      ["oak gold", "#CAA043"],
      ["river slate", "#57737A"],
      ["fieldstone gray", "#817E74"],
    ),
    motifs: [
      motif(
        "the Connecticut River passing autumn hardwoods and old fieldstone walls",
        "leaf",
        2,
        0.28,
        0.4,
        0.3,
        0.4,
      ),
      motif("a narrow waterway linking inland towns to the Sound", "ribbon", 1, 0.59, 0.55, 0.56, 0.14),
      motif(
        "rolling forest, river valleys, rocky ridges, and tidal coast",
        "horizon",
        3,
        0.5,
        0.76,
        0.8,
        0.22,
      ),
    ],
    relationship:
      "Two broad water marks cross one fieldstone ridge, making the river-to-Sound connection legible at miniature scale.",
    edgeStrategy: "The tidal ridge reaches the bottom edge while the river exits through the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "delaware",
    sourceCue: "Atlantic dunes meeting the salt marshes of Delaware Bay",
    primaryStyleId: "mineral-line-engraving",
    palette: palette(
      ["dune cream", "#E4D2A7"],
      ["marsh green", "#607A4B"],
      ["bay blue", "#4E8398"],
      ["shell pink", "#D7A095"],
    ),
    motifs: [
      motif("Atlantic dunes meeting the salt marshes of Delaware Bay", "horizon", 1, 0.5, 0.68, 0.8, 0.25),
      motif("a tidal creek reflecting an open coastal sky", "ribbon", 2, 0.5, 0.47, 0.64, 0.14),
      motif("low coastal plain, barrier beaches, marsh, and estuary", "stripe", 3, 0.5, 0.79, 0.76, 0.14),
    ],
    relationship: "One tidal creek divides the dune horizon from a low shell-pink coastal band.",
    edgeStrategy: "The barrier beach runs along the bottom edge and the bay color opens at the right edge.",
  }),
  defineLandscapeArtProfile({
    slug: "florida",
    sourceCue: "Everglades sawgrass opening around mangrove islands and a roseate spoonbill",
    primaryStyleId: "aquatint-atmosphere",
    palette: palette(
      ["sawgrass green", "#6D7C3A"],
      ["mangrove black", "#1F302D"],
      ["spoonbill pink", "#D88791"],
      ["turquoise", "#39969B"],
      ["sun gold", "#E2B54A"],
    ),
    motifs: [
      motif(
        "Everglades sawgrass opening around mangrove islands and a roseate spoonbill",
        "bird",
        2,
        0.68,
        0.34,
        0.44,
        0.26,
      ),
      motif("fresh water moving almost invisibly toward the sea", "ribbon", 3, 0.5, 0.56, 0.68, 0.14),
      motif(
        "wet prairie, limestone keys, mangrove coast, and shallow reef",
        "horizon",
        1,
        0.5,
        0.76,
        0.82,
        0.22,
      ),
    ],
    relationship: "A single spoonbill crosses one slow freshwater path above the mangrove coast.",
    edgeStrategy: "The wet prairie reaches the bottom edge and turquoise water exits at the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "georgia",
    sourceCue: "live oaks and salt-marsh grass along the Georgia coast",
    primaryStyleId: "risograph-overprint",
    palette: palette(
      ["marsh gold", "#C69B46"],
      ["live-oak green", "#3E5C3D"],
      ["tidal blue", "#4B8193"],
      ["clay red", "#A6533E"],
    ),
    motifs: [
      motif("live oaks and salt-marsh grass along the Georgia coast", "leaf", 1, 0.3, 0.36, 0.42, 0.22),
      motif("golden tidal channels threading beneath broad shade", "ribbon", 2, 0.57, 0.55, 0.58, 0.14),
      motif(
        "Blue Ridge headwaters, Piedmont, coastal plain, and barrier islands",
        "horizon",
        3,
        0.5,
        0.76,
        0.82,
        0.22,
      ),
    ],
    relationship: "One oak canopy shades a single tidal channel before the barrier-island plain opens below.",
    edgeStrategy: "The coastal plain meets the bottom edge while the oak canopy breaks only the left edge.",
  }),
] as const;
