import {
  arc,
  circle,
  color,
  curve,
  ellipse,
  forms,
  palette,
  polygon,
  recipe,
  rect,
} from "./code-native-art-recipe-builders";

export const codeNativeSciencePhilosophyRecipes = [
  recipe({
    catalogueDirectory: "books-read",
    slug: "a-brief-history-of-time",
    primaryStyleId: "screenprint-night",
    manufacturingLanguage: "screenprint-masses",
    styleComparison:
      "Preserves screenprint-night through expanding spot-color rings without starscape speckle or gradients.",
    forms: forms("one black center", "two expanding rings", "one curved star ribbon"),
    relationship: "Two rings expand from darkness while one star ribbon bends around them.",
    palette: palette(
      color("night black", "#11151B"),
      color("deep blue", "#1F396B"),
      color("silver", "#C7D0D3"),
      color("electric cyan", "#36B8C8"),
    ),
    backgroundColor: 1,
    commands: [
      circle(0, 448, 448, 118),
      arc(2, 448, 448, 234, 182, 0, 360),
      arc(3, 448, 448, 350, 294, 0, 360),
      curve(2, 44, [-40, 674], [236, 412], [616, 236], [940, 354]),
    ],
    minimumFeaturePixels: 44,
    minimumNegativeGapPixels: 52,
    edgeStrategy:
      "The star ribbon bleeds left and right while deep blue reaches top and bottom; rings do not create an outer inset.",
    sourceSpecificExclusions: [
      "exactly two rings",
      "no individual stars or constellation marks",
      "no lens glow or gradient",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-selfish-gene",
    primaryStyleId: "stained-glass-field",
    manufacturingLanguage: "large-stained-glass-cells",
    styleComparison:
      "Preserves stained-glass-field through a few broad ribbon cells without tiny biological compartments or tessellation.",
    forms: forms("two thick helix ribbons", "three broad connecting bridges", "one cell disk"),
    relationship: "Two ribbons pass through one cell with exactly three durable bridges.",
    palette: palette(
      color("cobalt", "#2855A5"),
      color("amber", "#D49A34"),
      color("deep violet", "#403068"),
      color("clear white", "#F0ECD9"),
    ),
    backgroundColor: 2,
    commands: [
      circle(3, 448, 448, 334),
      curve(0, 92, [256, 164], [650, 260], [238, 604], [640, 742]),
      curve(1, 92, [640, 164], [246, 260], [658, 604], [256, 742]),
      rect(2, 330, 286, 236, 46),
      rect(2, 330, 426, 236, 46),
      rect(2, 330, 566, 236, 46),
    ],
    minimumFeaturePixels: 46,
    minimumNegativeGapPixels: 28,
    edgeStrategy:
      "Violet reaches all four edges; the cell remains a large central field rather than an enclosing badge border.",
    sourceSpecificExclusions: [
      "exactly two ribbons and three bridges",
      "no DNA letters, base pairs, organelles, or tiny cells",
      "no glowing or glass depth",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-gene",
    primaryStyleId: "cyanotype-field-study",
    manufacturingLanguage: "cyanotype-silhouette",
    styleComparison:
      "Preserves cyanotype-field-study using broad exposed silhouettes without botanical veins, family figures, or photographic grain.",
    forms: forms("one large chromosome silhouette", "one branching lineage form", "one luminous cell"),
    relationship: "The lineage grows from the chromosome and resolves inside the cell.",
    palette: palette(
      color("Prussian blue", "#173F78"),
      color("exposure white", "#EEF0DE"),
      color("botanical green", "#4D8155"),
      color("mineral gold", "#D0A344"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(
        1,
        260,
        120,
        390,
        120,
        470,
        210,
        438,
        340,
        380,
        420,
        430,
        540,
        520,
        690,
        420,
        780,
        300,
        710,
        270,
        570,
        300,
        450,
        240,
        340,
        180,
        230,
      ),
      curve(2, 70, [390, 492], [484, 402], [570, 306], [642, 202]),
      curve(2, 58, [520, 360], [632, 400], [718, 344], [786, 302]),
      circle(3, 694, 212, 122),
      circle(1, 694, 212, 62),
    ],
    minimumFeaturePixels: 58,
    minimumNegativeGapPixels: 28,
    edgeStrategy:
      "Prussian blue fills all four edges; chromosome and lineage stay open silhouettes without a containing frame.",
    sourceSpecificExclusions: [
      "no human lineage figures or family tree labels",
      "no chromosome bands or cell organelles",
      "no cyanotype grain",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-emperor-of-all-maladies",
    primaryStyleId: "monoprint-ink-wash",
    manufacturingLanguage: "monoprint-overlap",
    styleComparison:
      "Preserves monoprint-ink-wash through a few offset overlapping masses without porous cells, washes, or gradients.",
    forms: forms("one dark cellular knot", "one clean white fork", "one gold horizon band"),
    relationship: "The clean fork opens the knot toward the narrow horizon.",
    palette: palette(
      color("charcoal", "#202326"),
      color("bone white", "#EEE5D0"),
      color("muted crimson", "#973F46"),
      color("restrained gold", "#C79A40"),
    ),
    backgroundColor: 1,
    commands: [
      rect(3, 0, 188, 896, 82),
      polygon(0, 180, 704, 132, 448, 306, 286, 500, 322, 692, 250, 790, 472, 670, 730, 420, 782),
      circle(2, 410, 520, 132),
      curve(1, 76, [430, 680], [430, 548], [462, 438], [530, 326]),
      curve(1, 62, [514, 358], [578, 292], [650, 248], [720, 222]),
      curve(1, 62, [514, 358], [540, 282], [552, 240], [566, 194]),
    ],
    minimumFeaturePixels: 62,
    minimumNegativeGapPixels: 30,
    edgeStrategy:
      "Gold horizon bleeds left and right, bone reaches top, and the knot exits bottom without an inset boundary.",
    sourceSpecificExclusions: [
      "one knot only",
      "no crown, cells, pores, veins, or medical iconography",
      "fork must remain white and open upward",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "cosmos",
    primaryStyleId: "scratchboard-nocturne",
    manufacturingLanguage: "scratchboard-cut-silhouette",
    styleComparison:
      "Preserves scratchboard-nocturne through broad inverse cut silhouettes without scratches, star speckle, or etched lines.",
    forms: forms("one ringed planet", "one observatory dome", "one broad Milky Way arc"),
    relationship: "The observatory faces the planet beneath one immense stellar arc.",
    palette: palette(
      color("black", "#101316"),
      color("star white", "#ECE8D8"),
      color("indigo", "#303B71"),
      color("restrained copper", "#B8783E"),
    ),
    backgroundColor: 0,
    commands: [
      arc(1, 448, 482, 430, 354, 198, 344),
      circle(3, 638, 270, 128),
      arc(1, 638, 270, 200, 166, 166, 374),
      rect(2, 142, 674, 286, 222),
      ellipse(1, 285, 674, 143, 112),
      rect(0, 206, 674, 158, 222),
    ],
    minimumFeaturePixels: 34,
    minimumNegativeGapPixels: 30,
    edgeStrategy:
      "The Milky Way arc bleeds left and right; black reaches all edges and the observatory exits bottom.",
    sourceSpecificExclusions: [
      "no individual stars, constellations, or galaxy texture",
      "no telescope or building detail",
      "one planet only",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "meditations",
    primaryStyleId: "woven-tapestry-field",
    manufacturingLanguage: "broad-woven-bands",
    styleComparison:
      "Preserves woven-tapestry-field using broad nested bands without stitches, fibers, hatching, or weave texture.",
    forms: forms("one calm central flame", "two concentric stone arcs", "one surrounding storm band"),
    relationship: "The flame stays upright inside exactly two arcs while the storm remains outside.",
    palette: palette(
      color("indigo", "#283A62"),
      color("wool gray", "#8A8C8A"),
      color("stone cream", "#D9CBAE"),
      color("ember gold", "#E0A33A"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(1, 102, 220, 260, 92, 636, 92, 794, 220, 836, 584, 704, 806, 192, 806, 60, 584),
      arc(2, 448, 490, 300, 244, 22, 158),
      arc(2, 448, 500, 198, 142, 16, 164),
      polygon(3, 448, 636, 366, 528, 408, 430, 448, 292, 488, 430, 530, 528),
      polygon(2, 448, 574, 414, 520, 448, 420, 482, 520),
    ],
    minimumFeaturePixels: 56,
    minimumNegativeGapPixels: 46,
    edgeStrategy:
      "Indigo storm reaches all four edges; the inner gray plane is irregular and never becomes an outer inset border.",
    sourceSpecificExclusions: [
      "exactly two arcs",
      "no stitches, fibers, or segmented ring",
      "flame must remain upright",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-republic",
    primaryStyleId: "fresco-mineral-pigment",
    manufacturingLanguage: "mineral-fresco-planes",
    styleComparison:
      "Preserves fresco-mineral-pigment through broad cave and stair planes without rays, stone texture, or architectural detail.",
    forms: forms("one cave arch", "one rising stair path", "one brilliant sun disk"),
    relationship: "The steps rise from the enclosing cave arch into the unobstructed sun.",
    palette: palette(
      color("plaster white", "#E8DFC8"),
      color("cave umber", "#604538"),
      color("mineral blue", "#416D85"),
      color("sun gold", "#D8A439"),
    ),
    backgroundColor: 0,
    commands: [
      circle(3, 676, 208, 140),
      arc(1, 338, 610, 330, 210, 180, 360),
      rect(1, 8, 608, 120, 288),
      rect(1, 548, 608, 120, 288),
      polygon(
        2,
        180,
        896,
        180,
        786,
        292,
        786,
        292,
        674,
        404,
        674,
        404,
        562,
        516,
        562,
        516,
        450,
        628,
        450,
        628,
        896,
      ),
    ],
    minimumFeaturePixels: 112,
    minimumNegativeGapPixels: 30,
    edgeStrategy:
      "Cave legs and stair plane exit bottom, plaster reaches top, and the composition stays open at left and right.",
    sourceSpecificExclusions: [
      "no tiny stair treads beyond four broad rises",
      "no cave texture or sun rays",
      "no figures",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "mans-search-for-meaning",
    primaryStyleId: "monoprint-ink-wash",
    manufacturingLanguage: "monoprint-overlap",
    styleComparison:
      "Preserves monoprint-ink-wash through an offset enclosure and figure silhouette without washes, bars, or photorealism.",
    forms: forms("one broken enclosure", "one upright human silhouette", "one horizon glow"),
    relationship: "The figure stands within the break and faces the distant light.",
    palette: palette(
      color("ink black", "#1B1E20"),
      color("warm gray", "#85847E"),
      color("paper white", "#EEE8D8"),
      color("quiet amber", "#C99843"),
    ),
    backgroundColor: 1,
    commands: [
      rect(3, 0, 224, 896, 104),
      rect(0, 122, 320, 92, 576),
      rect(0, 122, 804, 650, 92),
      rect(0, 680, 548, 92, 348),
      circle(2, 448, 474, 68),
      polygon(2, 370, 806, 382, 574, 448, 536, 514, 574, 526, 806),
    ],
    minimumFeaturePixels: 68,
    minimumNegativeGapPixels: 92,
    edgeStrategy:
      "Amber horizon crosses left and right, enclosure exits bottom, and warm gray remains open at top.",
    sourceSpecificExclusions: [
      "no bars, wire, camp architecture, or historical uniform",
      "one figure only",
      "enclosure must contain one broad break",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-myth-of-sisyphus",
    primaryStyleId: "relief-blockprint",
    manufacturingLanguage: "relief-cut-spot-shapes",
    styleComparison:
      "Preserves relief-blockprint through three hard spot-color cuts without veins, rays, hatching, or carved texture.",
    forms: forms("one steep slope", "one monumental round stone", "one rising sun"),
    relationship: "The stone holds against the slope while dawn begins behind it.",
    palette: palette(
      color("paper cream", "#EEE0BC"),
      color("ink black", "#1E2022"),
      color("stone gray", "#777B7D"),
      color("ochre", "#D99A2B"),
    ),
    backgroundColor: 0,
    commands: [circle(3, 680, 266, 176), polygon(1, -40, 896, 896, 124, 936, 896), circle(2, 530, 312, 132)],
    minimumFeaturePixels: 132,
    minimumNegativeGapPixels: 30,
    edgeStrategy: "Slope bleeds left, right, and bottom; cream reaches top, so no four-edge inset can form.",
    sourceSpecificExclusions: [
      "no slope veins or sun rays",
      "no four-edge inset",
      "stone must touch the slope and overlap the sun",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "justice",
    primaryStyleId: "prismatic-geometric-symbolism",
    manufacturingLanguage: "prismatic-cells",
    styleComparison:
      "Preserves prismatic-geometric-symbolism using three large directional cells without facets, scales, or ornamental geometry.",
    forms: forms("two contrasting paths", "one central light", "one shared circular ground"),
    relationship: "Two paths hold equal weight before meeting at the light on shared ground.",
    palette: palette(
      color("deep navy", "#1B2D4D"),
      color("rust", "#A84A38"),
      color("clear teal", "#2E8B83"),
      color("warm white", "#EFE5CE"),
    ),
    backgroundColor: 0,
    commands: [
      circle(3, 448, 500, 330),
      curve(1, 116, [-50, 760], [192, 706], [276, 548], [448, 500]),
      curve(2, 116, [946, 760], [704, 706], [620, 548], [448, 500]),
      circle(0, 448, 500, 82),
      circle(3, 448, 500, 42),
    ],
    minimumFeaturePixels: 40,
    minimumNegativeGapPixels: 32,
    edgeStrategy:
      "Contrasting paths bleed left and right; navy reaches top and bottom around the shared circular field.",
    sourceSpecificExclusions: [
      "no scale, gavel, courthouse, or political emblem",
      "paths must have equal width",
      "one central light only",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "nicomachean-ethics",
    primaryStyleId: "ceramic-underglaze",
    manufacturingLanguage: "ceramic-underglaze-fields",
    styleComparison:
      "Preserves ceramic-underglaze through a few calm fired-color fields without glaze shine, cracks, or painted ornament.",
    forms: forms("one middle path", "two dark cliff masses", "one olive branch"),
    relationship: "The path keeps a deliberate course between two extremes toward the open olive branch.",
    palette: palette(
      color("clay cream", "#E8D9B8"),
      color("olive green", "#617A45"),
      color("iron black", "#25282A"),
      color("warm terracotta", "#B65B43"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(2, 0, 896, 0, 256, 232, 326, 330, 584, 254, 896),
      polygon(2, 896, 896, 896, 246, 676, 330, 570, 584, 646, 896),
      curve(3, 112, [448, 940], [420, 706], [474, 478], [510, 300]),
      curve(1, 62, [474, 288], [560, 248], [650, 210], [774, 190]),
      polygon(1, 548, 220, 606, 150, 682, 176, 618, 246),
      polygon(1, 648, 222, 718, 190, 786, 230, 704, 274),
    ],
    minimumFeaturePixels: 62,
    minimumNegativeGapPixels: 42,
    edgeStrategy:
      "Both cliffs and the middle path exit bottom, cliffs bleed left and right, and cream remains open at top.",
    sourceSpecificExclusions: [
      "exactly two cliff masses and one path",
      "no scales, columns, bust, lettering, or Greek-key ornament",
      "olive branch limited to one broad stem and two large leaves",
    ],
  }),
] as const;
