import { defineLandscapeArtProfile, motif, palette } from "./code-native-landscape-profile";

export const codeNativeUsStateProfiles02 = [
  defineLandscapeArtProfile({
    slug: "hawaii",
    sourceCue: "dark volcanic slopes meeting the Pacific beside red ʻōhiʻa lehua blossoms",
    primaryStyleId: "matte-gouache-editorial",
    palette: palette(
      ["lava black", "#242421"],
      ["ocean cobalt", "#286A9A"],
      ["lehua red", "#C94335"],
      ["fern green", "#3E7048"],
      ["cloud white", "#EAE9DF"],
    ),
    motifs: [
      motif(
        "dark volcanic slopes meeting the Pacific beside red ʻōhiʻa lehua blossoms",
        "triangle",
        2,
        0.38,
        0.4,
        0.5,
        0.46,
      ),
      motif("new land cooling at the edge of an immense ocean", "horizon", 1, 0.5, 0.68, 0.8, 0.23),
      motif(
        "shield volcanoes, rain forest, dry leeward slopes, and coral coast",
        "leaf",
        3,
        0.73,
        0.42,
        0.25,
        0.3,
      ),
    ],
    relationship:
      "A dark volcanic mass meets one Pacific band while a single lehua-colored leaf marks the living coast.",
    edgeStrategy: "The Pacific reaches the bottom edge and the volcanic slope presses through the left side.",
  }),
  defineLandscapeArtProfile({
    slug: "idaho",
    sourceCue: "the jagged Sawtooth Range reflected in a clear alpine lake",
    primaryStyleId: "woven-tapestry-field",
    palette: palette(
      ["granite gray", "#6E7476"],
      ["lake blue", "#4D89A5"],
      ["pine green", "#315442"],
      ["snow white", "#EDF0EA"],
      ["sage", "#82906A"],
    ),
    motifs: [
      motif(
        "the jagged Sawtooth Range reflected in a clear alpine lake",
        "triangle",
        3,
        0.5,
        0.36,
        0.56,
        0.46,
      ),
      motif("a cold headwater beginning beneath granite peaks", "ribbon", 1, 0.5, 0.59, 0.62, 0.14),
      motif(
        "mountain ranges, deep river canyons, forest, and volcanic plain",
        "horizon",
        2,
        0.5,
        0.77,
        0.82,
        0.21,
      ),
    ],
    relationship: "One snow peak reflects into a single cold headwater above the dark forested plain.",
    edgeStrategy: "The volcanic plain spans the bottom edge while the peak leaves both upper corners open.",
  }),
  defineLandscapeArtProfile({
    slug: "illinois",
    sourceCue: "Chicago's lakefront skyline rising beyond the blue plane of Lake Michigan",
    primaryStyleId: "cut-paper-strata",
    palette: palette(
      ["lake blue", "#4A82A0"],
      ["steel gray", "#666F76"],
      ["prairie gold", "#C7A14A"],
      ["brick red", "#9D4B3C"],
    ),
    motifs: [
      motif(
        "Chicago's lakefront skyline rising beyond the blue plane of Lake Michigan",
        "block",
        1,
        0.55,
        0.39,
        0.48,
        0.44,
      ),
      motif("prairie lines converging on a city of vertical light", "stripe", 3, 0.39, 0.58, 0.58, 0.14),
      motif(
        "tallgrass plain, great rivers, glacial hills, and freshwater shore",
        "horizon",
        2,
        0.5,
        0.76,
        0.82,
        0.22,
      ),
    ],
    relationship: "One steel skyline rises from a single lake plane as a prairie line converges beneath it.",
    edgeStrategy:
      "The freshwater shore runs along the bottom edge and the skyline opens toward the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "indiana",
    sourceCue: "marram grass bending across the dunes of Lake Michigan",
    primaryStyleId: "cyanotype-field-study",
    palette: palette(
      ["dune cream", "#DDCDA4"],
      ["lake blue", "#477F9C"],
      ["marram green", "#667A48"],
      ["cloud silver", "#C4C5BF"],
    ),
    motifs: [
      motif("marram grass bending across the dunes of Lake Michigan", "leaf", 2, 0.3, 0.4, 0.42, 0.18),
      motif("wind-written sand opening toward a freshwater horizon", "stripe", 1, 0.56, 0.56, 0.62, 0.14),
      motif(
        "glacial plain, hardwood forest, river lowlands, and lake dunes",
        "horizon",
        3,
        0.5,
        0.76,
        0.82,
        0.22,
      ),
    ],
    relationship: "One bent grass form leads across a broad dune mark toward the freshwater horizon.",
    edgeStrategy: "The lake dune meets the bottom edge while the horizon opens fully along the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "iowa",
    sourceCue: "the Loess Hills rising above patchwork farms near the Missouri River",
    primaryStyleId: "watercolor-naturalist-study",
    palette: palette(
      ["corn gold", "#D0A33D"],
      ["prairie green", "#687A45"],
      ["soil umber", "#73503B"],
      ["river blue", "#4E8498"],
    ),
    motifs: [
      motif(
        "the Loess Hills rising above patchwork farms near the Missouri River",
        "horizon",
        2,
        0.5,
        0.52,
        0.78,
        0.34,
      ),
      motif("patient field lines following wind-shaped ridges", "stripe", 1, 0.5, 0.65, 0.66, 0.14),
      motif(
        "rolling prairie, glacial plains, river valleys, and loess bluffs",
        "ribbon",
        3,
        0.5,
        0.79,
        0.76,
        0.14,
      ),
    ],
    relationship: "One loess ridge carries a single field line toward the Missouri River at its base.",
    edgeStrategy: "The river valley reaches the bottom edge and the rolling ridge spans both side margins.",
  }),
  defineLandscapeArtProfile({
    slug: "kansas",
    sourceCue: "Flint Hills tallgrass rolling beneath a summer thunderstorm",
    primaryStyleId: "charcoal-pastel-weather",
    palette: palette(
      ["grass green", "#536B3D"],
      ["storm violet", "#55465F"],
      ["limestone cream", "#D9CBA7"],
      ["lightning gold", "#E0B744"],
    ),
    motifs: [
      motif(
        "Flint Hills tallgrass rolling beneath a summer thunderstorm",
        "horizon",
        1,
        0.5,
        0.48,
        0.8,
        0.34,
      ),
      motif("one luminous horizon holding weather and open distance", "stripe", 3, 0.5, 0.61, 0.7, 0.14),
      motif(
        "high plains, prairie uplands, river valleys, and chalk bluffs",
        "ribbon",
        2,
        0.5,
        0.78,
        0.76,
        0.14,
      ),
    ],
    relationship: "A single storm mass floats over one gold horizon and a broad rolling prairie line.",
    edgeStrategy: "The tallgrass plain reaches the bottom edge while storm violet remains open at the top.",
  }),
  defineLandscapeArtProfile({
    slug: "kentucky",
    sourceCue: "a lantern revealing the broad limestone passages of Mammoth Cave",
    primaryStyleId: "screenprint-night",
    palette: palette(
      ["cave black", "#202322"],
      ["lantern amber", "#D48D35"],
      ["limestone gray", "#89887D"],
      ["bluegrass green", "#416342"],
    ),
    motifs: [
      motif(
        "a lantern revealing the broad limestone passages of Mammoth Cave",
        "arch",
        2,
        0.5,
        0.43,
        0.64,
        0.5,
      ),
      motif("a small warm light entering a vast hidden landscape", "disk", 1, 0.5, 0.46, 0.16, 0.16),
      motif(
        "karst plateau, wooded knobs, bluegrass uplands, and river valleys",
        "horizon",
        3,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship: "One amber light sits inside a single limestone passage above the bluegrass karst base.",
    edgeStrategy:
      "The cave field reaches the left and right edges while the karst base meets the bottom edge.",
  }),
  defineLandscapeArtProfile({
    slug: "louisiana",
    sourceCue: "bald cypress and knees standing in a quiet bayou",
    primaryStyleId: "mosaic-tesserae-field",
    palette: palette(
      ["cypress green", "#395B44"],
      ["water black", "#202E2D"],
      ["Spanish-moss silver", "#A8AAA0"],
      ["egret white", "#EEECE1"],
      ["mud ochre", "#99703E"],
    ),
    motifs: [
      motif("bald cypress and knees standing in a quiet bayou", "triangle", 2, 0.3, 0.4, 0.32, 0.44),
      motif("reflected branches turning water into a second forest", "oval", 1, 0.58, 0.58, 0.56, 0.2),
      motif(
        "delta plain, natural levees, wetlands, bayous, and Gulf marsh",
        "horizon",
        4,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship: "One cypress mass stands above a single dark reflection and the ochre delta plain.",
    edgeStrategy: "The Gulf marsh reaches the bottom edge and the reflected water exits at the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "maine",
    sourceCue: "a granite Atlantic headland with spruce islands and a working lighthouse",
    primaryStyleId: "fresco-mineral-pigment",
    palette: palette(
      ["granite gray", "#737878"],
      ["spruce green", "#2F5142"],
      ["Atlantic navy", "#294B63"],
      ["beacon gold", "#D8AA43"],
    ),
    motifs: [
      motif(
        "a granite Atlantic headland with spruce islands and a working lighthouse",
        "block",
        1,
        0.3,
        0.43,
        0.16,
        0.46,
      ),
      motif("a steady beam crossing cold coastal weather", "stripe", 3, 0.59, 0.34, 0.56, 0.14),
      motif(
        "rocky coast, forested interior, lakes, and rounded mountains",
        "horizon",
        2,
        0.5,
        0.76,
        0.82,
        0.23,
      ),
    ],
    relationship: "One lighthouse block sends a single gold beam across the dark Atlantic headland.",
    edgeStrategy: "The rocky coast reaches the bottom edge and the beacon beam exits through the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "maryland",
    sourceCue: "a Chesapeake Bay skipjack crossing among tidal creeks and blue herons",
    primaryStyleId: "prismatic-geometric-symbolism",
    palette: palette(
      ["bay blue", "#467F9B"],
      ["marsh green", "#61764B"],
      ["sail cream", "#EEE2C7"],
      ["heron gray", "#858C8C"],
      ["sunset copper", "#B26442"],
    ),
    motifs: [
      motif(
        "a Chesapeake Bay skipjack crossing among tidal creeks and blue herons",
        "triangle",
        2,
        0.46,
        0.42,
        0.4,
        0.4,
      ),
      motif("many tributaries joining one wide estuary", "ribbon", 4, 0.5, 0.59, 0.64, 0.14),
      motif(
        "Appalachian ridge, Piedmont rivers, coastal plain, and tidal bay",
        "horizon",
        1,
        0.5,
        0.77,
        0.82,
        0.21,
      ),
    ],
    relationship: "One cream sail crosses a single copper tributary above the broad marsh-and-bay plane.",
    edgeStrategy:
      "The Chesapeake plane runs to the bottom edge and its estuary opens through the right side.",
  }),
] as const;
