import { defineLandscapeArtProfile, motif, palette } from "./code-native-landscape-profile";

export const codeNativeUsStateProfiles05 = [
  defineLandscapeArtProfile({
    slug: "south-dakota",
    sourceCue: "striped Badlands pinnacles opening abruptly from mixed-grass prairie",
    primaryStyleId: "screenprint-night",
    palette: palette(
      ["clay rose", "#B56C5F"],
      ["prairie gold", "#C79C42"],
      ["sage green", "#6D7D57"],
      ["violet shadow", "#5E4E69"],
    ),
    motifs: [
      motif(
        "striped Badlands pinnacles opening abruptly from mixed-grass prairie",
        "triangle",
        3,
        0.5,
        0.41,
        0.56,
        0.48,
      ),
      motif("eroded towers catching the last warm light", "stripe", 1, 0.5, 0.59, 0.66, 0.14),
      motif("prairie plains, Missouri breaks, Black Hills, and badlands", "horizon", 2, 0.5, 0.78, 0.82, 0.2),
    ],
    relationship: "One violet pinnacle rises through a single gold light band above the sage prairie.",
    edgeStrategy: "The prairie reaches the bottom edge and the eroded tower leaves both top corners open.",
  }),
  defineLandscapeArtProfile({
    slug: "tennessee",
    sourceCue: "blue Great Smoky Mountain ridges rising behind flowering rhododendron",
    primaryStyleId: "mosaic-tesserae-field",
    palette: palette(
      ["smoky blue", "#587D91"],
      ["forest green", "#3D6043"],
      ["rhododendron pink", "#C6778E"],
      ["haze gold", "#C5A25C"],
    ),
    motifs: [
      motif(
        "blue Great Smoky Mountain ridges rising behind flowering rhododendron",
        "triangle",
        2,
        0.48,
        0.4,
        0.56,
        0.48,
      ),
      motif("layer after layer of forest dissolving into warm haze", "stripe", 3, 0.5, 0.61, 0.7, 0.14),
      motif(
        "Appalachian mountains, ridge and valley, central basin, and Mississippi plain",
        "horizon",
        1,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship:
      "One pink mountain mass dissolves through a single gold haze band above the green central basin.",
    edgeStrategy: "The central basin reaches the bottom edge and the smoky ridge opens along the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "texas",
    sourceCue: "the Rio Grande curving through the sheer walls of Santa Elena Canyon",
    primaryStyleId: "fresco-mineral-pigment",
    palette: palette(
      ["adobe red", "#A6533C"],
      ["river teal", "#3F8583"],
      ["desert gold", "#D1A046"],
      ["cactus green", "#477047"],
      ["sky cobalt", "#326A9A"],
    ),
    motifs: [
      motif(
        "the Rio Grande curving through the sheer walls of Santa Elena Canyon",
        "corner",
        2,
        0.5,
        0.4,
        0.66,
        0.48,
      ),
      motif(
        "one river drawing a bright line across immense desert stone",
        "ribbon",
        1,
        0.5,
        0.61,
        0.68,
        0.14,
      ),
      motif(
        "Gulf plain, prairie, hill country, desert basins, and mountain ranges",
        "horizon",
        3,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship: "One canyon wall holds a single teal river line above the broad desert-and-prairie plane.",
    edgeStrategy: "The desert basin reaches the bottom edge and the Rio Grande exits through the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "utah",
    sourceCue: "a sandstone arch framing fins, canyon plateaus, and desert sky",
    primaryStyleId: "prismatic-geometric-symbolism",
    palette: palette(
      ["sandstone orange", "#C96632"],
      ["cream", "#E8D6B0"],
      ["sage green", "#6F8058"],
      ["indigo", "#3E486F"],
      ["sun gold", "#E0B13E"],
    ),
    motifs: [
      motif(
        "a sandstone arch framing fins, canyon plateaus, and desert sky",
        "arch",
        1,
        0.5,
        0.41,
        0.64,
        0.5,
      ),
      motif("open stone holding a window onto deep geologic distance", "arch", 3, 0.5, 0.45, 0.32, 0.28),
      motif(
        "Colorado Plateau canyons, Great Basin ranges, salt flats, and Wasatch peaks",
        "horizon",
        2,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship: "One cream arch frames a single indigo distance above the sage plateau.",
    edgeStrategy: "The salt-flat plateau reaches the bottom edge while the arch leaves the upper field open.",
  }),
  defineLandscapeArtProfile({
    slug: "vermont",
    sourceCue: "a covered bridge crossing a clear river beneath autumn Green Mountains",
    primaryStyleId: "ceramic-underglaze",
    palette: palette(
      ["maple red", "#A44635"],
      ["forest green", "#3E6142"],
      ["bridge white", "#EFE9DA"],
      ["river blue", "#4A819A"],
      ["gold", "#D1A13D"],
    ),
    motifs: [
      motif(
        "a covered bridge crossing a clear river beneath autumn Green Mountains",
        "block",
        2,
        0.5,
        0.42,
        0.68,
        0.22,
      ),
      motif("a small passage joining two wooded banks", "arch", 4, 0.5, 0.46, 0.3, 0.24),
      motif(
        "Green Mountain spine, river valleys, hardwood forest, and lake shore",
        "horizon",
        1,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship: "One white bridge block crosses a single gold passage above the green river-valley shore.",
    edgeStrategy: "The wooded valley reaches the bottom edge and the river passage opens at the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "virginia",
    sourceCue: "Shenandoah Valley fields held between long blue mountain ridges",
    primaryStyleId: "wood-marquetry-landscape",
    palette: palette(
      ["ridge blue", "#537C94"],
      ["field green", "#587141"],
      ["river silver", "#A6B3B3"],
      ["autumn copper", "#A85F3C"],
    ),
    motifs: [
      motif(
        "Shenandoah Valley fields held between long blue mountain ridges",
        "horizon",
        1,
        0.5,
        0.47,
        0.82,
        0.34,
      ),
      motif("a river valley opening east from the Appalachian wall", "ribbon", 2, 0.5, 0.62, 0.66, 0.14),
      motif(
        "ridge and valley, Blue Ridge, Piedmont rivers, and Chesapeake plain",
        "stripe",
        3,
        0.5,
        0.79,
        0.76,
        0.14,
      ),
    ],
    relationship:
      "One long blue ridge holds a single silver river opening above the copper Chesapeake plain.",
    edgeStrategy: "The Chesapeake plain meets the bottom edge while the Shenandoah opens at the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "washington",
    sourceCue: "Mount Rainier above dark evergreen forest and subalpine wildflowers",
    primaryStyleId: "scratchboard-nocturne",
    palette: palette(
      ["glacier white", "#EEF0E9"],
      ["fir green", "#2E5643"],
      ["sky blue", "#568AA8"],
      ["wildflower magenta", "#B55078"],
      ["basalt gray", "#676F72"],
    ),
    motifs: [
      motif(
        "Mount Rainier above dark evergreen forest and subalpine wildflowers",
        "triangle",
        4,
        0.5,
        0.38,
        0.56,
        0.5,
      ),
      motif(
        "one ice-covered summit gathering cloud and river headwaters",
        "ribbon",
        2,
        0.5,
        0.59,
        0.62,
        0.14,
      ),
      motif(
        "Pacific coast, Olympic rainforest, Cascade volcanoes, and dry plateau",
        "horizon",
        1,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship:
      "One basalt-edged summit gathers a single sky-blue headwater above the evergreen Pacific field.",
    edgeStrategy:
      "The Pacific field reaches the bottom edge and the glacier summit leaves both top corners open.",
  }),
  defineLandscapeArtProfile({
    slug: "west-virginia",
    sourceCue: "the steel arch of New River Gorge Bridge spanning a forested canyon",
    primaryStyleId: "luminous-ligne-claire",
    palette: palette(
      ["sandstone gray", "#E6E1D4"],
      ["forest green", "#315C43"],
      ["steel rust", "#9A503B"],
      ["river blue", "#4B8398"],
      ["autumn gold", "#D0A13F"],
    ),
    motifs: [
      motif(
        "the steel arch of New River Gorge Bridge spanning a forested canyon",
        "arch",
        2,
        0.5,
        0.39,
        0.62,
        0.38,
      ),
      motif("a single curve joining steep Appalachian walls", "stripe", 3, 0.5, 0.55, 0.5, 0.12),
      motif(
        "dissected plateau, narrow valleys, sandstone gorges, and forested ridges",
        "horizon",
        1,
        0.5,
        0.76,
        0.72,
        0.18,
      ),
    ],
    accent: motif("one open New River journey", "ribbon", 4, 0.58, 0.27, 0.42, 0.12),
    relationship:
      "One rust arch, one blue canyon curve, and one low ridge leave open sky around a gold journey line.",
    edgeStrategy:
      "The forested ridge rests on the bottom edge while the open journey exits at the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "wisconsin",
    sourceCue: "Apostle Islands sandstone sea caves opening onto Lake Superior",
    primaryStyleId: "pixel-cluster-landscape",
    palette: palette(
      ["sandstone red", "#A8583E"],
      ["lake blue", "#427F9B"],
      ["ice white", "#EDF0E9"],
      ["pine green", "#365B45"],
    ),
    motifs: [
      motif(
        "Apostle Islands sandstone sea caves opening onto Lake Superior",
        "arch",
        2,
        0.5,
        0.42,
        0.64,
        0.5,
      ),
      motif("freshwater waves carving rooms into red rock", "ribbon", 1, 0.5, 0.6, 0.66, 0.14),
      motif(
        "glacial lake country, northern forest, driftless hills, and Great Lakes shore",
        "horizon",
        3,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship:
      "One ice-white sea cave opens around a single blue wave above the pine-green Great Lakes shore.",
    edgeStrategy:
      "The Great Lakes shore reaches the bottom edge and the freshwater wave exits at the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "wyoming",
    sourceCue: "the Grand Teton rising above sagebrush and the winding Snake River",
    primaryStyleId: "thread-painted-embroidery",
    palette: palette(
      ["granite gray", "#73797A"],
      ["sage green", "#71805A"],
      ["river blue", "#4A829C"],
      ["snow white", "#EFF0E8"],
      ["sunrise rose", "#C98176"],
    ),
    motifs: [
      motif(
        "the Grand Teton rising above sagebrush and the winding Snake River",
        "triangle",
        3,
        0.48,
        0.38,
        0.56,
        0.5,
      ),
      motif("a sharp mountain silhouette anchoring an open basin", "stripe", 4, 0.5, 0.57, 0.64, 0.14),
      motif(
        "high basins, mountain ranges, volcanic plateau, and grassland",
        "ribbon",
        2,
        0.5,
        0.78,
        0.76,
        0.14,
      ),
    ],
    relationship:
      "One snow-white Teton silhouette anchors a single rose basin line above the blue Snake River.",
    edgeStrategy: "The high basin reaches the bottom edge and the sharp summit leaves the upper field open.",
  }),
] as const;
