import { defineLandscapeArtProfile, motif, palette } from "./code-native-landscape-profile";

export const codeNativeUsStateProfiles04 = [
  defineLandscapeArtProfile({
    slug: "new-mexico",
    sourceCue: "white gypsum dunes folding beneath the blue San Andres Mountains",
    primaryStyleId: "contour-atlas-ink",
    palette: palette(
      ["gypsum white", "#EEE9DB"],
      ["sky cobalt", "#326A9C"],
      ["adobe red", "#A6543D"],
      ["sage green", "#71805B"],
      ["violet shadow", "#62506D"],
    ),
    motifs: [
      motif(
        "white gypsum dunes folding beneath the blue San Andres Mountains",
        "triangle",
        1,
        0.51,
        0.39,
        0.56,
        0.48,
      ),
      motif("wind drawing new curves across an ancient basin", "ribbon", 4, 0.5, 0.61, 0.66, 0.14),
      motif(
        "high desert basins, mesas, volcanic fields, and mountain ranges",
        "horizon",
        2,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship: "One cobalt mountain rises above a single violet wind curve and the adobe desert basin.",
    edgeStrategy: "The gypsum basin reaches the bottom edge while the mountain leaves both top corners open.",
  }),
  defineLandscapeArtProfile({
    slug: "new-york",
    sourceCue:
      "the low broad American Falls beside the slender Bridal Veil Falls, separated by wooded Luna Island, with a distant city skyline on a flat Great Lakes horizon",
    primaryStyleId: "mineral-line-engraving",
    palette: palette(
      ["water white", "#EFF0E8"],
      ["river teal", "#3E8587"],
      ["gorge gray", "#747A7C"],
      ["maple copper", "#A65D3C"],
    ),
    motifs: [
      motif(
        "the low broad American Falls beside the slender Bridal Veil Falls, separated by wooded Luna Island, with a distant city skyline on a flat Great Lakes horizon",
        "corner",
        1,
        0.47,
        0.4,
        0.64,
        0.46,
      ),
      motif(
        "Great Lakes water gathering into one luminous edge above the Niagara River gorge",
        "stripe",
        3,
        0.5,
        0.6,
        0.7,
        0.14,
      ),
      motif(
        "the flat Niagara River corridor and urban Great Lakes plain at Niagara Falls",
        "horizon",
        2,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship:
      "One broad-and-slender waterfall edge stands above a single gray gorge and the flat teal corridor.",
    edgeStrategy:
      "The Niagara corridor runs to the bottom edge while the waterfall opens through the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "north-carolina",
    sourceCue: "layered Blue Ridge summits with blooming rhododendron in the foreground",
    primaryStyleId: "aquatint-atmosphere",
    palette: palette(
      ["ridge blue", "#517D98"],
      ["rhododendron pink", "#C87691"],
      ["forest green", "#3C6046"],
      ["mist silver", "#B4BCB9"],
    ),
    motifs: [
      motif(
        "layered Blue Ridge summits with blooming rhododendron in the foreground",
        "triangle",
        1,
        0.48,
        0.39,
        0.56,
        0.48,
      ),
      motif(
        "successive blue horizons descending toward the coastal plain",
        "stripe",
        3,
        0.5,
        0.61,
        0.7,
        0.14,
      ),
      motif(
        "Appalachian ridges, Piedmont rivers, pocosins, and barrier islands",
        "horizon",
        2,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship:
      "One Blue Ridge summit recedes through a single mist band above the forest-green coastal descent.",
    edgeStrategy: "The coastal plain reaches the bottom edge and the mist horizon exits at the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "north-dakota",
    sourceCue: "painted badlands rising behind bison and mixed-grass prairie",
    primaryStyleId: "risograph-overprint",
    palette: palette(
      ["prairie gold", "#C79D43"],
      ["clay rose", "#B66E61"],
      ["sage green", "#6F7F58"],
      ["bison brown", "#664735"],
      ["sky blue", "#6393AD"],
    ),
    motifs: [
      motif(
        "painted badlands rising behind bison and mixed-grass prairie",
        "horizon",
        1,
        0.5,
        0.49,
        0.82,
        0.34,
      ),
      motif("one dark animal crossing bands of ancient earth", "bison", 3, 0.6, 0.58, 0.42, 0.22),
      motif(
        "northern prairie, Missouri Plateau, badlands, and glacial lake plain",
        "stripe",
        2,
        0.5,
        0.79,
        0.76,
        0.14,
      ),
    ],
    relationship:
      "One dark bison silhouette crosses a single painted badland mass above the sage prairie band.",
    edgeStrategy: "The northern prairie meets the bottom edge while the badland sky stays open at the top.",
  }),
  defineLandscapeArtProfile({
    slug: "ohio",
    sourceCue: "a Hocking Hills sandstone recess beneath beech and maple forest",
    primaryStyleId: "matte-gouache-editorial",
    palette: palette(
      ["sandstone ochre", "#B7803F"],
      ["beech gold", "#D0A445"],
      ["moss green", "#526A43"],
      ["water blue", "#4D8398"],
    ),
    motifs: [
      motif(
        "a Hocking Hills sandstone recess beneath beech and maple forest",
        "arch",
        2,
        0.5,
        0.41,
        0.62,
        0.48,
      ),
      motif("water and roots opening a hidden room in stone", "ribbon", 3, 0.5, 0.59, 0.62, 0.14),
      motif(
        "glacial till plain, Appalachian plateau, river valleys, and Lake Erie shore",
        "horizon",
        1,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship:
      "One moss-dark recess opens around a single blue root-and-water curve above the gold till plain.",
    edgeStrategy:
      "The glacial plain reaches the bottom edge while the hidden recess stays open toward the top.",
  }),
  defineLandscapeArtProfile({
    slug: "oklahoma",
    sourceCue: "rounded Wichita Mountains granite above prairie and a grazing bison",
    primaryStyleId: "woven-tapestry-field",
    palette: palette(
      ["granite rose", "#A96F68"],
      ["prairie gold", "#C9A044"],
      ["bison brown", "#664937"],
      ["storm blue", "#4F7086"],
    ),
    motifs: [
      motif(
        "rounded Wichita Mountains granite above prairie and a grazing bison",
        "bison",
        2,
        0.65,
        0.55,
        0.38,
        0.26,
      ),
      motif("old red stone holding firm above moving grass", "triangle", 1, 0.24, 0.36, 0.28, 0.32),
      motif(
        "prairie plains, cross timbers, red-bed hills, and low granite mountains",
        "horizon",
        3,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship:
      "One brown bison silhouette crosses beneath a single rose granite mass and above the storm-blue prairie.",
    edgeStrategy: "The prairie reaches the bottom edge and the low mountain mass opens at the left side.",
  }),
  defineLandscapeArtProfile({
    slug: "oregon",
    sourceCue: "Pacific sea stacks beyond a wind-shaped Douglas-fir coast",
    primaryStyleId: "cut-paper-strata",
    palette: palette(
      ["fir green", "#315C46"],
      ["ocean blue", "#3F7E9B"],
      ["basalt black", "#263033"],
      ["mist gray", "#A9B2B0"],
      ["sunset coral", "#D47865"],
    ),
    motifs: [
      motif(
        "Pacific sea stacks beyond a wind-shaped Douglas-fir coast",
        "triangle",
        2,
        0.6,
        0.42,
        0.42,
        0.42,
      ),
      motif("mist joining dark forest to bright ocean", "stripe", 3, 0.5, 0.56, 0.68, 0.14),
      motif(
        "volcanic Cascades, forested coast, high desert, and river gorge",
        "horizon",
        1,
        0.5,
        0.77,
        0.82,
        0.21,
      ),
    ],
    relationship: "One basalt sea stack rises through a single mist band above the bright Pacific coast.",
    edgeStrategy: "The forested coast meets the bottom edge and the Pacific opens along the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "pennsylvania",
    sourceCue: "the Susquehanna River turning between long forested Appalachian ridges",
    primaryStyleId: "cyanotype-field-study",
    palette: palette(
      ["forest green", "#3C6043"],
      ["river blue", "#487F9A"],
      ["shale gray", "#707879"],
      ["autumn copper", "#A9613E"],
    ),
    motifs: [
      motif(
        "the Susquehanna River turning between long forested Appalachian ridges",
        "ribbon",
        1,
        0.5,
        0.55,
        0.68,
        0.14,
      ),
      motif("parallel mountains parting for one broad watercourse", "stripe", 3, 0.5, 0.38, 0.7, 0.14),
      motif(
        "ridge and valley, Allegheny Plateau, Piedmont, and major river gaps",
        "horizon",
        2,
        0.5,
        0.76,
        0.82,
        0.23,
      ),
    ],
    relationship: "One blue river turns through a single copper mountain parting above the shale plateau.",
    edgeStrategy: "The plateau reaches the bottom edge while the Susquehanna exits through the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "rhode-island",
    sourceCue: "a rocky Narragansett Bay shore opening around islands and a white sail",
    primaryStyleId: "watercolor-naturalist-study",
    palette: palette(
      ["bay blue", "#4B819B"],
      ["granite gray", "#777E7F"],
      ["sail white", "#F0EDE2"],
      ["beach-rose pink", "#C67B88"],
    ),
    motifs: [
      motif(
        "a rocky Narragansett Bay shore opening around islands and a white sail",
        "triangle",
        2,
        0.6,
        0.4,
        0.34,
        0.38,
      ),
      motif("many sheltered coves gathered inside one ocean horizon", "arch", 3, 0.45, 0.56, 0.56, 0.32),
      motif(
        "coastal lowland, tidal bay, rocky headlands, and wooded uplands",
        "horizon",
        1,
        0.5,
        0.78,
        0.82,
        0.2,
      ),
    ],
    relationship: "One white sail crosses a single rose-colored cove above the granite tidal lowland.",
    edgeStrategy: "The tidal bay reaches the bottom edge and the ocean horizon opens along the right side.",
  }),
  defineLandscapeArtProfile({
    slug: "south-carolina",
    sourceCue: "cypress knees and tupelo reflected in a blackwater river",
    primaryStyleId: "charcoal-pastel-weather",
    palette: palette(
      ["water black", "#202D2D"],
      ["cypress green", "#365C43"],
      ["tupelo gold", "#C99E43"],
      ["mist silver", "#ADB4AF"],
    ),
    motifs: [
      motif("cypress knees and tupelo reflected in a blackwater river", "triangle", 1, 0.28, 0.4, 0.28, 0.42),
      motif("tea-dark water carrying forest light toward the coast", "ribbon", 2, 0.57, 0.56, 0.58, 0.14),
      motif(
        "Blue Ridge edge, Piedmont, sandhills, coastal plain, and sea islands",
        "horizon",
        3,
        0.5,
        0.77,
        0.82,
        0.21,
      ),
    ],
    relationship:
      "One cypress form reflects into a single gold-lit blackwater curve above the misty coastal plain.",
    edgeStrategy: "The coastal plain meets the bottom edge and the blackwater river exits at the right side.",
  }),
] as const;
