import {
  arc,
  circle,
  color,
  curve,
  ellipse,
  forms,
  palette,
  polygon,
  recipe,
  rect,
  star,
} from "./code-native-art-recipe-builders";

export const codeNativeClassicHistoryRecipes = [
  recipe({
    catalogueDirectory: "books-read",
    slug: "nineteen-eighty-four",
    primaryStyleId: "screenprint-night",
    manufacturingLanguage: "screenprint-masses",
    styleComparison:
      "Preserves screenprint-night through overlapping high-contrast masses without ink texture.",
    forms: forms("one observing aperture", "one lone doorway", "two red light beams"),
    relationship: "The doorway stands beneath the aperture while paired beams divide the dark field.",
    palette: palette(
      color("charcoal black", "#17191C"),
      color("paper cream", "#EEE1C5"),
      color("warning red", "#B32E36"),
      color("cold gray", "#7E858B"),
    ),
    backgroundColor: 0,
    commands: [
      ellipse(3, 448, 238, 230, 126),
      ellipse(0, 448, 238, 128, 58),
      rect(1, 374, 510, 148, 386),
      polygon(2, 0, 370, 0, 470, 374, 620, 374, 528),
      polygon(2, 896, 370, 896, 470, 522, 620, 522, 528),
    ],
    minimumFeaturePixels: 74,
    minimumNegativeGapPixels: 40,
    edgeStrategy:
      "Red beams bleed through left and right; the doorway opens through bottom while the dark field remains open at top.",
    sourceSpecificExclusions: [
      "no eye illustration or facial detail",
      "no numeral-like marks",
      "exactly two beams",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "to-kill-a-mockingbird",
    primaryStyleId: "watercolor-naturalist-study",
    manufacturingLanguage: "cut-paper-naturalist",
    styleComparison:
      "Translates watercolor-naturalist-study into broad botanical cut shapes without washes or feather microbarbs.",
    forms: forms("one broad oak branch", "one white feather", "one courthouse-step wedge"),
    relationship: "The feather settles between the sheltering branch and severe ascending steps.",
    palette: palette(
      color("warm paper", "#EADABC"),
      color("oak brown", "#70442E"),
      color("soft white", "#F7F1E3"),
      color("courthouse gray", "#3E454A"),
    ),
    backgroundColor: 0,
    commands: [
      curve(1, 120, [-70, 218], [240, 112], [510, 270], [940, 126]),
      polygon(1, 162, 218, 232, 116, 302, 232),
      polygon(2, 410, 270, 500, 398, 446, 610, 376, 424),
      curve(1, 30, [442, 306], [456, 380], [430, 500], [418, 594]),
      polygon(3, 540, 896, 540, 694, 638, 694, 638, 584, 742, 584, 742, 468, 896, 468, 896, 896),
    ],
    minimumFeaturePixels: 30,
    minimumNegativeGapPixels: 32,
    edgeStrategy:
      "The branch crosses left and right; the courthouse wedge exits right and bottom, leaving top open paper.",
    sourceSpecificExclusions: [
      "no bird likeness",
      "no courthouse columns, windows, or seal",
      "no feather barb lines",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-great-gatsby",
    primaryStyleId: "stained-glass-field",
    manufacturingLanguage: "large-stained-glass-cells",
    styleComparison:
      "Preserves stained-glass-field using four large separated cells without tessellation or luminous gradients.",
    forms: forms("one green harbor light", "one black water arc", "one distant gold skyline"),
    relationship: "The green light remains across the water from one compressed skyline mass.",
    palette: palette(
      color("midnight blue", "#182645"),
      color("harbor green", "#3FA06A"),
      color("antique gold", "#C89A43"),
      color("black lead", "#131619"),
    ),
    backgroundColor: 3,
    commands: [
      rect(0, 0, 0, 896, 430),
      arc(3, 448, 850, 520, 332, 190, 350),
      polygon(
        2,
        0,
        500,
        0,
        396,
        180,
        396,
        180,
        350,
        372,
        350,
        372,
        418,
        570,
        418,
        570,
        372,
        896,
        372,
        896,
        500,
      ),
      circle(1, 694, 256, 92),
    ],
    minimumFeaturePixels: 84,
    minimumNegativeGapPixels: 28,
    edgeStrategy:
      "Skyline and water cross both side edges; black leading and water reach bottom while sky reaches top.",
    sourceSpecificExclusions: [
      "no miniature buildings or windows",
      "no eyes or cover-art trade dress",
      "one skyline mass only",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-count-of-monte-cristo",
    primaryStyleId: "mosaic-tesserae-field",
    manufacturingLanguage: "large-enamel-cells",
    styleComparison:
      "Translates mosaic-tesserae-field into a few large enamel cells without tesserae, grout noise, or faux depth.",
    forms: forms("one dark island silhouette", "one oversized key", "one broken chain arc"),
    relationship: "The key rises from the island as the broken chain opens around it.",
    palette: palette(
      color("sea blue", "#28708B"),
      color("volcanic black", "#202326"),
      color("aged brass", "#C08A35"),
      color("foam white", "#EEE8D5"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(1, -40, 896, 122, 650, 286, 586, 448, 630, 620, 570, 812, 664, 936, 896),
      circle(2, 448, 348, 128),
      circle(0, 448, 348, 62),
      rect(2, 414, 446, 68, 270),
      polygon(2, 448, 662, 616, 662, 616, 726, 534, 726, 534, 782, 414, 782, 414, 662),
      arc(3, 448, 496, 366, 306, 196, 274),
      arc(3, 448, 496, 366, 306, 286, 344),
    ],
    minimumFeaturePixels: 60,
    minimumNegativeGapPixels: 28,
    edgeStrategy:
      "Sea fills all four edges and the island exits left, right, and bottom; the broken arc never forms an inset enclosure.",
    sourceSpecificExclusions: [
      "no letter-like key teeth",
      "no chain links or repeated cells",
      "no prison or treasure micro-scenery",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-odyssey",
    primaryStyleId: "relief-blockprint",
    manufacturingLanguage: "relief-cut-spot-shapes",
    styleComparison:
      "Preserves relief-blockprint using hard spot-color cuts without carved hatching or paper texture.",
    forms: forms("one black sail", "one spiral wave", "one homeward star"),
    relationship: "The sail climbs the single spiral wave toward the fixed star.",
    palette: palette(
      color("Aegean blue", "#276A8A"),
      color("ink black", "#1A1D20"),
      color("sun ochre", "#D49A35"),
      color("star white", "#F0E8D3"),
    ),
    backgroundColor: 0,
    commands: [
      arc(3, 560, 650, 318, 232, 160, 450),
      polygon(1, 214, 704, 488, 252, 488, 704),
      rect(2, 474, 226, 34, 500),
      star(3, 700, 184, 100, 46, 5),
    ],
    minimumFeaturePixels: 34,
    minimumNegativeGapPixels: 34,
    edgeStrategy:
      "The wave crosses left and right and sea fills all edges; the sail remains open against the field without a frame.",
    sourceSpecificExclusions: ["one wave only", "no ship rigging or crew", "no carved line texture"],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-brothers-karamazov",
    primaryStyleId: "fresco-mineral-pigment",
    manufacturingLanguage: "mineral-fresco-planes",
    styleComparison:
      "Preserves fresco-mineral-pigment through asymmetric mineral planes without cracks, grain, or modeled plaster.",
    forms: forms("one four-branched path", "one dark dome", "one dawn disk"),
    relationship: "Four branches converge beneath the dome before the path opens toward dawn.",
    palette: palette(
      color("plaster white", "#E9DFC4"),
      color("earth umber", "#604232"),
      color("oxblood", "#8E3034"),
      color("dawn gold", "#D3A03D"),
    ),
    backgroundColor: 0,
    commands: [
      circle(3, 672, 174, 100),
      rect(1, 182, 350, 288, 176),
      ellipse(1, 326, 350, 144, 106),
      curve(2, 74, [74, 896], [128, 702], [284, 674], [390, 574]),
      curve(2, 74, [286, 896], [292, 714], [346, 650], [390, 574]),
      curve(2, 74, [610, 896], [582, 714], [472, 652], [390, 574]),
      curve(2, 74, [830, 896], [744, 702], [508, 668], [390, 574]),
      curve(2, 78, [390, 574], [452, 486], [520, 374], [574, 284]),
    ],
    minimumFeaturePixels: 74,
    minimumNegativeGapPixels: 30,
    edgeStrategy: "The four paths bleed through bottom while the plaster field reaches top, left, and right.",
    sourceSpecificExclusions: [
      "exactly four broad branches",
      "no faces, figures, crosses, or lettering",
      "no architectural detail on dome",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-dawn-of-everything",
    primaryStyleId: "fresco-mineral-pigment",
    manufacturingLanguage: "mineral-fresco-planes",
    styleComparison:
      "Preserves fresco-mineral-pigment through open earth planes without cracks, tiny people, or modeled texture.",
    forms: forms("one sunrise disk", "one open earth-strata field", "one communal ring"),
    relationship: "The ring rests within exposed strata as sunrise widens the field above.",
    palette: palette(
      color("lime plaster", "#D9D1A9"),
      color("clay red", "#A5533E"),
      color("soil brown", "#654536"),
      color("dawn yellow", "#D8A93F"),
    ),
    backgroundColor: 0,
    commands: [
      circle(3, 448, 244, 168),
      polygon(1, -30, 610, 180, 532, 416, 586, 656, 520, 926, 620, 926, 896, -30, 896),
      polygon(2, -30, 744, 204, 676, 440, 726, 682, 662, 926, 748, 926, 896, -30, 896),
      circle(0, 448, 640, 142),
      circle(2, 448, 640, 76),
    ],
    minimumFeaturePixels: 66,
    minimumNegativeGapPixels: 30,
    edgeStrategy:
      "Both strata bleed left, right, and bottom; the plaster sky reaches top and the ring remains open within the field.",
    sourceSpecificExclusions: [
      "no tiny communal figures",
      "no archaeological artifacts",
      "no fresco cracks or granular earth",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-silk-roads",
    primaryStyleId: "contour-atlas-ink",
    manufacturingLanguage: "broad-map-bands",
    styleComparison:
      "Preserves contour-atlas-ink using three broad navigational bands without contour-line repetition or labels.",
    forms: forms("one continuous route band", "one mountain arch", "one broad sea arc"),
    relationship: "The route crosses the mountain opening and continues into the sea.",
    palette: palette(
      color("desert ochre", "#CE9A46"),
      color("lapis blue", "#275A8A"),
      color("mulberry", "#813C62"),
      color("ink black", "#232629"),
    ),
    backgroundColor: 0,
    commands: [
      arc(1, 448, 890, 570, 380, 190, 350),
      arc(3, 448, 548, 290, 190, 180, 360),
      curve(2, 72, [-40, 724], [252, 640], [484, 414], [940, 236]),
    ],
    minimumFeaturePixels: 72,
    minimumNegativeGapPixels: 30,
    edgeStrategy:
      "Route and sea bands bleed through both sides and bottom while the desert field reaches top.",
    sourceSpecificExclusions: [
      "no map labels or place markers",
      "no repeated contour lines",
      "one route only",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "team-of-rivals",
    primaryStyleId: "wood-marquetry-landscape",
    manufacturingLanguage: "marquetry-inlay",
    styleComparison:
      "Preserves wood-marquetry-landscape through four broad inlaid chair planes without grain or furniture detail.",
    forms: forms("four contrasting chair backs", "one oval table", "one shared light pool"),
    relationship: "Four chair backs lean toward the oval table while one light holds the center.",
    palette: palette(
      color("walnut", "#543526"),
      color("maple", "#E5CCA0"),
      color("cherry", "#914B36"),
      color("lamplight gold", "#D6A23C"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(1, 146, 170, 310, 226, 282, 422, 126, 344),
      polygon(2, 750, 170, 586, 226, 614, 422, 770, 344),
      polygon(2, 142, 730, 286, 526, 364, 668, 252, 840),
      polygon(1, 754, 730, 610, 526, 532, 668, 644, 840),
      ellipse(1, 448, 500, 250, 170),
      ellipse(3, 448, 500, 136, 88),
    ],
    minimumFeaturePixels: 78,
    minimumNegativeGapPixels: 28,
    edgeStrategy:
      "Walnut field reaches all four edges; chairs remain separate and no enclosing inlay border is drawn.",
    sourceSpecificExclusions: [
      "exactly four chair backs",
      "no faces or presidential likeness",
      "no wood grain, legs, spindles, or upholstery",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "spqr",
    primaryStyleId: "mineral-line-engraving",
    manufacturingLanguage: "engraved-broad-linework",
    styleComparison:
      "Preserves mineral-line-engraving using a few broad incised-looking bands without hatching, fine leaves, or inscriptions.",
    forms: forms("one broad Roman arch", "one laurel branch", "one river band"),
    relationship: "The branch crosses the arch while the river carries beneath it.",
    palette: palette(
      color("warm paper", "#E7D7B8"),
      color("graphite", "#3C4142"),
      color("iron red", "#9A4438"),
      color("verdigris", "#3D817A"),
    ),
    backgroundColor: 0,
    commands: [
      arc(1, 448, 468, 266, 174, 180, 360),
      rect(1, 182, 466, 92, 430),
      rect(1, 622, 466, 92, 430),
      curve(3, 138, [-50, 770], [224, 666], [586, 842], [946, 692]),
      curve(2, 46, [162, 554], [354, 390], [580, 514], [768, 332]),
      polygon(2, 258, 484, 316, 392, 366, 494),
      polygon(2, 470, 456, 532, 358, 578, 474),
      polygon(2, 632, 410, 698, 316, 742, 430),
    ],
    minimumFeaturePixels: 46,
    minimumNegativeGapPixels: 30,
    edgeStrategy: "River bleeds left and right and arch legs exit bottom; paper remains open at top.",
    sourceSpecificExclusions: [
      "no letters, numerals, inscriptions, or coin motifs",
      "exactly three broad leaves",
      "no hatching or masonry lines",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-warmth-of-other-suns",
    primaryStyleId: "thread-painted-embroidery",
    manufacturingLanguage: "broad-embroidery-bands",
    styleComparison:
      "Preserves thread-painted-embroidery through three broad directional bands without stitches, fibers, or thread texture.",
    forms: forms("three broad migration streams", "one northern horizon", "one golden sun"),
    relationship: "Three separate streams rise toward one warm northern horizon beneath the sun.",
    palette: palette(
      color("deep indigo", "#26345F"),
      color("rust", "#A54E3D"),
      color("warm gold", "#D3A13A"),
      color("cotton white", "#EDE5D2"),
    ),
    backgroundColor: 0,
    commands: [
      rect(3, 0, 180, 896, 110),
      circle(2, 720, 154, 96),
      curve(1, 98, [80, 940], [116, 660], [184, 430], [258, 286]),
      curve(3, 98, [356, 940], [370, 682], [404, 444], [424, 286]),
      curve(2, 98, [786, 940], [732, 686], [650, 454], [578, 286]),
    ],
    minimumFeaturePixels: 96,
    minimumNegativeGapPixels: 40,
    edgeStrategy:
      "Horizon bleeds left and right, all three streams exit bottom, and indigo reaches top without an enclosing seam.",
    sourceSpecificExclusions: [
      "exactly three broad streams",
      "no people, arrows, maps, place labels, or city detail",
      "no individual stitches, fibers, thread highlights, or repeated dash marks",
    ],
  }),
] as const;
