import {
  circle,
  color,
  ellipse,
  forms,
  palette,
  polygon,
  recipe,
  rect,
} from "./code-native-art-recipe-builders";

export const codeNativeEducationRecipes = [
  recipe({
    catalogueDirectory: "life-milestones",
    slug: "university-nebraska-lincoln-degree",
    primaryStyleId: "stained-glass-field",
    manufacturingLanguage: "large-stained-glass-cells",
    styleComparison:
      "Preserves stained-glass-field using four monumental campus cells without windows, brick repetition, logos, or glass shading.",
    forms: forms(
      "one tall octagonal Mueller Tower silhouette",
      "one low Love Library mass",
      "one broad white cupola",
      "one continuous campus mall path",
    ),
    relationship: "The mall joins the tall tower and low library beneath an open prairie sky.",
    palette: palette(
      color("deep glass blue", "#1F4F79"),
      color("limestone cream", "#E5D8B8"),
      color("campus brick", "#9B4F3C"),
      color("prairie gold", "#C99A3E"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(1, 182, 700, 182, 266, 210, 210, 264, 210, 292, 266, 292, 700, 264, 742, 210, 742),
      rect(2, 486, 492, 314, 250),
      ellipse(1, 643, 492, 157, 98),
      rect(1, 594, 386, 98, 106),
      polygon(3, 300, 896, 376, 676, 520, 612, 608, 742, 536, 896),
    ],
    minimumFeaturePixels: 54,
    minimumNegativeGapPixels: 42,
    edgeStrategy:
      "Prairie mall exits bottom while blue sky reaches top, left, and right; landmarks do not sit within an outer border.",
    sourceSpecificExclusions: [
      "no university logo, seal, mascot, or letter N",
      "no windows, bricks, bells, columns, or corn ornament",
      "tower remains one octagonal silhouette and library one low mass",
    ],
  }),
  recipe({
    catalogueDirectory: "life-milestones",
    slug: "masters-degree",
    primaryStyleId: "ceramic-underglaze",
    manufacturingLanguage: "ceramic-underglaze-fields",
    styleComparison:
      "Preserves ceramic-underglaze through four monumental fired-color fields without glaze shine, academic emblems, or architectural detail.",
    forms: forms(
      "one monumental open doorway",
      "one broad three-step staircase",
      "one rising sun disk",
      "one continuous horizon field",
    ),
    relationship: "A single staircase crosses the open doorway toward the sun and calm horizon beyond.",
    palette: palette(
      color("deep cobalt", "#24527D"),
      color("warm clay", "#A85540"),
      color("sunlit ochre", "#D2A03B"),
      color("quiet cream", "#ECE1C5"),
    ),
    backgroundColor: 0,
    commands: [
      rect(3, 0, 400, 896, 112),
      circle(2, 448, 284, 102),
      rect(1, 200, 60, 496, 100),
      rect(1, 200, 60, 100, 836),
      rect(1, 596, 60, 100, 836),
      polygon(
        2,
        300,
        896,
        300,
        780,
        360,
        780,
        360,
        680,
        420,
        680,
        420,
        580,
        476,
        580,
        476,
        680,
        536,
        680,
        536,
        780,
        596,
        780,
        596,
        896,
      ),
    ],
    minimumFeaturePixels: 56,
    minimumNegativeGapPixels: 44,
    edgeStrategy:
      "Horizon bleeds left and right, doorway pillars and staircase exit bottom, and cobalt remains open above the lintel.",
    sourceSpecificExclusions: [
      "no graduation cap, diploma, trophy, confetti, books, equations, or classroom tools",
      "no school seal, crest, logo, wordmark, monogram, letters, numerals, or signs",
      "doorway and staircase remain blank monumental forms without masonry or railings",
    ],
  }),
] as const;
