import {
  arc,
  circle,
  color,
  curve,
  ellipse,
  forms,
  palette,
  polygon,
  recipe,
  rect,
} from "./code-native-art-recipe-builders";

export const codeNativeRetainedBookRecipes = [
  recipe({
    catalogueDirectory: "books-read",
    slug: "pride-and-prejudice",
    primaryStyleId: "cut-paper-strata",
    manufacturingLanguage: "layered-paper-silhouette",
    styleComparison:
      "Preserves cut-paper-strata through broad garden and profile layers without facial detail, foliage texture, or paper fibers.",
    forms: forms(
      "two facing profile silhouettes",
      "one winding garden path",
      "one left hedge mass",
      "one right hedge mass",
    ),
    relationship: "The profiles remain apart while the path winds between two contrasting hedge masses.",
    palette: palette(
      color("parchment", "#E8D8B8"),
      color("garden green", "#4F704F"),
      color("mulberry", "#7D3F5A"),
      color("ink brown", "#49372F"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(1, -40, 896, -40, 486, 174, 414, 330, 520, 270, 896),
      polygon(2, 936, 896, 936, 466, 710, 414, 566, 520, 636, 896),
      curve(0, 112, [448, 940], [380, 734], [530, 596], [448, 430]),
      polygon(3, 180, 520, 204, 378, 262, 302, 322, 318, 358, 354, 326, 382, 350, 424, 314, 452, 330, 520),
      polygon(2, 716, 520, 692, 378, 634, 302, 574, 318, 538, 354, 570, 382, 546, 424, 582, 452, 566, 520),
    ],
    minimumFeaturePixels: 70,
    minimumNegativeGapPixels: 44,
    edgeStrategy:
      "The hedges bleed through both sides and bottom, the path exits bottom, and parchment remains open at top.",
    sourceSpecificExclusions: [
      "exactly two faceless profile silhouettes",
      "no manor, lettering, clothing detail, or botanical microdetail",
      "hedges remain two broad masses without individual leaves",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "guns-germs-and-steel",
    primaryStyleId: "prismatic-geometric-symbolism",
    manufacturingLanguage: "prismatic-crossroad-inlay",
    styleComparison:
      "Preserves prismatic-geometric-symbolism through three large intersecting emblems without facets, diagrams, or literal weapon imagery.",
    forms: forms("one grain stalk", "one circular cell", "one spanning steel beam"),
    relationship: "The grain, cell, and beam meet without hierarchy at one geometric crossroads.",
    palette: palette(
      color("charcoal", "#20272A"),
      color("wheat gold", "#D2A143"),
      color("oxidized teal", "#3D827C"),
      color("steel gray", "#8B9498"),
    ),
    backgroundColor: 0,
    commands: [
      polygon(3, -40, 548, 936, 266, 936, 394, -40, 676),
      circle(2, 566, 432, 154),
      circle(0, 566, 432, 78),
      curve(1, 48, [292, 792], [304, 590], [328, 370], [342, 186]),
      polygon(1, 310, 548, 202, 452, 316, 476),
      polygon(1, 324, 430, 438, 330, 330, 356),
      ellipse(1, 344, 170, 72, 112),
    ],
    minimumFeaturePixels: 48,
    minimumNegativeGapPixels: 32,
    edgeStrategy:
      "The steel beam crosses both side edges, the grain exits bottom, and charcoal remains open at top.",
    sourceSpecificExclusions: [
      "no gun, projectile, microbe detail, map, or chronology",
      "one cell and one grain stalk only",
      "no kernels, rivets, facets, or diagram labels",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-sixth-extinction",
    primaryStyleId: "charcoal-pastel-weather",
    manufacturingLanguage: "charcoal-pastel-inlay",
    styleComparison:
      "Preserves charcoal-pastel-weather through three flat inlaid silhouettes without smudging, dust, feather lines, or fossil texture.",
    forms: forms("one ammonite arc", "one fading wing", "one ash horizon"),
    relationship: "The wing narrows into the ash horizon above one enduring fossil arc.",
    palette: palette(
      color("charcoal black", "#202326"),
      color("ash gray", "#858784"),
      color("fossil cream", "#E4D5B5"),
      color("warning coral", "#C85A50"),
    ),
    backgroundColor: 0,
    commands: [
      rect(1, 0, 216, 896, 118),
      polygon(3, 896, 216, 636, 216, 492, 354, 624, 338, 756, 306, 896, 334),
      arc(2, 332, 612, 230, 132, 18, 346),
      circle(0, 332, 612, 62),
    ],
    minimumFeaturePixels: 62,
    minimumNegativeGapPixels: 42,
    edgeStrategy:
      "The ash horizon and wing bleed through right and left, charcoal reaches top and bottom, and the fossil remains open rather than framed.",
    sourceSpecificExclusions: [
      "one open ammonite arc rather than a repeated spiral",
      "no species collage, bones, feathers, shell ridges, or dust texture",
      "wing remains one tapering silhouette",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-design-of-everyday-things",
    primaryStyleId: "matte-gouache-editorial",
    manufacturingLanguage: "gouache-affordance-planes",
    styleComparison:
      "Preserves matte-gouache-editorial through three direct flat planes without brush texture, shading, diagrams, or instructional symbols.",
    forms: forms("one simple door plane", "one round handle", "one opening wedge of light"),
    relationship: "The handle explains the opening action before the light wedge reveals the result.",
    palette: palette(
      color("matte cream", "#EADFC8"),
      color("charcoal", "#303538"),
      color("rust", "#A8503C"),
      color("clear yellow", "#DEB844"),
    ),
    backgroundColor: 0,
    commands: [
      rect(1, 206, 0, 500, 896),
      polygon(3, 522, 126, 896, 42, 896, 832, 522, 664),
      circle(2, 500, 444, 76),
    ],
    minimumFeaturePixels: 76,
    minimumNegativeGapPixels: 92,
    edgeStrategy:
      "The door exits top and bottom, the light reaches the right edge, and cream remains open along the left edge.",
    sourceSpecificExclusions: [
      "one door and one handle only",
      "no hinges, signage, arrows, labels, room detail, or wood grain",
      "no shadow, highlight, or perspective-line microdetail",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "dune",
    primaryStyleId: "cut-paper-strata",
    manufacturingLanguage: "desert-paper-strata",
    styleComparison:
      "Preserves cut-paper-strata through two oversized desert bands without sand grain, contour repetition, or atmospheric shading.",
    forms: forms("one giant sun", "two sweeping dune curves", "one blue oasis"),
    relationship: "The two dunes eclipse part of the sun while the oasis holds one cool counterpoint.",
    palette: palette(
      color("sand ochre", "#D0A250"),
      color("burnt orange", "#C86735"),
      color("deep umber", "#4C382E"),
      color("oasis blue", "#367F9A"),
    ),
    backgroundColor: 0,
    commands: [
      circle(1, 600, 284, 226),
      curve(2, 266, [-110, 650], [248, 408], [636, 796], [1006, 500]),
      curve(1, 224, [-110, 844], [264, 596], [642, 904], [1006, 650]),
      ellipse(3, 700, 668, 116, 54),
    ],
    minimumFeaturePixels: 54,
    minimumNegativeGapPixels: 42,
    edgeStrategy:
      "Both dunes bleed left, right, and bottom while ochre reaches top; the oasis remains an open accent without a rim.",
    sourceSpecificExclusions: [
      "exactly two broad dune curves",
      "no figures, creatures, buildings, lettering, sand grain, or contour lines",
      "one small oasis ellipse only",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "the-remains-of-the-day",
    primaryStyleId: "aquatint-atmosphere",
    manufacturingLanguage: "aquatint-corridor-planes",
    styleComparison:
      "Preserves aquatint-atmosphere through receding flat planes without tonal gradients, stipple, interior clutter, or reflective modeling.",
    forms: forms("one long corridor", "one centered silver tray", "one garden-window glow"),
    relationship: "The tray remains centered while the corridor recedes toward the fading garden window.",
    palette: palette(
      color("smoke gray", "#5F6668"),
      color("silver", "#CFD2CD"),
      color("garden green", "#4C745B"),
      color("late gold", "#C69B45"),
    ),
    backgroundColor: 0,
    commands: [
      rect(3, 300, 66, 296, 260),
      rect(2, 344, 108, 208, 176),
      polygon(1, 0, 0, 300, 66, 300, 896, 0, 896),
      polygon(1, 896, 0, 596, 66, 596, 896, 896, 896),
      ellipse(1, 448, 594, 184, 72),
      rect(1, 416, 620, 64, 190),
    ],
    minimumFeaturePixels: 64,
    minimumNegativeGapPixels: 44,
    edgeStrategy:
      "Corridor planes reach all four edges while the central smoke path stays open to the garden window.",
    sourceSpecificExclusions: [
      "one centered tray silhouette only",
      "no tableware, furniture, doors, molding, reflections, or stippled tone",
      "garden remains one green field without leaves or flowers",
    ],
  }),
  recipe({
    catalogueDirectory: "books-read",
    slug: "educated",
    primaryStyleId: "plein-air-broken-color",
    manufacturingLanguage: "plein-air-color-blocks",
    styleComparison:
      "Preserves plein-air-broken-color through four large landscape blocks without daubs, canvas texture, snow detail, or atmospheric gradients.",
    forms: forms("one mountain ridge", "one open doorway", "one broad dawn band"),
    relationship: "The doorway opens away from the mountain interior into the broad dawn band.",
    palette: palette(
      color("mountain umber", "#624536"),
      color("sky blue", "#6E9DB4"),
      color("dawn peach", "#D99172"),
      color("snow white", "#EEE8D7"),
    ),
    backgroundColor: 1,
    commands: [
      rect(2, 0, 146, 896, 166),
      polygon(0, -40, 896, -40, 606, 180, 388, 322, 500, 500, 276, 714, 480, 936, 352, 936, 896),
      rect(3, 350, 520, 196, 376),
      polygon(1, 402, 570, 546, 520, 546, 896, 402, 896),
    ],
    minimumFeaturePixels: 80,
    minimumNegativeGapPixels: 52,
    edgeStrategy:
      "The mountain exits both sides and bottom, the doorway exits bottom, and sky reaches the top edge.",
    sourceSpecificExclusions: [
      "one ridge and one doorway only",
      "no house, school, books, text, windows, trees, or snow texture",
      "no broken-color dabs smaller than the broad source forms",
    ],
  }),
] as const;
