import type { CommonAchievementIdea } from "./types";

const idea = (
  id: string,
  category: CommonAchievementIdea["category"],
  title: string,
  criterion: string,
  themeCues: CommonAchievementIdea["themeCues"],
  suggestedStyleIds: CommonAchievementIdea["suggestedStyleIds"],
): CommonAchievementIdea => ({ id, category, title, criterion, themeCues, suggestedStyleIds });

export const commonAchievementIdeas: readonly CommonAchievementIdea[] = [
  idea(
    "saw-northern-lights",
    "nature",
    "Saw the northern lights",
    "Witness the aurora with your own eyes",
    ["ribbons of light", "winter silence", "wide night sky"],
    ["screenprint-night", "pixel-cluster-landscape", "charcoal-pastel-weather"],
  ),
  idea(
    "saw-total-eclipse",
    "nature",
    "Saw a total eclipse",
    "Experience totality during a solar eclipse",
    ["black sun", "silver corona", "hushed horizon"],
    ["aquatint-atmosphere", "prismatic-geometric-symbolism", "luminous-ligne-claire"],
  ),
  idea(
    "saw-bioluminescence",
    "nature",
    "Saw bioluminescence",
    "See living light in the ocean at night",
    ["glowing wake", "dark water", "constellation below"],
    ["screenprint-night", "stained-glass-field", "pixel-cluster-landscape"],
  ),
  idea(
    "planted-a-tree",
    "nature",
    "Planted a tree",
    "Plant a tree that can keep growing",
    ["young roots", "two hands", "future canopy"],
    ["wood-marquetry-landscape", "watercolor-naturalist-study", "thread-painted-embroidery"],
  ),
  idea(
    "grew-a-garden",
    "nature",
    "Grew a garden",
    "Grow and tend a garden through a season",
    ["seed to blossom", "patient rows", "harvest light"],
    ["watercolor-naturalist-study", "woven-tapestry-field", "ceramic-underglaze"],
  ),
  idea(
    "slept-under-stars",
    "adventure",
    "Slept under the stars",
    "Spend a night outdoors beneath an open sky",
    ["small camp", "Milky Way", "quiet horizon"],
    ["screenprint-night", "scratchboard-nocturne", "pixel-cluster-landscape"],
  ),
  idea(
    "first-solo-trip",
    "adventure",
    "Took a solo trip",
    "Complete a meaningful trip on your own",
    ["open road", "single pack", "self-trust"],
    ["luminous-ligne-claire", "contour-atlas-ink", "matte-gouache-editorial"],
  ),
  idea(
    "cross-country-road-trip",
    "adventure",
    "Crossed the country by road",
    "Complete a coast-to-coast road trip",
    ["changing horizons", "ribbon road", "weathered map"],
    ["luminous-ligne-claire", "contour-atlas-ink", "risograph-overprint"],
  ),
  idea(
    "visited-all-50-states",
    "adventure",
    "Visited all 50 states",
    "Spend meaningful time in every U.S. state",
    ["many landscapes", "one long route", "fifty memories"],
    ["contour-atlas-ink", "mosaic-tesserae-field", "thread-painted-embroidery"],
  ),
  idea(
    "visited-seven-continents",
    "adventure",
    "Visited seven continents",
    "Set foot on all seven continents",
    ["seven horizons", "ocean crossings", "planet scale"],
    ["prismatic-geometric-symbolism", "contour-atlas-ink", "cut-paper-strata"],
  ),
  idea(
    "first-summit",
    "adventure",
    "Reached a mountain summit",
    "Reach a personally meaningful mountain summit",
    ["final ridge", "cloud sea", "small figure"],
    ["mineral-line-engraving", "plein-air-broken-color", "luminous-ligne-claire"],
  ),
  idea(
    "completed-long-trail",
    "adventure",
    "Completed a long trail",
    "Finish a long-distance trail that matters to you",
    ["worn path", "successive seasons", "last blaze"],
    ["contour-atlas-ink", "thread-painted-embroidery", "relief-blockprint"],
  ),
  idea(
    "learned-to-swim",
    "wellbeing",
    "Learned to swim",
    "Become able to swim with confidence",
    ["first clean stroke", "breath and water", "bright lane"],
    ["stained-glass-field", "matte-gouache-editorial", "mosaic-tesserae-field"],
  ),
  idea(
    "finished-first-5k",
    "wellbeing",
    "Finished a first 5K",
    "Complete your first five-kilometer event",
    ["dawn road", "steady breath", "finish ahead"],
    ["risograph-overprint", "pixel-cluster-landscape", "relief-blockprint"],
  ),
  idea(
    "finished-marathon",
    "wellbeing",
    "Finished a marathon",
    "Complete a marathon honestly",
    ["long course", "spent shoes", "last turn"],
    ["mineral-line-engraving", "luminous-ligne-claire", "plein-air-broken-color"],
  ),
  idea(
    "cycled-century",
    "wellbeing",
    "Rode a century",
    "Complete a one-hundred-mile bicycle ride",
    ["turning wheels", "rolling elevation", "far horizon"],
    ["contour-atlas-ink", "risograph-overprint", "wood-marquetry-landscape"],
  ),
  idea(
    "swam-a-mile",
    "wellbeing",
    "Swam a mile",
    "Swim one continuous mile",
    ["measured water", "repeating stroke", "calm strength"],
    ["stained-glass-field", "cyanotype-field-study", "prismatic-geometric-symbolism"],
  ),
  idea(
    "returned-after-injury",
    "wellbeing",
    "Came back after injury",
    "Return to a valued activity after healing",
    ["mended line", "new growth", "first confident step"],
    ["ceramic-underglaze", "thread-painted-embroidery", "cut-paper-strata"],
  ),
  idea(
    "read-50-books",
    "learning",
    "Read fifty books",
    "Finish fifty books in a personally meaningful period",
    ["many spines", "opening worlds", "quiet chair"],
    ["wood-marquetry-landscape", "risograph-overprint", "woven-tapestry-field"],
  ),
  idea(
    "learned-a-language",
    "learning",
    "Learned another language",
    "Reach a conversational level in another language",
    ["two shores", "shared meaning", "new voice"],
    ["prismatic-geometric-symbolism", "mosaic-tesserae-field", "luminous-ligne-claire"],
  ),
  idea(
    "finished-online-course",
    "learning",
    "Finished a serious course",
    "Complete a substantial course of study",
    ["ascending modules", "worked notebook", "open threshold"],
    ["cut-paper-strata", "mineral-line-engraving", "matte-gouache-editorial"],
  ),
  idea(
    "defended-thesis",
    "learning",
    "Defended a thesis",
    "Successfully defend an academic thesis",
    ["dense pages", "clear argument", "room of light"],
    ["mineral-line-engraving", "aquatint-atmosphere", "prismatic-geometric-symbolism"],
  ),
  idea(
    "taught-a-class",
    "learning",
    "Taught a class",
    "Teach a complete class or workshop",
    ["circle of learners", "passed spark", "open hands"],
    ["fresco-mineral-pigment", "matte-gouache-editorial", "risograph-overprint"],
  ),
  idea(
    "earned-degree",
    "learning",
    "Earned a degree",
    "Complete a degree that matters to you",
    ["long staircase", "open door", "gathered years"],
    ["mineral-line-engraving", "cut-paper-strata", "prismatic-geometric-symbolism"],
  ),
  idea(
    "first-job",
    "life",
    "Started a first job",
    "Begin your first meaningful job",
    ["first key", "morning commute", "new desk"],
    ["risograph-overprint", "matte-gouache-editorial", "pixel-cluster-landscape"],
  ),
  idea(
    "career-change",
    "life",
    "Changed careers",
    "Make a deliberate move into a new career",
    ["forked path", "shed skin", "new horizon"],
    ["luminous-ligne-claire", "prismatic-geometric-symbolism", "cut-paper-strata"],
  ),
  idea(
    "bought-first-home",
    "life",
    "Made a first home",
    "Move into a home that is truly yours",
    ["warm window", "held key", "settled roots"],
    ["wood-marquetry-landscape", "thread-painted-embroidery", "matte-gouache-editorial"],
  ),
  idea(
    "moved-new-city",
    "life",
    "Moved to a new city",
    "Build a life in a new city",
    ["packed boxes", "unknown skyline", "first familiar street"],
    ["luminous-ligne-claire", "risograph-overprint", "cut-paper-strata"],
  ),
  idea(
    "got-drivers-license",
    "life",
    "Earned a driver's license",
    "Qualify for and receive a driver's license",
    ["open road", "green light", "new independence"],
    ["pixel-cluster-landscape", "risograph-overprint", "relief-blockprint"],
  ),
  idea(
    "became-citizen",
    "life",
    "Became a citizen",
    "Complete a meaningful citizenship journey",
    ["two histories", "belonging", "new chapter"],
    ["woven-tapestry-field", "mosaic-tesserae-field", "prismatic-geometric-symbolism"],
  ),
  idea(
    "retired",
    "life",
    "Retired",
    "Complete a working career and enter retirement",
    ["tools at rest", "wide morning", "unclaimed path"],
    ["plein-air-broken-color", "wood-marquetry-landscape", "aquatint-atmosphere"],
  ),
  idea(
    "became-parent",
    "life",
    "Became a parent",
    "Welcome a child into your life",
    ["small hand", "night vigil", "growing circle"],
    ["thread-painted-embroidery", "watercolor-naturalist-study", "cut-paper-strata"],
  ),
  idea(
    "adopted-pet",
    "life",
    "Adopted a companion",
    "Give an animal a lasting home",
    ["two sets of footprints", "open door", "shared routine"],
    ["watercolor-naturalist-study", "matte-gouache-editorial", "woven-tapestry-field"],
  ),
  idea(
    "published-book",
    "creative",
    "Published a book",
    "Publish a complete book",
    ["bound pages", "ink becoming horizon", "reader's light"],
    ["mineral-line-engraving", "wood-marquetry-landscape", "risograph-overprint"],
  ),
  idea(
    "finished-novel",
    "creative",
    "Finished a novel",
    "Write a complete novel draft",
    ["last line", "stacked pages", "world beyond desk"],
    ["aquatint-atmosphere", "luminous-ligne-claire", "cut-paper-strata"],
  ),
  idea(
    "shipped-app",
    "creative",
    "Shipped an app",
    "Release a software application for real people to use",
    ["assembled system", "launch glow", "first signal"],
    ["pixel-cluster-landscape", "prismatic-geometric-symbolism", "luminous-ligne-claire"],
  ),
  idea(
    "exhibited-art",
    "creative",
    "Exhibited original art",
    "Show your original work in a public exhibition",
    ["lit wall", "gathered works", "viewer pausing"],
    ["plein-air-broken-color", "fresco-mineral-pigment", "matte-gouache-editorial"],
  ),
  idea(
    "performed-live",
    "creative",
    "Performed live",
    "Complete a live performance before an audience",
    ["stage light", "held breath", "shared applause"],
    ["screenprint-night", "risograph-overprint", "prismatic-geometric-symbolism"],
  ),
  idea(
    "recorded-song",
    "creative",
    "Recorded a song",
    "Finish and record an original song",
    ["waveform river", "quiet microphone", "captured moment"],
    ["screenprint-night", "mosaic-tesserae-field", "luminous-ligne-claire"],
  ),
  idea(
    "made-short-film",
    "creative",
    "Made a film",
    "Complete an original short film",
    ["frames in motion", "projected light", "final cut"],
    ["screenprint-night", "aquatint-atmosphere", "risograph-overprint"],
  ),
  idea(
    "knit-sweater",
    "craft",
    "Made a sweater",
    "Knit or crochet a complete wearable sweater",
    ["interlocking loops", "warm sleeves", "patient rows"],
    ["thread-painted-embroidery", "woven-tapestry-field", "mosaic-tesserae-field"],
  ),
  idea(
    "built-furniture",
    "craft",
    "Built a piece of furniture",
    "Design and build a useful piece of furniture",
    ["shavings", "joined wood", "finished form"],
    ["wood-marquetry-landscape", "mineral-line-engraving", "relief-blockprint"],
  ),
  idea(
    "sewed-garment",
    "craft",
    "Sewed a garment",
    "Make and wear a complete garment",
    ["pattern pieces", "clean seam", "moving fabric"],
    ["thread-painted-embroidery", "cut-paper-strata", "risograph-overprint"],
  ),
  idea(
    "mastered-signature-dish",
    "craft",
    "Mastered a signature dish",
    "Create a dish you are proud to make for others",
    ["steam spiral", "shared table", "practiced hands"],
    ["ceramic-underglaze", "watercolor-naturalist-study", "matte-gouache-editorial"],
  ),
  idea(
    "restored-something",
    "craft",
    "Restored something treasured",
    "Repair and restore an object worth keeping",
    ["mended break", "old material", "renewed use"],
    ["fresco-mineral-pigment", "wood-marquetry-landscape", "mineral-line-engraving"],
  ),
  idea(
    "hosted-family-reunion",
    "community",
    "Hosted a family reunion",
    "Bring family together for a reunion",
    ["long table", "many generations", "shared stories"],
    ["woven-tapestry-field", "thread-painted-embroidery", "matte-gouache-editorial"],
  ),
  idea(
    "volunteered-year",
    "community",
    "Gave a year of service",
    "Complete a sustained year of meaningful volunteer service",
    ["many hands", "steady return", "changed place"],
    ["relief-blockprint", "mosaic-tesserae-field", "fresco-mineral-pigment"],
  ),
  idea(
    "mentored-someone",
    "community",
    "Mentored someone",
    "Help another person grow through sustained mentorship",
    ["passed lantern", "parallel path", "new confidence"],
    ["luminous-ligne-claire", "watercolor-naturalist-study", "prismatic-geometric-symbolism"],
  ),
  idea(
    "organized-community-event",
    "community",
    "Organized a community event",
    "Bring people together around a shared purpose",
    ["gathering circle", "many small lights", "common ground"],
    ["mosaic-tesserae-field", "risograph-overprint", "thread-painted-embroidery"],
  ),
  idea(
    "donated-blood",
    "community",
    "Donated blood",
    "Complete a blood donation",
    ["red river", "open hand", "quiet gift"],
    ["prismatic-geometric-symbolism", "watercolor-naturalist-study", "screenprint-night"],
  ),
  idea(
    "learned-first-aid",
    "community",
    "Learned first aid",
    "Complete practical first-aid training",
    ["steady hands", "field kit", "calm response"],
    ["matte-gouache-editorial", "cyanotype-field-study", "risograph-overprint"],
  ),
  idea(
    "scuba-certified",
    "adventure",
    "Learned to scuba dive",
    "Earn an entry-level scuba certification",
    ["first descent", "rising bubbles", "blue world"],
    ["stained-glass-field", "cyanotype-field-study", "mosaic-tesserae-field"],
  ),
  idea(
    "first-skydive",
    "adventure",
    "Made a skydive",
    "Complete a first skydive",
    ["open aircraft door", "vast patchwork", "rush of air"],
    ["luminous-ligne-claire", "prismatic-geometric-symbolism", "risograph-overprint"],
  ),
  idea(
    "sailed-open-water",
    "adventure",
    "Sailed open water",
    "Crew or captain a meaningful open-water sail",
    ["full sail", "deep horizon", "weather sense"],
    ["wood-marquetry-landscape", "plein-air-broken-color", "relief-blockprint"],
  ),
  idea(
    "learned-instrument",
    "creative",
    "Learned an instrument",
    "Play a complete piece confidently on an instrument",
    ["practiced scales", "resonant wood", "first whole song"],
    ["wood-marquetry-landscape", "screenprint-night", "mineral-line-engraving"],
  ),
  idea(
    "gave-keynote",
    "learning",
    "Gave a major talk",
    "Deliver a substantial public talk or keynote",
    ["single stage", "clear voice", "listening room"],
    ["aquatint-atmosphere", "prismatic-geometric-symbolism", "risograph-overprint"],
  ),
  idea(
    "kept-long-friendship",
    "community",
    "Kept a lifelong friendship",
    "Honor a friendship sustained across major seasons of life",
    ["two paths", "changing seasons", "same meeting place"],
    ["woven-tapestry-field", "plein-air-broken-color", "luminous-ligne-claire"],
  ),
] as const;
