import type { MichelinInventorySnapshotRow } from "./michelin-inventory-snapshot";

// Official New York result page 1, normalized with each linked Guide record on 2026-08-25.
export const michelinInventoryNewYorkPageOne = Object.freeze([
  [
    1,
    "Icca",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/icca",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    2,
    "Atera",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/atera",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    3,
    "Huso",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/huso-1218089",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    4,
    "Jungsik New York",
    3,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/jungsik-new-york",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    5,
    "Crown Shy",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/crown-shy",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    6,
    "Saga",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/saga",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    7,
    "Bridges",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/bridges-1216261",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    8,
    "Yamada",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/yamada",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    9,
    "Le Coucou",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/le-coucou",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    10,
    "Muku",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/muku",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    11,
    "L’Abeille",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/l%E2%80%99abeille",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    12,
    "Corima",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/corima",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    13,
    "Dirt Candy",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/dirt-candy",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    14,
    "César",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/cesar",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    15,
    "Torrisi",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/torrisi",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    16,
    "Estela",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/estela",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    17,
    "Torien",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/torien",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    18,
    "Yoshino",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/yoshino-1185037",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    19,
    "Sixty Three Clinton",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/63-clinton",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    20,
    "Sushi Nakazawa New York",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/sushi-nakazawa",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    21,
    "Family Meal at Blue Hill",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/blue-hill",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    22,
    "Jeju Noodle Bar",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/jeju-noodle-bar",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    23,
    "Frevo",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/frevo",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    24,
    "Shmoné",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/shmone",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    25,
    "Tuome",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/tuome",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    26,
    "Bar Miller",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/bar-miller",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    27,
    "Tsukimi",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/tsukimi",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    28,
    "Semma",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/semma",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    29,
    "Kosaka",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/kosaka",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    30,
    "Casa Mono",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/casa-mono",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    31,
    "Oiji Mi",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/oiji-mi",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    32,
    "bōm",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/bom",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    33,
    "Gramercy Tavern",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/gramercy-tavern",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    34,
    "Rezdôra",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/rezdora-osteria-emiliana",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    35,
    "Noda",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/noda",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    36,
    "Odo",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/odo",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    37,
    "Noz 17",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/noz17",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    38,
    "Aska",
    2,
    "Brooklyn, NY, USA",
    "https://guide.michelin.com/en/new-york-state/brooklyn/restaurant/aska",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    39,
    "Cote",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/cote",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    40,
    "Jua",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/jua",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    41,
    "Shota Omakase",
    1,
    "Brooklyn, NY, USA",
    "https://guide.michelin.com/en/new-york-state/brooklyn/restaurant/shota-omakase",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    42,
    "Eleven Madison Park",
    3,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/eleven-madison-park",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    43,
    "Francie",
    1,
    "Brooklyn, NY, USA",
    "https://guide.michelin.com/en/new-york-state/brooklyn/restaurant/francie",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    44,
    "Atomix",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/atomix",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    45,
    "The Four Horsemen",
    1,
    "Brooklyn, NY, USA",
    "https://guide.michelin.com/en/new-york-state/brooklyn/restaurant/the-four-horsemen",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    46,
    "Joo Ok",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/joo-ok-1214822",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    47,
    "Nōksu",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/noksu",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
  [
    48,
    "Oxomoco",
    1,
    "Brooklyn, NY, USA",
    "https://guide.michelin.com/en/new-york-state/brooklyn/restaurant/oxomoco",
    "https://guide.michelin.com/en/us/new-york-state/new-york/restaurants/all-starred",
  ],
] satisfies readonly MichelinInventorySnapshotRow[]);
