import type { MichelinRestaurantNycInput } from "./michelin-restaurants-nyc-types";

export const newYorkCityMichelinRestaurantInputs03b = [
  {
    slug: "le-bernardin",
    restaurantName: "Le Bernardin",
    city: "New York",
    starCount: 3,
    cuisine: "Seafood",
    guidePath: "le-bernardin",
    listingPage: 2,
    cueType: "dish",
    evidenceCue:
      "A thin sheet of yellowfin tuna over a foie-gras-topped baguette expresses the seafood kitchen's quiet French precision.",
    primaryForms: [
      "one broad tuna veil",
      "one slender baguette block",
      "one seafood-kitchen wave",
      "one foie-gras oval",
    ],
    supportingAccents: ["one horseradish-ivory curve"],
    colorFamilies: ["tuna rose", "ocean blue", "baguette gold", "formal charcoal"],
    candidateStyles: ["matte-gouache-editorial", "stained-glass-field", "ceramic-underglaze"],
  },
  {
    slug: "the-modern",
    restaurantName: "The Modern",
    city: "New York",
    starCount: 2,
    cuisine: "Contemporary",
    guidePath: "the-modern",
    listingPage: 2,
    cueType: "interior",
    evidenceCue: "A bright dining room opens directly toward the Museum of Modern Art's sculpture garden.",
    primaryForms: [
      "one broad garden window",
      "one sculptural oval",
      "one bright room plane",
      "one gallery-frame band",
    ],
    supportingAccents: ["one abstract blue curve"],
    colorFamilies: ["gallery ivory", "garden green", "modern blue", "soft graphite"],
    candidateStyles: ["prismatic-geometric-symbolism", "cut-paper-strata", "stained-glass-field"],
  },
  {
    slug: "yingtao",
    restaurantName: "YingTao",
    city: "New York",
    starCount: 1,
    cuisine: "Contemporary, Chinese",
    guidePath: "yingtao",
    listingPage: 2,
    cueType: "dish",
    evidenceCue:
      "A curved chef's counter overlooks YingTao's open kitchen, where Berkshire-pork-and-tiger-prawn wontons float in broth before a coconut-forward nian gao.",
    additionalEvidenceSourceUrls: [
      "https://guide.michelin.com/us/en/new-york-state/new-york/restaurant/yingtao",
      "https://www.yingtaonyc.com/about",
      "https://www.yingtaonyc.com/menu",
    ],
    primaryForms: [
      "one curved chef-counter crescent",
      "two pleated pork-and-prawn wontons",
      "one golden broth bowl",
    ],
    supportingAccents: [],
    colorFamilies: ["cherry crimson", "broth gold", "porcelain ivory", "ink black"],
    candidateStyles: ["ceramic-underglaze", "thread-painted-embroidery", "stained-glass-field"],
  },
  {
    slug: "aquavit",
    restaurantName: "Aquavit",
    city: "New York",
    starCount: 2,
    cuisine: "Scandinavian",
    guidePath: "aquavit",
    listingPage: 2,
    cueType: "culture",
    evidenceCue:
      "Nordic light woods and a restrained room frame Scandinavian traditions including herring, gravlax, and preserved flavors.",
    primaryForms: [
      "one pale timber plane",
      "one restrained-room horizon",
      "one herring-silver crescent",
      "one preserved-flavor jar arch",
    ],
    supportingAccents: ["one dill-green curve"],
    colorFamilies: ["pale birch", "fjord blue", "silver gray", "dill green"],
    candidateStyles: ["wood-marquetry-landscape", "woven-tapestry-field", "stained-glass-field"],
  },
  {
    slug: "per-se",
    restaurantName: "Per Se",
    city: "New York",
    starCount: 3,
    cuisine: "Contemporary",
    guidePath: "per-se",
    listingPage: 2,
    cueType: "interior",
    evidenceCue:
      "A blue entrance door leads to a fireplace and broad Central Park views in the formal dining room.",
    primaryForms: [
      "one blue doorway arch",
      "one fireplace block",
      "one park-canopy horizon",
      "one tall window plane",
    ],
    supportingAccents: ["one warm hearth curve"],
    colorFamilies: ["doorway blue", "park green", "hearth amber", "limestone cream"],
    candidateStyles: ["stained-glass-field", "wood-marquetry-landscape", "fresco-mineral-pigment"],
  },
  {
    slug: "masa",
    restaurantName: "Masa",
    city: "New York",
    starCount: 2,
    cuisine: "Japanese, Sushi",
    guidePath: "masa",
    listingPage: 2,
    cueType: "interior",
    evidenceCue:
      "A strikingly smooth hinoki counter creates a calm ceremonial setting for an imaginative luxury omakase.",
    primaryForms: [
      "one smooth hinoki counter",
      "one calm circular field",
      "one omakase plate crescent",
      "one ceremonial serving wave",
    ],
    supportingAccents: ["one abalone-shell arc"],
    colorFamilies: ["hinoki honey", "pearl gray", "deep charcoal", "shell blue"],
    candidateStyles: ["wood-marquetry-landscape", "ceramic-underglaze", "stained-glass-field"],
  },
  {
    slug: "jean-georges",
    restaurantName: "Jean-Georges",
    city: "New York",
    starCount: 2,
    cuisine: "Contemporary",
    guidePath: "jean-georges",
    listingPage: 2,
    cueType: "interior",
    evidenceCue:
      "A light-filled room at Central Park West frames French technique sharpened by Asian aromatics and bright acidity.",
    primaryForms: [
      "one luminous window arch",
      "one park-green canopy",
      "one citrus-gold disk",
      "one aromatic leaf curve",
    ],
    supportingAccents: ["one pale sauce wave"],
    colorFamilies: ["park green", "citrus gold", "warm ivory", "soft gray"],
    candidateStyles: ["stained-glass-field", "thread-painted-embroidery", "matte-gouache-editorial"],
  },
  {
    slug: "cafe-boulud",
    restaurantName: "Café Boulud",
    city: "New York",
    starCount: 1,
    cuisine: "French",
    guidePath: "cafe-boulud",
    listingPage: 2,
    cueType: "dish",
    evidenceCue:
      "Café Boulud's Art Deco-inspired room frames black sea bass wrapped in crispy potato, set over leek fondue with a rich red-wine sauce meurette.",
    additionalEvidenceSourceUrls: [
      "https://guide.michelin.com/us/en/new-york-state/new-york/restaurant/cafe-boulud",
      "https://www.cafeboulud.com/nyc/our-menu/dinner/",
    ],
    primaryForms: [
      "one pointed black-sea-bass silhouette",
      "two diagonal crispy-potato bands",
      "one burgundy meurette-sauce pool",
      "one stepped Art Deco corner",
    ],
    supportingAccents: [],
    colorFamilies: ["midnight blue", "crispy-potato gold", "burgundy", "leek green", "warm ivory"],
    candidateStyles: ["wood-marquetry-landscape", "woven-tapestry-field", "stained-glass-field"],
  },
  {
    slug: "daniel",
    restaurantName: "Daniel",
    city: "New York",
    starCount: 1,
    cuisine: "French",
    guidePath: "daniel",
    listingPage: 2,
    cueType: "interior",
    evidenceCue:
      "Grand neoclassical arches and columns give the formal Upper East Side dining room a stately architectural rhythm.",
    primaryForms: [
      "three neoclassical arches",
      "two broad column blocks",
      "one formal floor plane",
      "one architectural rhythm band",
    ],
    supportingAccents: ["one gilded curve"],
    colorFamilies: ["stone cream", "deep blue", "antique gold", "soft plum"],
    candidateStyles: ["fresco-mineral-pigment", "stained-glass-field", "wood-marquetry-landscape"],
  },
  {
    slug: "sushi-noz",
    restaurantName: "Sushi Noz",
    city: "New York",
    starCount: 2,
    cuisine: "Japanese, Sushi",
    guidePath: "sushi-noz",
    listingPage: 2,
    cueType: "interior",
    evidenceCue:
      "A cedar-lined room and hinoki counter evoke an old Kyoto setting for a rigorous Edomae omakase.",
    primaryForms: [
      "one hinoki counter band",
      "one cedar room arch",
      "one old-room wall plane",
      "one Edomae tasting disk",
    ],
    supportingAccents: ["one antique icebox block"],
    colorFamilies: ["cedar brown", "hinoki honey", "tide blue", "rice ivory"],
    candidateStyles: ["wood-marquetry-landscape", "relief-blockprint", "ceramic-underglaze"],
  },
  {
    slug: "essential-by-christophe",
    restaurantName: "Essential by Christophe",
    city: "New York",
    starCount: 1,
    cuisine: "French Contemporary",
    guidePath: "essential-by-christophe",
    listingPage: 2,
    cueType: "dish",
    evidenceCue:
      "Essential's heavy iron doors, leather, brass, and beige room frame three blue prawns with genmaicha tuile, Kirby chutney, and dill-and-chive bouillon.",
    additionalEvidenceSourceUrls: [
      "https://guide.michelin.com/ca/en/new-york-state/new-york/restaurant/essential-by-christophe",
      "https://www.essentialbychristophe.com/menus/",
    ],
    primaryForms: [
      "three broad blue-prawn curls",
      "one toasted genmaicha tuile",
      "one herb-green bouillon disk",
      "one iron doorway with brass-and-beige field",
    ],
    supportingAccents: [],
    colorFamilies: ["prawn cobalt", "toasted tan", "herb green", "soft brass", "warm beige"],
    candidateStyles: ["matte-gouache-editorial", "stained-glass-field", "ceramic-underglaze"],
  },
] satisfies readonly MichelinRestaurantNycInput[];
