import type { MichelinRestaurantNycInput } from "./michelin-restaurants-nyc-types";

export const newYorkCityMichelinRestaurantInputs03a = [
  {
    slug: "noksu",
    restaurantName: "Nōksu",
    city: "New York",
    starCount: 1,
    cuisine: "Contemporary",
    guidePath: "noksu",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A passage inside a subway station leads to a dark, theatrical twelve-seat counter facing the kitchen.",
    primaryForms: [
      "one subway passage arch",
      "one continuous counter band",
      "one theatrical light cone",
      "one dark kitchen block",
    ],
    supportingAccents: ["one steel rail curve"],
    colorFamilies: ["subway charcoal", "steel gray", "stage amber", "deep navy"],
    candidateStyles: ["screenprint-night", "cut-paper-strata", "prismatic-geometric-symbolism"],
  },
  {
    slug: "oxomoco",
    restaurantName: "Oxomoco",
    city: "Brooklyn",
    starCount: 1,
    cuisine: "Mexican",
    guidePath: "oxomoco",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A skylit Greenpoint room filled with hanging plants supports a menu centered on wood-fired Mexican cooking.",
    primaryForms: [
      "one broad skylight plane",
      "one hanging plant canopy",
      "one wood-fire disk",
      "one low room arch",
    ],
    supportingAccents: ["one smoke ribbon"],
    colorFamilies: ["leaf green", "sky blue", "ember amber", "stucco cream"],
    candidateStyles: ["stained-glass-field", "thread-painted-embroidery", "ceramic-underglaze"],
  },
  {
    slug: "tempura-matsui",
    restaurantName: "Tempura Matsui",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Tempura",
    guidePath: "tempura-matsui",
    listingPage: 2,
    cueType: "culture",
    evidenceCue:
      "Counter seats reveal a traditional tempura sequence fried in sesame and cottonseed oils with an especially light batter.",
    primaryForms: [
      "one long chef counter",
      "one pale batter arc",
      "one sesame-gold oil wave",
      "one crisp shrimp-leg fan",
    ],
    supportingAccents: ["one shiso-green leaf"],
    colorFamilies: ["sesame gold", "batter ivory", "shiso green", "charcoal"],
    candidateStyles: ["ceramic-underglaze", "relief-blockprint", "wood-marquetry-landscape"],
  },
  {
    slug: "restaurant-yuu",
    restaurantName: "Restaurant Yuu",
    city: "Brooklyn",
    starCount: 1,
    cuisine: "French Contemporary, Japanese",
    guidePath: "restaurant-yuu",
    listingPage: 2,
    cueType: "interior",
    evidenceCue:
      "At service, curtains open to reveal the full kitchen team in a large warehouse-like room staged as a culinary performance.",
    primaryForms: [
      "two opening curtain bands",
      "one broad kitchen stage",
      "one warehouse ceiling arch",
      "one spotlight disk",
    ],
    supportingAccents: ["one pastry-gold curve"],
    colorFamilies: ["stage charcoal", "curtain blue", "bright ivory", "pastry gold"],
    candidateStyles: ["cut-paper-strata", "screenprint-night", "thread-painted-embroidery"],
  },
  {
    slug: "chefs-table-at-brooklyn-fare",
    restaurantName: "Chef's Table at Brooklyn Fare",
    city: "New York",
    starCount: 2,
    cuisine: "Contemporary",
    guidePath: "chef-s-table-at-brooklyn-fare",
    listingPage: 2,
    cueType: "interior",
    evidenceCue:
      "A glossy walnut counter wraps around the visible brigade in a spotlighted room hidden behind a grocery store.",
    primaryForms: [
      "one glossy walnut horseshoe",
      "one central kitchen block",
      "one hidden-store doorway",
      "one bright spotlight cone",
    ],
    supportingAccents: ["one crisp pastry crescent"],
    colorFamilies: ["walnut brown", "spotlight ivory", "deep charcoal", "copper"],
    candidateStyles: ["wood-marquetry-landscape", "screenprint-night", "prismatic-geometric-symbolism"],
  },
  {
    slug: "sushi-sho",
    restaurantName: "Sushi Sho",
    city: "New York",
    starCount: 3,
    cuisine: "Japanese, Sushi",
    guidePath: "sushi-sho-1213976",
    listingPage: 2,
    cueType: "interior",
    evidenceCue:
      "A hinoki counter stands between towering carved-wood iceboxes as an omakase explores fermentation and preserved Edomae techniques.",
    primaryForms: [
      "one broad hinoki counter",
      "two towering icebox blocks",
      "one fermentation spiral",
      "one preserved-fish crescent",
    ],
    supportingAccents: ["one carved-wood wave"],
    colorFamilies: ["hinoki honey", "ice gray", "ocean blue", "deep charcoal"],
    candidateStyles: ["wood-marquetry-landscape", "relief-blockprint", "ceramic-underglaze"],
  },
  {
    slug: "gabriel-kreuther",
    restaurantName: "Gabriel Kreuther",
    city: "New York",
    starCount: 2,
    cuisine: "French, Contemporary",
    guidePath: "gabriel-kreuther",
    listingPage: 2,
    cueType: "interior",
    evidenceCue:
      "A cavernous Bryant Park room uses cream banquettes, fine art, and sparkling table settings for polished Alsatian-rooted dining.",
    primaryForms: [
      "one cavernous room arch",
      "one cream banquette crescent",
      "one framed art block",
      "one park-green horizon",
    ],
    supportingAccents: ["one kugelhopf-gold curve"],
    colorFamilies: ["cream", "park green", "Alsatian gold", "soft graphite"],
    candidateStyles: ["stained-glass-field", "fresco-mineral-pigment", "thread-painted-embroidery"],
  },
  {
    slug: "le-pavillon",
    restaurantName: "Le Pavillon",
    city: "New York",
    starCount: 1,
    cuisine: "French, Contemporary",
    guidePath: "le-pavillon-1192744",
    listingPage: 2,
    cueType: "interior",
    evidenceCue:
      "Soaring ceilings, plate glass, a warm palette, and a blown-glass chandelier define the skyscraper dining room.",
    primaryForms: [
      "one soaring ceiling arch",
      "one plate-glass window",
      "one blown-glass chandelier",
      "one skyline horizon band",
    ],
    supportingAccents: ["one vegetable-green curve"],
    colorFamilies: ["warm amber", "glass blue", "vegetable green", "soft cream"],
    candidateStyles: ["stained-glass-field", "cut-paper-strata", "prismatic-geometric-symbolism"],
  },
  {
    slug: "joji",
    restaurantName: "Jōji",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "joji",
    listingPage: 2,
    cueType: "culture",
    evidenceCue:
      "A calm counter beneath One Vanderbilt pairs Toyosu seafood with carefully vinegared blended rice and seasonal Japanese accents.",
    primaryForms: [
      "one calm counter band",
      "one tower-base arch",
      "one blended-rice crescent",
      "one Toyosu-seafood wave",
    ],
    supportingAccents: ["one yuzu-gold disk"],
    colorFamilies: ["cypress tan", "tide blue", "rice ivory", "yuzu gold"],
    candidateStyles: ["wood-marquetry-landscape", "ceramic-underglaze", "woven-tapestry-field"],
  },
  {
    slug: "meju",
    restaurantName: "Meju",
    city: "Queens",
    starCount: 1,
    cuisine: "Korean",
    guidePath: "meju",
    listingPage: 2,
    cueType: "culture",
    evidenceCue:
      "An eight-seat L-shaped counter hides behind a banchan shop, facing an open kitchen while decade-aged Korean ferments shape the menu.",
    primaryForms: [
      "one hidden market doorway",
      "three fermentation vessel ovals",
      "one cellar shelf block",
      "one slow-rising spiral",
    ],
    supportingAccents: ["one soybean-gold crescent"],
    colorFamilies: ["earthen brown", "soybean gold", "celadon", "ink black"],
    candidateStyles: ["ceramic-underglaze", "fresco-mineral-pigment", "relief-blockprint"],
  },
  {
    slug: "kochi",
    restaurantName: "Kochi",
    city: "New York",
    starCount: 1,
    cuisine: "Korean",
    guidePath: "kochi",
    listingPage: 2,
    cueType: "culture",
    evidenceCue:
      "A Korean tasting menu is organized around composed skewers, drawing inspiration from royal-court and street-food traditions.",
    primaryForms: [
      "three broad skewer diagonals",
      "one royal-fan arc",
      "one street-grill disk",
      "one street-food counter band",
    ],
    supportingAccents: ["one sesame-gold curve"],
    colorFamilies: ["deep teal", "sesame gold", "plum", "warm ivory"],
    candidateStyles: ["thread-painted-embroidery", "relief-blockprint", "stained-glass-field"],
  },
  {
    slug: "mari",
    restaurantName: "Mari",
    city: "New York",
    starCount: 1,
    cuisine: "Korean",
    guidePath: "mari",
    listingPage: 2,
    cueType: "dish",
    evidenceCue: "A multi-course tasting sequence builds Korean flavors into carefully folded hand rolls.",
    primaryForms: [
      "three folded seaweed cones",
      "one rice-ivory wave",
      "one sesame disk",
      "one tasting-course band",
    ],
    supportingAccents: ["one pickled-vegetable curve"],
    colorFamilies: ["seaweed green", "rice ivory", "sesame gold", "mountain blue"],
    candidateStyles: ["cut-paper-strata", "ceramic-underglaze", "thread-painted-embroidery"],
  },
] satisfies readonly MichelinRestaurantNycInput[];
