import type { MichelinInventorySnapshotRow } from "./michelin-inventory-snapshot";

// Official New York result page 2, normalized with each linked Guide record on 2026-08-25.
export const michelinInventoryNewYorkPageTwo = Object.freeze([
  [
    49,
    "Tempura Matsui",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/tempura-matsui",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    50,
    "Restaurant Yuu",
    1,
    "Brooklyn, NY, USA",
    "https://guide.michelin.com/en/new-york-state/brooklyn/restaurant/restaurant-yuu",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    51,
    "Chef's Table at Brooklyn Fare",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/chef-s-table-at-brooklyn-fare",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    52,
    "Sushi Sho",
    3,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/sushi-sho-1213976",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    53,
    "Gabriel Kreuther",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/gabriel-kreuther",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    54,
    "Le Pavillon",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/le-pavillon-1192744",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    55,
    "Jōji",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/joji",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    56,
    "Meju",
    1,
    "Queens, NY, USA",
    "https://guide.michelin.com/en/new-york-state/queens/restaurant/meju",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    57,
    "Kochi",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/kochi",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    58,
    "Mari",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/mari",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    59,
    "Le Bernardin",
    3,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/le-bernardin",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    60,
    "The Modern",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/the-modern",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    61,
    "YingTao",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/yingtao",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    62,
    "Aquavit",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/aquavit",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    63,
    "Per Se",
    3,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/per-se",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    64,
    "Masa",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/masa",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    65,
    "Jean-Georges",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/jean-georges",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    66,
    "Café Boulud",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/cafe-boulud",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    67,
    "Daniel",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/daniel",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    68,
    "Sushi Noz",
    2,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/sushi-noz",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
  [
    69,
    "Essential by Christophe",
    1,
    "New York, NY, USA",
    "https://guide.michelin.com/en/new-york-state/new-york/restaurant/essential-by-christophe",
    "https://guide.michelin.com/us/en/new-york-state/new-york/restaurants/all-starred/page/2",
  ],
] satisfies readonly MichelinInventorySnapshotRow[]);
