import { defineMichelinRestaurantNycSeed } from "./michelin-restaurants-nyc-types";
import type { MichelinRestaurantNycInput } from "./michelin-restaurants-nyc-types";

const inputs = [
  {
    slug: "icca",
    restaurantName: "Icca",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "icca",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A discreet cocktail bar gives way to a secluded chef counter where traditional nigiri is lightly brushed with nikiri.",
    primaryForms: [
      "one shadowed doorway arch",
      "one long cypress counter",
      "one brushed amber wave",
      "one nigiri plate disk",
    ],
    supportingAccents: ["one pale rice crescent"],
    colorFamilies: ["smoked charcoal", "cypress honey", "ocean blue", "rice ivory"],
    candidateStyles: ["wood-marquetry-landscape", "stained-glass-field", "relief-blockprint"],
  },
  {
    slug: "atera",
    restaurantName: "Atera",
    city: "New York",
    starCount: 2,
    cuisine: "Contemporary",
    guidePath: "atera",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "The dark, sleek dining room centers on a spacious U-shaped counter facing the open kitchen.",
    primaryForms: [
      "one sweeping counter horseshoe",
      "one central kitchen block",
      "one charcoal ceiling plane",
      "one luminous copper disk",
    ],
    supportingAccents: ["two narrow light bars"],
    colorFamilies: ["charcoal", "warm copper", "slate blue", "soft ivory"],
    candidateStyles: ["screenprint-night", "cut-paper-strata", "prismatic-geometric-symbolism"],
  },
  {
    slug: "huso",
    restaurantName: "Huso",
    city: "New York",
    starCount: 1,
    cuisine: "Contemporary",
    guidePath: "huso-1218089",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "Flowing white drapes and soft lighting turn the room behind a caviar shop into a quiet hideaway.",
    primaryForms: [
      "two flowing curtain bands",
      "one pearl-like central oval",
      "one low counter block",
      "one soft shadow arch",
    ],
    supportingAccents: ["one silver current"],
    colorFamilies: ["pearl ivory", "mist gray", "midnight blue", "soft silver"],
    candidateStyles: ["thread-painted-embroidery", "stained-glass-field", "woven-tapestry-field"],
  },
  {
    slug: "jungsik-new-york",
    restaurantName: "Jungsik New York",
    city: "New York",
    starCount: 3,
    cuisine: "Korean",
    guidePath: "jungsik-new-york",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "Jungsik's tasting opens with banchan before striped jack with white kimchi, crisp octopus with gochujang aioli, and dry-aged Arctic char.",
    additionalEvidenceSourceUrls: [
      "https://dgaddcosprod.blob.core.windows.net/cxf-corporate/attachments/endyick6oro494vpmrmcjzus-20241210-pr-michelinguide-nyc-chi-dc-2025.pdf",
      "https://www.jungsik.com/menu/",
    ],
    primaryForms: [
      "one banchan presentation disk",
      "one striped-jack ribbon",
      "one crisp octopus arc",
      "one Arctic-char oval",
    ],
    supportingAccents: ["one white-kimchi inset"],
    colorFamilies: ["ink black", "kimchi ivory", "striped-jack blue", "gochujang coral"],
    candidateStyles: ["ceramic-underglaze", "fresco-mineral-pigment", "relief-blockprint"],
  },
  {
    slug: "crown-shy",
    restaurantName: "Crown Shy",
    city: "New York",
    starCount: 1,
    cuisine: "Contemporary, American",
    guidePath: "crown-shy",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "An Art Deco tower lobby brings soaring ceilings, marble floors, and tall windows to the dining room.",
    primaryForms: [
      "one tall stepped tower",
      "three window arches",
      "one marble floor wedge",
      "one upward gold ray",
    ],
    supportingAccents: ["one geometric canopy"],
    colorFamilies: ["marble cream", "deep teal", "aged gold", "graphite"],
    candidateStyles: ["stained-glass-field", "wood-marquetry-landscape", "prismatic-geometric-symbolism"],
  },
  {
    slug: "saga",
    restaurantName: "Saga",
    city: "New York",
    starCount: 2,
    cuisine: "Contemporary",
    guidePath: "saga",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A high-rise terrace and jewel-toned rooms pair skyline views with peach velvet, green marble, and carved stone.",
    primaryForms: [
      "one tall skyline silhouette",
      "one terrace horizon",
      "one velvet peach arc",
      "one green marble block",
    ],
    supportingAccents: ["one carved-stone crescent"],
    colorFamilies: ["emerald", "soft peach", "night navy", "stone cream"],
    candidateStyles: ["cut-paper-strata", "stained-glass-field", "thread-painted-embroidery"],
  },
  {
    slug: "bridges",
    restaurantName: "Bridges",
    city: "New York",
    starCount: 1,
    cuisine: "Contemporary",
    guidePath: "bridges-1216261",
    listingPage: 1,
    cueType: "dish",
    evidenceCue:
      "Cured tuna, mushrooms, and dates express the warm, contemporary bistro's preference for layered savory contrasts.",
    primaryForms: [
      "one broad tuna crescent",
      "two mushroom-cap disks",
      "one date-brown oval",
      "one amber room arch",
    ],
    supportingAccents: ["one pale sauce ribbon"],
    colorFamilies: ["tuna rose", "mushroom taupe", "date brown", "warm amber"],
    candidateStyles: ["matte-gouache-editorial", "ceramic-underglaze", "risograph-overprint"],
  },
  {
    slug: "yamada",
    restaurantName: "Yamada",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese",
    guidePath: "yamada",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A pale earth-toned L-shaped counter faces ikebana and a dry garden visible through the windows.",
    primaryForms: [
      "one L-shaped pale counter",
      "one raked garden field",
      "one branch-like ikebana curve",
      "one square window frame",
    ],
    supportingAccents: ["one river-stone oval"],
    colorFamilies: ["sand", "pale oak", "sage green", "stone gray"],
    candidateStyles: ["wood-marquetry-landscape", "fresco-mineral-pigment", "ceramic-underglaze"],
  },
  {
    slug: "le-coucou",
    restaurantName: "Le Coucou",
    city: "New York",
    starCount: 1,
    cuisine: "French",
    guidePath: "le-coucou",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "An ornate bar and hand-painted murals give the lofty room an eighteenth-century French atmosphere.",
    primaryForms: [
      "one ornate bar arch",
      "one broad mural field",
      "one tall window block",
      "one sweeping chandelier curve",
    ],
    supportingAccents: ["one gilded leaf"],
    colorFamilies: ["parchment", "antique gold", "dusty blue", "walnut brown"],
    candidateStyles: ["fresco-mineral-pigment", "wood-marquetry-landscape", "stained-glass-field"],
  },
  {
    slug: "muku",
    restaurantName: "Muku",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese",
    guidePath: "muku",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "Chef Manabu Asanuma's kaiseki progression moves from sashimi through steamed, charcoal-grilled, and fried courses to Yamagata soba made with his family's hometown buckwheat.",
    additionalEvidenceSourceUrls: ["https://www.restaurantmuku.nyc/menu"],
    primaryForms: [
      "one sashimi disk",
      "one steamed-course oval",
      "one charcoal-grill ribbon",
      "one Yamagata buckwheat leaf",
    ],
    supportingAccents: ["one soba-gold inset"],
    colorFamilies: ["mist blue", "sashimi coral", "charcoal ember", "buckwheat green"],
    candidateStyles: ["ceramic-underglaze", "woven-tapestry-field", "wood-marquetry-landscape"],
  },
  {
    slug: "labeille",
    restaurantName: "L’Abeille",
    city: "New York",
    starCount: 1,
    cuisine: "French, Contemporary",
    guidePath: "l%E2%80%99abeille",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "Velvet seating, intimate booths, and a marble bar frame cooking shaped by French technique and Japanese influence.",
    primaryForms: [
      "one velvet booth crescent",
      "one marble bar block",
      "one folded screen plane",
      "one honeyed light disk",
    ],
    supportingAccents: ["one slender blossom curve"],
    colorFamilies: ["deep plum", "marble cream", "honey gold", "ink blue"],
    candidateStyles: ["thread-painted-embroidery", "stained-glass-field", "wood-marquetry-landscape"],
  },
  {
    slug: "corima",
    restaurantName: "Corima",
    city: "New York",
    starCount: 1,
    cuisine: "Mexican, Contemporary",
    guidePath: "corima",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "Northern Mexican traditions meet a live-fire tasting format, with wheat tortillas and desert ingredients as recurring anchors.",
    primaryForms: [
      "one desert-ingredient oval",
      "one live-fire sun disk",
      "one folded tortilla crescent",
      "one rising smoke ribbon",
    ],
    supportingAccents: ["one agave spear"],
    colorFamilies: ["desert ochre", "charcoal", "wheat cream", "agave green"],
    candidateStyles: ["relief-blockprint", "ceramic-underglaze", "fresco-mineral-pigment"],
  },
  {
    slug: "dirt-candy",
    restaurantName: "Dirt Candy",
    city: "New York",
    starCount: 1,
    cuisine: "Vegetarian, Vegan",
    guidePath: "dirt-candy",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "Seasonal vegetables appear raw, cooked, pickled, and preserved, making changing produce the tasting menu's central subject.",
    primaryForms: [
      "one broad leaf fan",
      "one root-vegetable oval",
      "one pickling-jar arch",
      "one preserved-produce disk",
    ],
    supportingAccents: ["one curling vine"],
    colorFamilies: ["leaf green", "beet purple", "squash gold", "earth brown"],
    candidateStyles: ["thread-painted-embroidery", "cut-paper-strata", "ceramic-underglaze"],
  },
  {
    slug: "cesar",
    restaurantName: "César",
    city: "New York",
    starCount: 2,
    cuisine: "Contemporary",
    guidePath: "cesar",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A simple, clean room gives every table a clear view of the kitchen preparing a seasonal seafood-forward tasting menu.",
    primaryForms: [
      "one open kitchen rectangle",
      "one broad viewing arc",
      "one seafood-blue wave",
      "one high ceiling plane",
    ],
    supportingAccents: ["one pearl-like disk"],
    colorFamilies: ["ocean blue", "warm ivory", "graphite", "pearl gray"],
    candidateStyles: ["prismatic-geometric-symbolism", "cut-paper-strata", "screenprint-night"],
  },
  {
    slug: "torrisi",
    restaurantName: "Torrisi",
    city: "New York",
    starCount: 1,
    cuisine: "Contemporary, Italian-American",
    guidePath: "torrisi",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "New York Italian-American pantry and deli traditions are reworked into polished contemporary dishes in Nolita.",
    primaryForms: [
      "one deli-counter block",
      "one arched pasta ribbon",
      "one city-window grid",
      "one olive-green oval",
    ],
    supportingAccents: ["one golden bread curve"],
    colorFamilies: ["olive green", "tomato coral", "warm cream", "city charcoal"],
    candidateStyles: ["risograph-overprint", "relief-blockprint", "ceramic-underglaze"],
  },
  {
    slug: "estela",
    restaurantName: "Estela",
    city: "New York",
    starCount: 1,
    cuisine: "Contemporary, American",
    guidePath: "estela",
    listingPage: 1,
    cueType: "dish",
    evidenceCue:
      "Ink-dark arroz negro with squid and hazelnut captures the kitchen's layered, high-contrast approach to familiar ingredients.",
    primaryForms: [
      "one ink-dark rice oval",
      "one pale squid arc",
      "one hazelnut disk",
      "one bright sauce crescent",
    ],
    supportingAccents: ["one coastal wave"],
    colorFamilies: ["ink black", "shell ivory", "hazelnut brown", "citrus gold"],
    candidateStyles: ["screenprint-night", "ceramic-underglaze", "matte-gouache-editorial"],
  },
  {
    slug: "torien",
    restaurantName: "Torien",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Yakitori",
    guidePath: "torien",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "A counter-side yakitori sequence uses binchotan charcoal to shape each skewered cut of chicken.",
    primaryForms: [
      "one charcoal hearth block",
      "three broad skewer diagonals",
      "one rising smoke spiral",
      "one amber ember disk",
    ],
    supportingAccents: ["one curtain-like dark band"],
    colorFamilies: ["charcoal", "ember amber", "cypress tan", "smoke gray"],
    candidateStyles: ["relief-blockprint", "screenprint-night", "wood-marquetry-landscape"],
  },
  {
    slug: "yoshino",
    restaurantName: "Yoshino",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "yoshino-1185037",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A hinoki counter cut from a centuries-old tree anchors an omakase known for warm saba maki and precise nigiri.",
    primaryForms: [
      "one ancient-tree counter",
      "one warm mackerel crescent",
      "one cypress grain wave",
      "one precise nigiri disk",
    ],
    supportingAccents: ["one rice-ivory band"],
    colorFamilies: ["hinoki honey", "mackerel blue", "rice ivory", "deep charcoal"],
    candidateStyles: ["wood-marquetry-landscape", "ceramic-underglaze", "thread-painted-embroidery"],
  },
  {
    slug: "sixty-three-clinton",
    restaurantName: "Sixty Three Clinton",
    city: "New York",
    starCount: 1,
    cuisine: "Contemporary",
    guidePath: "63-clinton",
    listingPage: 1,
    cueType: "dish",
    evidenceCue:
      "A playful breakfast taco has become a signature within the understated Lower East Side tasting sequence.",
    primaryForms: [
      "one folded taco crescent",
      "one rising sun disk",
      "one low city-block band",
      "one soft egg oval",
    ],
    supportingAccents: ["one chili-gold curve"],
    colorFamilies: ["corn gold", "sunrise peach", "soft cream", "city charcoal"],
    candidateStyles: ["cut-paper-strata", "risograph-overprint", "ceramic-underglaze"],
  },
  {
    slug: "sushi-nakazawa-new-york",
    restaurantName: "Sushi Nakazawa New York",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "sushi-nakazawa",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A sleek ten-seat counter frames tender fish, seasoned rice, wasabi, and a restrained brush of nikiri.",
    primaryForms: [
      "one sleek counter band",
      "one continuous seat arcade",
      "one tender fish crescent",
      "one brushed sauce wave",
    ],
    supportingAccents: ["one wasabi-green disk"],
    colorFamilies: ["deep charcoal", "rice ivory", "ocean blue", "wasabi green"],
    candidateStyles: ["stained-glass-field", "wood-marquetry-landscape", "screenprint-night"],
  },
  {
    slug: "family-meal-at-blue-hill",
    restaurantName: "Family Meal at Blue Hill",
    city: "New York",
    starCount: 1,
    cuisine: "American",
    guidePath: "blue-hill",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "Family-style courses center seasonal vegetables and grains connected to the restaurant's upstate farm network.",
    primaryForms: [
      "one broad farm field",
      "one shared-table oval",
      "one grain-sheaf arc",
      "one seasonal vegetable fan",
    ],
    supportingAccents: ["one river-blue curve"],
    colorFamilies: ["field green", "grain gold", "earth brown", "river blue"],
    candidateStyles: ["thread-painted-embroidery", "wood-marquetry-landscape", "woven-tapestry-field"],
  },
  {
    slug: "jeju-noodle-bar",
    restaurantName: "Jeju Noodle Bar",
    city: "New York",
    starCount: 1,
    cuisine: "Korean",
    guidePath: "jeju-noodle-bar",
    listingPage: 1,
    cueType: "dish",
    evidenceCue: "Gochu ramyun brings curly noodles and pork broth together in a deeply savory Korean bowl.",
    primaryForms: [
      "one broad broth bowl",
      "one curling noodle spiral",
      "one pork-broth oval",
      "one steam ribbon",
    ],
    supportingAccents: ["one chili-coral crescent"],
    colorFamilies: ["broth amber", "chili coral", "noodle gold", "volcanic charcoal"],
    candidateStyles: ["ceramic-underglaze", "relief-blockprint", "thread-painted-embroidery"],
  },
  {
    slug: "frevo",
    restaurantName: "Frevo",
    city: "New York",
    starCount: 1,
    cuisine: "Contemporary",
    guidePath: "frevo",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A rotating art panel conceals the entrance to an intimate chef counter tucked behind a gallery.",
    primaryForms: [
      "one rotating gallery panel",
      "one hidden doorway arch",
      "one intimate counter curve",
      "one framed color field",
    ],
    supportingAccents: ["one pivot-point disk"],
    colorFamilies: ["gallery ivory", "midnight blue", "burnished brass", "plum"],
    candidateStyles: ["prismatic-geometric-symbolism", "cut-paper-strata", "risograph-overprint"],
  },
] satisfies readonly MichelinRestaurantNycInput[];

export const newYorkCityMichelinRestaurantSeeds01 = inputs.map(defineMichelinRestaurantNycSeed);
