import type { BayAreaMichelinRestaurantInput } from "./michelin-restaurants-bay-area-types";

export const bayAreaMichelinRestaurantInputsPartOne = [
  {
    slug: "kiln",
    restaurantName: "Kiln",
    locationLabel: "149 Fell St., San Francisco, CA, 94102, USA",
    locationAliases: ["San Francisco, California", "SF", "Bay Area"],
    starCount: 2,
    cuisine: "Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/kiln-1210355",
    cueType: "culture",
    evidenceCue:
      "A warmed warehouse frames Nordic-inspired curing, drying, and fermentation alongside precise modern cooking.",
    primaryForms: [
      "one tall warehouse arch",
      "three preservation-vessel ovals",
      "one curling dried ribbon",
      "one warm service block",
    ],
    supportingAccents: ["one honey-colored arc"],
    colorFamilies: ["warm clay", "smoke gray", "honey gold", "cream", "forest green"],
    candidateStyles: ["wood-marquetry-landscape", "relief-blockprint", "ceramic-underglaze"],
  },
  {
    slug: "birdsong",
    restaurantName: "Birdsong",
    locationLabel: "1085 Mission St., San Francisco, CA, 94103, USA",
    locationAliases: ["San Francisco, California", "SF", "Bay Area"],
    starCount: 2,
    cuisine: "Contemporary, American",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/birdsong",
    cueType: "dish",
    evidenceCue:
      "Live fire anchors a high-ceilinged room, while lacquered quail arrives with grilled rolls and crisp pickles.",
    primaryForms: [
      "one high room arch",
      "one glowing hearth oval",
      "one lacquered quail silhouette",
      "two soft bread domes",
    ],
    supportingAccents: ["one pickle-green crescent"],
    colorFamilies: ["ember orange", "deep umber", "bread cream", "pickle green", "charcoal"],
    candidateStyles: ["stained-glass-field", "thread-painted-embroidery", "screenprint-night"],
  },
  {
    slug: "nari",
    restaurantName: "Nari",
    locationLabel: "Hotel Kabuki, 1625 Post St., San Francisco, CA, 94115, USA",
    locationAliases: ["Japantown", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Thai, Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/nari",
    cueType: "dish",
    evidenceCue:
      "A brick-colored bumbai curry pairs crisp eggplant with an airy folded roti in a refined Thai family-style meal.",
    primaryForms: [
      "one broad curry bowl oval",
      "one folded bread fan",
      "one crisp eggplant crescent",
      "one rising aroma ribbon",
    ],
    supportingAccents: ["one peanut-gold disk"],
    colorFamilies: ["brick orange", "eggplant violet", "bread cream", "leaf green", "charcoal"],
    candidateStyles: ["ceramic-underglaze", "cut-paper-strata", "matte-gouache-editorial"],
  },
  {
    slug: "kin-khao",
    restaurantName: "Kin Khao",
    locationLabel: "55 Cyril Magnin St., San Francisco, CA, 94102, USA",
    locationAliases: ["Union Square", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Thai",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/kin-khao",
    cueType: "dish",
    evidenceCue:
      "Mushroom hor mok presents fragrant curry mousse in a jar with coconut cream and crisp rice cakes.",
    otherEvidenceSourceUrls: ["https://www.kinkhao.com/lets-eat"],
    primaryForms: [
      "one tall curry-vessel oval",
      "one coconut-cream wave",
      "two crisp rice disks",
      "one mushroom dome",
    ],
    supportingAccents: ["one aromatic leaf curve"],
    colorFamilies: ["coconut cream", "mushroom brown", "saffron", "leaf green", "ink black"],
    candidateStyles: ["mosaic-tesserae-field", "ceramic-underglaze", "risograph-overprint"],
  },
  {
    slug: "californios",
    restaurantName: "Californios",
    locationLabel: "355 11th St., San Francisco, CA, 94103, USA",
    locationAliases: ["SoMa", "San Francisco, California", "Bay Area"],
    starCount: 3,
    cuisine: "Mexican, Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/californios",
    cueType: "dish",
    evidenceCue:
      "A pillowy sourdough tortilla carries crisp black cod between contrasting huitlacoche and yellow-corn cremas.",
    primaryForms: [
      "one soft tortilla crescent",
      "one crisp fish block",
      "one dark corn wave",
      "one golden corn wave",
    ],
    supportingAccents: ["one agave-blue arc"],
    colorFamilies: ["maize gold", "charcoal", "warm cream", "agave blue", "deep plum"],
    candidateStyles: ["stained-glass-field", "fresco-mineral-pigment", "cut-paper-strata"],
  },
  {
    slug: "state-bird-provisions",
    restaurantName: "State Bird Provisions",
    locationLabel: "1529 Fillmore St., San Francisco, CA, 94115, USA",
    locationAliases: ["Fillmore District", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Californian",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/state-bird-provisions",
    cueType: "culture",
    evidenceCue:
      "Small Californian provisions travel through the lively room on rolling dim-sum-style carts and trays.",
    otherEvidenceSourceUrls: ["https://www.statebirdsf.com/"],
    primaryForms: [
      "one rolling cart block",
      "three broad provision ovals",
      "one long provision-tray band",
      "one sweeping service path",
    ],
    supportingAccents: ["two warm tray disks"],
    colorFamilies: ["warm oak", "sage green", "soft ivory", "mustard gold", "charcoal"],
    candidateStyles: ["risograph-overprint", "thread-painted-embroidery", "relief-blockprint"],
  },
  {
    slug: "the-progress",
    restaurantName: "The Progress",
    locationLabel: "1525 Fillmore St., San Francisco, CA, 94115, USA",
    locationAliases: ["Fillmore District", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Californian",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/the-progress",
    cueType: "interior",
    evidenceCue:
      "Tall windows, leafy plants, and a geometric hanging form connect the dining room, balcony, and concrete mezzanine.",
    otherEvidenceSourceUrls: ["https://theprogress-sf.com/"],
    primaryForms: [
      "three tall window arches",
      "one leafy canopy mass",
      "one raised balcony band",
      "one hanging geometric diamond",
    ],
    supportingAccents: ["one warm pendant disk"],
    colorFamilies: ["window blue", "leaf green", "concrete gray", "warm oak", "cream"],
    candidateStyles: ["wood-marquetry-landscape", "stained-glass-field", "prismatic-geometric-symbolism"],
  },
  {
    slug: "7-adams",
    restaurantName: "7 Adams",
    locationLabel: "1963 Sutter St., San Francisco, CA, 94115, USA",
    locationAliases: ["Lower Pacific Heights", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Californian, Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/7-adams",
    cueType: "interior",
    evidenceCue:
      "A calm railway-shaped room draws the eye along an open kitchen toward warm milk bread and cultured butter.",
    primaryForms: [
      "one long railway-room band",
      "one open kitchen rectangle",
      "one warm bread dome",
      "one butter-gold oval",
    ],
    supportingAccents: ["two narrow light bars"],
    colorFamilies: ["warm oak", "bread cream", "butter gold", "slate blue", "charcoal"],
    candidateStyles: ["cut-paper-strata", "wood-marquetry-landscape", "screenprint-night"],
  },
  {
    slug: "acquerello",
    restaurantName: "Acquerello",
    locationLabel: "1722 Sacramento St., San Francisco, CA, 94109, USA",
    locationAliases: ["Nob Hill", "San Francisco, California", "Bay Area"],
    starCount: 2,
    cuisine: "Italian, Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/acquerello",
    cueType: "interior",
    evidenceCue:
      "A signature A-frame ceiling and warm furnishings culminate in a rolling cart laden with petite sweets.",
    primaryForms: [
      "one steep ceiling chevron",
      "one warm room arch",
      "one rolling service block",
      "three broad confection disks",
    ],
    supportingAccents: ["one cellar-dark curve"],
    colorFamilies: ["walnut brown", "warm cream", "antique gold", "plum", "charcoal"],
    candidateStyles: ["wood-marquetry-landscape", "stained-glass-field", "woven-tapestry-field"],
  },
  {
    slug: "restaurant-naides",
    restaurantName: "Restaurant Naides",
    locationLabel: "708 Bush St., San Francisco, CA, 94108, USA",
    locationAliases: ["Nob Hill", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Filipino",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/naides",
    cueType: "dish",
    evidenceCue:
      "A Filipino steamed rice cake carries pork rillette, thin lardo, and fresh herbs in the tasting sequence.",
    otherEvidenceSourceUrls: [
      "https://www.restaurantnaides.com/",
      "https://www.7x7.com/filipino-fine-dining-restaurant-naides-2675574022.html",
    ],
    primaryForms: [
      "one steamed rice-cake disk",
      "one savory rillette wave",
      "one pale lardo oval",
      "one fresh-herb leaf",
    ],
    supportingAccents: ["one fresh-herb curve"],
    colorFamilies: ["rice ivory", "lardo cream", "warm umber", "herb green", "charcoal"],
    candidateStyles: ["matte-gouache-editorial", "ceramic-underglaze", "mosaic-tesserae-field"],
  },
  {
    slug: "niku-steakhouse",
    restaurantName: "Niku Steakhouse",
    locationLabel: "61 Division St., San Francisco, CA, 94103, USA",
    locationAliases: ["Design District", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Steakhouse",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/niku-steakhouse",
    cueType: "interior",
    evidenceCue:
      "A gleaming entry opens to a wood-lined room and long chef counter glowing over a bed of coals.",
    primaryForms: [
      "one luminous entry rectangle",
      "one long chef-counter arc",
      "one wood-lined wall field",
      "one glowing coal oval",
    ],
    supportingAccents: ["one steel-gray diagonal"],
    colorFamilies: ["burnished gold", "walnut brown", "coal black", "ember orange", "cream"],
    candidateStyles: ["wood-marquetry-landscape", "screenprint-night", "relief-blockprint"],
  },
  {
    slug: "ssal",
    restaurantName: "Ssal",
    locationLabel: "2226 Polk St., San Francisco, CA, 94109, USA",
    locationAliases: ["Russian Hill", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Korean",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/ssal",
    cueType: "culture",
    evidenceCue:
      "A single tasting menu joins Korean aesthetics and sensibilities with French dégustation technique beside an open kitchen.",
    otherEvidenceSourceUrls: ["https://ssalsf.com/"],
    primaryForms: [
      "one open kitchen window",
      "one single-menu oval",
      "one folded tasting path",
      "one degustation arc",
    ],
    supportingAccents: ["one brass horizon"],
    colorFamilies: ["rice ivory", "ink black", "celadon green", "warm brass", "clay brown"],
    candidateStyles: ["ceramic-underglaze", "fresco-mineral-pigment", "woven-tapestry-field"],
  },
  {
    slug: "mister-jius",
    restaurantName: "Mister Jiu’s",
    locationLabel: "28 Waverly Pl., San Francisco, CA, 94108, USA",
    locationAliases: ["Chinatown", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Chinese",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/mister-jiu%E2%80%99s",
    cueType: "culture",
    evidenceCue:
      "A contemporary banquet meal in historic Chinatown centers on whole roasted duck prepared through traditional Chinese technique.",
    otherEvidenceSourceUrls: ["https://www.misterjius.com/menu"],
    primaryForms: [
      "one round banquet-table disk",
      "one broad roast-duck silhouette",
      "one Chinatown window arch",
      "one shared serving arc",
    ],
    supportingAccents: ["one jade-green crescent"],
    colorFamilies: ["roast umber", "jade green", "warm ivory", "night blue", "brass gold"],
    candidateStyles: ["relief-blockprint", "stained-glass-field", "wood-marquetry-landscape"],
  },
  {
    slug: "benu",
    restaurantName: "Benu",
    locationLabel: "22 Hawthorne St., San Francisco, CA, 94105, USA",
    locationAliases: ["SoMa", "San Francisco, California", "Bay Area"],
    starCount: 3,
    cuisine: "Asian",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/benu",
    cueType: "dish",
    evidenceCue:
      "Michelin highlights Benu's whole roasted quail, glazed with maple and soy and served with sweet-potato crepinette and black truffles.",
    otherEvidenceSourceUrls: ["https://www.benusf.com/menu/", "https://www.benusf.com/book"],
    primaryForms: [
      "one whole roasted-quail silhouette",
      "one maple-soy wing leaf",
      "one sweet-potato crepinette oval",
      "three broad black-truffle rosettes",
    ],
    supportingAccents: [],
    colorFamilies: ["maple amber", "soy brown", "sweet-potato plum", "truffle black", "porcelain ivory"],
    candidateStyles: ["monoprint-ink-wash", "ceramic-underglaze", "wood-marquetry-landscape"],
  },
  {
    slug: "nisei",
    restaurantName: "Nisei",
    locationLabel: "2316 Polk St., San Francisco, CA, 94109, USA",
    locationAliases: ["Russian Hill", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Japanese",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/nisei",
    cueType: "dish",
    evidenceCue:
      "Michelin identifies Nisei's omurice topped with Japanese omelet and caviar, alongside nori maki filled with silken tofu, Blue Lake lava beans, and trout roe.",
    otherEvidenceSourceUrls: [
      "https://guide.michelin.com/ca/en/california/san-francisco/restaurant/nisei",
      "https://www.restaurantnisei.com/menu",
    ],
    primaryForms: [
      "one omelet-covered omurice oval",
      "three black-caviar beads",
      "one dark nori-maki ring",
      "one violet lava-bean center",
      "one vermilion trout-roe bead",
    ],
    supportingAccents: [],
    colorFamilies: [
      "omelet gold",
      "nori green-black",
      "tofu ivory",
      "lava-bean violet",
      "trout-roe vermilion",
    ],
    candidateStyles: ["ceramic-underglaze", "thread-painted-embroidery", "relief-blockprint"],
  },
] as const satisfies readonly BayAreaMichelinRestaurantInput[];
