import { MICHELIN_RESTAURANT_RESEARCH_CHECKED_AT } from "./michelin-restaurant-seed";
import type { MichelinRestaurantResearchSeed, RestaurantVisualCueType } from "./michelin-restaurant-seed";

export const WASHINGTON_DC_MICHELIN_CHECKED_AT = MICHELIN_RESTAURANT_RESEARCH_CHECKED_AT;

export const WASHINGTON_DC_MICHELIN_LIST_URL =
  "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred" as const;

export const WASHINGTON_DC_MICHELIN_ART_EXCLUSIONS = [
  "commercial guide branding, rating marks, or star pictograms",
  "restaurant names, signage, logos, menus, words, letters, numerals, or typography",
  "red commercial-guide trade dress",
  "individual plate or dish microdetail",
  "photographic copying of the referenced interior or food",
] as const;

export const washingtonDcMichelinRestaurantSet = {
  schemaVersion: 1,
  setId: "michelin-restaurants-washington-dc",
  title: "MICHELIN-starred restaurants — Washington, DC & surroundings",
  declaredCount: 22,
  checkedAt: WASHINGTON_DC_MICHELIN_CHECKED_AT,
  sourceUrl: WASHINGTON_DC_MICHELIN_LIST_URL,
  distinctionCounts: { two: 3, one: 19 },
} as const;

interface DcRestaurantInput {
  readonly slug: string;
  readonly restaurantName: string;
  readonly locationLabel: string;
  readonly locationAliases?: readonly [string, string, ...string[]];
  readonly starCount: 1 | 2;
  readonly cuisine: string;
  readonly guidePath: string;
  readonly cueType: RestaurantVisualCueType;
  readonly evidenceCue: string;
  readonly primaryForms: readonly [string, string, string, ...string[]];
  readonly supportingAccents: readonly string[];
  readonly colorFamilies: readonly [string, string, string, ...string[]];
  readonly candidateStyles: readonly [string, string, string];
}

const restaurantInputs: readonly DcRestaurantInput[] = [
  {
    slug: "the-inn-at-little-washington",
    restaurantName: "The Inn at Little Washington",
    locationLabel: "309 Middle St., Washington, VA, 22747, USA",
    locationAliases: ["Washington, Virginia", "Rappahannock County", "Washington, DC & surroundings"],
    starCount: 2,
    cuisine: "French, Classic French",
    guidePath: "the-inn-at-little-washington",
    cueType: "interior",
    evidenceCue: "Stately maximalist décor surrounds roaming bread and cheese carts.",
    primaryForms: [
      "one stately decor arch",
      "one maximalist decor wedge",
      "one roaming cheese-wheel oval",
      "one tall service-cart block",
    ],
    supportingAccents: ["one gilded curve"],
    colorFamilies: ["deep plum", "garden green", "warm cream", "antique gold", "charcoal"],
    candidateStyles: ["stained-glass-field", "thread-painted-embroidery", "wood-marquetry-landscape"],
  },
  {
    slug: "jont",
    restaurantName: "Jônt",
    locationLabel: "1904 14th St. NW, Washington, DC, 20009, USA",
    starCount: 2,
    cuisine: "Contemporary",
    guidePath: "jont",
    cueType: "interior",
    evidenceCue: "Chefs and servers move in rhythm around a compact kitchen counter.",
    primaryForms: [
      "one sweeping chef-counter arc",
      "one central kitchen block",
      "two interlocking motion ribbons",
      "one compact counter rectangle",
    ],
    supportingAccents: ["one bold sauce wave"],
    colorFamilies: ["ink black", "warm ivory", "copper", "sea blue", "plum"],
    candidateStyles: ["relief-blockprint", "ceramic-underglaze", "cut-paper-strata"],
  },
  {
    slug: "minibar-by-jose-andres",
    restaurantName: "minibar by José Andrés",
    locationLabel: "855 E St. NW, Washington, DC, 20004, USA",
    starCount: 2,
    cuisine: "Creative",
    guidePath: "minibar",
    cueType: "interior",
    evidenceCue: "An all-white room leads to a twelve-seat wood kitchen counter.",
    primaryForms: [
      "one white anteroom block",
      "one warm wood counter arc",
      "one twelve-seat counter block",
      "one room-to-counter passage",
    ],
    supportingAccents: ["one surprise spiral"],
    colorFamilies: ["pure ivory", "walnut brown", "graphite", "electric blue", "warm gold"],
    candidateStyles: ["prismatic-geometric-symbolism", "stained-glass-field", "risograph-overprint"],
  },
  {
    slug: "xiquet",
    restaurantName: "Xiquet",
    locationLabel: "2404 Wisconsin Ave. NW, Washington, DC, 20007, USA",
    starCount: 1,
    cuisine: "Spanish",
    guidePath: "xiquet",
    cueType: "dish",
    evidenceCue: "Valencian rice with rabbit and mushrooms cooks over a wood-fired hearth.",
    primaryForms: [
      "one broad hearth arch",
      "one rising smoke ribbon",
      "one saffron rice oval",
      "one wood-fire horizon band",
    ],
    supportingAccents: ["one mushroom-cap disk"],
    colorFamilies: ["saffron", "smoke gray", "sea blue", "warm cream", "charcoal"],
    candidateStyles: ["ceramic-underglaze", "wood-marquetry-landscape", "screenprint-night"],
  },
  {
    slug: "rooster-and-owl",
    restaurantName: "Rooster & Owl",
    locationLabel: "2436 14th St. NW, Washington, DC, 20009, USA",
    starCount: 1,
    cuisine: "Contemporary, Fusion",
    guidePath: "rooster-owl",
    cueType: "dish",
    evidenceCue: "Pistachio olive-oil cake combines blackberry and goat-cheese mousse.",
    primaryForms: [
      "one low cake block",
      "one blackberry-purple disk",
      "one pistachio-green wave",
      "one soft cream arc",
    ],
    supportingAccents: ["one dark berry crescent"],
    colorFamilies: ["pistachio green", "blackberry purple", "cream", "olive gold", "charcoal"],
    candidateStyles: ["matte-gouache-editorial", "cut-paper-strata", "mosaic-tesserae-field"],
  },
  {
    slug: "masseria",
    restaurantName: "Masseria",
    locationLabel: "1340 4th St. NE, Washington, DC, 20002, USA",
    starCount: 1,
    cuisine: "Italian, Regional Cuisine",
    guidePath: "masseria",
    cueType: "interior",
    evidenceCue: "A brick warehouse room joins a steel kitchen, glass cellar, and terrace.",
    primaryForms: [
      "one broad brick wall block",
      "one steel kitchen rectangle",
      "one glass cellar arch",
      "one open terrace plane",
    ],
    supportingAccents: ["one vine curve"],
    colorFamilies: ["clay brown", "steel gray", "glass blue", "olive green", "warm ivory"],
    candidateStyles: ["wood-marquetry-landscape", "stained-glass-field", "ceramic-underglaze"],
  },
  {
    slug: "omakase-at-barracks-row",
    restaurantName: "Omakase at Barracks Row",
    locationLabel: "522 8th St. SE, Washington, DC, 20003, USA",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "omakase-at-barracks-row",
    cueType: "culture",
    evidenceCue: "Stairway art recalls printing inked fish onto rice paper in gyotaku.",
    primaryForms: [
      "one ascending stair band",
      "one bold fish silhouette",
      "one rice-paper rectangle",
      "one ink-wash disk",
    ],
    supportingAccents: ["one brushed current curve"],
    colorFamilies: ["sumi black", "paper ivory", "steel gray", "ocean blue", "warm tan"],
    candidateStyles: ["monoprint-ink-wash", "relief-blockprint", "thread-painted-embroidery"],
  },
  {
    slug: "the-dabney",
    restaurantName: "The Dabney",
    locationLabel: "122 Blagden Alley NW, Washington, DC, 20001, USA",
    starCount: 1,
    cuisine: "American, Contemporary",
    guidePath: "the-dabney",
    cueType: "interior",
    evidenceCue: "Exposed brick, dark wood, and an open kitchen frame a wood-fired hearth.",
    primaryForms: [
      "one glowing hearth arch",
      "one dark wood beam",
      "one brick wall field",
      "one open-kitchen window",
    ],
    supportingAccents: ["one coal-black crescent"],
    colorFamilies: ["brick brown", "charcoal", "warm amber", "herb green", "cream"],
    candidateStyles: ["relief-blockprint", "woven-tapestry-field", "ceramic-underglaze"],
  },
  {
    slug: "elcielo-washington-dc",
    restaurantName: "Elcielo Washington DC",
    locationLabel: "1280 4th St. NE, Washington, DC, 20002, USA",
    starCount: 1,
    cuisine: "Colombian, Contemporary",
    guidePath: "elcielo-d-c",
    cueType: "dish",
    evidenceCue: "A Colombian tasting moves from corn broth to a chocolate finale in two rooms.",
    primaryForms: [
      "one golden corn crescent",
      "one cocoa-colored wave",
      "two paired room arches",
      "one corn-broth horizon band",
    ],
    supportingAccents: ["one rising aroma curve"],
    colorFamilies: ["maize gold", "cocoa brown", "Andean blue", "warm ivory", "leaf green"],
    candidateStyles: ["stained-glass-field", "cut-paper-strata", "fresco-mineral-pigment"],
  },
  {
    slug: "oyster-oyster",
    restaurantName: "Oyster Oyster",
    locationLabel: "1440 8th St. NW, Washington, DC, 20001, USA",
    starCount: 1,
    cuisine: "Vegetarian, Contemporary",
    guidePath: "oyster-oyster",
    cueType: "culture",
    evidenceCue: "The vegetable kitchen centers regenerative farms, reuse, and seasonality.",
    primaryForms: [
      "one broad leaf oval",
      "one seasonal produce dome",
      "one regenerative-farm disk",
      "one circular reuse band",
    ],
    supportingAccents: ["one seed-paper fleck"],
    colorFamilies: ["leaf green", "soil brown", "sunflower gold", "mushroom cream", "night blue"],
    candidateStyles: ["thread-painted-embroidery", "matte-gouache-editorial", "ceramic-underglaze"],
  },
  {
    slug: "pineapple-and-pearls",
    restaurantName: "Pineapple and Pearls",
    locationLabel: "715 8th St. SE, Washington, DC, 20003, USA",
    starCount: 1,
    cuisine: "Contemporary",
    guidePath: "pineapple-and-pearls",
    cueType: "interior",
    evidenceCue: "Balloons, velvet jackets, pop music, and tableside theater evoke a lavish party.",
    primaryForms: [
      "one large balloon disk",
      "one velvet lapel chevron",
      "one tableside-theater circle",
      "one sweeping party ribbon",
    ],
    supportingAccents: ["two confetti blocks"],
    colorFamilies: ["midnight blue", "velvet plum", "champagne gold", "warm ivory", "teal"],
    candidateStyles: ["prismatic-geometric-symbolism", "risograph-overprint", "stained-glass-field"],
  },
  {
    slug: "causa",
    restaurantName: "Causa",
    locationLabel: "920 Blagden Alley NW, Washington, DC, 20001, USA",
    starCount: 1,
    cuisine: "Peruvian, Latin American",
    guidePath: "causa",
    cueType: "culture",
    evidenceCue: "The Nikkei tasting travels from Lima’s coast through the Andes and Amazon.",
    primaryForms: [
      "one Lima-coast water band",
      "one high Andes triangle",
      "one broad rainforest leaf",
      "one Amazon basin oval",
    ],
    supportingAccents: ["one journey curve"],
    colorFamilies: ["Pacific blue", "mountain violet", "rainforest green", "sun gold", "potato cream"],
    candidateStyles: ["cut-paper-strata", "fresco-mineral-pigment", "woven-tapestry-field"],
  },
  {
    slug: "imperfecto-the-chefs-table",
    restaurantName: "Imperfecto: The Chef's Table",
    locationLabel: "1124 23rd St. NW, Washington, DC, 20037, USA",
    starCount: 1,
    cuisine: "Latin American",
    guidePath: "imperfecto-the-chef-s-table",
    cueType: "interior",
    evidenceCue: "Glass, marble, brass, and terra-cotta frame a counter below the chef’s perch.",
    primaryForms: [
      "one tall glass tower block",
      "one white marble plane",
      "one brass counter crescent",
      "one terra-cotta base",
    ],
    supportingAccents: ["one upward light beam"],
    colorFamilies: ["glass blue", "marble ivory", "brass gold", "terra cotta", "charcoal"],
    candidateStyles: ["prismatic-geometric-symbolism", "ceramic-underglaze", "screenprint-night"],
  },
  {
    slug: "sushi-nakazawa-washington-dc",
    restaurantName: "Sushi Nakazawa Washington DC",
    locationLabel: "Waldorf Astoria, 1100 Pennsylvania Ave. NW, Washington, DC, 20004, USA",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "sushi-nakazawa1160153",
    cueType: "interior",
    evidenceCue: "Dark wood and gold surround a marble counter and precise itamae work.",
    primaryForms: [
      "one dark wood wall field",
      "one pale marble counter arc",
      "one warm gold light block",
      "one precise itamae-work ribbon",
    ],
    supportingAccents: ["one precise silver diagonal"],
    colorFamilies: ["walnut brown", "marble ivory", "warm gold", "ink black", "silver gray"],
    candidateStyles: ["wood-marquetry-landscape", "stained-glass-field", "relief-blockprint"],
  },
  {
    slug: "albi",
    restaurantName: "Albi",
    locationLabel: "1346 4th St. SE, Washington, DC, 20003, USA",
    starCount: 1,
    cuisine: "Middle Eastern",
    guidePath: "albi",
    cueType: "culture",
    evidenceCue: "Palestinian childhood flavors are reimagined through open-fire cooking.",
    primaryForms: [
      "one open hearth arch",
      "one reimagined-flavor dome",
      "one childhood-memory curve",
      "one ember-glow disk",
    ],
    supportingAccents: ["one smoke ribbon"],
    colorFamilies: ["ember orange", "pita cream", "date brown", "olive green", "night blue"],
    candidateStyles: ["ceramic-underglaze", "woven-tapestry-field", "relief-blockprint"],
  },
  {
    slug: "mita",
    restaurantName: "MITA",
    locationLabel: "804 V St. NW, Washington, DC, 20001, USA",
    starCount: 1,
    cuisine: "Vegetarian, Latin American",
    guidePath: "mita",
    cueType: "dish",
    evidenceCue: "Arepas pair guasacaca, cashew cream, chili oil, and chontaduro butter.",
    primaryForms: [
      "one round arepa disk",
      "one chontaduro-butter oval",
      "one cashew-cream wave",
      "one guasacaca arc",
    ],
    supportingAccents: ["one chili-orange crescent"],
    colorFamilies: ["maize gold", "tropical green", "cashew cream", "chili orange", "earth brown"],
    candidateStyles: ["mosaic-tesserae-field", "matte-gouache-editorial", "cut-paper-strata"],
  },
  {
    slug: "roses-luxury",
    restaurantName: "Rose’s Luxury",
    locationLabel: "717 8th St. SE, Washington, DC, 20003, USA",
    starCount: 1,
    cuisine: "Contemporary",
    guidePath: "rose-s-luxury",
    cueType: "interior",
    evidenceCue: "Globe lights, eclectic décor, and an open kitchen suggest a playful party.",
    primaryForms: [
      "one globe pendant disk",
      "one open kitchen rectangle",
      "one eclectic-decor oval",
      "one playful-party curve",
    ],
    supportingAccents: ["two lively light blocks"],
    colorFamilies: ["warm amber", "deep teal", "soft cream", "plum", "charcoal"],
    candidateStyles: ["risograph-overprint", "cut-paper-strata", "stained-glass-field"],
  },
  {
    slug: "little-pearl",
    restaurantName: "Little Pearl",
    locationLabel: "921 Pennsylvania Ave. SE, Washington, DC, 20003, USA",
    starCount: 1,
    cuisine: "Contemporary",
    guidePath: "little-pearl",
    cueType: "interior",
    evidenceCue: "A carriage-house shell opens into a glassy sunroom facing greenery.",
    primaryForms: [
      "one carriage-house arch",
      "one tall sunroom block",
      "one broad green canopy",
      "one glassy light disk",
    ],
    supportingAccents: ["one garden-path curve"],
    colorFamilies: ["leaf green", "glass blue", "warm ivory", "brick brown", "sun gold"],
    candidateStyles: ["stained-glass-field", "thread-painted-embroidery", "matte-gouache-editorial"],
  },
  {
    slug: "fiola",
    restaurantName: "Fiola",
    locationLabel: "601 Pennsylvania Ave. NW, Washington, DC, 20004, USA",
    starCount: 1,
    cuisine: "Italian, Contemporary",
    guidePath: "fiola",
    cueType: "interior",
    evidenceCue: "Stone walls, seasonal décor, and pop-art prints mix lodge warmth and retro glamour.",
    primaryForms: [
      "one rugged stone wall",
      "two bold pop-art blocks",
      "one seasonal branch curve",
      "one retro-glamour band",
    ],
    supportingAccents: ["one cream doorway"],
    colorFamilies: ["stone gray", "forest green", "electric gold", "deep plum", "cream"],
    candidateStyles: ["fresco-mineral-pigment", "prismatic-geometric-symbolism", "wood-marquetry-landscape"],
  },
  {
    slug: "bresca",
    restaurantName: "Bresca",
    locationLabel: "1906 14th St. NW, Washington, DC, 20009, USA",
    starCount: 1,
    cuisine: "Contemporary, American",
    guidePath: "bresca",
    cueType: "interior",
    evidenceCue: "A moss wall, gold flashes, and sculptural forms create a surreal room.",
    primaryForms: [
      "one moss wall rectangle",
      "one broad gold crescent",
      "one sculptural arch",
      "one surreal-room field",
    ],
    supportingAccents: ["one floating cream disk"],
    colorFamilies: ["moss green", "warm gold", "deep teal", "cream", "charcoal"],
    candidateStyles: ["mosaic-tesserae-field", "stained-glass-field", "ceramic-underglaze"],
  },
  {
    slug: "gravitas",
    restaurantName: "Gravitas",
    locationLabel: "1401 Okie St. NE, Washington, DC, 20002, USA",
    starCount: 1,
    cuisine: "Contemporary, American",
    guidePath: "gravitas",
    cueType: "interior",
    evidenceCue: "Exposed brick and industrial walls soften with greenery and an open kitchen.",
    primaryForms: [
      "one exposed brick rectangle",
      "one open kitchen window block",
      "one industrial wall plane",
      "one broad greenery mass",
    ],
    supportingAccents: ["one steel-gray curve"],
    colorFamilies: ["brick brown", "ivory", "leaf green", "steel gray", "charcoal"],
    candidateStyles: ["relief-blockprint", "wood-marquetry-landscape", "woven-tapestry-field"],
  },
  {
    slug: "rania",
    restaurantName: "Rania",
    locationLabel: "427 11th St. NW, Washington, DC, 20004, USA",
    starCount: 1,
    cuisine: "Indian, Contemporary",
    guidePath: "rania",
    cueType: "dish",
    evidenceCue: "Pork vindaloo arrives with crisp belly, dal, Kashmiri pulao, and buttered naan.",
    primaryForms: [
      "one crisp pork-belly arch",
      "one spice-colored wave",
      "one warm bread crescent",
      "one dark pulao block",
    ],
    supportingAccents: ["one butter-gold curve"],
    colorFamilies: ["saffron", "deep violet", "warm cream", "leaf green", "charcoal"],
    candidateStyles: ["stained-glass-field", "ceramic-underglaze", "thread-painted-embroidery"],
  },
];

export const washingtonDcMichelinRestaurantSeeds: readonly MichelinRestaurantResearchSeed[] =
  restaurantInputs.map(buildRestaurantSeed);

export const washingtonDcMichelinRestaurantRecords = washingtonDcMichelinRestaurantSeeds;

function buildRestaurantSeed(input: DcRestaurantInput): MichelinRestaurantResearchSeed {
  const guideUrl =
    `https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/${input.guidePath}` as const;
  return {
    slug: input.slug,
    restaurantName: input.restaurantName,
    locationLabel: input.locationLabel,
    locationAliases: input.locationAliases ?? ["Washington, DC", "District of Columbia"],
    regionId: "washington-dc",
    regionLabel: "Washington, DC & surroundings",
    starCount: input.starCount,
    cuisine: input.cuisine,
    guideUrl,
    checkedAt: WASHINGTON_DC_MICHELIN_CHECKED_AT,
    cueType: input.cueType,
    evidenceCue: input.evidenceCue,
    evidenceSourceUrls: [guideUrl],
    primaryForms: input.primaryForms,
    supportingAccents: input.supportingAccents,
    colorFamilies: input.colorFamilies,
    candidateStyles: input.candidateStyles,
    accessibleDescription: `An original ${input.cueType}-led miniature badge study for ${input.restaurantName}, composed from ${input.primaryForms.length} broad forms: ${input.primaryForms.join(", ")}.`,
  };
}
