import {
  BAY_AREA_MICHELIN_CALIFORNIA_LIST_PAGE_2_URL,
  BAY_AREA_MICHELIN_CALIFORNIA_LIST_URL,
  BAY_AREA_NINE_COUNTY_BOUNDARY_SOURCE_URL,
} from "./michelin-restaurants-bay-area-types";
import type { BayAreaMichelinRestaurantInput } from "./michelin-restaurants-bay-area-types";

const PAGE_ONE_SOURCES = [
  BAY_AREA_MICHELIN_CALIFORNIA_LIST_URL,
  BAY_AREA_NINE_COUNTY_BOUNDARY_SOURCE_URL,
] as const;

const PAGE_TWO_SOURCES = [
  BAY_AREA_MICHELIN_CALIFORNIA_LIST_PAGE_2_URL,
  BAY_AREA_NINE_COUNTY_BOUNDARY_SOURCE_URL,
] as const;

export const bayAreaMichelinRestaurantInputsPartThree = [
  {
    slug: "singlethread",
    restaurantName: "SingleThread",
    locationLabel: "131 North St., Healdsburg, CA, 95448, USA",
    locationAliases: ["Healdsburg, California", "Sonoma County", "Bay Area"],
    starCount: 3,
    cuisine: "Contemporary, Californian",
    guideUrl: "https://guide.michelin.com/us/en/california/healdsburg/restaurant/singlethread",
    cueType: "culture",
    evidenceCue:
      "A botanical opening arrangement links precise first bites to a nearby 24-acre farm, followed by donabe-cooked seafood and vegetables shaped by Japanese kaiseki.",
    otherEvidenceSourceUrls: [
      ...PAGE_ONE_SOURCES,
      "https://guide.michelin.com/en/california/healdsburg/restaurant/singlethread",
    ],
    primaryForms: [
      "one botanical first-bite canopy",
      "one farm-field band",
      "one donabe bowl arc",
      "one seafood-and-vegetable ribbon",
    ],
    supportingAccents: ["one precise knife-line curve"],
    colorFamilies: ["leaf green", "farm umber", "donabe clay", "sea blue", "warm cream"],
    candidateStyles: ["thread-painted-embroidery", "ceramic-underglaze", "woven-tapestry-field"],
  },
  {
    slug: "auberge-du-soleil",
    restaurantName: "Auberge du Soleil",
    locationLabel: "180 Rutherford Hill Rd., Rutherford, CA, 94573, USA",
    locationAliases: ["Rutherford, California", "Napa County", "Bay Area"],
    starCount: 1,
    cuisine: "Californian",
    guideUrl: "https://guide.michelin.com/us/en/california/rutherford/restaurant/auberge-du-soleil",
    cueType: "interior",
    evidenceCue:
      "A terrace-like perch overlooks vineyard and mountain bands while a local-grower wine program accompanies scallops in green garlic and dark squid-ink pasta.",
    otherEvidenceSourceUrls: [
      ...PAGE_ONE_SOURCES,
      "https://guide.michelin.com/en/california/rutherford/restaurant/auberge-du-soleil",
      "https://guide.michelin.com/ca/en/california/rutherford/restaurant/auberge-du-soleil",
    ],
    primaryForms: [
      "one vineyard terrace",
      "one mountain horizon",
      "one scallop disk",
      "one squid-ink pasta ribbon",
    ],
    supportingAccents: ["one green-garlic curve"],
    colorFamilies: ["vineyard green", "mountain blue", "scallop cream", "ink charcoal", "wine plum"],
    candidateStyles: ["wood-marquetry-landscape", "stained-glass-field", "cut-paper-strata"],
  },
  {
    slug: "auro",
    restaurantName: "Auro",
    locationLabel:
      "Four Seasons Resort and Residences Napa Valley, 400 Silverado Trl., Calistoga, CA, 94515, USA",
    locationAliases: ["Calistoga, California", "Napa County", "Bay Area"],
    starCount: 1,
    cuisine: "Contemporary, French",
    guideUrl: "https://guide.michelin.com/us/en/california/calistoga/restaurant/auro",
    cueType: "interior",
    evidenceCue:
      "A glass-encased kitchen flanks the dining room while on-site garden produce meets Mexican accents in mole, bright aguachile, and a blue-and-yellow corn tetela.",
    otherEvidenceSourceUrls: [
      ...PAGE_ONE_SOURCES,
      "https://guide.michelin.com/en/california/calistoga/restaurant/auro",
    ],
    primaryForms: [
      "one glass-kitchen frame",
      "one garden-leaf mass",
      "one mole-dark oval",
      "one blue-and-yellow corn fan",
    ],
    supportingAccents: ["one bright aguachile arc"],
    colorFamilies: ["glass blue", "garden green", "mole umber", "corn gold", "warm cream"],
    candidateStyles: ["stained-glass-field", "prismatic-geometric-symbolism", "ceramic-underglaze"],
  },
  {
    slug: "enclos",
    restaurantName: "Enclos",
    locationLabel: "139 E. Napa St., Sonoma, CA, 95476, USA",
    locationAliases: ["Sonoma, California", "Sonoma County", "Bay Area"],
    starCount: 3,
    cuisine: "Contemporary, Californian",
    guideUrl: "https://guide.michelin.com/us/en/california/sonoma/restaurant/enclos",
    cueType: "culture",
    evidenceCue:
      "A cozy Victorian shell frames Stone Edge Farm produce and New England memory through clam-chowder chawanmushi and hearth-roasted quail with rose and burnt citrus.",
    otherEvidenceSourceUrls: [
      ...PAGE_ONE_SOURCES,
      "https://guide.michelin.com/en/california/sonoma/restaurant/enclos",
    ],
    primaryForms: [
      "one Victorian-house arch",
      "one farm-field band",
      "one chowder-bowl oval",
      "one hearth-quail silhouette",
    ],
    supportingAccents: ["one burnt-citrus disk"],
    colorFamilies: ["Victorian cream", "field green", "hearth amber", "rose pink", "charcoal"],
    candidateStyles: ["fresco-mineral-pigment", "thread-painted-embroidery", "relief-blockprint"],
  },
  {
    slug: "the-french-laundry",
    restaurantName: "The French Laundry",
    locationLabel: "6640 Washington St., Yountville, CA, 94599, USA",
    locationAliases: ["Yountville, California", "Napa County", "Bay Area"],
    starCount: 3,
    cuisine: "Contemporary, French",
    guideUrl: "https://guide.michelin.com/us/en/california/yountville/restaurant/the-french-laundry",
    cueType: "interior",
    evidenceCue:
      "Flowing ceiling lines crown a precisely planned cooking space, while a crisp cornet of crème fraîche and salmon tartare introduces produce from the garden across the street.",
    otherEvidenceSourceUrls: [
      ...PAGE_ONE_SOURCES,
      "https://guide.michelin.com/en/california/yountville/restaurant/the-french-laundry",
    ],
    primaryForms: [
      "two flowing ceiling ribbons",
      "one crisp cornet cone",
      "one salmon-tartare disk",
      "one garden-field band",
    ],
    supportingAccents: ["one cream-filled arc"],
    colorFamilies: ["ceiling ivory", "garden green", "salmon coral", "cornet gold", "charcoal"],
    candidateStyles: ["stained-glass-field", "luminous-ligne-claire", "wood-marquetry-landscape"],
  },
  {
    slug: "the-village-pub",
    restaurantName: "The Village Pub",
    locationLabel: "2967 Woodside Rd., Woodside, CA, 94062, USA",
    locationAliases: ["Woodside, California", "San Mateo County", "Bay Area"],
    starCount: 1,
    cuisine: "Contemporary, American Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/woodside/restaurant/the-village-pub",
    cueType: "dish",
    evidenceCue:
      "A polished pub room pairs a single round raviolo with molten yolk and potato against a row of warm, fluffy Parker House rolls.",
    otherEvidenceSourceUrls: [
      ...PAGE_ONE_SOURCES,
      "https://guide.michelin.com/en/california/woodside/restaurant/the-village-pub",
    ],
    primaryForms: [
      "one polished pub arch",
      "one raviolo disk",
      "one molten-yolk disk",
      "three Parker House roll domes",
    ],
    supportingAccents: ["one potato-cream curve"],
    colorFamilies: ["pub walnut", "pasta gold", "yolk amber", "roll cream", "charcoal"],
    candidateStyles: ["wood-marquetry-landscape", "ceramic-underglaze", "matte-gouache-editorial"],
  },
  {
    slug: "cyrus",
    restaurantName: "Cyrus",
    locationLabel: "275 CA-128, Geyserville, CA, 95441, USA",
    locationAliases: ["Geyserville, California", "Sonoma County", "Bay Area"],
    starCount: 1,
    cuisine: "Californian, Modern Cuisine",
    guideUrl: "https://guide.michelin.com/us/en/california/geyserville/restaurant/cyrus",
    cueType: "interior",
    evidenceCue:
      "Concrete and glass sit against rolling vineyard bands and an old plum tree, while dinner moves from lounge to kitchen, dining room, and chocolate room.",
    otherEvidenceSourceUrls: [
      ...PAGE_ONE_SOURCES,
      "https://guide.michelin.com/en/california/geyserville/restaurant/cyrus",
      "https://guide.michelin.com/gb/en/california/geyserville/restaurant/cyrus",
    ],
    primaryForms: [
      "one concrete-and-glass block",
      "one vineyard horizon",
      "one old plum-tree canopy",
      "one four-room progression ribbon",
    ],
    supportingAccents: ["one chocolate-brown disk"],
    colorFamilies: ["concrete gray", "glass blue", "vineyard green", "plum purple", "chocolate brown"],
    candidateStyles: ["cut-paper-strata", "wood-marquetry-landscape", "stained-glass-field"],
  },
  {
    slug: "protege",
    restaurantName: "Protégé",
    locationLabel: "250 California Ave., Palo Alto, CA, 94306, USA",
    locationAliases: ["Palo Alto, California", "Santa Clara County", "Bay Area"],
    starCount: 1,
    cuisine: "Contemporary, Californian",
    guideUrl: "https://guide.michelin.com/us/en/california/palo-alto/restaurant/protege",
    cueType: "dish",
    evidenceCue:
      "A sleek modern room presents a nine-layer morel lasagna with Madeira before a rolling dessert trolley of tarts and cookies.",
    otherEvidenceSourceUrls: [
      ...PAGE_TWO_SOURCES,
      "https://guide.michelin.com/en/california/palo-alto/restaurant/protege",
    ],
    primaryForms: [
      "one sleek dining-room frame",
      "one nine-layer lasagna block",
      "one Madeira ribbon",
      "one dessert-trolley arc",
    ],
    supportingAccents: ["two tart disks"],
    colorFamilies: ["room charcoal", "morel brown", "pasta gold", "Madeira plum", "pastry cream"],
    candidateStyles: ["cut-paper-strata", "relief-blockprint", "matte-gouache-editorial"],
  },
  {
    slug: "selbys",
    restaurantName: "Selby's",
    locationLabel: "3001 El Camino Real, Atherton, CA, 94061, USA",
    locationAliases: ["Atherton, California", "San Mateo County", "Bay Area"],
    starCount: 1,
    cuisine: "American, Classic Cuisine",
    guideUrl: "https://guide.michelin.com/us/en/california/atherton/restaurant/selby-s",
    cueType: "culture",
    evidenceCue:
      "Old-Hollywood glamour frames a tall Gruyère popover and a butter-poached lobster composition with golden gnocchi and black trumpet mushrooms.",
    otherEvidenceSourceUrls: [
      ...PAGE_TWO_SOURCES,
      "https://guide.michelin.com/en/california/atherton/restaurant/selby-s",
    ],
    primaryForms: [
      "one Hollywood-glamour arch",
      "one Gruyere popover dome",
      "one lobster crescent",
      "three golden gnocchi disks",
    ],
    supportingAccents: ["one dark mushroom curve"],
    colorFamilies: ["glamour cream", "popover gold", "lobster coral", "mushroom black", "velvet plum"],
    candidateStyles: ["matte-gouache-editorial", "stained-glass-field", "screenprint-night"],
  },
  {
    slug: "troubadour",
    restaurantName: "Troubadour",
    locationLabel: "381 Healdsburg Ave., Healdsburg, CA, 95448, USA",
    locationAliases: ["Healdsburg, California", "Sonoma County", "Bay Area"],
    starCount: 1,
    cuisine: "French, Californian",
    guideUrl: "https://guide.michelin.com/us/en/california/healdsburg/restaurant/troubadour",
    cueType: "culture",
    evidenceCue:
      "A small daytime bakery transforms at night, pairing a prominent bread course with gently cooked rockfish, saffron-yuzu emulsion, and a clam croquette.",
    otherEvidenceSourceUrls: [
      ...PAGE_TWO_SOURCES,
      "https://guide.michelin.com/en/california/healdsburg/restaurant/troubadour",
    ],
    primaryForms: [
      "one bakery-to-evening split field",
      "one bread-course dome",
      "one rockfish oval",
      "one saffron-yuzu ribbon",
    ],
    supportingAccents: ["one clam-croquette disk"],
    colorFamilies: ["bakery cream", "night blue", "bread gold", "rockfish silver", "saffron amber"],
    candidateStyles: ["woven-tapestry-field", "ceramic-underglaze", "screenprint-night"],
  },
  {
    slug: "plumed-horse",
    restaurantName: "Plumed Horse",
    locationLabel: "14555 Big Basin Way, Saratoga, CA, 95070, USA",
    locationAliases: ["Saratoga, California", "Santa Clara County", "Bay Area"],
    starCount: 1,
    cuisine: "Contemporary, American Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/saratoga/restaurant/plumed-horse",
    cueType: "interior",
    evidenceCue:
      "An elegant room opens toward a glass wine cellar while a tall black-pepper and Parmesan soufflé rises above uni and Dungeness crab sauce.",
    otherEvidenceSourceUrls: [
      ...PAGE_TWO_SOURCES,
      "https://guide.michelin.com/en/california/saratoga/restaurant/plumed-horse",
    ],
    primaryForms: [
      "one elegant dining-room arch",
      "one glass-wine-cellar block",
      "one tall souffle dome",
      "one crab-and-uni sauce wave",
    ],
    supportingAccents: ["one pepper-dark curve"],
    colorFamilies: ["room ivory", "glass blue", "wine burgundy", "souffle gold", "crab coral"],
    candidateStyles: ["stained-glass-field", "wood-marquetry-landscape", "thread-painted-embroidery"],
  },
  {
    slug: "press",
    restaurantName: "Press",
    locationLabel: "587 St. Helena St., Saint Helena, CA, 94574, USA",
    locationAliases: ["Saint Helena, California", "Napa County", "Bay Area"],
    starCount: 1,
    cuisine: "Modern Cuisine",
    guideUrl: "https://guide.michelin.com/us/en/california/saint-helena/restaurant/press",
    cueType: "interior",
    evidenceCue:
      "A soaring warm-wood dining room centers a fireplace, with charcoal-grilled lobster and round ricotta gnudi receiving a tableside consommé pour.",
    otherEvidenceSourceUrls: [
      ...PAGE_TWO_SOURCES,
      "https://guide.michelin.com/en/california/saint-helena/restaurant/press",
    ],
    primaryForms: [
      "one soaring warm-wood arch",
      "one central fireplace oval",
      "one charcoal-lobster crescent",
      "one tableside consomme arc",
    ],
    supportingAccents: ["two ricotta-gnudi disks"],
    colorFamilies: ["warm wood", "fireplace amber", "charcoal", "lobster coral", "consomme gold"],
    candidateStyles: ["wood-marquetry-landscape", "stained-glass-field", "fresco-mineral-pigment"],
  },
] as const satisfies readonly BayAreaMichelinRestaurantInput[];
