import type { MichelinInventorySnapshotRow } from "./michelin-inventory-snapshot";

// Independently normalized from California all-starred pages 1-2 and each linked Guide record on 2026-08-26.
export const michelinInventoryBayAreaAdditions = Object.freeze([
  [
    30,
    "SingleThread",
    3,
    "131 North St., Healdsburg, CA, 95448, USA",
    "https://guide.michelin.com/us/en/california/healdsburg/restaurant/singlethread",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred",
  ],
  [
    31,
    "Auberge du Soleil",
    1,
    "180 Rutherford Hill Rd., Rutherford, CA, 94573, USA",
    "https://guide.michelin.com/us/en/california/rutherford/restaurant/auberge-du-soleil",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred",
  ],
  [
    32,
    "Auro",
    1,
    "Four Seasons Resort and Residences Napa Valley, 400 Silverado Trl., Calistoga, CA, 94515, USA",
    "https://guide.michelin.com/us/en/california/calistoga/restaurant/auro",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred",
  ],
  [
    33,
    "Enclos",
    3,
    "139 E. Napa St., Sonoma, CA, 95476, USA",
    "https://guide.michelin.com/us/en/california/sonoma/restaurant/enclos",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred",
  ],
  [
    34,
    "The French Laundry",
    3,
    "6640 Washington St., Yountville, CA, 94599, USA",
    "https://guide.michelin.com/us/en/california/yountville/restaurant/the-french-laundry",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred",
  ],
  [
    35,
    "The Village Pub",
    1,
    "2967 Woodside Rd., Woodside, CA, 94062, USA",
    "https://guide.michelin.com/us/en/california/woodside/restaurant/the-village-pub",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred",
  ],
  [
    36,
    "Cyrus",
    1,
    "275 CA-128, Geyserville, CA, 95441, USA",
    "https://guide.michelin.com/us/en/california/geyserville/restaurant/cyrus",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred",
  ],
  [
    37,
    "Protégé",
    1,
    "250 California Ave., Palo Alto, CA, 94306, USA",
    "https://guide.michelin.com/us/en/california/palo-alto/restaurant/protege",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred/page/2",
  ],
  [
    38,
    "Selby's",
    1,
    "3001 El Camino Real, Atherton, CA, 94061, USA",
    "https://guide.michelin.com/us/en/california/atherton/restaurant/selby-s",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred/page/2",
  ],
  [
    39,
    "Troubadour",
    1,
    "381 Healdsburg Ave., Healdsburg, CA, 95448, USA",
    "https://guide.michelin.com/us/en/california/healdsburg/restaurant/troubadour",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred/page/2",
  ],
  [
    40,
    "Plumed Horse",
    1,
    "14555 Big Basin Way, Saratoga, CA, 95070, USA",
    "https://guide.michelin.com/us/en/california/saratoga/restaurant/plumed-horse",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred/page/2",
  ],
  [
    41,
    "Press",
    1,
    "587 St. Helena St., Saint Helena, CA, 94574, USA",
    "https://guide.michelin.com/us/en/california/saint-helena/restaurant/press",
    "https://guide.michelin.com/us/en/california/restaurants/all-starred/page/2",
  ],
] satisfies readonly MichelinInventorySnapshotRow[]);
