import { defineMichelinRestaurantNycSeed } from "./michelin-restaurants-nyc-types";
import type { MichelinRestaurantNycInput } from "./michelin-restaurants-nyc-types";

const inputs = [
  {
    slug: "shmone",
    restaurantName: "Shmoné",
    city: "New York",
    starCount: 1,
    cuisine: "Israeli, Middle Eastern",
    guidePath: "shmone",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A small, lively counter looks directly into the close-quarters kitchen as dishes emerge from changing market ingredients.",
    primaryForms: [
      "one compact counter arc",
      "one open kitchen block",
      "one market-basket oval",
      "one lively flame curve",
    ],
    supportingAccents: ["one warm bread crescent"],
    colorFamilies: ["warm clay", "olive green", "bread gold", "charcoal"],
    candidateStyles: ["relief-blockprint", "ceramic-underglaze", "risograph-overprint"],
  },
  {
    slug: "tuome",
    restaurantName: "Tuome",
    city: "New York",
    starCount: 1,
    cuisine: "Fusion, Asian Contemporary",
    guidePath: "tuome",
    listingPage: 1,
    cueType: "dish",
    evidenceCue: "Tender octopus with pork XO sauce captures the menu's layered Asian-influenced contrasts.",
    primaryForms: [
      "one broad octopus curve",
      "one dark sauce wave",
      "one backlit bar block",
      "one bay-window arch",
    ],
    supportingAccents: ["one purple seat crescent"],
    colorFamilies: ["deep plum", "sauce brown", "warm amber", "ocean blue"],
    candidateStyles: ["stained-glass-field", "matte-gouache-editorial", "ceramic-underglaze"],
  },
  {
    slug: "bar-miller",
    restaurantName: "Bar Miller",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "bar-miller",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "An intimate wooden counter presents a sustainable omakase built around local seafood and carefully aged fish.",
    primaryForms: [
      "one intimate wood counter",
      "one local-seafood wave",
      "one aged-fish crescent",
      "one dry-aging cabinet block",
    ],
    supportingAccents: ["one pale rice band"],
    colorFamilies: ["walnut brown", "Atlantic blue", "rice ivory", "moon silver"],
    candidateStyles: ["wood-marquetry-landscape", "woven-tapestry-field", "ceramic-underglaze"],
  },
  {
    slug: "tsukimi",
    restaurantName: "Tsukimi",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Seasonal Cuisine",
    guidePath: "tsukimi",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "Illuminated ceramics, mirrored panels, and soft arches evoke the restaurant's moon-viewing name.",
    primaryForms: [
      "one luminous moon disk",
      "two soft room arches",
      "one mirrored vertical plane",
      "one ceramic vessel oval",
    ],
    supportingAccents: ["one silver reflection wave"],
    colorFamilies: ["moon ivory", "midnight blue", "silver gray", "soft mauve"],
    candidateStyles: ["ceramic-underglaze", "stained-glass-field", "screenprint-night"],
  },
  {
    slug: "semma",
    restaurantName: "Semma",
    city: "New York",
    starCount: 1,
    cuisine: "Indian, Regional Cuisine",
    guidePath: "semma",
    listingPage: 1,
    cueType: "dish",
    evidenceCue:
      "A crisp gunpowder dosa wrapped around potato masala expresses the kitchen's focus on regional South Indian cooking.",
    primaryForms: [
      "one broad dosa spiral",
      "one potato-gold oval",
      "one palm-leaf fan",
      "one spice-colored sun",
    ],
    supportingAccents: ["one coconut-cream wave"],
    colorFamilies: ["turmeric gold", "palm green", "coconut cream", "spice brown"],
    candidateStyles: ["ceramic-underglaze", "thread-painted-embroidery", "relief-blockprint"],
  },
  {
    slug: "kosaka",
    restaurantName: "Kosaka",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "kosaka",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A classic twelve-seat counter and subdued room keep attention on the measured omakase progression.",
    primaryForms: [
      "one long counter band",
      "one continuous seat arcade",
      "one measured course disk",
      "one pale ceiling plane",
    ],
    supportingAccents: ["one measured rice curve"],
    colorFamilies: ["pale oak", "deep navy", "rice ivory", "soft graphite"],
    candidateStyles: ["wood-marquetry-landscape", "stained-glass-field", "screenprint-night"],
  },
  {
    slug: "casa-mono",
    restaurantName: "Casa Mono",
    city: "New York",
    starCount: 1,
    cuisine: "Spanish, Contemporary",
    guidePath: "casa-mono",
    listingPage: 1,
    cueType: "dish",
    evidenceCue:
      "Creamy scrambled eggs with sea urchin exemplify the compact kitchen's bold Spanish tapas combinations.",
    primaryForms: [
      "one soft egg oval",
      "one sea-urchin sunburst",
      "one compact counter block",
      "one tapas-plate disk",
    ],
    supportingAccents: ["one olive-green crescent"],
    colorFamilies: ["egg gold", "urchin orange", "Mediterranean blue", "olive green"],
    candidateStyles: ["matte-gouache-editorial", "ceramic-underglaze", "stained-glass-field"],
  },
  {
    slug: "oiji-mi",
    restaurantName: "Oiji Mi",
    city: "New York",
    starCount: 1,
    cuisine: "Korean, Contemporary",
    guidePath: "oiji-mi",
    listingPage: 1,
    cueType: "dish",
    evidenceCue:
      "Lobster ramyun brings luxurious shellfish to a composed contemporary Korean tasting format.",
    primaryForms: [
      "one curling noodle spiral",
      "one lobster-coral crescent",
      "one polished room arch",
      "one dark broth disk",
    ],
    supportingAccents: ["one brass light curve"],
    colorFamilies: ["lobster coral", "broth brown", "brass gold", "deep teal"],
    candidateStyles: ["cut-paper-strata", "ceramic-underglaze", "screenprint-night"],
  },
  {
    slug: "bom",
    restaurantName: "bōm",
    city: "New York",
    starCount: 1,
    cuisine: "Korean, Contemporary",
    guidePath: "bom",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A marble counter with integrated grills faces the open kitchen and a visible dry-aging cabinet.",
    primaryForms: [
      "one marble counter arc",
      "three built-in grill disks",
      "one dry-aging cabinet block",
      "one open kitchen plane",
    ],
    supportingAccents: ["one rising smoke curve"],
    colorFamilies: ["marble cream", "charcoal", "aged amber", "steel gray"],
    candidateStyles: ["prismatic-geometric-symbolism", "fresco-mineral-pigment", "wood-marquetry-landscape"],
  },
  {
    slug: "gramercy-tavern",
    restaurantName: "Gramercy Tavern",
    city: "New York",
    starCount: 1,
    cuisine: "Contemporary, American",
    guidePath: "gramercy-tavern",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A warm wood tavern opens into a more formal dining room, joining neighborhood ease with polished service.",
    primaryForms: [
      "one timber tavern arch",
      "one formal room rectangle",
      "one shared hearth disk",
      "one connecting doorway band",
    ],
    supportingAccents: ["one seasonal branch"],
    colorFamilies: ["walnut brown", "warm cream", "forest green", "hearth amber"],
    candidateStyles: ["wood-marquetry-landscape", "woven-tapestry-field", "thread-painted-embroidery"],
  },
  {
    slug: "rezdora",
    restaurantName: "Rezdôra",
    city: "New York",
    starCount: 1,
    cuisine: "Italian, Regional Cuisine",
    guidePath: "rezdora-osteria-emiliana",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "Handmade pasta and airy gnocco fritto draw the menu toward the regional food traditions of Emilia-Romagna.",
    primaryForms: [
      "one looping pasta ribbon",
      "one puffed bread oval",
      "one pasta-work counter block",
      "one regional tasting disk",
    ],
    supportingAccents: ["one cheese-gold curve"],
    colorFamilies: ["pasta gold", "farmhouse cream", "hill green", "terra brown"],
    candidateStyles: ["thread-painted-embroidery", "wood-marquetry-landscape", "ceramic-underglaze"],
  },
  {
    slug: "noda",
    restaurantName: "Noda",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "noda",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "An eight-seat half-moon counter sits beyond a cocktail lounge in a dark, speakeasy-like room.",
    primaryForms: [
      "one half-moon counter",
      "one dark lounge arch",
      "one hidden doorway plane",
      "one omakase plate disk",
    ],
    supportingAccents: ["one cocktail-gold curve"],
    colorFamilies: ["midnight blue", "warm gold", "ebony", "rice ivory"],
    candidateStyles: ["screenprint-night", "stained-glass-field", "wood-marquetry-landscape"],
  },
  {
    slug: "odo",
    restaurantName: "Odo",
    city: "New York",
    starCount: 2,
    cuisine: "Japanese, Contemporary",
    guidePath: "odo",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A secluded, serene kaiseki counter is reached through a cocktail bar, separating ceremony from the city outside.",
    primaryForms: [
      "one secluded counter band",
      "one passageway arch",
      "one separating room plane",
      "one composed tasting disk",
    ],
    supportingAccents: ["one soba-brown curve"],
    colorFamilies: ["cypress tan", "garden green", "moon ivory", "deep charcoal"],
    candidateStyles: ["wood-marquetry-landscape", "ceramic-underglaze", "fresco-mineral-pigment"],
  },
  {
    slug: "noz-17",
    restaurantName: "Noz 17",
    city: "New York",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "noz17",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "A tiny chef counter foregrounds dry-aging, curing, and fermentation within an Edomae-inspired omakase.",
    primaryForms: [
      "one tiny counter arc",
      "one preserved-fish crescent",
      "one fermentation spiral",
      "one curing-shelf band",
    ],
    supportingAccents: ["one rice-ivory disk"],
    colorFamilies: ["deep tide blue", "aged amber", "rice ivory", "charcoal"],
    candidateStyles: ["ceramic-underglaze", "relief-blockprint", "screenprint-night"],
  },
  {
    slug: "aska",
    restaurantName: "Aska",
    city: "Brooklyn",
    starCount: 2,
    cuisine: "Scandinavian, Contemporary",
    guidePath: "aska",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "Austere Nordic cooking uses smoke, fire, preserved flavors, and seasonal northeastern ingredients in a dark Williamsburg setting.",
    primaryForms: [
      "one dark room arch",
      "one preserved-flavor oval",
      "one smoke ribbon",
      "one seasonal-ingredient disk",
    ],
    supportingAccents: ["one ember-gold disk"],
    colorFamilies: ["charcoal", "pine green", "winter ivory", "ember gold"],
    candidateStyles: ["screenprint-night", "relief-blockprint", "fresco-mineral-pigment"],
  },
  {
    slug: "cote",
    restaurantName: "Cote",
    city: "New York",
    starCount: 1,
    cuisine: "Korean, Steakhouse",
    guidePath: "cote",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "Korean barbecue meets an American steakhouse through tabletop grills and a prominent dry-aging program.",
    primaryForms: [
      "one tabletop grill disk",
      "one dry-aging cabinet",
      "one bold steakhouse arch",
      "one rising smoke curve",
    ],
    supportingAccents: ["one brass ember band"],
    colorFamilies: ["charcoal", "aged amber", "brass gold", "deep navy"],
    candidateStyles: ["screenprint-night", "prismatic-geometric-symbolism", "wood-marquetry-landscape"],
  },
  {
    slug: "jua",
    restaurantName: "Jua",
    city: "New York",
    starCount: 1,
    cuisine: "Korean, Korean Contemporary",
    guidePath: "jua",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "Soaring ceilings and sultry light frame a modern Korean tasting menu shaped by dry-aging and wood fire.",
    primaryForms: [
      "one soaring ceiling arch",
      "one wood-fire disk",
      "one dry-aged ingredient crescent",
      "one tall shadow plane",
    ],
    supportingAccents: ["one glazed-donut ring"],
    colorFamilies: ["deep plum", "ember amber", "smoke gray", "warm ivory"],
    candidateStyles: ["stained-glass-field", "screenprint-night", "thread-painted-embroidery"],
  },
  {
    slug: "shota-omakase",
    restaurantName: "Shota Omakase",
    city: "Brooklyn",
    starCount: 1,
    cuisine: "Japanese, Sushi",
    guidePath: "shota-omakase",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "A close Brooklyn sushi counter emphasizes wild seafood, maturation, and traditional Edomae preparation.",
    primaryForms: [
      "one close counter band",
      "one wild-seafood wave",
      "one matured-fish crescent",
      "one maturation vessel oval",
    ],
    supportingAccents: ["one cypress-grain curve"],
    colorFamilies: ["harbor blue", "cypress honey", "rice ivory", "deep charcoal"],
    candidateStyles: ["wood-marquetry-landscape", "ceramic-underglaze", "woven-tapestry-field"],
  },
  {
    slug: "eleven-madison-park",
    restaurantName: "Eleven Madison Park",
    city: "New York",
    starCount: 3,
    cuisine: "Contemporary",
    guidePath: "eleven-madison-park",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A vast Art Deco dining room overlooks Madison Square while the tasting menu is built entirely around plants.",
    primaryForms: [
      "one vast stepped arch",
      "one Madison Square horizon",
      "one tall window grid",
      "one plant-like central fan",
    ],
    supportingAccents: ["one brass horizon"],
    colorFamilies: ["park green", "limestone cream", "aged brass", "city charcoal"],
    candidateStyles: ["stained-glass-field", "prismatic-geometric-symbolism", "thread-painted-embroidery"],
  },
  {
    slug: "francie",
    restaurantName: "Francie",
    city: "Brooklyn",
    starCount: 1,
    cuisine: "Contemporary, Italian",
    guidePath: "francie",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A limestone building combines ash wood, mosaic flooring, exposed brick, and an open kitchen.",
    primaryForms: [
      "one limestone facade block",
      "one ash-wood arch",
      "one mosaic floor plane",
      "one open kitchen window",
    ],
    supportingAccents: ["one exposed-brick band"],
    colorFamilies: ["limestone cream", "ash tan", "brick brown", "mosaic blue"],
    candidateStyles: ["wood-marquetry-landscape", "fresco-mineral-pigment", "stained-glass-field"],
  },
  {
    slug: "atomix",
    restaurantName: "Atomix",
    city: "New York",
    starCount: 2,
    cuisine: "Korean",
    guidePath: "atomix",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A townhouse descends to a basement U-shaped counter where a contemporary Korean tasting menu unfolds.",
    primaryForms: [
      "one townhouse silhouette",
      "one descending stair band",
      "one basement counter horseshoe",
      "one tasting-course disk",
    ],
    supportingAccents: ["one fermentation curve"],
    colorFamilies: ["townhouse gray", "ink black", "ceramic ivory", "burnished bronze"],
    candidateStyles: ["cut-paper-strata", "ceramic-underglaze", "screenprint-night"],
  },
  {
    slug: "the-four-horsemen",
    restaurantName: "The Four Horsemen",
    city: "Brooklyn",
    starCount: 1,
    cuisine: "American",
    guidePath: "the-four-horsemen",
    listingPage: 1,
    cueType: "culture",
    evidenceCue:
      "A compact wood-lined wine bar pairs natural wines with concise, highly seasonal American plates.",
    primaryForms: [
      "one compact timber room",
      "one wine-glass oval",
      "one seasonal leaf fan",
      "one shared-table band",
    ],
    supportingAccents: ["one vineyard curve"],
    colorFamilies: ["walnut brown", "grape purple", "leaf green", "warm cream"],
    candidateStyles: ["wood-marquetry-landscape", "woven-tapestry-field", "risograph-overprint"],
  },
  {
    slug: "joo-ok",
    restaurantName: "Joo Ok",
    city: "New York",
    starCount: 2,
    cuisine: "Korean",
    guidePath: "joo-ok-1214822",
    listingPage: 1,
    cueType: "interior",
    evidenceCue:
      "A high-floor dining room opens to broad skyline views while the menu draws on Korean fermentation and royal-court traditions.",
    primaryForms: [
      "one high skyline band",
      "one panoramic window arch",
      "one fermentation vessel oval",
      "one royal-pattern fan",
    ],
    supportingAccents: ["one moonlit cloud curve"],
    colorFamilies: ["sky blue", "night navy", "celadon", "warm gold"],
    candidateStyles: ["stained-glass-field", "ceramic-underglaze", "woven-tapestry-field"],
  },
] satisfies readonly MichelinRestaurantNycInput[];

export const newYorkCityMichelinRestaurantSeeds02 = inputs.map(defineMichelinRestaurantNycSeed);
