import type { MichelinInventorySnapshotRow } from "./michelin-inventory-snapshot";

// Normalized from the official all-starred result set and each linked Guide record on 2026-08-25.
export const michelinInventoryWashingtonDc = Object.freeze([
  [
    1,
    "The Inn at Little Washington",
    2,
    "309 Middle St., Washington, VA, 22747, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/the-inn-at-little-washington",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    2,
    "Jônt",
    2,
    "1904 14th St. NW, Washington, DC, 20009, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/jont",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    3,
    "minibar by José Andrés",
    2,
    "855 E St. NW, Washington, DC, 20004, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/minibar",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    4,
    "Xiquet",
    1,
    "2404 Wisconsin Ave. NW, Washington, DC, 20007, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/xiquet",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    5,
    "Rooster & Owl",
    1,
    "2436 14th St. NW, Washington, DC, 20009, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/rooster-owl",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    6,
    "Masseria",
    1,
    "1340 4th St. NE, Washington, DC, 20002, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/masseria",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    7,
    "Omakase at Barracks Row",
    1,
    "522 8th St. SE, Washington, DC, 20003, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/omakase-at-barracks-row",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    8,
    "The Dabney",
    1,
    "122 Blagden Alley NW, Washington, DC, 20001, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/the-dabney",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    9,
    "Elcielo Washington DC",
    1,
    "1280 4th St. NE, Washington, DC, 20002, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/elcielo-d-c",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    10,
    "Oyster Oyster",
    1,
    "1440 8th St. NW, Washington, DC, 20001, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/oyster-oyster",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    11,
    "Pineapple and Pearls",
    1,
    "715 8th St. SE, Washington, DC, 20003, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/pineapple-and-pearls",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    12,
    "Causa",
    1,
    "920 Blagden Alley NW, Washington, DC, 20001, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/causa",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    13,
    "Imperfecto: The Chef's Table",
    1,
    "1124 23rd St. NW, Washington, DC, 20037, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/imperfecto-the-chef-s-table",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    14,
    "Sushi Nakazawa Washington DC",
    1,
    "Waldorf Astoria, 1100 Pennsylvania Ave. NW, Washington, DC, 20004, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/sushi-nakazawa1160153",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    15,
    "Albi",
    1,
    "1346 4th St. SE, Washington, DC, 20003, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/albi",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    16,
    "MITA",
    1,
    "804 V St. NW, Washington, DC, 20001, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/mita",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    17,
    "Rose’s Luxury",
    1,
    "717 8th St. SE, Washington, DC, 20003, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/rose-s-luxury",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    18,
    "Little Pearl",
    1,
    "921 Pennsylvania Ave. SE, Washington, DC, 20003, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/little-pearl",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    19,
    "Fiola",
    1,
    "601 Pennsylvania Ave. NW, Washington, DC, 20004, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/fiola",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    20,
    "Bresca",
    1,
    "1906 14th St. NW, Washington, DC, 20009, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/bresca",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    21,
    "Gravitas",
    1,
    "1401 Okie St. NE, Washington, DC, 20002, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/gravitas",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
  [
    22,
    "Rania",
    1,
    "427 11th St. NW, Washington, DC, 20004, USA",
    "https://guide.michelin.com/us/en/district-of-columbia/washington-dc/restaurant/rania",
    "https://guide.michelin.com/us/en/district-of-columbia/restaurants/all-starred",
  ],
] satisfies readonly MichelinInventorySnapshotRow[]);
