import type { BayAreaMichelinRestaurantInput } from "./michelin-restaurants-bay-area-types";

export const bayAreaMichelinRestaurantInputsPartTwo = [
  {
    slug: "lazy-bear",
    restaurantName: "Lazy Bear",
    locationLabel: "3416 19th St., San Francisco, CA, 94110, USA",
    locationAliases: ["Mission District", "San Francisco, California", "Bay Area"],
    starCount: 2,
    cuisine: "Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/lazy-bear",
    cueType: "dish",
    evidenceCue:
      "Lazy Bear's bi-level warehouse resembles a hunting lodge; its paired oysters use gooseberry mignonette or charbroiled Jimmy Nardello pepper glaze with pickled biquinho peppers.",
    otherEvidenceSourceUrls: [
      "https://guide.michelin.com/ae-du/en/california/san-francisco/restaurant/lazy-bear",
      "https://www.lazybearsf.com/dinner/",
    ],
    primaryForms: [
      "two broad oyster half-shells",
      "three broad gooseberry drops",
      "one Jimmy-Nardello glaze ribbon",
      "two pickled-biquinho pepper disks",
      "one broad bi-level timber roofline",
    ],
    supportingAccents: [],
    colorFamilies: ["oyster pearl", "timber brown", "gooseberry green", "pepper vermilion", "ember orange"],
    candidateStyles: ["ceramic-underglaze", "wood-marquetry-landscape", "woven-tapestry-field"],
  },
  {
    slug: "sons-and-daughters",
    restaurantName: "Sons & Daughters",
    locationLabel: "2875 18th St., San Francisco, CA, 94110, USA",
    locationAliases: ["Mission District", "San Francisco, California", "Bay Area"],
    starCount: 2,
    cuisine: "Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/sons-daughters",
    cueType: "culture",
    evidenceCue:
      "New Nordic preservation shapes vegetables, foraged mushrooms, and seafood, with British roots appearing in a quail Scotch egg.",
    primaryForms: [
      "one preserved-vegetable ribbon",
      "one broad mushroom dome",
      "one ocean-blue wave",
      "one nested egg oval",
    ],
    supportingAccents: ["one foraged leaf curve"],
    colorFamilies: ["forest green", "mushroom cream", "ocean blue", "yolk gold", "charcoal"],
    candidateStyles: ["thread-painted-embroidery", "ceramic-underglaze", "relief-blockprint"],
  },
  {
    slug: "hilda-and-jesse",
    restaurantName: "Hilda and Jesse",
    locationLabel: "701 Union St., San Francisco, CA, 94133, USA",
    locationAliases: ["North Beach", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "American, Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/hilda-and-jesse",
    cueType: "culture",
    evidenceCue:
      "A cheerful modernist-diner room delivers an ambitious brunch as a frequently changing sequence of surprise dishes.",
    primaryForms: [
      "one modernist diner arch",
      "one brunch-course disk",
      "one surprise-path zigzag",
      "one open counter block",
    ],
    supportingAccents: ["two playful color tiles"],
    colorFamilies: ["sunny gold", "soft teal", "cream", "deep plum", "charcoal"],
    candidateStyles: ["risograph-overprint", "cut-paper-strata", "prismatic-geometric-symbolism"],
  },
  {
    slug: "san-ho-won",
    restaurantName: "San Ho Won",
    locationLabel: "2170 Bryant St., San Francisco, CA, 94110, USA",
    locationAliases: ["Mission District", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Korean, Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/san-ho-won",
    cueType: "dish",
    evidenceCue:
      "Korean barbecue and home cooking meet in pork jowl with aged kimchi stew and a soy-pickled ramp.",
    primaryForms: [
      "one charcoal grill oval",
      "one warm stew-bowl arc",
      "one pork-jowl crescent",
      "one pickled ramp curve",
    ],
    supportingAccents: ["one ember-orange block"],
    colorFamilies: ["charcoal", "ember orange", "kimchi amber", "leaf green", "rice ivory"],
    candidateStyles: ["ceramic-underglaze", "relief-blockprint", "screenprint-night"],
  },
  {
    slug: "quince",
    restaurantName: "Quince",
    locationLabel: "470 Pacific Ave., San Francisco, CA, 94133, USA",
    locationAliases: ["Jackson Square", "San Francisco, California", "Bay Area"],
    starCount: 3,
    cuisine: "Contemporary, Californian",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/quince",
    cueType: "dish",
    evidenceCue:
      "Fireplace-cooked local lamb meets fava beans, green garlic, edible blossoms, and vegetable-ash bread.",
    primaryForms: [
      "one hearth-glow arch",
      "one local lamb silhouette",
      "one broad fava-leaf mass",
      "one ash-dark bread dome",
    ],
    supportingAccents: ["two blossom-colored disks"],
    colorFamilies: ["hearth amber", "fava green", "ash charcoal", "bread cream", "blossom violet"],
    candidateStyles: ["fresco-mineral-pigment", "thread-painted-embroidery", "stained-glass-field"],
  },
  {
    slug: "saison",
    restaurantName: "Saison",
    locationLabel: "178 Townsend St., San Francisco, CA, 94107, USA",
    locationAliases: ["South Beach", "San Francisco, California", "Bay Area"],
    starCount: 2,
    cuisine: "Californian",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/saison",
    cueType: "culture",
    evidenceCue:
      "An open wood hearth shapes a California-terroir menu sourced from regional farms, ranches, and fisheries.",
    otherEvidenceSourceUrls: ["https://www.saisonhospitality.com/brands-saison/"],
    primaryForms: [
      "one broad open-hearth arch",
      "one rising flame ribbon",
      "one farm-field band",
      "one fishery wave",
    ],
    supportingAccents: ["one smoke-gray curve"],
    colorFamilies: ["ember orange", "smoke gray", "field green", "Pacific blue", "warm cream"],
    candidateStyles: ["screenprint-night", "wood-marquetry-landscape", "ceramic-underglaze"],
  },
  {
    slug: "atelier-crenn",
    restaurantName: "Atelier Crenn",
    locationLabel: "3127 Fillmore St., San Francisco, CA, 94123, USA",
    locationAliases: ["Cow Hollow", "San Francisco, California", "Bay Area"],
    starCount: 3,
    cuisine: "Contemporary, French",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/atelier-crenn",
    cueType: "culture",
    evidenceCue:
      "A pescatarian tasting connects Brittany and California through seafood, farm produce, sauces, and a grandmother's brioche.",
    primaryForms: [
      "one Brittany-seafood wave",
      "one California field band",
      "one seafood silhouette",
      "one braided bread dome",
    ],
    supportingAccents: ["one farm-leaf curve"],
    colorFamilies: ["Atlantic blue", "field green", "bread gold", "warm cream", "charcoal"],
    candidateStyles: ["woven-tapestry-field", "stained-glass-field", "matte-gouache-editorial"],
  },
  {
    slug: "sorrel",
    restaurantName: "Sorrel",
    locationLabel: "3228 Sacramento St., San Francisco, CA, 94115, USA",
    locationAliases: ["Presidio Heights", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/sorrel",
    cueType: "culture",
    evidenceCue:
      "Italian-inflected Californian cooking follows farmers-market harvests and ingredients foraged from a rooftop garden.",
    otherEvidenceSourceUrls: ["https://www.sorrelrestaurant.com/about/"],
    primaryForms: [
      "one rooftop garden terrace",
      "one market-basket oval",
      "one climbing sorrel leaf",
      "one Italian-inflected course band",
    ],
    supportingAccents: ["one harvest-gold disk"],
    colorFamilies: ["sorrel green", "terra cotta", "harvest gold", "sky blue", "cream"],
    candidateStyles: ["thread-painted-embroidery", "fresco-mineral-pigment", "wood-marquetry-landscape"],
  },
  {
    slug: "angler-sf",
    restaurantName: "Angler SF",
    locationLabel: "132 The Embarcadero, San Francisco, CA, 94105, USA",
    locationAliases: ["Embarcadero", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Contemporary, Seafood",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/angler-sf",
    cueType: "interior",
    evidenceCue:
      "A waterfront dining room frames steel beams, native flowers, and an expansive wood hearth touching every seafood dish with fire.",
    primaryForms: [
      "one broad waterfront horizon",
      "two steel beam diagonals",
      "one expansive hearth oval",
      "one seafood silhouette",
    ],
    supportingAccents: ["two native flower disks"],
    colorFamilies: ["Bay blue", "steel gray", "ember orange", "flower gold", "charcoal"],
    candidateStyles: ["stained-glass-field", "screenprint-night", "wood-marquetry-landscape"],
  },
  {
    slug: "wolfsbane",
    restaurantName: "Wolfsbane",
    locationLabel: "2495 Third St., San Francisco, CA, 94107, USA",
    locationAliases: ["Dogpatch", "San Francisco, California", "Bay Area"],
    starCount: 1,
    cuisine: "Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-francisco/restaurant/wolfsbane",
    cueType: "dish",
    evidenceCue:
      "Michelin pairs Wolfsbane's Dungeness crab with earthy sweet potato and buttery Maltaise sauce, tinted blush with blood orange and beet.",
    otherEvidenceSourceUrls: [
      "https://guide.michelin.com/gb/en/california/san-francisco/restaurant/wolfsbane",
      "https://wolfsbanesf.com/",
    ],
    primaryForms: [
      "one Dungeness-crab claw",
      "one Maltaise-sauce disk",
      "one sweet-potato crescent",
      "one blood-orange-and-beet ring",
    ],
    supportingAccents: [],
    colorFamilies: ["crab coral", "sauce ivory", "beet blush", "blood-orange crimson", "sweet-potato purple"],
    candidateStyles: ["cut-paper-strata", "ceramic-underglaze", "stained-glass-field"],
  },
  {
    slug: "sun-moon-studio",
    restaurantName: "Sun Moon Studio",
    locationLabel: "1940 Union St., Ste. 21, Oakland, CA, 94607, USA",
    locationAliases: ["West Oakland", "Oakland, California", "Bay Area"],
    starCount: 1,
    cuisine: "Californian",
    guideUrl: "https://guide.michelin.com/us/en/california/oakland/restaurant/sun-moon-studio",
    cueType: "dish",
    evidenceCue:
      "An intimate seasonal tasting pairs Dungeness crab and yuzu-kosho butter with silken tofu, plus savory egg tart and salmon roe.",
    primaryForms: [
      "one crab-claw crescent",
      "one silken tofu block",
      "one savory tart disk",
      "one yuzu-butter arc",
    ],
    supportingAccents: ["one roe-orange oval"],
    colorFamilies: ["moon ivory", "sun gold", "crab coral", "deep teal", "charcoal"],
    candidateStyles: ["ceramic-underglaze", "mosaic-tesserae-field", "prismatic-geometric-symbolism"],
  },
  {
    slug: "commis",
    restaurantName: "Commis",
    locationLabel: "3859 Piedmont Ave., Oakland, CA, 94611, USA",
    locationAliases: ["Piedmont Avenue", "Oakland, California", "Bay Area"],
    starCount: 2,
    cuisine: "Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/oakland/restaurant/commis",
    cueType: "dish",
    evidenceCue:
      "A signature slow-poached egg yolk rests in onion-and-malt cream within a serene, pendant-lit dining room.",
    primaryForms: [
      "one glowing yolk disk",
      "one onion-cream wave",
      "one malt-brown bowl arc",
      "two pendant-light ovals",
    ],
    supportingAccents: ["one dark walnut band"],
    colorFamilies: ["yolk gold", "cream", "malt brown", "walnut", "charcoal"],
    candidateStyles: ["stained-glass-field", "wood-marquetry-landscape", "matte-gouache-editorial"],
  },
  {
    slug: "madcap",
    restaurantName: "Madcap",
    locationLabel: "198 Sir Francis Drake Blvd., San Anselmo, CA, 94960, USA",
    locationAliases: ["San Anselmo, California", "Marin County", "Bay Area"],
    starCount: 1,
    cuisine: "Contemporary, Asian Contemporary",
    guideUrl: "https://guide.michelin.com/us/en/california/san-anselmo/restaurant/madcap",
    cueType: "dish",
    evidenceCue:
      "Crisp-skinned trout, cauliflower purée, and kohlrabi ribbons finish with a tableside stream of dashi.",
    primaryForms: [
      "one broad trout silhouette",
      "one cauliflower-cream oval",
      "two kohlrabi ribbons",
      "one pouring dashi arc",
    ],
    supportingAccents: ["one river-blue curve"],
    colorFamilies: ["trout silver", "cauliflower cream", "leaf green", "dashi amber", "river blue"],
    candidateStyles: ["watercolor-naturalist-study", "cut-paper-strata", "ceramic-underglaze"],
  },
  {
    slug: "wakuriya",
    restaurantName: "Wakuriya",
    locationLabel: "115 De Anza Blvd., San Mateo, CA, 94402, USA",
    locationAliases: ["San Mateo, California", "Peninsula", "Bay Area"],
    starCount: 1,
    cuisine: "Japanese",
    guideUrl: "https://guide.michelin.com/us/en/california/san-mateo/restaurant/wakuriya",
    cueType: "culture",
    evidenceCue:
      "A reservation-only Japanese kitchen presents kaiseki as a measured progression from starter and appetizers through seasonal cooked courses.",
    otherEvidenceSourceUrls: ["https://www.wakuriya.com/"],
    primaryForms: [
      "one measured course-path ribbon",
      "one seasonal course disk",
      "one steaming bowl arc",
      "one folded appetizer fan",
    ],
    supportingAccents: ["one quiet garden curve"],
    colorFamilies: ["moon ivory", "ink black", "celadon green", "warm clay", "seasonal gold"],
    candidateStyles: ["ceramic-underglaze", "monoprint-ink-wash", "wood-marquetry-landscape"],
  },
] as const satisfies readonly BayAreaMichelinRestaurantInput[];
