import type { MichelinInventorySnapshotRow } from "./michelin-inventory-snapshot";

// Normalized from the official all-starred result set and each linked Guide record on 2026-08-25.
export const michelinInventorySanFrancisco = Object.freeze([
  [
    1,
    "Kiln",
    2,
    "149 Fell St., San Francisco, CA, 94102, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/kiln-1210355",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    2,
    "Birdsong",
    2,
    "1085 Mission St., San Francisco, CA, 94103, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/birdsong",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    3,
    "Nari",
    1,
    "Hotel Kabuki, 1625 Post St., San Francisco, CA, 94115, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/nari",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    4,
    "Kin Khao",
    1,
    "55 Cyril Magnin St., San Francisco, CA, 94102, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/kin-khao",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    5,
    "Californios",
    3,
    "355 11th St., San Francisco, CA, 94103, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/californios",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    6,
    "State Bird Provisions",
    1,
    "1529 Fillmore St., San Francisco, CA, 94115, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/state-bird-provisions",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    7,
    "The Progress",
    1,
    "1525 Fillmore St., San Francisco, CA, 94115, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/the-progress",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    8,
    "7 Adams",
    1,
    "1963 Sutter St., San Francisco, CA, 94115, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/7-adams",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    9,
    "Acquerello",
    2,
    "1722 Sacramento St., San Francisco, CA, 94109, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/acquerello",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    10,
    "Restaurant Naides",
    1,
    "708 Bush St., San Francisco, CA, 94108, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/naides",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    11,
    "Niku Steakhouse",
    1,
    "61 Division St., San Francisco, CA, 94103, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/niku-steakhouse",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    12,
    "Ssal",
    1,
    "2226 Polk St., San Francisco, CA, 94109, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/ssal",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    13,
    "Mister Jiu’s",
    1,
    "28 Waverly Pl., San Francisco, CA, 94108, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/mister-jiu%E2%80%99s",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    14,
    "Benu",
    3,
    "22 Hawthorne St., San Francisco, CA, 94105, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/benu",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    15,
    "Nisei",
    1,
    "2316 Polk St., San Francisco, CA, 94109, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/nisei",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    16,
    "Lazy Bear",
    2,
    "3416 19th St., San Francisco, CA, 94110, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/lazy-bear",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    17,
    "Sons & Daughters",
    2,
    "2875 18th St., San Francisco, CA, 94110, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/sons-daughters",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    18,
    "Hilda and Jesse",
    1,
    "701 Union St., San Francisco, CA, 94133, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/hilda-and-jesse",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    19,
    "San Ho Won",
    1,
    "2170 Bryant St., San Francisco, CA, 94110, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/san-ho-won",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    20,
    "Quince",
    3,
    "470 Pacific Ave., San Francisco, CA, 94133, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/quince",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    21,
    "Saison",
    2,
    "178 Townsend St., San Francisco, CA, 94107, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/saison",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    22,
    "Atelier Crenn",
    3,
    "3127 Fillmore St., San Francisco, CA, 94123, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/atelier-crenn",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    23,
    "Sorrel",
    1,
    "3228 Sacramento St., San Francisco, CA, 94115, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/sorrel",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    24,
    "Angler SF",
    1,
    "132 The Embarcadero, San Francisco, CA, 94105, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/angler-sf",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    25,
    "Wolfsbane",
    1,
    "2495 Third St., San Francisco, CA, 94107, USA",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurant/wolfsbane",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    26,
    "Sun Moon Studio",
    1,
    "1940 Union St., Ste. 21, Oakland, CA, 94607, USA",
    "https://guide.michelin.com/us/en/california/oakland/restaurant/sun-moon-studio",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    27,
    "Commis",
    2,
    "3859 Piedmont Ave., Oakland, CA, 94611, USA",
    "https://guide.michelin.com/us/en/california/oakland/restaurant/commis",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    28,
    "Madcap",
    1,
    "198 Sir Francis Drake Blvd., San Anselmo, CA, 94960, USA",
    "https://guide.michelin.com/us/en/california/san-anselmo/restaurant/madcap",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
  [
    29,
    "Wakuriya",
    1,
    "115 De Anza Blvd., San Mateo, CA, 94402, USA",
    "https://guide.michelin.com/us/en/california/san-mateo/restaurant/wakuriya",
    "https://guide.michelin.com/us/en/california/san-francisco/restaurants/all-starred",
  ],
] satisfies readonly MichelinInventorySnapshotRow[]);
