import { defineLandscapeArtProfile, motif, palette } from "./code-native-landscape-profile";

export const nationalParkLandscapeProfiles03 = [
  defineLandscapeArtProfile({
    slug: "gates-of-the-arctic",
    sourceCue: "the Arrigetch peaks beyond a winding tundra river with no road in sight",
    primaryStyleId: "fresco-mineral-pigment",
    palette: palette(
      ["tundra", "#72553E"],
      ["peak", "#D7D4C7"],
      ["river", "#516F80"],
      ["lichen", "#B59A42"],
      ["aurora", "#6D9A72"],
    ),
    motifs: [
      motif(
        "the Arrigetch peaks beyond a winding tundra river with no road in sight",
        "triangle",
        1,
        0.58,
        0.43,
        0.6,
        0.58,
      ),
      motif("two mountains opening onto untouched northern distance", "arch", 4, 0.29, 0.42, 0.32, 0.34),
      motif(
        "Brooks Range valleys, wild rivers, tundra, and untracked passes",
        "ribbon",
        2,
        0.48,
        0.79,
        0.74,
        0.22,
      ),
    ],
    relationship: "Two broad mountain forms open around one untracked river crossing the tundra.",
    edgeStrategy:
      "The river exits both lower sides and tundra reaches bottom while northern sky remains open.",
  }),
  defineLandscapeArtProfile({
    slug: "gateway-arch",
    sourceCue: "the stainless arc rising over the Mississippi at blue hour",
    primaryStyleId: "prismatic-geometric-symbolism",
    palette: palette(
      ["blue hour", "#27395D"],
      ["steel", "#C7CDD0"],
      ["river", "#3B7192"],
      ["brick", "#995348"],
      ["window", "#D5A249"],
    ),
    motifs: [
      motif("the stainless arc rising over the Mississippi at blue hour", "arch", 1, 0.5, 0.43, 0.56, 0.64),
      motif("a single curve joining river, city, and western sky", "ribbon", 2, 0.36, 0.73, 0.58, 0.2),
      motif("riverfront axis, broad bend, and urban horizon", "horizon", 3, 0.65, 0.82, 0.62, 0.18),
    ],
    relationship: "The single steel arc bridges a river curve and a compressed brick riverfront horizon.",
    edgeStrategy: "River and horizon cross the lower sides; blue hour stays open around the arc crown.",
  }),
  defineLandscapeArtProfile({
    slug: "glacier-bay",
    sourceCue: "a tidewater glacier calving beyond a humpback whale's fluke",
    primaryStyleId: "ceramic-underglaze",
    palette: palette(
      ["fjord", "#174B70"],
      ["ice", "#9FD8DE"],
      ["snow", "#EEF0E6"],
      ["granite", "#657078"],
      ["kelp", "#3F6B55"],
    ),
    motifs: [
      motif(
        "a tidewater glacier calving beyond a humpback whale's fluke",
        "shell",
        1,
        0.56,
        0.43,
        0.62,
        0.48,
      ),
      motif("ice withdrawing to reveal a living blue corridor", "ribbon", 3, 0.26, 0.68, 0.3, 0.2),
      motif(
        "deep fjords, tidewater ice, islands, and coastal mountains",
        "ribbon",
        2,
        0.61,
        0.79,
        0.62,
        0.22,
      ),
    ],
    relationship: "A broad glacier front recedes behind one whale-fluke silhouette and a deep fjord ribbon.",
    edgeStrategy:
      "The fjord reaches right, left, and bottom while the snow field remains open over the glacier.",
  }),
  defineLandscapeArtProfile({
    slug: "glacier",
    sourceCue: "Hidden Lake below sharp peaks with a mountain goat on the overlook",
    primaryStyleId: "wood-marquetry-landscape",
    palette: palette(
      ["cedar", "#2F5541"],
      ["granite", "#6E7680"],
      ["lake", "#347F8B"],
      ["snow", "#E9E8D8"],
      ["beargrass", "#D7C56D"],
    ),
    motifs: [
      motif(
        "Hidden Lake below sharp peaks with a mountain goat on the overlook",
        "triangle",
        1,
        0.49,
        0.42,
        0.62,
        0.56,
      ),
      motif("the continental divide splitting weather and water", "stripe", 3, 0.74, 0.61, 0.24, 0.16),
      motif(
        "glacial cirques, alpine lakes, serrated ridges, and cedar valleys",
        "oval",
        2,
        0.42,
        0.8,
        0.62,
        0.2,
      ),
    ],
    relationship: "The sharp divide rises above one lake form while a small goat holds the overlook edge.",
    edgeStrategy: "Cedar ground and lake reach the lower edges; snow sky opens beyond the serrated peak.",
  }),
  defineLandscapeArtProfile({
    slug: "grand-canyon",
    sourceCue: "layer after layer of canyon opening around a distant Colorado River",
    primaryStyleId: "scratchboard-nocturne",
    palette: palette(
      ["shadow", "#262233"],
      ["canyon", "#A4513A"],
      ["river", "#477A72"],
      ["cream", "#E7D7B8"],
      ["sun", "#D5A23D"],
    ),
    motifs: [
      motif(
        "layer after layer of canyon opening around a distant Colorado River",
        "corner",
        1,
        0.47,
        0.5,
        0.8,
        0.64,
      ),
      motif("deep time written as bands of light and shadow", "stripe", 4, 0.67, 0.31, 0.42, 0.2),
      motif("terraced cliffs, side canyons, buttes, and river gorge", "ribbon", 2, 0.52, 0.82, 0.7, 0.18),
    ],
    relationship: "One canyon corner exposes a single light band above the distant river gorge.",
    edgeStrategy:
      "Terraces and river reach every lower edge while the cream opening breaks the upper shadow.",
  }),
  defineLandscapeArtProfile({
    slug: "grand-teton",
    sourceCue: "the Teton skyline reflected in still Snake River water",
    primaryStyleId: "luminous-ligne-claire",
    palette: palette(
      ["open dawn", "#EFD9C4"],
      ["granite contour", "#34465E"],
      ["river", "#6A9EB1"],
      ["sage", "#71855B"],
      ["snow light", "#F4F0E4"],
    ),
    motifs: [
      motif("the Teton skyline reflected in still Snake River water", "triangle", 1, 0.49, 0.47, 0.5, 0.5),
      motif(
        "jagged peaks rising without foothills from a wide sage valley",
        "horizon",
        3,
        0.57,
        0.77,
        0.62,
        0.18,
      ),
      motif(
        "fault-block range, braided river, moraine lakes, and sage flats",
        "oval",
        2,
        0.38,
        0.84,
        0.46,
        0.14,
      ),
    ],
    accent: motif("one open journey line through the immense valley", "ribbon", 1, 0.27, 0.32, 0.3, 0.14),
    relationship:
      "A monumental clear-contour peak rises above a small river reflection and one airy journey line.",
    edgeStrategy:
      "Sage and river touch the lower edges while more than a third of the dawn field stays unobstructed.",
  }),
  defineLandscapeArtProfile({
    slug: "great-basin",
    sourceCue: "ancient bristlecone pines twisting beneath the Milky Way",
    primaryStyleId: "pixel-cluster-landscape",
    palette: palette(
      ["night", "#1E274A"],
      ["wood", "#8A6845"],
      ["star", "#EADDB8"],
      ["sage", "#627A53"],
      ["snow", "#B6CDDA"],
    ),
    motifs: [
      motif("ancient bristlecone pines twisting beneath the Milky Way", "leaf", 1, 0.38, 0.56, 0.34, 0.58),
      motif(
        "a living tree measuring time against a star-filled desert sky",
        "ring",
        2,
        0.72,
        0.27,
        0.24,
        0.24,
      ),
      motif(
        "isolated range, limestone caverns, alpine lakes, and dry basin",
        "horizon",
        3,
        0.61,
        0.82,
        0.68,
        0.2,
      ),
    ],
    relationship:
      "The solitary tree stands against one star ring while a dry-basin horizon holds the lower field.",
    edgeStrategy:
      "The basin crosses bottom and right, the tree exits left-bottom, and night surrounds the star ring.",
  }),
  defineLandscapeArtProfile({
    slug: "great-sand-dunes",
    sourceCue: "wind-rippled dunes rising before snowbound Sangre de Cristo peaks",
    primaryStyleId: "thread-painted-embroidery",
    palette: palette(
      ["cobalt", "#32568A"],
      ["sand", "#D1A14E"],
      ["snow", "#EEEBDD"],
      ["grass", "#667A45"],
      ["violet", "#6F557A"],
    ),
    motifs: [
      motif(
        "wind-rippled dunes rising before snowbound Sangre de Cristo peaks",
        "stripe",
        1,
        0.48,
        0.58,
        0.8,
        0.38,
      ),
      motif("tiny footprints crossing a mountain made of moving sand", "ribbon", 4, 0.28, 0.71, 0.26, 0.16),
      motif(
        "dune field, seasonal creek, grassland, and abrupt alpine wall",
        "triangle",
        2,
        0.7,
        0.39,
        0.4,
        0.44,
      ),
    ],
    relationship:
      "One dune field sweeps toward an abrupt snowy wall while a tiny broad path crosses the sand.",
    edgeStrategy: "Dunes reach both sides and bottom; cobalt sky remains open above the alpine wall.",
  }),
  defineLandscapeArtProfile({
    slug: "great-smoky-mountains",
    sourceCue: "blue ridges dissolving through mist above a flame-azalea forest",
    primaryStyleId: "plein-air-broken-color",
    palette: palette(
      ["mist", "#D9D8CA"],
      ["ridge", "#4D6884"],
      ["forest", "#3F6447"],
      ["azalea", "#C7613B"],
      ["violet", "#6E5A79"],
    ),
    motifs: [
      motif(
        "blue ridges dissolving through mist above a flame-azalea forest",
        "horizon",
        1,
        0.52,
        0.48,
        0.82,
        0.4,
      ),
      motif(
        "successive mountain silhouettes breathing into one another",
        "stripe",
        4,
        0.37,
        0.66,
        0.62,
        0.22,
      ),
      motif("layered Appalachian ridges, coves, streams, and old forest", "leaf", 3, 0.72, 0.78, 0.24, 0.28),
    ],
    relationship:
      "One blue ridge recedes behind a violet layer while a single azalea-forest form holds the foreground.",
    edgeStrategy: "Layered ridges cross both sides, forest reaches bottom, and mist stays open at top.",
  }),
];
