import { defineLandscapeArtProfile, motif, palette } from "./code-native-landscape-profile";

export const nationalParkLandscapeProfiles02 = [
  defineLandscapeArtProfile({
    slug: "carlsbad-caverns",
    sourceCue: "the Big Room's immense mineral columns descending into darkness",
    primaryStyleId: "scratchboard-nocturne",
    palette: palette(["cave", "#15171C"], ["calcite", "#D6C49D"], ["copper", "#A8663F"], ["dusk", "#3D4E76"]),
    motifs: [
      motif(
        "the Big Room's immense mineral columns descending into darkness",
        "corner",
        1,
        0.48,
        0.55,
        0.68,
        0.7,
      ),
      motif("a spiral of bats rising from the natural entrance at dusk", "bat", 3, 0.72, 0.27, 0.24, 0.2),
      motif(
        "subterranean chambers, flowstone curtains, and branching passages",
        "shell",
        2,
        0.3,
        0.79,
        0.48,
        0.24,
      ),
    ],
    relationship: "One mineral chamber descends behind a rising bat silhouette and a single flowstone shelf.",
    edgeStrategy: "The chamber reaches left, right, and bottom; the dusk opening interrupts the top field.",
  }),
  defineLandscapeArtProfile({
    slug: "channel-islands",
    sourceCue: "sea cliffs, kelp forest, and an island fox above clear Pacific water",
    primaryStyleId: "matte-gouache-editorial",
    palette: palette(
      ["Pacific", "#2C7090"],
      ["cliff", "#C79B67"],
      ["kelp", "#385F45"],
      ["fox", "#B85F38"],
      ["fog", "#E9E2CF"],
    ),
    motifs: [
      motif(
        "sea cliffs, kelp forest, and an island fox above clear Pacific water",
        "horizon",
        1,
        0.48,
        0.52,
        0.8,
        0.42,
      ),
      motif("five islands held apart and connected by ocean", "oval", 4, 0.72, 0.29, 0.22, 0.18),
      motif("offshore ridges, coves, arches, and kelp channels", "ribbon", 2, 0.38, 0.78, 0.62, 0.22),
    ],
    relationship: "The cliff-and-fox mass overlooks one island form while a kelp channel sweeps below.",
    edgeStrategy:
      "The channel crosses the lower sides, the cliff exits left, and Pacific blue stays open above.",
  }),
  defineLandscapeArtProfile({
    slug: "congaree",
    sourceCue: "a flooded old-growth forest mirrored in blackwater",
    primaryStyleId: "woven-tapestry-field",
    palette: palette(
      ["blackwater", "#1F3030"],
      ["cypress", "#6B4934"],
      ["moss", "#526D3F"],
      ["amber", "#C29242"],
      ["mist", "#D7D8C8"],
    ),
    motifs: [
      motif("a flooded old-growth forest mirrored in blackwater", "block", 1, 0.34, 0.48, 0.3, 0.62),
      motif("towering bald cypress knees becoming a cathedral aisle", "triangle", 3, 0.7, 0.51, 0.32, 0.5),
      motif("floodplain channels, root forms, and layered hardwood canopy", "ribbon", 2, 0.5, 0.8, 0.78, 0.2),
    ],
    relationship: "Two broad cypress forms define an aisle above one continuous blackwater channel.",
    edgeStrategy:
      "Blackwater crosses the bottom and both sides while the mist field opens between the trees.",
  }),
  defineLandscapeArtProfile({
    slug: "crater-lake",
    sourceCue: "Wizard Island inside an impossibly blue caldera under snow",
    primaryStyleId: "cut-paper-strata",
    palette: palette(
      ["snow", "#EDF0E6"],
      ["lake", "#164E9A"],
      ["basalt", "#343947"],
      ["pine", "#2E5948"],
      ["dusk", "#6B568B"],
    ),
    motifs: [
      motif("Wizard Island inside an impossibly blue caldera under snow", "ring", 1, 0.5, 0.54, 0.62, 0.62),
      motif("a perfect dark-blue circle held by a broken volcanic rim", "cone", 2, 0.5, 0.57, 0.22, 0.3),
      motif("steep caldera walls, island cone, and radial snowfields", "stripe", 3, 0.63, 0.81, 0.62, 0.2),
    ],
    relationship: "A single island cone interrupts the blue caldera ring above one dark volcanic shelf.",
    edgeStrategy:
      "The shelf crosses bottom and right while the snowy ground remains open across top and left.",
  }),
  defineLandscapeArtProfile({
    slug: "cuyahoga-valley",
    sourceCue:
      "Brandywine Falls' tall sixty-foot bridal-veil cascade dropping over a hard Berea Sandstone cap and Bedford and Cleveland shale into a narrow deciduous gorge",
    primaryStyleId: "cyanotype-field-study",
    palette: palette(
      ["Prussian", "#143E78"],
      ["water", "#E8EEE2"],
      ["shale", "#9A674A"],
      ["forest", "#4E764B"],
      ["leaf", "#C49B3A"],
    ),
    motifs: [
      motif(
        "Brandywine Falls' tall sixty-foot bridal-veil cascade dropping over a hard Berea Sandstone cap and Bedford and Cleveland shale into a narrow deciduous gorge",
        "stripe",
        1,
        0.48,
        0.49,
        0.24,
        0.68,
      ),
      motif("a towpath and river reclaiming a once-industrial valley", "ribbon", 4, 0.7, 0.7, 0.36, 0.38),
      motif(
        "a high vertical waterfall lip, long white bridal-veil drop, thin layered shale ledges, and a narrow wooded ravine",
        "corner",
        2,
        0.36,
        0.7,
        0.56,
        0.46,
      ),
    ],
    relationship:
      "The white vertical fall clears one shale corner before joining a single wooded river path.",
    edgeStrategy: "The ravine and river exit bottom and sides while Prussian sky-water remains open above.",
  }),
  defineLandscapeArtProfile({
    slug: "death-valley",
    sourceCue: "Mesquite dunes and salt polygons beneath a violet mountain dusk",
    primaryStyleId: "fresco-mineral-pigment",
    palette: palette(
      ["dusk", "#665479"],
      ["salt", "#E9DFCA"],
      ["sand", "#D4A14E"],
      ["bloom", "#B5525E"],
      ["night", "#283552"],
    ),
    motifs: [
      motif(
        "Mesquite dunes and salt polygons beneath a violet mountain dusk",
        "stripe",
        2,
        0.48,
        0.58,
        0.84,
        0.38,
      ),
      motif("one resilient desert bloom in the lowest basin", "leaf", 3, 0.7, 0.7, 0.2, 0.24),
      motif(
        "salt flats, alluvial fans, dunes, and basin-range horizons",
        "horizon",
        1,
        0.43,
        0.82,
        0.78,
        0.2,
      ),
    ],
    relationship: "One desert bloom rises between a broad dune band and the pale lowest-basin horizon.",
    edgeStrategy: "Dune and basin forms cross all lower edges while violet dusk remains open above.",
  }),
  defineLandscapeArtProfile({
    slug: "denali",
    sourceCue: "Denali rising above braided tundra rivers and autumn taiga",
    primaryStyleId: "charcoal-pastel-weather",
    palette: palette(
      ["weather", "#4B5260"],
      ["snow", "#ECE9DC"],
      ["tundra", "#A9573F"],
      ["river", "#5B91A4"],
      ["willow", "#C49A3F"],
    ),
    motifs: [
      motif(
        "Denali rising above braided tundra rivers and autumn taiga",
        "triangle",
        1,
        0.53,
        0.43,
        0.62,
        0.62,
      ),
      motif("a small caribou beneath overwhelming white scale", "caribou", 2, 0.25, 0.73, 0.24, 0.18),
      motif(
        "Alaska Range, glacial valleys, braided rivers, and open tundra",
        "ribbon",
        3,
        0.6,
        0.81,
        0.66,
        0.22,
      ),
    ],
    relationship:
      "The immense white peak towers over one small caribou while a braided river carries through tundra.",
    edgeStrategy:
      "Tundra and river reach the lower sides; weather gray remains open around the mountain summit.",
  }),
  defineLandscapeArtProfile({
    slug: "dry-tortugas",
    sourceCue: "Fort Jefferson floating in turquoise water beneath circling frigatebirds",
    primaryStyleId: "screenprint-night",
    palette: palette(
      ["sea", "#197F91"],
      ["fort", "#A24B39"],
      ["sand", "#E2C987"],
      ["night", "#1D2944"],
      ["bird", "#E9E6D8"],
    ),
    motifs: [
      motif(
        "Fort Jefferson floating in turquoise water beneath circling frigatebirds",
        "block",
        1,
        0.47,
        0.55,
        0.48,
        0.34,
      ),
      motif("one brick-red hexagon isolated by luminous sea", "hexagon", 1, 0.73, 0.3, 0.24, 0.22),
      motif("tiny coral islands, reef shelf, and open Gulf horizon", "oval", 2, 0.35, 0.8, 0.58, 0.2),
    ],
    relationship:
      "One brick fort mass and its clear hexagonal plan float above a single coral shelf in open sea.",
    edgeStrategy:
      "Sea reaches every edge, the reef shelf exits left and bottom, and open water separates the fort forms.",
  }),
  defineLandscapeArtProfile({
    slug: "everglades",
    sourceCue: "an alligator gliding through sawgrass under a roseate sky",
    primaryStyleId: "mosaic-tesserae-field",
    palette: palette(
      ["sky", "#C97978"],
      ["alligator", "#36583D"],
      ["water", "#4B746B"],
      ["sawgrass", "#8B9A4E"],
      ["egret", "#EEE8D7"],
    ),
    motifs: [
      motif(
        "an alligator gliding through sawgrass under a roseate sky",
        "alligator",
        1,
        0.43,
        0.56,
        0.5,
        0.24,
      ),
      motif("a river of grass moving too slowly to see", "ribbon", 2, 0.59, 0.73, 0.64, 0.24),
      motif("shallow sheet flow, mangrove channels, and cypress domes", "oval", 3, 0.72, 0.34, 0.22, 0.24),
    ],
    relationship: "The alligator silhouette crosses one slow water ribbon beneath a single sawgrass dome.",
    edgeStrategy: "Water and grass bleed through the lower sides while roseate sky remains open at top.",
  }),
];
