import { defineLandscapeArtProfile, motif, palette } from "./code-native-landscape-profile";

export const nationalParkLandscapeProfiles04 = [
  defineLandscapeArtProfile({
    slug: "guadalupe-mountains",
    sourceCue:
      "El Capitan's connected limestone reef escarpment forming a prow-like triangular sloping profile above Chihuahuan Desert flats under migrating clouds",
    primaryStyleId: "relief-blockprint",
    palette: palette(
      ["sky", "#506B83"],
      ["limestone", "#D8C69F"],
      ["desert", "#A95E3F"],
      ["juniper", "#47644A"],
    ),
    motifs: [
      motif(
        "El Capitan's connected limestone reef escarpment forming a prow-like triangular sloping profile above Chihuahuan Desert flats under migrating clouds",
        "triangle",
        1,
        0.56,
        0.46,
        0.66,
        0.56,
      ),
      motif(
        "the fossil reef's southern prow rising continuously from the basin",
        "stripe",
        2,
        0.37,
        0.66,
        0.48,
        0.2,
      ),
      motif(
        "connected reef escarpment, desert flats, canyons, and high forest",
        "horizon",
        3,
        0.57,
        0.82,
        0.78,
        0.2,
      ),
    ],
    relationship:
      "The connected limestone prow rises above one desert band and a continuous high-forest horizon.",
    edgeStrategy: "Desert flats cross both lower sides while blue sky remains open around the sloping prow.",
  }),
  defineLandscapeArtProfile({
    slug: "haleakala",
    sourceCue: "silversword plants inside the vast volcanic summit crater at sunrise",
    primaryStyleId: "stained-glass-field",
    palette: palette(
      ["violet", "#5D4A75"],
      ["cinder", "#A94937"],
      ["silver", "#B9C0BD"],
      ["sun", "#E2AD42"],
      ["cloud", "#EEE8D9"],
    ),
    motifs: [
      motif(
        "silversword plants inside the vast volcanic summit crater at sunrise",
        "ring",
        1,
        0.48,
        0.58,
        0.62,
        0.56,
      ),
      motif("the first sun spilling above a sea of clouds", "disk", 3, 0.73, 0.23, 0.2, 0.2),
      motif(
        "shield-volcano summit basin, cinder cones, cloud forest, and coast",
        "cone",
        2,
        0.29,
        0.73,
        0.3,
        0.32,
      ),
    ],
    relationship: "The sunrise clears a broad crater ring as one cinder cone anchors the summit basin.",
    edgeStrategy: "The crater reaches bottom and left while cloud-white ground opens at top and right.",
  }),
  defineLandscapeArtProfile({
    slug: "hawaii-volcanoes",
    sourceCue: "orange lava meeting black land beneath a rainforest edge",
    primaryStyleId: "monoprint-ink-wash",
    palette: palette(
      ["basalt", "#17191B"],
      ["lava", "#D9552C"],
      ["fern", "#3E704A"],
      ["sulfur", "#D6B13B"],
      ["night", "#24365A"],
    ),
    motifs: [
      motif("orange lava meeting black land beneath a rainforest edge", "ribbon", 1, 0.51, 0.62, 0.72, 0.26),
      motif("new earth glowing under a field of stars", "disk", 3, 0.7, 0.28, 0.2, 0.2),
      motif(
        "active caldera, lava flows, rift zones, rainforest, and sea cliff",
        "horizon",
        2,
        0.4,
        0.81,
        0.68,
        0.2,
      ),
    ],
    relationship:
      "One lava river cuts the basalt field beneath a sulfur light and a consolidated rainforest rim.",
    edgeStrategy: "Lava and basalt reach both lower sides while night remains open around the upper light.",
  }),
  defineLandscapeArtProfile({
    slug: "hot-springs",
    sourceCue:
      "the real brick and stucco Bathhouse Row streetscape fronting a dry formal Central Avenue promenade, with wooded Hot Springs Mountain behind",
    primaryStyleId: "contour-atlas-ink",
    palette: palette(
      ["steam", "#E7E3D4"],
      ["brick", "#9A4F40"],
      ["tile", "#4E7591"],
      ["forest", "#3C6747"],
      ["brass", "#C49A42"],
    ),
    motifs: [
      motif(
        "the real brick and stucco Bathhouse Row streetscape fronting a dry formal Central Avenue promenade, with wooded Hot Springs Mountain behind",
        "block",
        1,
        0.44,
        0.55,
        0.56,
        0.42,
      ),
      motif(
        "subtle geothermal warmth and one faint veil of steam among trees high on the slope",
        "ribbon",
        4,
        0.7,
        0.31,
        0.24,
        0.3,
      ),
      motif(
        "dry formal promenade, capped thermal-spring infrastructure, landscaped urban streetscape, and wooded Ouachita slope",
        "horizon",
        3,
        0.55,
        0.82,
        0.82,
        0.2,
      ),
    ],
    relationship:
      "One brick streetscape fronts the dry promenade while a restrained steam path rises into the wooded slope.",
    edgeStrategy: "The promenade and slope reach both lower edges while pale steam ground stays open above.",
  }),
  defineLandscapeArtProfile({
    slug: "indiana-dunes",
    sourceCue: "marram grass bending above Lake Michigan dunes at sunset",
    primaryStyleId: "mineral-line-engraving",
    palette: palette(
      ["lake", "#3F7392"],
      ["dune", "#D6AD62"],
      ["marram", "#637A49"],
      ["sunset", "#D9785D"],
      ["steel", "#666D72"],
    ),
    motifs: [
      motif("marram grass bending above Lake Michigan dunes at sunset", "leaf", 2, 0.31, 0.59, 0.3, 0.5),
      motif(
        "wild shoreline holding its ground beside an industrial horizon",
        "stripe",
        4,
        0.68,
        0.44,
        0.48,
        0.2,
      ),
      motif(
        "beach ridges, dunes, wetlands, oak savanna, and great lake",
        "horizon",
        1,
        0.53,
        0.81,
        0.82,
        0.22,
      ),
    ],
    relationship: "One marram form bends over the dune-and-lake horizon opposite a restrained steel band.",
    edgeStrategy: "Lake and dune cross the lower sides while sunset color remains open above the grass.",
  }),
  defineLandscapeArtProfile({
    slug: "isle-royale",
    sourceCue: "a moose wading between boreal islands in cold Lake Superior dawn",
    primaryStyleId: "aquatint-atmosphere",
    palette: palette(
      ["fog", "#D5D8D0"],
      ["Superior", "#416D86"],
      ["spruce", "#345A47"],
      ["moose", "#6C4B36"],
      ["granite", "#777A77"],
    ),
    motifs: [
      motif(
        "a moose wading between boreal islands in cold Lake Superior dawn",
        "moose",
        3,
        0.37,
        0.57,
        0.32,
        0.26,
      ),
      motif("one remote ridge surrounded by endless freshwater", "oval", 2, 0.7, 0.44, 0.34, 0.22),
      motif(
        "long island spine, rock coves, inland lakes, and archipelago",
        "horizon",
        1,
        0.53,
        0.81,
        0.84,
        0.22,
      ),
    ],
    relationship:
      "The moose silhouette wades before one remote island while the long freshwater spine anchors the dawn.",
    edgeStrategy: "Water and island spine cross the lower sides; cold fog remains open across the top.",
  }),
  defineLandscapeArtProfile({
    slug: "joshua-tree",
    sourceCue: "Joshua trees and rounded boulders beneath a violet desert sky",
    primaryStyleId: "scratchboard-nocturne",
    palette: palette(
      ["night", "#2A2145"],
      ["tree", "#3F4E31"],
      ["sand", "#CFA35E"],
      ["rose", "#B96768"],
      ["moon", "#E9DFC6"],
    ),
    motifs: [
      motif(
        "Joshua trees and rounded boulders beneath a violet desert sky",
        "leaf",
        1,
        0.34,
        0.54,
        0.34,
        0.58,
      ),
      motif("branching silhouettes gesturing toward the stars", "disk", 4, 0.73, 0.25, 0.19, 0.19),
      motif(
        "Mojave high desert, Colorado Desert, granite piles, and washes",
        "oval",
        2,
        0.59,
        0.82,
        0.7,
        0.2,
      ),
    ],
    relationship:
      "One branching Joshua tree gestures toward the moon above a consolidated boulder-and-wash shelf.",
    edgeStrategy: "The desert shelf reaches both lower sides while violet sky opens around tree and moon.",
  }),
  defineLandscapeArtProfile({
    slug: "katmai",
    sourceCue:
      "a brown bear fishing from the broad low roughly six-foot horizontal lip of Brooks Falls as sockeye salmon leap",
    primaryStyleId: "matte-gouache-editorial",
    palette: palette(
      ["river", "#38798B"],
      ["bear", "#70503B"],
      ["salmon", "#C85A48"],
      ["spruce", "#426247"],
      ["cloud", "#D4D8CF"],
    ),
    motifs: [
      motif(
        "a brown bear fishing from the broad low roughly six-foot horizontal lip of Brooks Falls as sockeye salmon leap",
        "bear",
        1,
        0.38,
        0.49,
        0.36,
        0.34,
      ),
      motif("wild abundance gathering along one long river ledge", "fish", 2, 0.68, 0.61, 0.3, 0.2),
      motif(
        "forested Brooks River and lake watershed, low natural dam, gravel banks, and spruce",
        "stripe",
        3,
        0.53,
        0.81,
        0.82,
        0.2,
      ),
    ],
    relationship:
      "The bear form holds the low river ledge opposite one salmon silhouette above a spruce bank.",
    edgeStrategy: "River ledge and spruce bank cross the lower edges while cloud gray remains open above.",
  }),
  defineLandscapeArtProfile({
    slug: "kenai-fjords",
    sourceCue: "ice flowing from Harding Icefield into a whale-filled fjord",
    primaryStyleId: "woven-tapestry-field",
    palette: palette(
      ["deep water", "#183F62"],
      ["ice", "#8ED1DA"],
      ["foam", "#EDF0E5"],
      ["rock", "#626B72"],
      ["kelp", "#45664E"],
    ),
    motifs: [
      motif(
        "ice flowing from Harding Icefield into a whale-filled fjord",
        "stripe",
        1,
        0.48,
        0.45,
        0.7,
        0.44,
      ),
      motif("blue crevasses becoming ocean currents", "ribbon", 2, 0.72, 0.67, 0.28, 0.2),
      motif(
        "icefield plateau, outlet glaciers, fjords, islands, and coast",
        "ribbon",
        3,
        0.39,
        0.81,
        0.64,
        0.2,
      ),
    ],
    relationship:
      "One broad ice flow descends toward a whale silhouette and continues as a dark fjord current.",
    edgeStrategy: "Fjord and current reach both lower sides while the pale ice field opens toward the top.",
  }),
];
