import { defineNationalPark } from "./national-park-record";

export const nationalParksGrandTetonThroughMountRainier = [
  defineNationalPark({
    slug: "grand-teton",
    siteCode: "grte",
    officialName: "Grand Teton National Park",
    shortName: "Grand Teton",
    locationLabel: "Wyoming",
    signature: "the Teton skyline reflected in still Snake River water",
    symbol: "jagged peaks rising without foothills from a wide sage valley",
    terrain: "fault-block range, braided river, moraine lakes, and sage flats",
    palette: ["granite blue", "sage", "snow", "willow gold", "dawn rose"],
    styles: ["luminous-ligne-claire", "wood-marquetry-landscape", "plein-air-broken-color"],
  }),
  defineNationalPark({
    slug: "great-basin",
    siteCode: "grba",
    officialName: "Great Basin National Park",
    shortName: "Great Basin",
    locationLabel: "Nevada",
    signature: "ancient bristlecone pines twisting beneath the Milky Way",
    symbol: "a living tree measuring time against a star-filled desert sky",
    terrain: "isolated range, limestone caverns, alpine lakes, and dry basin",
    palette: ["night indigo", "weathered wood", "star cream", "sage", "snow blue"],
    styles: ["pixel-cluster-landscape", "scratchboard-nocturne", "mineral-line-engraving"],
  }),
  defineNationalPark({
    slug: "great-sand-dunes",
    siteCode: "grsa",
    officialName: "Great Sand Dunes National Park",
    shortName: "Great Sand Dunes",
    locationLabel: "Colorado",
    signature: "wind-rippled dunes rising before snowbound Sangre de Cristo peaks",
    symbol: "tiny footprints crossing a mountain made of moving sand",
    terrain: "dune field, seasonal creek, grassland, and abrupt alpine wall",
    palette: ["sand gold", "cobalt", "snow white", "grass green", "violet shadow"],
    styles: ["thread-painted-embroidery", "charcoal-pastel-weather", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "great-smoky-mountains",
    siteCode: "grsm",
    officialName: "Great Smoky Mountains National Park",
    shortName: "Great Smoky Mountains",
    locationLabel: "North Carolina and Tennessee",
    signature: "blue ridges dissolving through mist above a flame-azalea forest",
    symbol: "successive mountain silhouettes breathing into one another",
    terrain: "layered Appalachian ridges, coves, streams, and old forest",
    palette: ["smoke blue", "forest green", "azalea orange", "mist", "violet"],
    styles: ["plein-air-broken-color", "woven-tapestry-field", "aquatint-atmosphere"],
  }),
  defineNationalPark({
    slug: "guadalupe-mountains",
    siteCode: "gumo",
    officialName: "Guadalupe Mountains National Park",
    shortName: "Guadalupe Mountains",
    locationLabel: "Texas",
    signature:
      "El Capitan's connected limestone reef escarpment forming a prow-like triangular sloping profile above Chihuahuan Desert flats under migrating clouds",
    symbol: "the fossil reef's southern prow rising continuously from the basin",
    terrain: "connected reef escarpment, desert flats, canyons, and high forest",
    palette: ["limestone cream", "desert rust", "juniper green", "storm blue"],
    styles: ["relief-blockprint", "fresco-mineral-pigment", "mineral-line-engraving"],
    excludedMotifs: [
      "isolated flat-topped butte or mesa",
      "detached Monument Valley monolith",
      "Devils Tower-like vertical pillar",
    ],
  }),
  defineNationalPark({
    slug: "haleakala",
    siteCode: "hale",
    officialName: "Haleakalā National Park",
    shortName: "Haleakalā",
    locationLabel: "Hawaii",
    signature: "silversword plants inside the vast volcanic summit crater at sunrise",
    symbol: "the first sun spilling above a sea of clouds",
    terrain: "shield-volcano summit basin, cinder cones, cloud forest, and coast",
    palette: ["cinder red", "silver", "cloud white", "sun gold", "violet"],
    styles: ["stained-glass-field", "watercolor-naturalist-study", "cut-paper-strata"],
  }),
  defineNationalPark({
    slug: "hawaii-volcanoes",
    siteCode: "havo",
    officialName: "Hawai'i Volcanoes National Park",
    shortName: "Hawai‘i Volcanoes",
    locationLabel: "Hawaii",
    signature: "orange lava meeting black land beneath a rainforest edge",
    symbol: "new earth glowing under a field of stars",
    terrain: "active caldera, lava flows, rift zones, rainforest, and sea cliff",
    palette: ["lava orange", "basalt black", "fern green", "sulfur yellow", "night blue"],
    styles: ["monoprint-ink-wash", "mosaic-tesserae-field", "screenprint-night"],
    aliases: ["Hawaiʻi Volcanoes National Park"],
    excludedMotifs: [
      "inset paper margin or rough rectangular paint border",
      "unpainted paper at the image edges",
    ],
  }),
  defineNationalPark({
    slug: "hot-springs",
    siteCode: "hosp",
    officialName: "Hot Springs National Park",
    shortName: "Hot Springs",
    locationLabel: "Arkansas",
    signature:
      "the real brick and stucco Bathhouse Row streetscape fronting a dry formal Central Avenue promenade, with wooded Hot Springs Mountain behind",
    symbol: "subtle geothermal warmth and one faint veil of steam among trees high on the slope",
    terrain:
      "dry formal promenade, capped thermal-spring infrastructure, landscaped urban streetscape, and wooded Ouachita slope",
    palette: ["steam white", "tile blue", "brick", "forest green", "brass gold"],
    styles: ["contour-atlas-ink", "risograph-overprint", "aquatint-atmosphere"],
    excludedMotifs: [
      "open-air natural bathing pool",
      "rocky wilderness creek beside Bathhouse Row",
      "European palace spa or invented bathhouse architecture",
      "river, visible creek, or open water beside Bathhouse Row",
      "geyser, erupting vent, or multiple steam plumes",
    ],
  }),
  defineNationalPark({
    slug: "indiana-dunes",
    siteCode: "indu",
    officialName: "Indiana Dunes National Park",
    shortName: "Indiana Dunes",
    locationLabel: "Indiana",
    signature: "marram grass bending above Lake Michigan dunes at sunset",
    symbol: "wild shoreline holding its ground beside an industrial horizon",
    terrain: "beach ridges, dunes, wetlands, oak savanna, and great lake",
    palette: ["lake blue", "dune gold", "marram green", "sunset coral", "steel gray"],
    styles: ["mineral-line-engraving", "cyanotype-field-study", "plein-air-broken-color"],
  }),
  defineNationalPark({
    slug: "isle-royale",
    siteCode: "isro",
    officialName: "Isle Royale National Park",
    shortName: "Isle Royale",
    locationLabel: "Michigan",
    signature: "a moose wading between boreal islands in cold Lake Superior dawn",
    symbol: "one remote ridge surrounded by endless freshwater",
    terrain: "long island spine, rock coves, inland lakes, and archipelago",
    palette: ["Superior blue", "spruce", "granite", "moose brown", "fog white"],
    styles: ["aquatint-atmosphere", "wood-marquetry-landscape", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "joshua-tree",
    siteCode: "jotr",
    officialName: "Joshua Tree National Park",
    shortName: "Joshua Tree",
    locationLabel: "California",
    signature: "Joshua trees and rounded boulders beneath a violet desert sky",
    symbol: "branching silhouettes gesturing toward the stars",
    terrain: "Mojave high desert, Colorado Desert, granite piles, and washes",
    palette: ["violet", "sand", "olive", "rose", "night navy"],
    styles: ["scratchboard-nocturne", "pixel-cluster-landscape", "relief-blockprint"],
  }),
  defineNationalPark({
    slug: "katmai",
    siteCode: "katm",
    officialName: "Katmai National Park",
    shortName: "Katmai",
    locationLabel: "Alaska",
    signature:
      "a brown bear fishing from the broad low roughly six-foot horizontal lip of Brooks Falls as sockeye salmon leap",
    symbol: "wild abundance gathering along one long river ledge",
    terrain: "forested Brooks River and lake watershed, low natural dam, gravel banks, and spruce",
    palette: ["salmon red", "river teal", "bear umber", "spruce", "cloud gray"],
    styles: ["matte-gouache-editorial", "watercolor-naturalist-study", "mosaic-tesserae-field"],
    excludedMotifs: [
      "tall multi-tier waterfall or mountain cascade",
      "ocean, sea coast, or fjord behind the falls",
      "isolated bear below a high vertical waterfall",
    ],
  }),
  defineNationalPark({
    slug: "kenai-fjords",
    siteCode: "kefj",
    officialName: "Kenai Fjords National Park",
    shortName: "Kenai Fjords",
    locationLabel: "Alaska",
    signature: "ice flowing from Harding Icefield into a whale-filled fjord",
    symbol: "blue crevasses becoming ocean currents",
    terrain: "icefield plateau, outlet glaciers, fjords, islands, and coast",
    palette: ["ice cyan", "deep navy", "rock gray", "foam white", "kelp green"],
    styles: ["woven-tapestry-field", "stained-glass-field", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "kings-canyon",
    siteCode: "seki",
    officialName: "Kings Canyon National Park",
    shortName: "Kings Canyon",
    locationLabel: "California",
    signature: "the South Fork Kings River beneath immense granite canyon walls",
    symbol: "a whitewater thread descending from high Sierra light",
    terrain: "deep glacial canyon, granite domes, river, and high basins",
    palette: ["granite silver", "river teal", "pine", "snow", "sun gold"],
    styles: ["cut-paper-strata", "mineral-line-engraving", "luminous-ligne-claire"],
  }),
  defineNationalPark({
    slug: "kobuk-valley",
    siteCode: "kova",
    officialName: "Kobuk Valley National Park",
    shortName: "Kobuk Valley",
    locationLabel: "Alaska",
    signature: "caribou crossing immense Arctic sand dunes under a low sun",
    symbol: "migration tracks writing one brief line across moving sand",
    terrain: "Great Kobuk dunes, broad river valley, tundra, and boreal forest",
    palette: ["sand gold", "tundra umber", "river blue", "lichen", "low-sun coral"],
    styles: ["cyanotype-field-study", "charcoal-pastel-weather", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "lake-clark",
    siteCode: "lacl",
    officialName: "Lake Clark National Park",
    shortName: "Lake Clark",
    locationLabel: "Alaska",
    signature: "turquoise Lake Clark below smoking volcanoes and red tundra",
    symbol: "salmon connecting ocean, river, bear, and mountain",
    terrain: "volcanic peaks, glacial lakes, braided rivers, tundra, and coast",
    palette: ["lake turquoise", "tundra crimson", "snow", "ash gray", "spruce"],
    styles: ["fresco-mineral-pigment", "watercolor-naturalist-study", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "lassen-volcanic",
    siteCode: "lavo",
    officialName: "Lassen Volcanic National Park",
    shortName: "Lassen Volcanic",
    locationLabel: "California",
    signature: "Lassen Peak above steaming hydrothermal pools and mountain lake",
    symbol: "four kinds of volcano gathered in one bright landscape",
    terrain: "volcanic dome, cinder cone, lava fields, meadows, and lakes",
    palette: ["sulfur yellow", "hydrothermal teal", "snow", "lava black", "pine"],
    styles: ["prismatic-geometric-symbolism", "ceramic-underglaze", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "mammoth-cave",
    siteCode: "maca",
    officialName: "Mammoth Cave National Park",
    shortName: "Mammoth Cave",
    locationLabel: "Kentucky",
    signature:
      "a historic lantern lighting one immense dry, broad limestone passage disappearing into darkness",
    symbol: "an unseen underground river connecting an endless maze",
    terrain:
      "vast horizontally layered passages, a Rotunda-like chamber, sinkholes, and restrained limestone detail",
    palette: ["cave black", "lantern amber", "limestone gray", "river blue", "forest green"],
    styles: ["ceramic-underglaze", "scratchboard-nocturne", "contour-atlas-ink"],
    excludedMotifs: [
      "daylight cave opening",
      "ornate stalactite or crystal grotto",
      "round fantasy caverns or dense speleothems",
    ],
  }),
  defineNationalPark({
    slug: "mesa-verde",
    siteCode: "meve",
    officialName: "Mesa Verde National Park",
    shortName: "Mesa Verde",
    locationLabel: "Colorado",
    signature: "Cliff Palace held beneath a great sandstone alcove",
    symbol: "warm windows and ladders nested inside protective stone",
    terrain: "mesa tops, branching canyons, cliff alcoves, and high-desert woodland",
    palette: ["sandstone", "adobe red", "juniper green", "shadow violet", "sky blue"],
    styles: ["wood-marquetry-landscape", "fresco-mineral-pigment", "mineral-line-engraving"],
  }),
  defineNationalPark({
    slug: "mount-rainier",
    siteCode: "mora",
    officialName: "Mount Rainier National Park",
    shortName: "Mount Rainier",
    locationLabel: "Washington",
    signature: "Mount Rainier above a meadow blazing with summer wildflowers",
    symbol: "a white volcanic dome gathering every river around it",
    terrain: "glaciated volcano, subalpine meadows, old forest, and radial valleys",
    palette: ["snow white", "sky blue", "meadow green", "lupine violet", "paintbrush red"],
    styles: ["luminous-ligne-claire", "plein-air-broken-color", "watercolor-naturalist-study"],
  }),
] as const;
