import { defineNationalPark } from "./national-park-record";

export const nationalParksAThroughG = [
  defineNationalPark({
    slug: "acadia",
    siteCode: "acad",
    officialName: "Acadia National Park",
    shortName: "Acadia",
    locationLabel: "Maine",
    signature: "dawn over Cadillac Mountain, granite ledges, spruce, and Atlantic islands",
    symbol: "the country's first light arriving over dark pines",
    terrain: "island-dotted coast and rounded glacial contours",
    palette: ["midnight navy", "granite violet", "spruce green", "coral dawn", "pale gold"],
    styles: ["pixel-cluster-landscape", "aquatint-atmosphere", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "arches",
    siteCode: "arch",
    officialName: "Arches National Park",
    shortName: "Arches",
    locationLabel: "Utah",
    signature: "Delicate Arch above red fins at blue hour",
    symbol: "a stone opening holding moon and sky",
    terrain: "eroded sandstone ribs and improbable spans",
    palette: ["rust red", "ochre", "indigo", "moon cream"],
    styles: ["thread-painted-embroidery", "relief-blockprint", "luminous-ligne-claire"],
  }),
  defineNationalPark({
    slug: "badlands",
    siteCode: "badl",
    officialName: "Badlands National Park",
    shortName: "Badlands",
    locationLabel: "South Dakota",
    signature: "striped pinnacles and mixed-grass prairie after a summer storm",
    symbol: "one bison crossing an enormous weathered amphitheater",
    terrain: "sharp erosion bands opening into rolling grassland",
    palette: ["warm ochre", "sage", "rose clay", "storm blue", "violet shadow"],
    styles: ["plein-air-broken-color", "fresco-mineral-pigment", "scratchboard-nocturne"],
  }),
  defineNationalPark({
    slug: "big-bend",
    siteCode: "bibe",
    officialName: "Big Bend National Park",
    shortName: "Big Bend",
    locationLabel: "Texas",
    signature: "the Rio Grande bending through Santa Elena Canyon beneath stars",
    symbol: "a turquoise river threading immense desert walls",
    terrain: "river curve, Chihuahuan Desert, and isolated mountain basin",
    palette: ["adobe red", "river teal", "moon cream", "cactus green", "black violet"],
    styles: ["relief-blockprint", "screenprint-night", "contour-atlas-ink"],
    excludedMotifs: [
      "inset paper margin or rough rectangular print border",
      "unprinted paper at the image edges",
    ],
  }),
  defineNationalPark({
    slug: "biscayne",
    siteCode: "bisc",
    officialName: "Biscayne National Park",
    shortName: "Biscayne",
    locationLabel: "Florida",
    signature: "a sea turtle gliding over coral gardens and seagrass",
    symbol: "sun shafts joining mangrove roots to a blue world below",
    terrain: "shallow reef shelves, keys, and tidal channels",
    palette: ["turquoise", "ultramarine", "coral", "lime", "amber"],
    styles: ["stained-glass-field", "watercolor-naturalist-study", "mosaic-tesserae-field"],
  }),
  defineNationalPark({
    slug: "black-canyon-gunnison",
    siteCode: "blca",
    officialName: "Black Canyon of the Gunnison National Park",
    shortName: "Black Canyon",
    locationLabel: "Colorado",
    signature: "a thin silver Gunnison River far below sheer dark walls",
    symbol: "one blade of dawn reaching an otherwise hidden depth",
    terrain: "narrow vertical gorge and striated Precambrian rock",
    palette: ["charcoal", "indigo", "silver gray", "ochre light"],
    styles: ["monoprint-ink-wash", "mineral-line-engraving", "aquatint-atmosphere"],
  }),
  defineNationalPark({
    slug: "bryce-canyon",
    siteCode: "brca",
    officialName: "Bryce Canyon National Park",
    shortName: "Bryce Canyon",
    locationLabel: "Utah",
    signature: "a sunrise amphitheater crowded with orange hoodoos",
    symbol: "stone figures catching light one by one",
    terrain: "scalloped rim and densely eroded columns",
    palette: ["persimmon", "salmon", "cream", "pine green", "cobalt shadow"],
    styles: ["contour-atlas-ink", "cut-paper-strata", "thread-painted-embroidery"],
  }),
  defineNationalPark({
    slug: "canyonlands",
    siteCode: "cany",
    officialName: "Canyonlands National Park",
    shortName: "Canyonlands",
    locationLabel: "Utah",
    signature: "Mesa Arch framing a maze of canyons at first light",
    symbol: "two rivers dividing an immense red-rock country",
    terrain: "nested mesas, needles, river corridors, and distant buttes",
    palette: ["burnished copper", "sandstone pink", "sage", "deep violet", "dawn gold"],
    styles: ["mineral-line-engraving", "luminous-ligne-claire", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "capitol-reef",
    siteCode: "care",
    officialName: "Capitol Reef National Park",
    shortName: "Capitol Reef",
    locationLabel: "Utah",
    signature: "the Waterpocket Fold rolling past pale domes and orchard trees",
    symbol: "a green fruit branch against folded desert stone",
    terrain: "long monocline, slot canyons, and reef-like cliffs",
    palette: ["apricot", "chalk white", "orchard green", "rust", "sky cyan"],
    styles: ["aquatint-atmosphere", "watercolor-naturalist-study", "cut-paper-strata"],
  }),
  defineNationalPark({
    slug: "carlsbad-caverns",
    siteCode: "cave",
    officialName: "Carlsbad Caverns National Park",
    shortName: "Carlsbad Caverns",
    locationLabel: "New Mexico",
    signature: "the Big Room's immense mineral columns descending into darkness",
    symbol: "a spiral of bats rising from the natural entrance at dusk",
    terrain: "subterranean chambers, flowstone curtains, and branching passages",
    palette: ["cave black", "calcite cream", "copper", "violet", "dusk blue"],
    styles: ["scratchboard-nocturne", "stained-glass-field", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "channel-islands",
    siteCode: "chis",
    officialName: "Channel Islands National Park",
    shortName: "Channel Islands",
    locationLabel: "California",
    signature: "sea cliffs, kelp forest, and an island fox above clear Pacific water",
    symbol: "five islands held apart and connected by ocean",
    terrain: "offshore ridges, coves, arches, and kelp channels",
    palette: ["Pacific blue", "kelp green", "sandstone", "fox rust", "fog white"],
    styles: ["matte-gouache-editorial", "watercolor-naturalist-study", "stained-glass-field"],
  }),
  defineNationalPark({
    slug: "congaree",
    siteCode: "cong",
    officialName: "Congaree National Park",
    shortName: "Congaree",
    locationLabel: "South Carolina",
    signature: "a flooded old-growth forest mirrored in blackwater",
    symbol: "towering bald cypress knees becoming a cathedral aisle",
    terrain: "floodplain channels, root forms, and layered hardwood canopy",
    palette: ["blackwater", "cypress brown", "moss green", "amber", "mist gray"],
    styles: ["woven-tapestry-field", "cyanotype-field-study", "monoprint-ink-wash"],
  }),
  defineNationalPark({
    slug: "crater-lake",
    siteCode: "crla",
    officialName: "Crater Lake National Park",
    shortName: "Crater Lake",
    locationLabel: "Oregon",
    signature: "Wizard Island inside an impossibly blue caldera under snow",
    symbol: "a perfect dark-blue circle held by a broken volcanic rim",
    terrain: "steep caldera walls, island cone, and radial snowfields",
    palette: ["ultramarine", "snow white", "basalt", "pine", "violet dusk"],
    styles: ["cut-paper-strata", "prismatic-geometric-symbolism", "aquatint-atmosphere"],
  }),
  defineNationalPark({
    slug: "cuyahoga-valley",
    siteCode: "cuva",
    officialName: "Cuyahoga Valley National Park",
    shortName: "Cuyahoga Valley",
    locationLabel: "Ohio",
    signature:
      "Brandywine Falls' tall sixty-foot bridal-veil cascade dropping over a hard Berea Sandstone cap and Bedford and Cleveland shale into a narrow deciduous gorge",
    symbol: "a towpath and river reclaiming a once-industrial valley",
    terrain:
      "a high vertical waterfall lip, long white bridal-veil drop, thin layered shale ledges, and a narrow wooded ravine",
    palette: ["Prussian blue", "leaf gold", "rust", "forest green", "mist white"],
    styles: ["cyanotype-field-study", "plein-air-broken-color", "wood-marquetry-landscape"],
    excludedMotifs: [
      "smokestacks directly behind Brandywine Falls",
      "factory buildings beside the waterfall",
      "one collapsed documentary vista combining distant sites",
      "low dam or weir",
      "broad low horizontal waterfall",
      "wide open river",
    ],
  }),
  defineNationalPark({
    slug: "death-valley",
    siteCode: "deva",
    officialName: "Death Valley National Park",
    shortName: "Death Valley",
    locationLabel: "California and Nevada",
    signature: "Mesquite dunes and salt polygons beneath a violet mountain dusk",
    symbol: "one resilient desert bloom in the lowest basin",
    terrain: "salt flats, alluvial fans, dunes, and basin-range horizons",
    palette: ["salt white", "sand gold", "rose", "violet", "night blue"],
    styles: ["fresco-mineral-pigment", "charcoal-pastel-weather", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "denali",
    siteCode: "dena",
    officialName: "Denali National Park",
    shortName: "Denali",
    locationLabel: "Alaska",
    signature: "Denali rising above braided tundra rivers and autumn taiga",
    symbol: "a small caribou beneath overwhelming white scale",
    terrain: "Alaska Range, glacial valleys, braided rivers, and open tundra",
    palette: ["snow white", "glacier blue", "tundra rust", "charcoal", "willow gold"],
    styles: ["charcoal-pastel-weather", "mineral-line-engraving", "woven-tapestry-field"],
  }),
  defineNationalPark({
    slug: "dry-tortugas",
    siteCode: "drto",
    officialName: "Dry Tortugas National Park",
    shortName: "Dry Tortugas",
    locationLabel: "Florida",
    signature: "Fort Jefferson floating in turquoise water beneath circling frigatebirds",
    symbol: "one brick-red hexagon isolated by luminous sea",
    terrain: "tiny coral islands, reef shelf, and open Gulf horizon",
    palette: ["turquoise", "brick red", "sand", "navy", "sun white"],
    styles: ["screenprint-night", "stained-glass-field", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "everglades",
    siteCode: "ever",
    officialName: "Everglades National Park",
    shortName: "Everglades",
    locationLabel: "Florida",
    signature: "an alligator gliding through sawgrass under a roseate sky",
    symbol: "a river of grass moving too slowly to see",
    terrain: "shallow sheet flow, mangrove channels, and cypress domes",
    palette: ["sawgrass green", "tea water", "rose", "egret white", "storm gray"],
    styles: ["mosaic-tesserae-field", "watercolor-naturalist-study", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "gates-of-the-arctic",
    siteCode: "gaar",
    officialName: "Gates of the Arctic National Park",
    shortName: "Gates of the Arctic",
    locationLabel: "Alaska",
    signature: "the Arrigetch peaks beyond a winding tundra river with no road in sight",
    symbol: "two mountains opening onto untouched northern distance",
    terrain: "Brooks Range valleys, wild rivers, tundra, and untracked passes",
    palette: ["tundra umber", "lichen gold", "river slate", "snow", "aurora green"],
    styles: ["fresco-mineral-pigment", "luminous-ligne-claire", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "gateway-arch",
    siteCode: "jeff",
    officialName: "Gateway Arch National Park",
    shortName: "Gateway Arch",
    locationLabel: "Missouri and Illinois",
    signature: "the stainless arc rising over the Mississippi at blue hour",
    symbol: "a single curve joining river, city, and western sky",
    terrain: "riverfront axis, broad bend, and urban horizon",
    palette: ["silver", "river blue", "brick", "indigo", "warm window gold"],
    styles: ["prismatic-geometric-symbolism", "risograph-overprint", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "glacier-bay",
    siteCode: "glba",
    officialName: "Glacier Bay National Park",
    shortName: "Glacier Bay",
    locationLabel: "Alaska",
    signature: "a tidewater glacier calving beyond a humpback whale's fluke",
    symbol: "ice withdrawing to reveal a living blue corridor",
    terrain: "deep fjords, tidewater ice, islands, and coastal mountains",
    palette: ["glacier cyan", "deep navy", "ice white", "granite", "kelp green"],
    styles: ["ceramic-underglaze", "stained-glass-field", "aquatint-atmosphere"],
  }),
  defineNationalPark({
    slug: "glacier",
    siteCode: "glac",
    officialName: "Glacier National Park",
    shortName: "Glacier",
    locationLabel: "Montana",
    signature: "Hidden Lake below sharp peaks with a mountain goat on the overlook",
    symbol: "the continental divide splitting weather and water",
    terrain: "glacial cirques, alpine lakes, serrated ridges, and cedar valleys",
    palette: ["alpine teal", "snow", "cedar green", "granite", "beargrass white"],
    styles: ["wood-marquetry-landscape", "watercolor-naturalist-study", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "grand-canyon",
    siteCode: "grca",
    officialName: "Grand Canyon National Park",
    shortName: "Grand Canyon",
    locationLabel: "Arizona",
    signature: "layer after layer of canyon opening around a distant Colorado River",
    symbol: "deep time written as bands of light and shadow",
    terrain: "terraced cliffs, side canyons, buttes, and river gorge",
    palette: ["canyon rust", "violet shadow", "cream", "river green", "sun gold"],
    styles: ["scratchboard-nocturne", "plein-air-broken-color", "mineral-line-engraving"],
  }),
] as const;
