import { defineNationalPark } from "./national-park-record";

export const nationalParksNThroughZ = [
  defineNationalPark({
    slug: "national-park-american-samoa",
    siteCode: "npsa",
    officialName: "National Park of American Samoa",
    shortName: "American Samoa",
    locationLabel: "American Samoa",
    signature: "a flying fox crossing a steep rainforest island above coral water",
    symbol: "mountain forest and reef joined by one tropical slope",
    terrain: "volcanic ridges, rainforest, village coast, and coral reef",
    palette: ["reef turquoise", "rainforest green", "lava black", "fruit red", "sun gold"],
    styles: ["pixel-cluster-landscape", "stained-glass-field", "woven-tapestry-field"],
  }),
  defineNationalPark({
    slug: "new-river-gorge",
    siteCode: "neri",
    officialName: "New River Gorge National Park and Preserve",
    shortName: "New River Gorge",
    locationLabel: "West Virginia",
    signature: "the New River Gorge Bridge spanning autumn forest and whitewater",
    symbol: "one steel arc connecting two ancient ridges",
    terrain: "deep Appalachian gorge, river rapids, cliffs, and forested plateaus",
    palette: ["river blue", "autumn rust", "forest green", "steel", "mist white"],
    styles: ["thread-painted-embroidery", "relief-blockprint", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "north-cascades",
    siteCode: "noca",
    officialName: "North Cascades National Park",
    shortName: "North Cascades",
    locationLabel: "Washington",
    signature: "jagged glacier peaks above a turquoise alpine lake",
    symbol: "a cascade of blue ice feeding forest and river",
    terrain: "serrated range, glaciers, deep valleys, lakes, and dense forest",
    palette: ["glacier cyan", "granite", "forest green", "snow", "alpine violet"],
    styles: ["plein-air-broken-color", "cut-paper-strata", "mineral-line-engraving"],
  }),
  defineNationalPark({
    slug: "olympic",
    siteCode: "olym",
    officialName: "Olympic National Park",
    shortName: "Olympic",
    locationLabel: "Washington",
    signature: "moss-draped rainforest opening onto wild sea stacks and snowy peaks",
    symbol: "three worlds meeting on one isolated peninsula",
    terrain: "temperate rainforest, glaciated mountains, river valleys, and Pacific coast",
    palette: ["moss green", "ocean blue", "cedar brown", "snow", "fog silver"],
    styles: ["relief-blockprint", "woven-tapestry-field", "aquatint-atmosphere"],
  }),
  defineNationalPark({
    slug: "petrified-forest",
    siteCode: "pefo",
    officialName: "Petrified Forest National Park",
    shortName: "Petrified Forest",
    locationLabel: "Arizona",
    signature: "rainbow petrified logs scattered across painted desert badlands",
    symbol: "tree rings transformed into quartz and deep time",
    terrain: "painted hills, broad mesas, grassland, and fossil wood fields",
    palette: ["quartz violet", "turquoise", "ochre", "rose clay", "cream"],
    styles: ["stained-glass-field", "mineral-line-engraving", "mosaic-tesserae-field"],
  }),
  defineNationalPark({
    slug: "pinnacles",
    siteCode: "pinn",
    officialName: "Pinnacles National Park",
    shortName: "Pinnacles",
    locationLabel: "California",
    signature: "a California condor soaring between volcanic spires at sunset",
    symbol: "wings returning above a landscape split from an ancient volcano",
    terrain: "rock pinnacles, talus caves, chaparral slopes, and oak valleys",
    palette: ["volcanic rust", "condor black", "sun gold", "chaparral green", "violet"],
    styles: ["monoprint-ink-wash", "watercolor-naturalist-study", "relief-blockprint"],
    excludedMotifs: [
      "inset paper margin or rough rectangular paint border",
      "unpainted paper at the image edges",
    ],
  }),
  defineNationalPark({
    slug: "redwood",
    siteCode: "redw",
    officialName: "Redwood National Park",
    shortName: "Redwood",
    locationLabel: "California",
    signature: "sunbeams descending through immense coast redwoods and fern",
    symbol: "one tiny person beneath trees older than memory",
    terrain: "tall forest, fog belt, river valleys, prairie, and rugged coast",
    palette: ["redwood umber", "fern green", "fog silver", "sun gold", "shadow teal"],
    styles: ["contour-atlas-ink", "wood-marquetry-landscape", "cyanotype-field-study"],
    aliases: ["Redwood National and State Parks"],
  }),
  defineNationalPark({
    slug: "rocky-mountain",
    siteCode: "romo",
    officialName: "Rocky Mountain National Park",
    shortName: "Rocky Mountain",
    locationLabel: "Colorado",
    signature: "elk crossing a golden alpine meadow beneath Longs Peak",
    symbol: "a trail rising from pine forest into open tundra sky",
    terrain: "continental divide, glacial valleys, alpine tundra, lakes, and forest",
    palette: ["tundra gold", "granite blue", "pine", "snow", "elk umber"],
    styles: ["mineral-line-engraving", "plein-air-broken-color", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "saguaro",
    siteCode: "sagu",
    officialName: "Saguaro National Park",
    shortName: "Saguaro",
    locationLabel: "Arizona",
    signature: "giant saguaros beneath a monsoon sunset and lightning",
    symbol: "upright cactus arms holding years of scarce rain",
    terrain: "Sonoran bajadas, rocky ranges, washes, and cactus forest",
    palette: ["cactus green", "sunset magenta", "ochre", "storm violet", "lightning cream"],
    styles: ["aquatint-atmosphere", "thread-painted-embroidery", "screenprint-night"],
  }),
  defineNationalPark({
    slug: "sequoia",
    siteCode: "seki",
    officialName: "Sequoia National Park",
    shortName: "Sequoia",
    locationLabel: "California",
    signature:
      "the living General Sherman sequoia, its extraordinarily massive fluted cinnamon trunk staying broad far upward and continuing visibly into an irregular high conifer crown of huge ascending limbs with fine scale-like evergreen sprays",
    symbol: "a sunlit forest path dwarfed by one ancient living conifer",
    terrain: "a giant sequoia grove backed by granite domes and the high Sierra",
    palette: ["sequoia cinnamon", "forest green", "sun gold", "granite", "sky blue"],
    styles: ["scratchboard-nocturne", "wood-marquetry-landscape", "woven-tapestry-field"],
    excludedMotifs: [
      "Half Dome or Yosemite Falls",
      "Yosemite Valley landmarks",
      "coastal redwood forest",
      "rounded broadleaf or deciduous foliage",
      "oak-like or lollipop crown",
      "a leafy canopy pasted onto a severed trunk",
    ],
  }),
  defineNationalPark({
    slug: "shenandoah",
    siteCode: "shen",
    officialName: "Shenandoah National Park",
    shortName: "Shenandoah",
    locationLabel: "Virginia",
    signature: "Blue Ridge layers seen from Skyline Drive through autumn leaves",
    symbol: "a long ridge road disappearing into morning mist",
    terrain: "parallel ridges, hollows, waterfalls, forest, and high meadows",
    palette: ["ridge blue", "maple red", "leaf gold", "forest green", "mist"],
    styles: ["matte-gouache-editorial", "plein-air-broken-color", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "theodore-roosevelt",
    siteCode: "thro",
    officialName: "Theodore Roosevelt National Park",
    shortName: "Theodore Roosevelt",
    locationLabel: "North Dakota",
    signature: "bison moving through Little Missouri badlands beneath a huge sky",
    symbol: "a winding river holding prairie and painted buttes together",
    terrain: "badland bluffs, grassland, river bends, and cottonwood bottoms",
    palette: ["prairie gold", "clay red", "sage", "river blue", "storm gray"],
    styles: ["woven-tapestry-field", "relief-blockprint", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "virgin-islands",
    siteCode: "viis",
    officialName: "Virgin Islands National Park",
    shortName: "Virgin Islands",
    locationLabel: "Virgin Islands",
    signature: "a green hillside descending into Trunk Bay's clear reef water",
    symbol: "a white-sand crescent holding sea turtles and coral",
    terrain: "steep island slopes, dry forest, bays, beaches, and reef",
    palette: ["Caribbean turquoise", "leaf green", "sand white", "coral", "deep blue"],
    styles: ["cut-paper-strata", "stained-glass-field", "watercolor-naturalist-study"],
  }),
  defineNationalPark({
    slug: "voyageurs",
    siteCode: "voya",
    officialName: "Voyageurs National Park",
    shortName: "Voyageurs",
    locationLabel: "Minnesota",
    signature: "a canoe threading pine islands beneath northern lights",
    symbol: "one paddle wake crossing a country made mostly of water",
    terrain: "interlocking lakes, rocky islands, boreal forest, and wetlands",
    palette: ["lake navy", "aurora green", "pine", "granite", "star white"],
    styles: ["cyanotype-field-study", "pixel-cluster-landscape", "screenprint-night"],
  }),
  defineNationalPark({
    slug: "white-sands",
    siteCode: "whsa",
    officialName: "White Sands National Park",
    shortName: "White Sands",
    locationLabel: "New Mexico",
    signature: "white gypsum dunes curving beneath a pink-blue twilight",
    symbol: "a lone soap-tree yucca holding still in luminous sand",
    terrain: "wave-like gypsum dunes, interdune flats, and mountain basin",
    palette: ["gypsum white", "twilight pink", "sky blue", "yucca green", "violet"],
    styles: ["fresco-mineral-pigment", "charcoal-pastel-weather", "luminous-ligne-claire"],
  }),
  defineNationalPark({
    slug: "wind-cave",
    siteCode: "wica",
    officialName: "Wind Cave National Park",
    shortName: "Wind Cave",
    locationLabel: "South Dakota",
    signature: "delicate honeycomb boxwork fins coating limestone walls below a sunlit bison prairie",
    symbol: "wind breathing between the visible grassland and hidden cave",
    terrain: "rolling prairie, ponderosa hills, dry cave passages, and thin calcite boxwork veins",
    palette: ["honey calcite", "prairie gold", "bison umber", "cave gray", "sky blue"],
    styles: ["prismatic-geometric-symbolism", "mineral-line-engraving", "contour-atlas-ink"],
    excludedMotifs: ["freestanding crystal blocks", "large gemstone clusters", "stalactite fantasy grotto"],
  }),
  defineNationalPark({
    slug: "wrangell-st-elias",
    siteCode: "wrst",
    officialName: "Wrangell-St. Elias National Park",
    shortName: "Wrangell–St. Elias",
    locationLabel: "Alaska",
    signature: "vast icefields flowing between volcanic peaks toward a tiny historic mill",
    symbol: "human scale almost disappearing inside the country's largest wild landscape",
    terrain: "volcanic range, immense glaciers, river valleys, tundra, and coast",
    palette: ["ice blue", "volcanic gray", "tundra rust", "snow", "copper"],
    styles: ["ceramic-underglaze", "aquatint-atmosphere", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "yellowstone",
    siteCode: "yell",
    officialName: "Yellowstone National Park",
    shortName: "Yellowstone",
    locationLabel: "Idaho, Montana, and Wyoming",
    signature: "Grand Prismatic Spring glowing beyond a lone bison in steam",
    symbol: "the living color of a volcanic world beneath the plateau",
    terrain: "caldera plateau, geyser basins, canyon, lake, rivers, and mountains",
    palette: ["thermal cyan", "sulfur yellow", "microbial orange", "steam white", "bison umber"],
    styles: ["wood-marquetry-landscape", "stained-glass-field", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "yosemite",
    siteCode: "yose",
    officialName: "Yosemite National Park",
    shortName: "Yosemite",
    locationLabel: "California",
    signature: "El Capitan, Half Dome, river, and pines opening through Yosemite Valley",
    symbol: "granite walls making a small trail feel infinite",
    terrain: "glacial valley, granite domes, waterfalls, high country, and river",
    palette: ["granite silver", "river turquoise", "pine", "sun gold", "deep shadow"],
    styles: ["luminous-ligne-claire", "mineral-line-engraving", "contour-atlas-ink"],
  }),
  defineNationalPark({
    slug: "zion",
    siteCode: "zion",
    officialName: "Zion National Park",
    shortName: "Zion",
    locationLabel: "Utah",
    signature: "the Virgin River winding below towering red-and-cream canyon walls",
    symbol: "a narrow bright path rising between stone giants",
    terrain: "deep sandstone canyon, hanging gardens, high plateaus, and river narrows",
    palette: ["sandstone red", "cream", "river green", "cottonwood gold", "cobalt sky"],
    styles: ["pixel-cluster-landscape", "thread-painted-embroidery", "relief-blockprint"],
  }),
] as const;
