import { defineLandscapeArtProfile, motif, palette } from "./code-native-landscape-profile";

export const nationalParkLandscapeProfiles01 = [
  defineLandscapeArtProfile({
    slug: "acadia",
    sourceCue: "dawn over Cadillac Mountain, granite ledges, spruce, and Atlantic islands",
    primaryStyleId: "pixel-cluster-landscape",
    palette: palette(
      ["night", "#1D2946"],
      ["granite", "#6D6487"],
      ["spruce", "#244B3D"],
      ["dawn", "#F0A06C"],
      ["sun", "#F4D98A"],
    ),
    motifs: [
      motif(
        "dawn over Cadillac Mountain, granite ledges, spruce, and Atlantic islands",
        "horizon",
        1,
        0.52,
        0.52,
        0.72,
        0.4,
      ),
      motif("the country's first light arriving over dark pines", "disk", 4, 0.74, 0.24, 0.2, 0.2),
      motif("island-dotted coast and rounded glacial contours", "shell", 2, 0.34, 0.79, 0.54, 0.24),
    ],
    relationship:
      "The first-light disk clears the rounded mountain while one dark coastal shelf anchors the islands below.",
    edgeStrategy:
      "The coastal shelf reaches left and bottom while the dawn ground stays open at top and right.",
  }),
  defineLandscapeArtProfile({
    slug: "arches",
    sourceCue: "Delicate Arch above red fins at blue hour",
    primaryStyleId: "thread-painted-embroidery",
    palette: palette(
      ["blue hour", "#26375D"],
      ["sandstone", "#B64F34"],
      ["ochre", "#D58D3D"],
      ["moon", "#EEE3BF"],
    ),
    motifs: [
      motif("Delicate Arch above red fins at blue hour", "arch", 1, 0.45, 0.53, 0.52, 0.52),
      motif("a stone opening holding moon and sky", "disk", 3, 0.7, 0.27, 0.19, 0.19),
      motif("eroded sandstone ribs and improbable spans", "stripe", 2, 0.55, 0.79, 0.7, 0.22),
    ],
    relationship: "One monumental arch holds the moon above a single diagonal sandstone rib.",
    edgeStrategy: "The sandstone rib bleeds left and right while blue hour remains open across the top.",
  }),
  defineLandscapeArtProfile({
    slug: "badlands",
    sourceCue: "striped pinnacles and mixed-grass prairie after a summer storm",
    primaryStyleId: "plein-air-broken-color",
    palette: palette(
      ["storm", "#394C6A"],
      ["clay", "#B66450"],
      ["prairie", "#83945D"],
      ["ochre", "#D39A4A"],
      ["light", "#EAD5A2"],
    ),
    motifs: [
      motif(
        "striped pinnacles and mixed-grass prairie after a summer storm",
        "horizon",
        1,
        0.55,
        0.46,
        0.82,
        0.38,
      ),
      motif("one bison crossing an enormous weathered amphitheater", "bison", 3, 0.29, 0.68, 0.3, 0.2),
      motif("sharp erosion bands opening into rolling grassland", "stripe", 2, 0.56, 0.8, 0.76, 0.22),
    ],
    relationship: "A lone dark animal crosses beneath one eroded wall as the prairie opens toward the storm.",
    edgeStrategy: "Prairie and erosion bands cross the lower edges; storm color remains uninterrupted above.",
  }),
  defineLandscapeArtProfile({
    slug: "big-bend",
    sourceCue: "the Rio Grande bending through Santa Elena Canyon beneath stars",
    primaryStyleId: "relief-blockprint",
    palette: palette(
      ["night", "#191D2D"],
      ["canyon", "#9D4935"],
      ["river", "#2E8B8B"],
      ["moon", "#E8D9B2"],
      ["desert", "#C38842"],
    ),
    motifs: [
      motif(
        "the Rio Grande bending through Santa Elena Canyon beneath stars",
        "ribbon",
        2,
        0.48,
        0.64,
        0.72,
        0.26,
      ),
      motif("a turquoise river threading immense desert walls", "corner", 1, 0.51, 0.47, 0.72, 0.58),
      motif(
        "river curve, Chihuahuan Desert, and isolated mountain basin",
        "horizon",
        4,
        0.54,
        0.82,
        0.84,
        0.2,
      ),
    ],
    relationship:
      "The bright river bends through one severe canyon corner before widening into the desert basin.",
    edgeStrategy: "Canyon and basin reach both side edges and bottom while the night remains open at top.",
  }),
  defineLandscapeArtProfile({
    slug: "biscayne",
    sourceCue: "a sea turtle gliding over coral gardens and seagrass",
    primaryStyleId: "stained-glass-field",
    palette: palette(
      ["deep sea", "#164A74"],
      ["turtle", "#48A38E"],
      ["coral", "#D96863"],
      ["sun", "#F0C45B"],
      ["seagrass", "#648A45"],
    ),
    motifs: [
      motif("a sea turtle gliding over coral gardens and seagrass", "oval", 1, 0.43, 0.46, 0.44, 0.28),
      motif("sun shafts joining mangrove roots to a blue world below", "stripe", 3, 0.72, 0.35, 0.2, 0.5),
      motif("shallow reef shelves, keys, and tidal channels", "horizon", 4, 0.5, 0.8, 0.84, 0.22),
    ],
    relationship: "One broad turtle form glides between a sun shaft and a continuous shallow reef shelf.",
    edgeStrategy: "The reef shelf crosses the bottom and both sides while open blue water reaches the top.",
  }),
  defineLandscapeArtProfile({
    slug: "black-canyon-gunnison",
    sourceCue: "a thin silver Gunnison River far below sheer dark walls",
    primaryStyleId: "monoprint-ink-wash",
    palette: palette(["ink", "#171A21"], ["wall", "#3C4050"], ["river", "#C8CFD2"], ["dawn", "#D4A24D"]),
    motifs: [
      motif("a thin silver Gunnison River far below sheer dark walls", "ribbon", 2, 0.49, 0.69, 0.18, 0.56),
      motif("one blade of dawn reaching an otherwise hidden depth", "stripe", 3, 0.73, 0.28, 0.18, 0.42),
      motif("narrow vertical gorge and striated Precambrian rock", "corner", 1, 0.46, 0.52, 0.7, 0.72),
    ],
    relationship: "A narrow silver river descends between one dark gorge corner and a single blade of dawn.",
    edgeStrategy: "The gorge reaches left, right, and bottom while the dawn opening breaks the upper field.",
  }),
  defineLandscapeArtProfile({
    slug: "bryce-canyon",
    sourceCue: "a sunrise amphitheater crowded with orange hoodoos",
    primaryStyleId: "contour-atlas-ink",
    palette: palette(
      ["cream", "#F0DFC0"],
      ["hoodoo", "#D96943"],
      ["shadow", "#6B4C75"],
      ["pine", "#315646"],
      ["sun", "#E6AF4A"],
    ),
    motifs: [
      motif("a sunrise amphitheater crowded with orange hoodoos", "triangle", 1, 0.5, 0.5, 0.66, 0.52),
      motif("stone figures catching light one by one", "disk", 4, 0.72, 0.23, 0.18, 0.18),
      motif("scalloped rim and densely eroded columns", "stripe", 3, 0.48, 0.79, 0.78, 0.24),
    ],
    relationship: "One consolidated hoodoo mass catches the sunrise above a single scalloped rim band.",
    edgeStrategy: "The rim crosses left and right; cream sky reaches top and the lower mass exits bottom.",
  }),
  defineLandscapeArtProfile({
    slug: "canyonlands",
    sourceCue: "Mesa Arch framing a maze of canyons at first light",
    primaryStyleId: "mineral-line-engraving",
    palette: palette(
      ["paper", "#E8D3AD"],
      ["arch", "#9D5038"],
      ["river", "#416E82"],
      ["sage", "#687B4A"],
      ["light", "#E3A947"],
    ),
    motifs: [
      motif("Mesa Arch framing a maze of canyons at first light", "arch", 1, 0.44, 0.46, 0.62, 0.5),
      motif("two rivers dividing an immense red-rock country", "ribbon", 2, 0.61, 0.63, 0.42, 0.34),
      motif(
        "nested mesas, needles, river corridors, and distant buttes",
        "horizon",
        3,
        0.55,
        0.81,
        0.82,
        0.22,
      ),
    ],
    relationship: "The arch frames one river path crossing a broad compressed mesa horizon.",
    edgeStrategy: "Mesa and river reach the lower and side edges while pale first light remains open above.",
  }),
  defineLandscapeArtProfile({
    slug: "capitol-reef",
    sourceCue: "the Waterpocket Fold rolling past pale domes and orchard trees",
    primaryStyleId: "aquatint-atmosphere",
    palette: palette(
      ["sky", "#83B9C7"],
      ["fold", "#C96E50"],
      ["dome", "#E7D9B8"],
      ["orchard", "#55784C"],
      ["shadow", "#725164"],
    ),
    motifs: [
      motif(
        "the Waterpocket Fold rolling past pale domes and orchard trees",
        "horizon",
        1,
        0.48,
        0.53,
        0.82,
        0.4,
      ),
      motif("a green fruit branch against folded desert stone", "leaf", 3, 0.25, 0.3, 0.24, 0.28),
      motif("long monocline, slot canyons, and reef-like cliffs", "stripe", 4, 0.58, 0.8, 0.76, 0.22),
    ],
    relationship:
      "A single green branch overlaps the long fold before the monocline settles into one shadow band.",
    edgeStrategy: "The fold and monocline cross both sides and bottom while cyan sky stays open at top.",
  }),
];
