import { defineLandscapeArtProfile, motif, palette } from "./code-native-landscape-profile";

export const nationalParkLandscapeProfiles06 = [
  defineLandscapeArtProfile({
    slug: "north-cascades",
    sourceCue: "jagged glacier peaks above a turquoise alpine lake",
    primaryStyleId: "plein-air-broken-color",
    palette: palette(
      ["sky", "#759EB2"],
      ["glacier", "#8DD0D8"],
      ["granite", "#767A7C"],
      ["forest", "#315D47"],
      ["snow", "#E7E8DE"],
    ),
    motifs: [
      motif("jagged glacier peaks above a turquoise alpine lake", "triangle", 2, 0.56, 0.42, 0.66, 0.54),
      motif("a cascade of blue ice feeding forest and river", "ribbon", 1, 0.38, 0.63, 0.28, 0.44),
      motif(
        "serrated range, glaciers, deep valleys, lakes, and dense forest",
        "oval",
        3,
        0.56,
        0.83,
        0.78,
        0.22,
      ),
    ],
    relationship: "A blue ice ribbon descends one serrated granite peak into a consolidated forest lake.",
    edgeStrategy: "Forest lake reaches both lower sides while blue sky stays open around the jagged summit.",
  }),
  defineLandscapeArtProfile({
    slug: "olympic",
    sourceCue: "moss-draped rainforest opening onto wild sea stacks and snowy peaks",
    primaryStyleId: "relief-blockprint",
    palette: palette(
      ["fog", "#CFD4CF"],
      ["moss", "#3F684A"],
      ["ocean", "#3F718B"],
      ["cedar", "#76503B"],
      ["snow", "#E8E6DA"],
    ),
    motifs: [
      motif(
        "moss-draped rainforest opening onto wild sea stacks and snowy peaks",
        "leaf",
        1,
        0.3,
        0.51,
        0.32,
        0.58,
      ),
      motif("three worlds meeting on one isolated peninsula", "shell", 3, 0.7, 0.57, 0.34, 0.34),
      motif(
        "temperate rainforest, glaciated mountains, river valleys, and Pacific coast",
        "triangle",
        4,
        0.55,
        0.34,
        0.42,
        0.38,
      ),
    ],
    relationship:
      "One moss form, one cedar sea-stack shell, and one snow peak meet across an open fog channel.",
    edgeStrategy:
      "Rainforest and coast touch opposite lower sides while the central fog passage remains open.",
  }),
  defineLandscapeArtProfile({
    slug: "petrified-forest",
    sourceCue: "rainbow petrified logs scattered across painted desert badlands",
    primaryStyleId: "stained-glass-field",
    palette: palette(
      ["cream", "#E6D9BC"],
      ["quartz", "#75618B"],
      ["turquoise", "#3E9297"],
      ["ochre", "#C58A43"],
      ["rose", "#B56563"],
    ),
    motifs: [
      motif(
        "rainbow petrified logs scattered across painted desert badlands",
        "block",
        1,
        0.38,
        0.6,
        0.46,
        0.28,
      ),
      motif("tree rings transformed into quartz and deep time", "ring", 2, 0.69, 0.47, 0.28, 0.28),
      motif(
        "painted hills, broad mesas, grassland, and fossil wood fields",
        "stripe",
        4,
        0.53,
        0.82,
        0.82,
        0.22,
      ),
    ],
    relationship: "One faceted fossil log points toward a quartz ring above a single painted-desert band.",
    edgeStrategy:
      "The rose badlands cross the lower edge while cream ground opens between the two mineral forms.",
  }),
  defineLandscapeArtProfile({
    slug: "pinnacles",
    sourceCue: "a California condor soaring between volcanic spires at sunset",
    primaryStyleId: "monoprint-ink-wash",
    palette: palette(
      ["sunset", "#D8A342"],
      ["volcanic", "#9B533D"],
      ["condor", "#242526"],
      ["chaparral", "#4A6744"],
      ["violet", "#625272"],
    ),
    motifs: [
      motif(
        "a California condor soaring between volcanic spires at sunset",
        "bird",
        2,
        0.49,
        0.34,
        0.34,
        0.24,
      ),
      motif(
        "wings returning above a landscape split from an ancient volcano",
        "triangle",
        1,
        0.28,
        0.59,
        0.3,
        0.48,
      ),
      motif(
        "rock pinnacles, talus caves, chaparral slopes, and oak valleys",
        "arch",
        3,
        0.7,
        0.65,
        0.34,
        0.4,
      ),
    ],
    relationship: "A single dark condor crosses between one rust spire and one green talus-cave arch.",
    edgeStrategy:
      "The spire and cave anchor opposite lower sides without a painted inset border; sunset fills the open face.",
  }),
  defineLandscapeArtProfile({
    slug: "redwood",
    sourceCue: "sunbeams descending through immense coast redwoods and fern",
    primaryStyleId: "contour-atlas-ink",
    palette: palette(
      ["fog", "#C7CDC8"],
      ["redwood", "#79513D"],
      ["fern", "#3D6848"],
      ["sun", "#D5A94F"],
      ["shadow", "#30555A"],
    ),
    motifs: [
      motif(
        "sunbeams descending through immense coast redwoods and fern",
        "block",
        1,
        0.46,
        0.46,
        0.38,
        0.72,
      ),
      motif("one tiny person beneath trees older than memory", "person", 4, 0.68, 0.7, 0.16, 0.28),
      motif(
        "tall forest, fog belt, river valleys, prairie, and rugged coast",
        "ribbon",
        2,
        0.6,
        0.83,
        0.7,
        0.2,
      ),
    ],
    relationship:
      "One immense redwood trunk dwarfs a single person while a broad fern-and-river ribbon crosses below.",
    edgeStrategy:
      "Tree and fern reach the lower edge while fog opens above and beside the intentionally spare forms.",
  }),
  defineLandscapeArtProfile({
    slug: "rocky-mountain",
    sourceCue: "elk crossing a golden alpine meadow beneath Longs Peak",
    primaryStyleId: "mineral-line-engraving",
    palette: palette(
      ["sky", "#6F91A5"],
      ["tundra", "#C39B48"],
      ["granite", "#747E89"],
      ["pine", "#385844"],
      ["elk", "#765038"],
    ),
    motifs: [
      motif("elk crossing a golden alpine meadow beneath Longs Peak", "elk", 4, 0.34, 0.65, 0.34, 0.26),
      motif("a trail rising from pine forest into open tundra sky", "ribbon", 3, 0.61, 0.68, 0.34, 0.34),
      motif(
        "continental divide, glacial valleys, alpine tundra, lakes, and forest",
        "triangle",
        2,
        0.6,
        0.36,
        0.56,
        0.44,
      ),
    ],
    relationship:
      "The elk crosses a gold meadow as one green trail rises toward a single granite divide peak.",
    edgeStrategy: "Meadow reaches both lower sides while open blue sky isolates elk, trail, and peak.",
  }),
  defineLandscapeArtProfile({
    slug: "saguaro",
    sourceCue: "giant saguaros beneath a monsoon sunset and lightning",
    primaryStyleId: "aquatint-atmosphere",
    palette: palette(
      ["storm", "#52446B"],
      ["cactus", "#3D7047"],
      ["ochre", "#C78B43"],
      ["sunset", "#C85276"],
      ["lightning", "#F1E4B9"],
    ),
    motifs: [
      motif("giant saguaros beneath a monsoon sunset and lightning", "leaf", 1, 0.38, 0.55, 0.36, 0.62),
      motif("upright cactus arms holding years of scarce rain", "stripe", 4, 0.7, 0.31, 0.26, 0.3),
      motif("Sonoran bajadas, rocky ranges, washes, and cactus forest", "horizon", 2, 0.55, 0.84, 0.82, 0.2),
    ],
    relationship:
      "One giant cactus stands opposite a broad lightning stroke above a single ochre desert shelf.",
    edgeStrategy:
      "The desert shelf reaches both lower sides while violet storm sky stays open around cactus and lightning.",
  }),
  defineLandscapeArtProfile({
    slug: "sequoia",
    sourceCue:
      "the living General Sherman sequoia, its extraordinarily massive fluted cinnamon trunk staying broad far upward and continuing visibly into an irregular high conifer crown of huge ascending limbs with fine scale-like evergreen sprays",
    primaryStyleId: "scratchboard-nocturne",
    palette: palette(
      ["shadow", "#1D2B27"],
      ["cinnamon", "#87503B"],
      ["forest", "#365A40"],
      ["sun", "#D4A54C"],
      ["granite", "#8A8B87"],
    ),
    motifs: [
      motif(
        "the living General Sherman sequoia, its extraordinarily massive fluted cinnamon trunk staying broad far upward and continuing visibly into an irregular high conifer crown of huge ascending limbs with fine scale-like evergreen sprays",
        "block",
        1,
        0.43,
        0.45,
        0.38,
        0.76,
      ),
      motif("a sunlit forest path dwarfed by one ancient living conifer", "ribbon", 3, 0.67, 0.71, 0.3, 0.34),
      motif(
        "a giant sequoia grove backed by granite domes and the high Sierra",
        "triangle",
        4,
        0.72,
        0.37,
        0.34,
        0.34,
      ),
    ],
    relationship:
      "The massive living cinnamon trunk continues into its crown while one gold path leads toward a restrained granite dome.",
    edgeStrategy:
      "The trunk and path meet the bottom edge while dark forest opens around the high conifer silhouette.",
  }),
  defineLandscapeArtProfile({
    slug: "shenandoah",
    sourceCue: "Blue Ridge layers seen from Skyline Drive through autumn leaves",
    primaryStyleId: "matte-gouache-editorial",
    palette: palette(
      ["mist", "#D4D5CA"],
      ["ridge", "#57758E"],
      ["maple", "#A94F42"],
      ["leaf", "#D0A341"],
      ["forest", "#3C6045"],
    ),
    motifs: [
      motif(
        "Blue Ridge layers seen from Skyline Drive through autumn leaves",
        "horizon",
        1,
        0.56,
        0.55,
        0.82,
        0.38,
      ),
      motif("a long ridge road disappearing into morning mist", "ribbon", 3, 0.49, 0.7, 0.38, 0.3),
      motif(
        "parallel ridges, hollows, waterfalls, forest, and high meadows",
        "leaf",
        2,
        0.77,
        0.35,
        0.26,
        0.32,
      ),
    ],
    relationship: "Layered blue ridges hold one gold road while a single red autumn leaf frames the mist.",
    edgeStrategy:
      "Ridges cross both sides and road reaches the bottom while pale mist remains open through the center.",
  }),
];
