// Generated by scripts/write-new-catalogue-integrity.mjs after visual review and asset normalization.
// Digests bind selected bytes and list derivatives to either an exact canonical prompt or an exact code-native design history.
// A superseded canonical digest records lineage only; it does not claim that its pixels were an input to the code-native renderer.
import { newCatalogueSelectedSourceIntegrityBooksRead } from "./new-catalogue-selected-source-hashes-books-read";
import { newCatalogueSelectedSourceIntegrityLifeMilestones } from "./new-catalogue-selected-source-hashes-life-milestones";
import { newCatalogueSelectedSourceIntegrityMichelinDiningBayArea } from "./new-catalogue-selected-source-hashes-michelin-dining-bay-area";
import { newCatalogueSelectedSourceIntegrityMichelinDiningNewYorkCityAM } from "./new-catalogue-selected-source-hashes-michelin-dining-new-york-city-a-m";
import { newCatalogueSelectedSourceIntegrityMichelinDiningNewYorkCityNZ } from "./new-catalogue-selected-source-hashes-michelin-dining-new-york-city-n-z";
import { newCatalogueSelectedSourceIntegrityMichelinDiningWashingtonDc } from "./new-catalogue-selected-source-hashes-michelin-dining-washington-dc";

export type NewCatalogueSelectedSourceIntegrity =
  | {
      readonly sourceWorkflow: "canonical-imagegen";
      readonly sourceSha256: string;
      readonly canonicalPromptSha256: string;
      readonly thumbnailSha256: string;
    }
  | {
      readonly sourceWorkflow: "code-native-replacement";
      readonly sourceSha256: string;
      readonly canonicalSourceSha256: string;
      readonly canonicalPromptSha256: string;
      readonly designBriefSha256: string;
      readonly rendererImplementationSha256: string;
      readonly thumbnailSha256: string;
    }
  | {
      readonly sourceWorkflow: "direct-code-native";
      readonly sourceSha256: string;
      readonly canonicalPromptSha256: string;
      readonly designBriefSha256: string;
      readonly rendererImplementationSha256: string;
      readonly thumbnailSha256: string;
    };

export const newCatalogueSelectedSourceIntegrity: Readonly<
  Record<string, NewCatalogueSelectedSourceIntegrity>
> = {
  ...newCatalogueSelectedSourceIntegrityBooksRead,
  ...newCatalogueSelectedSourceIntegrityLifeMilestones,
  ...newCatalogueSelectedSourceIntegrityMichelinDiningBayArea,
  ...newCatalogueSelectedSourceIntegrityMichelinDiningNewYorkCityAM,
  ...newCatalogueSelectedSourceIntegrityMichelinDiningNewYorkCityNZ,
  ...newCatalogueSelectedSourceIntegrityMichelinDiningWashingtonDc,
};
