import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles02aPart2 = [
  defineRestaurantArtProfile({
    slug: "casa-mono",
    sourceCue:
      "Creamy scrambled eggs with sea urchin exemplify the compact kitchen's bold Spanish tapas combinations.",
    styleSignature: "painted-mass",
    palette: [
      { name: "olive-green ground", hex: "#58613E" },
      { name: "cream construction", hex: "#F2E2C4" },
      { name: "egg-gold center", hex: "#D4A43A" },
      { name: "urchin-orange burst", hex: "#D36A35" },
      { name: "tapas-blue contrast", hex: "#3C7187" },
    ],
    motifs: [
      {
        label: "one soft egg oval",
        kind: "oval",
        count: 1,
        colorIndex: 2,
        x: 0.47,
        y: 0.52,
        width: 0.56,
        height: 0.34,
      },
      {
        label: "one sea-urchin sunburst",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.63,
        y: 0.44,
        width: 0.24,
        height: 0.24,
      },
      {
        label: "one compact counter block",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.72,
        width: 0.66,
        height: 0.18,
      },
      {
        label: "one tapas-plate disk",
        kind: "disk",
        count: 1,
        colorIndex: 4,
        x: 0.37,
        y: 0.38,
        width: 0.3,
        height: 0.3,
      },
    ],
    relationship:
      "The egg oval and urchin disk overlap on the tapas plate above the compact counter, keeping all four forms broad and bold.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "oiji-mi",
    sourceCue: "Lobster ramyun brings luxurious shellfish to a composed contemporary Korean tasting format.",
    styleSignature: "paper-layer",
    palette: [
      { name: "deep-teal ground", hex: "#214D53" },
      { name: "brass-gold construction", hex: "#C6973D" },
      { name: "lobster-coral shell", hex: "#D2695A" },
      { name: "broth-brown bowl", hex: "#744739" },
      { name: "noodle-ivory line", hex: "#F0DDB4" },
    ],
    motifs: [
      {
        label: "one curling noodle spiral",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.5,
        width: 0.58,
        height: 0.42,
      },
      {
        label: "one lobster-coral crescent",
        kind: "arch",
        count: 1,
        colorIndex: 2,
        x: 0.39,
        y: 0.42,
        width: 0.38,
        height: 0.28,
      },
      {
        label: "one polished room arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.54,
        width: 0.76,
        height: 0.68,
      },
      {
        label: "one dark broth disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.58,
        y: 0.58,
        width: 0.34,
        height: 0.34,
      },
    ],
    relationship:
      "The noodle spiral and lobster crescent layer over the broth disk, all framed by one polished contemporary arch.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "bom",
    sourceCue:
      "A marble counter with integrated grills faces the open kitchen and a visible dry-aging cabinet.",
    styleSignature: "geometric-facet",
    palette: [
      { name: "charcoal ground", hex: "#242B2D" },
      { name: "marble-cream construction", hex: "#ECE2D1" },
      { name: "steel-gray kitchen", hex: "#667479" },
      { name: "aged-amber cabinet", hex: "#A96E3E" },
      { name: "ember-orange grill", hex: "#D06A32" },
    ],
    motifs: [
      {
        label: "one marble counter arc",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.62,
        width: 0.72,
        height: 0.42,
      },
      {
        label: "three built-in grill disks",
        kind: "disk",
        count: 3,
        colorIndex: 4,
        x: 0.5,
        y: 0.58,
        width: 0.17,
        height: 0.17,
        spreadX: 0.22,
      },
      {
        label: "one dry-aging cabinet block",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.72,
        y: 0.34,
        width: 0.27,
        height: 0.4,
      },
      {
        label: "one open kitchen plane",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.34,
        y: 0.34,
        width: 0.34,
        height: 0.35,
      },
    ],
    relationship:
      "Three separate grill disks follow the marble arc, facing the kitchen plane with the dry-aging cabinet held visibly beside it.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "gramercy-tavern",
    sourceCue:
      "A warm wood tavern opens into a more formal dining room, joining neighborhood ease with polished service.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "walnut-brown ground", hex: "#543A2D" },
      { name: "warm-cream construction", hex: "#EFE1C4" },
      { name: "forest-green room", hex: "#486448" },
      { name: "hearth-amber glow", hex: "#C37D34" },
      { name: "formal-slate plane", hex: "#58666B" },
    ],
    motifs: [
      {
        label: "one timber tavern arch",
        kind: "arch",
        count: 1,
        colorIndex: 2,
        x: 0.32,
        y: 0.52,
        width: 0.44,
        height: 0.54,
      },
      {
        label: "one formal room rectangle",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.69,
        y: 0.44,
        width: 0.36,
        height: 0.44,
      },
      {
        label: "one shared hearth disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.55,
        width: 0.24,
        height: 0.24,
      },
      {
        label: "one connecting doorway band",
        kind: "horizon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.68,
        width: 0.68,
        height: 0.13,
      },
    ],
    relationship:
      "The timber arch and formal rectangle occupy opposite rooms, joined by the doorway band and one shared hearth at their overlap.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "rezdora",
    sourceCue:
      "Handmade pasta and airy gnocco fritto draw the menu toward the regional food traditions of Emilia-Romagna.",
    styleSignature: "fiber-applique",
    palette: [
      { name: "terra-brown ground", hex: "#704838" },
      { name: "farmhouse-cream construction", hex: "#F0E1C5" },
      { name: "pasta-gold ribbon", hex: "#D1A13C" },
      { name: "hill-green regional", hex: "#627447" },
      { name: "cheese-amber accent", hex: "#BF7637" },
    ],
    motifs: [
      {
        label: "one looping pasta ribbon",
        kind: "ribbon",
        count: 1,
        colorIndex: 2,
        x: 0.43,
        y: 0.44,
        width: 0.54,
        height: 0.44,
      },
      {
        label: "one puffed bread oval",
        kind: "oval",
        count: 1,
        colorIndex: 1,
        x: 0.68,
        y: 0.42,
        width: 0.3,
        height: 0.22,
      },
      {
        label: "one pasta-work counter block",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.7,
        width: 0.7,
        height: 0.18,
      },
      {
        label: "one regional tasting disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.61,
        y: 0.61,
        width: 0.28,
        height: 0.28,
      },
    ],
    relationship:
      "The handmade pasta loops above its work counter, with airy bread and the regional tasting disk kept as two clear companion forms.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "noda",
    sourceCue:
      "An eight-seat half-moon counter sits beyond a cocktail lounge in a dark, speakeasy-like room.",
    styleSignature: "screenprint-overlap",
    palette: [
      { name: "midnight-blue ground", hex: "#1D2D3A" },
      { name: "rice-ivory construction", hex: "#EFE3CB" },
      { name: "warm-gold lounge", hex: "#C18E39" },
      { name: "ebony doorway", hex: "#313033" },
      { name: "plate-blue focus", hex: "#416C7B" },
    ],
    motifs: [
      {
        label: "one half-moon counter",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.62,
        width: 0.68,
        height: 0.42,
      },
      {
        label: "one dark lounge arch",
        kind: "arch",
        count: 1,
        colorIndex: 3,
        x: 0.31,
        y: 0.42,
        width: 0.4,
        height: 0.5,
      },
      {
        label: "one hidden doorway plane",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.69,
        y: 0.39,
        width: 0.3,
        height: 0.44,
      },
      {
        label: "one omakase plate disk",
        kind: "disk",
        count: 1,
        colorIndex: 4,
        x: 0.57,
        y: 0.53,
        width: 0.24,
        height: 0.24,
      },
    ],
    relationship:
      "The half-moon counter emerges beyond the lounge arch and hidden doorway, with one omakase disk centered inside the secluded curve.",
    edgeStrategy: fullBleed,
  }),
] as const;
