import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import type { RestaurantGeometryMotif, RestaurantMotifKind } from "./restaurant-art-profile";

const ARTBOARD = 896;

export const washingtonDcRestaurantArtProfilesPartTwo = [
  defineRestaurantArtProfile({
    slug: "causa",
    sourceCue: "The Nikkei tasting travels from Lima’s coast through the Andes and Amazon.",
    styleSignature: "paper-layer",
    palette: [
      { name: "potato-cream paper", hex: "#F0E2C7" },
      { name: "charcoal cut edge", hex: "#293034" },
      { name: "Lima-coast blue", hex: "#417287" },
      { name: "mountain violet", hex: "#6D526E" },
      { name: "rainforest green", hex: "#46734E" },
      { name: "Amazon-water teal", hex: "#37746F" },
    ],
    motifs: [
      motif("one Lima-coast water band", "horizon", 1, 2, 448, 676, 790, 162, 0, 0),
      motif("one high Andes triangle", "triangle", 1, 3, 316, 440, 390, 440, 0, 0),
      motif("one broad rainforest leaf", "leaf", 1, 4, 606, 420, 340, 360, 0, 0),
      motif("one Amazon basin oval", "oval", 1, 5, 550, 618, 330, 180, 0, 0),
    ],
    relationship:
      "The route moves from Lima's coast past an Andean peak into rainforest and Amazon basin forms.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "imperfecto-the-chefs-table",
    sourceCue: "Glass, marble, brass, and terra-cotta frame a counter below the chef’s perch.",
    styleSignature: "geometric-facet",
    palette: [
      { name: "marble-ivory ground", hex: "#F0E5D2" },
      { name: "charcoal facet edge", hex: "#293034" },
      { name: "glass blue", hex: "#4C7488" },
      { name: "brass gold", hex: "#C39238" },
      { name: "terra-cotta base", hex: "#AF5E43" },
      { name: "marble plane gray", hex: "#CAC5B9" },
    ],
    motifs: [
      motif("one tall glass tower block", "block", 1, 2, 286, 390, 260, 520, 0, 0),
      motif("one white marble plane", "horizon", 1, 5, 448, 660, 780, 164, 0, 0),
      motif("one brass counter crescent", "arch", 1, 3, 542, 510, 540, 300, 0, 0),
      motif("one terra-cotta base", "block", 1, 4, 448, 748, 790, 100, 0, 0),
    ],
    relationship: "The tall glass form rises from marble and terra cotta beside the brass chef counter.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "sushi-nakazawa-washington-dc",
    sourceCue: "Dark wood and gold surround a marble counter and precise itamae work.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "marble-ivory ground", hex: "#F0E4CF" },
      { name: "ink-black join", hex: "#22282B" },
      { name: "walnut wall", hex: "#75503C" },
      { name: "warm-gold light", hex: "#C89436" },
      { name: "silver-gray precision", hex: "#7B8589" },
      { name: "pale-marble counter", hex: "#D2C8B9" },
    ],
    motifs: [
      motif("one dark wood wall field", "block", 1, 2, 448, 420, 780, 520, 0, 0),
      motif("one pale marble counter arc", "arch", 1, 5, 448, 608, 680, 280, 0, 0),
      motif("one warm gold light block", "block", 1, 3, 448, 250, 520, 150, 0, 0),
      motif("one precise itamae-work ribbon", "ribbon", 1, 1, 448, 126, 790, 120, 0, 0),
    ],
    relationship:
      "Gold light and a precise itamae-work ribbon cross the dark wood room above the pale counter.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "albi",
    sourceCue: "Palestinian childhood flavors are reimagined through open-fire cooking.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "pita-cream glaze", hex: "#F0E2C5" },
      { name: "night-blue contour", hex: "#28364A" },
      { name: "ember-orange hearth", hex: "#CF6331" },
      { name: "olive-green memory", hex: "#5E744A" },
      { name: "childhood-memory brown", hex: "#89553F" },
      { name: "pita-gold dome", hex: "#D2AD70" },
    ],
    motifs: [
      motif("one open hearth arch", "arch", 1, 2, 448, 476, 690, 580, 0, 0),
      motif("one reimagined-flavor dome", "arch", 1, 5, 448, 610, 360, 210, 0, 0),
      motif("one childhood-memory curve", "ribbon", 1, 3, 448, 340, 550, 110, 0, 0),
      motif("one ember-glow disk", "disk", 1, 2, 448, 474, 230, 230, 0, 0),
    ],
    relationship:
      "The childhood-memory curve enters an open hearth above reimagined flavor and one ember glow.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "mita",
    sourceCue: "Arepas pair guasacaca, cashew cream, chili oil, and chontaduro butter.",
    styleSignature: "mosaic-cell",
    palette: [
      { name: "cashew-cream stone", hex: "#F0E2C5" },
      { name: "earth-brown grout", hex: "#4D3D35" },
      { name: "maize-gold arepa", hex: "#D2A038" },
      { name: "guasacaca green", hex: "#4E774E" },
      { name: "cashew-cream wave", hex: "#D9C9AA" },
      { name: "chontaduro butter", hex: "#C98737" },
    ],
    motifs: [
      motif("one round arepa disk", "disk", 1, 2, 448, 518, 480, 480, 0, 0),
      motif("one chontaduro-butter oval", "oval", 1, 5, 300, 382, 290, 180, 0, 0),
      motif("one cashew-cream wave", "ribbon", 1, 4, 448, 568, 560, 112, 0, 0),
      motif("one guasacaca arc", "arch", 1, 3, 590, 402, 320, 230, 0, 0),
    ],
    relationship: "The arepa disk carries chontaduro, cashew cream, and guasacaca as three broad toppings.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "roses-luxury",
    sourceCue: "Globe lights, eclectic décor, and an open kitchen suggest a playful party.",
    styleSignature: "screenprint-overlap",
    palette: [
      { name: "soft-cream paper", hex: "#F2E4CA" },
      { name: "charcoal overprint", hex: "#272C2E" },
      { name: "warm-amber light", hex: "#CF9336" },
      { name: "deep-teal kitchen", hex: "#3D7373" },
      { name: "plum fabric", hex: "#714A65" },
    ],
    motifs: [
      motif("one globe pendant disk", "disk", 1, 2, 448, 224, 230, 230, 0, 0),
      motif("one open kitchen rectangle", "block", 1, 3, 594, 440, 300, 310, 0, 0),
      motif("one eclectic-decor oval", "oval", 1, 1, 448, 624, 620, 230, 0, 0),
      motif("one playful-party curve", "ribbon", 1, 4, 330, 430, 470, 116, 0, 0),
    ],
    relationship: "One globe light and playful curve energize the open kitchen and eclectic decor oval.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "little-pearl",
    sourceCue: "A carriage-house shell opens into a glassy sunroom facing greenery.",
    styleSignature: "lead-cell",
    palette: [
      { name: "warm-ivory glass", hex: "#F1E5CC" },
      { name: "charcoal lead", hex: "#252B2D" },
      { name: "leaf-green canopy", hex: "#50734C" },
      { name: "glass-blue sunroom", hex: "#4A7686" },
      { name: "brick-brown shell", hex: "#A25A43" },
      { name: "sun-gold light", hex: "#D09B35" },
    ],
    motifs: [
      motif("one carriage-house arch", "arch", 1, 4, 330, 460, 470, 540, 0, 0),
      motif("one tall sunroom block", "block", 1, 3, 618, 430, 300, 500, 0, 0),
      motif("one broad green canopy", "leaf", 1, 2, 570, 304, 420, 280, 0, 0),
      motif("one glassy light disk", "disk", 1, 5, 648, 210, 200, 200, 0, 0),
    ],
    relationship:
      "The carriage-house arch opens into a tall glass room beneath greenery and one luminous disk.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "fiola",
    sourceCue: "Stone walls, seasonal décor, and pop-art prints mix lodge warmth and retro glamour.",
    styleSignature: "painted-mass",
    palette: [
      { name: "cream-plaster ground", hex: "#EFE2C9" },
      { name: "stone-charcoal edge", hex: "#393D3E" },
      { name: "forest-green decor", hex: "#4F714B" },
      { name: "electric-gold print", hex: "#D09B35" },
      { name: "deep-plum print", hex: "#704760" },
      { name: "stone-gray wall", hex: "#77746C" },
    ],
    motifs: [
      motif("one rugged stone wall", "block", 1, 5, 448, 450, 780, 520, 0, 0),
      motif("two bold pop-art blocks", "block", 2, 3, 448, 350, 220, 250, 300, 0),
      motif("one seasonal branch curve", "ribbon", 1, 2, 448, 220, 560, 110, 0, 0),
      motif("one retro-glamour band", "horizon", 1, 4, 448, 686, 790, 130, 0, 0),
    ],
    relationship: "Two bold prints and a seasonal branch sit against stone above one retro-glamour band.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "bresca",
    sourceCue: "A moss wall, gold flashes, and sculptural forms create a surreal room.",
    styleSignature: "mosaic-cell",
    palette: [
      { name: "cream-stone ground", hex: "#F0E3CA" },
      { name: "charcoal grout", hex: "#272D2F" },
      { name: "moss-green wall", hex: "#4D714B" },
      { name: "warm-gold flash", hex: "#CE9735" },
      { name: "deep-teal floor", hex: "#386C70" },
    ],
    motifs: [
      motif("one moss wall rectangle", "block", 1, 2, 304, 422, 430, 500, 0, 0),
      motif("one broad gold crescent", "arch", 1, 3, 570, 360, 390, 280, 0, 0),
      motif("one sculptural arch", "arch", 1, 1, 560, 488, 430, 440, 0, 0),
      motif("one surreal-room field", "horizon", 1, 4, 448, 696, 790, 180, 0, 0),
    ],
    relationship: "The moss wall and gold crescent offset one sculptural arch above the surreal room field.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "gravitas",
    sourceCue: "Exposed brick and industrial walls soften with greenery and an open kitchen.",
    styleSignature: "relief-cut",
    palette: [
      { name: "ivory paper ground", hex: "#F0E4CF" },
      { name: "charcoal carved line", hex: "#282D2F" },
      { name: "brick-brown wall", hex: "#A55A43" },
      { name: "leaf-green mass", hex: "#51734C" },
      { name: "steel-gray kitchen", hex: "#68737A" },
      { name: "stark-ivory plane", hex: "#D8CDBB" },
    ],
    motifs: [
      motif("one exposed brick rectangle", "block", 1, 2, 300, 438, 440, 500, 0, 0),
      motif("one open kitchen window block", "block", 1, 4, 600, 430, 320, 310, 0, 0),
      motif("one industrial wall plane", "horizon", 1, 5, 448, 684, 780, 152, 0, 0),
      motif("one broad greenery mass", "leaf", 1, 3, 580, 292, 380, 290, 0, 0),
    ],
    relationship: "Brick and kitchen blocks meet an industrial wall softened by one broad greenery mass.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "rania",
    sourceCue: "Pork vindaloo arrives with crisp belly, dal, Kashmiri pulao, and buttered naan.",
    styleSignature: "lead-cell",
    palette: [
      { name: "warm-cream glass", hex: "#F1E3C7" },
      { name: "charcoal lead", hex: "#252A2C" },
      { name: "saffron spice", hex: "#D09A32" },
      { name: "deep-violet vindaloo", hex: "#704A68" },
      { name: "leaf-green dal", hex: "#5B744B" },
      { name: "naan-gold bread", hex: "#D1AF72" },
    ],
    motifs: [
      motif("one crisp pork-belly arch", "arch", 1, 3, 448, 376, 420, 300, 0, 0),
      motif("one spice-colored wave", "ribbon", 1, 2, 448, 506, 600, 116, 0, 0),
      motif("one warm bread crescent", "arch", 1, 5, 304, 624, 320, 210, 0, 0),
      motif("one dark pulao block", "block", 1, 4, 600, 630, 330, 200, 0, 0),
    ],
    relationship: "The crisp pork arc sits over vindaloo spice, with broad naan and pulao forms below.",
    edgeStrategy: "full-bleed",
  }),
] as const;

function motif(
  label: string,
  kind: RestaurantMotifKind,
  count: 1 | 2 | 3,
  colorIndex: number,
  x: number,
  y: number,
  width: number,
  height: number,
  spreadX: number,
  spreadY: number,
): RestaurantGeometryMotif {
  return {
    label,
    kind,
    count,
    colorIndex,
    x: x / ARTBOARD,
    y: y / ARTBOARD,
    width: width / ARTBOARD,
    height: height / ARTBOARD,
    spreadX: spreadX / ARTBOARD,
    spreadY: spreadY / ARTBOARD,
  };
}
