import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles02bPart1 = [
  defineRestaurantArtProfile({
    slug: "odo",
    sourceCue:
      "A secluded, serene kaiseki counter is reached through a cocktail bar, separating ceremony from the city outside.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "deep-charcoal ground", hex: "#252C2D" },
      { name: "ceremony-ivory construction", hex: "#EFE5D0" },
      { name: "cypress-tan counter", hex: "#C19A67" },
      { name: "garden-green separation", hex: "#526E50" },
      { name: "soba-brown ceremony", hex: "#76513B" },
    ],
    motifs: [
      {
        label: "one secluded counter band",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.7,
        width: 0.75,
        height: 0.19,
      },
      {
        label: "one passageway arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.31,
        y: 0.45,
        width: 0.4,
        height: 0.56,
      },
      {
        label: "one separating room plane",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.69,
        y: 0.43,
        width: 0.35,
        height: 0.5,
      },
      {
        label: "one composed tasting disk",
        kind: "disk",
        count: 1,
        colorIndex: 4,
        x: 0.54,
        y: 0.52,
        width: 0.25,
        height: 0.25,
      },
    ],
    relationship:
      "The passage arch crosses the separating plane toward the secluded counter, where one composed tasting disk marks the ceremonial destination.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "noz-17",
    sourceCue:
      "A tiny chef counter foregrounds dry-aging, curing, and fermentation within an Edomae-inspired omakase.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "deep-blue ground", hex: "#243645" },
      { name: "rice-ivory construction", hex: "#F0E3CA" },
      { name: "aged-amber preserve", hex: "#AD7140" },
      { name: "charcoal curing", hex: "#303536" },
      { name: "celadon fermentation", hex: "#7C988B" },
    ],
    motifs: [
      {
        label: "one tiny counter arc",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.68,
        width: 0.58,
        height: 0.3,
      },
      {
        label: "one preserved-fish crescent",
        kind: "arch",
        count: 1,
        colorIndex: 2,
        x: 0.38,
        y: 0.43,
        width: 0.4,
        height: 0.25,
      },
      {
        label: "one fermentation spiral",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.67,
        y: 0.38,
        width: 0.3,
        height: 0.36,
      },
      {
        label: "one curing-shelf band",
        kind: "horizon",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.56,
        width: 0.63,
        height: 0.13,
      },
    ],
    relationship:
      "The preserved fish and fermentation spiral sit in separate zones above the curing shelf, all presented by the small counter arc.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "aska",
    sourceCue:
      "Austere Nordic cooking uses smoke, fire, preserved flavors, and seasonal northeastern ingredients in a dark Williamsburg setting.",
    styleSignature: "screenprint-overlap",
    palette: [
      { name: "charcoal ground", hex: "#202727" },
      { name: "winter-ivory construction", hex: "#E9E1CF" },
      { name: "pine-green season", hex: "#405F4A" },
      { name: "ember-gold fire", hex: "#D08A2F" },
      { name: "preserved-amber flavor", hex: "#9A613B" },
    ],
    motifs: [
      {
        label: "one dark room arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.52,
        width: 0.76,
        height: 0.68,
      },
      {
        label: "one preserved-flavor oval",
        kind: "oval",
        count: 1,
        colorIndex: 4,
        x: 0.35,
        y: 0.52,
        width: 0.32,
        height: 0.24,
      },
      {
        label: "one smoke ribbon",
        kind: "ribbon",
        count: 1,
        colorIndex: 2,
        x: 0.53,
        y: 0.34,
        width: 0.22,
        height: 0.43,
      },
      {
        label: "one seasonal-ingredient disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.69,
        y: 0.52,
        width: 0.25,
        height: 0.25,
      },
    ],
    relationship:
      "The dark room contains separate preserved and seasonal forms, linked only by one rising smoke ribbon from the fire-colored disk.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "cote",
    sourceCue:
      "Korean barbecue meets an American steakhouse through tabletop grills and a prominent dry-aging program.",
    styleSignature: "screenprint-overlap",
    palette: [
      { name: "deep-navy ground", hex: "#1D3040" },
      { name: "brass-gold construction", hex: "#C49137" },
      { name: "charcoal grill", hex: "#303638" },
      { name: "aged-amber cabinet", hex: "#A96F3E" },
      { name: "ember-red smoke", hex: "#B84D36" },
    ],
    motifs: [
      {
        label: "one tabletop grill disk",
        kind: "disk",
        count: 1,
        colorIndex: 2,
        x: 0.45,
        y: 0.57,
        width: 0.34,
        height: 0.34,
      },
      {
        label: "one dry-aging cabinet",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.7,
        y: 0.38,
        width: 0.28,
        height: 0.46,
      },
      {
        label: "one bold steakhouse arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.5,
        width: 0.76,
        height: 0.68,
      },
      {
        label: "one rising smoke curve",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.34,
        y: 0.3,
        width: 0.22,
        height: 0.4,
      },
    ],
    relationship:
      "The steakhouse arch holds the tabletop grill opposite the dry-aging cabinet, while one smoke curve marks the barbecue heat.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "jua",
    sourceCue:
      "Soaring ceilings and sultry light frame a modern Korean tasting menu shaped by dry-aging and wood fire.",
    styleSignature: "lead-cell",
    palette: [
      { name: "deep-plum ground", hex: "#453344" },
      { name: "warm-ivory construction", hex: "#F0E2CA" },
      { name: "ember-amber fire", hex: "#D07A2E" },
      { name: "smoke-gray aging", hex: "#737C7B" },
      { name: "shadow-blue plane", hex: "#334F62" },
    ],
    motifs: [
      {
        label: "one soaring ceiling arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.47,
        width: 0.76,
        height: 0.72,
      },
      {
        label: "one wood-fire disk",
        kind: "disk",
        count: 1,
        colorIndex: 2,
        x: 0.35,
        y: 0.58,
        width: 0.27,
        height: 0.27,
      },
      {
        label: "one dry-aged ingredient crescent",
        kind: "arch",
        count: 1,
        colorIndex: 3,
        x: 0.62,
        y: 0.5,
        width: 0.4,
        height: 0.25,
      },
      {
        label: "one tall shadow plane",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.72,
        y: 0.34,
        width: 0.22,
        height: 0.5,
      },
    ],
    relationship:
      "The high arch frames wood fire and dry-aged ingredient as two distinct tasting anchors, with the tall shadow plane intensifying the sultry light.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "shota-omakase",
    sourceCue:
      "A close Brooklyn sushi counter emphasizes wild seafood, maturation, and traditional Edomae preparation.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "deep-charcoal ground", hex: "#252B2C" },
      { name: "rice-ivory construction", hex: "#EFE4CE" },
      { name: "cypress-honey counter", hex: "#C19355" },
      { name: "seafood-blue wild catch", hex: "#3E6B7A" },
      { name: "matured-amber fish", hex: "#A96942" },
    ],
    motifs: [
      {
        label: "one close counter band",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.24,
        width: 0.7,
        height: 0.14,
      },
      {
        label: "one wild-seafood wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.43,
        width: 0.68,
        height: 0.2,
      },
      {
        label: "one matured-fish crescent",
        kind: "arch",
        count: 1,
        colorIndex: 4,
        x: 0.27,
        y: 0.58,
        width: 0.28,
        height: 0.22,
      },
      {
        label: "one maturation vessel oval",
        kind: "oval",
        count: 1,
        colorIndex: 1,
        x: 0.58,
        y: 0.66,
        width: 0.34,
        height: 0.38,
      },
    ],
    layerOrder: [0, 1, 3, 2],
    relationship:
      "The seafood wave descends from the close counter toward the maturation vessel, while the matured-fish crescent remains separate for traditional preparation.",
    edgeStrategy: fullBleed,
  }),
] as const;
