import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles01aPart1 = [
  defineRestaurantArtProfile({
    slug: "icca",
    sourceCue:
      "A discreet cocktail bar gives way to a secluded chef counter where traditional nigiri is lightly brushed with nikiri.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "smoked-charcoal ground", hex: "#202629" },
      { name: "rice-ivory construction", hex: "#F1E6CF" },
      { name: "cypress-honey counter", hex: "#C48A48" },
      { name: "ocean-blue calm", hex: "#356D7B" },
      { name: "brushed-amber sauce", hex: "#D8783A" },
    ],
    motifs: [
      {
        label: "one shadowed doorway arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.27,
        y: 0.38,
        width: 0.34,
        height: 0.5,
      },
      {
        label: "one long cypress counter",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.68,
        width: 0.76,
        height: 0.2,
      },
      {
        label: "one brushed amber wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.56,
        y: 0.55,
        width: 0.58,
        height: 0.16,
      },
      {
        label: "one nigiri plate disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.72,
        y: 0.29,
        width: 0.22,
        height: 0.22,
      },
    ],
    relationship:
      "The doorway reveals the long counter; the amber brush crosses it once while the nigiri disk holds the secluded upper field.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "atera",
    sourceCue: "The dark, sleek dining room centers on a spacious U-shaped counter facing the open kitchen.",
    styleSignature: "screenprint-overlap",
    palette: [
      { name: "dark-room ground", hex: "#182329" },
      { name: "soft-ivory construction", hex: "#F0E6D2" },
      { name: "warm-copper counter", hex: "#B8643A" },
      { name: "slate-blue kitchen", hex: "#466779" },
      { name: "deep-charcoal ceiling", hex: "#30393D" },
    ],
    motifs: [
      {
        label: "one sweeping counter horseshoe",
        kind: "arch",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.56,
        width: 0.7,
        height: 0.56,
      },
      {
        label: "one central kitchen block",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.43,
        width: 0.28,
        height: 0.24,
      },
      {
        label: "one charcoal ceiling plane",
        kind: "horizon",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.17,
        width: 0.78,
        height: 0.16,
      },
      {
        label: "one luminous copper disk",
        kind: "disk",
        count: 1,
        colorIndex: 2,
        x: 0.75,
        y: 0.28,
        width: 0.19,
        height: 0.19,
      },
    ],
    relationship:
      "The horseshoe encloses the kitchen block, below the low ceiling plane, with one copper light offset toward the open work side.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "huso",
    sourceCue:
      "Flowing white drapes and soft lighting turn the room behind a caviar shop into a quiet hideaway.",
    styleSignature: "fiber-applique",
    palette: [
      { name: "midnight-hideaway ground", hex: "#1C2632" },
      { name: "soft-silver construction", hex: "#BBC4C5" },
      { name: "pearl-ivory drapery", hex: "#EFE7D6" },
      { name: "mist-gray counter", hex: "#879294" },
      { name: "muted-blue shadow", hex: "#3E5768" },
    ],
    motifs: [
      {
        label: "two flowing curtain bands",
        kind: "ribbon",
        count: 2,
        colorIndex: 2,
        x: 0.5,
        y: 0.36,
        width: 0.24,
        height: 0.58,
        spreadX: 0.38,
      },
      {
        label: "one pearl-like central oval",
        kind: "oval",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.42,
        width: 0.24,
        height: 0.18,
      },
      {
        label: "one low counter block",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.73,
        width: 0.62,
        height: 0.17,
      },
      {
        label: "one soft shadow arch",
        kind: "arch",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.53,
        width: 0.72,
        height: 0.68,
      },
    ],
    layerOrder: [2, 0, 3, 1],
    relationship:
      "The paired drapes part around the pearl oval and low counter, all nested within one broad shadow arch.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "jungsik-new-york",
    sourceCue:
      "Jungsik's tasting opens with banchan before striped jack with white kimchi, crisp octopus with gochujang aioli, and dry-aged Arctic char.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "ink-black ground", hex: "#20272A" },
      { name: "white-kimchi construction", hex: "#F2E8D3" },
      { name: "striped-jack blue", hex: "#66808A" },
      { name: "gochujang coral", hex: "#C65F4B" },
      { name: "Arctic-char amber", hex: "#C58A3A" },
    ],
    motifs: [
      {
        label: "one banchan presentation disk",
        kind: "disk",
        count: 1,
        colorIndex: 1,
        x: 0.28,
        y: 0.35,
        width: 0.3,
        height: 0.3,
      },
      {
        label: "one striped-jack ribbon",
        kind: "ribbon",
        count: 1,
        colorIndex: 2,
        x: 0.55,
        y: 0.36,
        width: 0.56,
        height: 0.18,
      },
      {
        label: "one crisp octopus arc",
        kind: "arch",
        count: 1,
        colorIndex: 3,
        x: 0.34,
        y: 0.64,
        width: 0.38,
        height: 0.32,
      },
      {
        label: "one Arctic-char oval",
        kind: "oval",
        count: 1,
        colorIndex: 4,
        x: 0.68,
        y: 0.62,
        width: 0.34,
        height: 0.24,
      },
    ],
    relationship:
      "The banchan disk opens at upper left; striped jack leads across the top to an octopus arc and Arctic-char oval below.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "crown-shy",
    sourceCue:
      "An Art Deco tower lobby brings soaring ceilings, marble floors, and tall windows to the dining room.",
    styleSignature: "lead-cell",
    palette: [
      { name: "deep-teal ground", hex: "#214A4B" },
      { name: "graphite construction", hex: "#252D31" },
      { name: "marble-cream floor", hex: "#E9DFC9" },
      { name: "aged-gold rise", hex: "#C3923F" },
      { name: "smoky-blue glass", hex: "#57727A" },
    ],
    motifs: [
      {
        label: "one tall stepped tower",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.43,
        width: 0.3,
        height: 0.66,
      },
      {
        label: "three window arches",
        kind: "arch",
        count: 3,
        colorIndex: 2,
        x: 0.5,
        y: 0.39,
        width: 0.17,
        height: 0.33,
        spreadX: 0.22,
      },
      {
        label: "one marble floor wedge",
        kind: "triangle",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.75,
        width: 0.72,
        height: 0.26,
      },
      {
        label: "one upward gold ray",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.66,
        y: 0.36,
        width: 0.14,
        height: 0.62,
      },
    ],
    layerOrder: [0, 2, 3, 1],
    relationship:
      "The stepped tower rises from the marble wedge; three arches read across its center while one gold ray emphasizes the soaring height.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "saga",
    sourceCue:
      "A high-rise terrace and jewel-toned rooms pair skyline views with peach velvet, green marble, and carved stone.",
    styleSignature: "paper-layer",
    palette: [
      { name: "night-navy ground", hex: "#1D3041" },
      { name: "stone-cream construction", hex: "#E7DDC8" },
      { name: "emerald-marble room", hex: "#2F6B57" },
      { name: "velvet-peach seating", hex: "#D58C73" },
      { name: "slate skyline", hex: "#536675" },
    ],
    motifs: [
      {
        label: "one tall skyline silhouette",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.66,
        y: 0.37,
        width: 0.5,
        height: 0.52,
      },
      {
        label: "one terrace horizon",
        kind: "horizon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.68,
        width: 0.8,
        height: 0.12,
      },
      {
        label: "one velvet peach arc",
        kind: "arch",
        count: 1,
        colorIndex: 3,
        x: 0.28,
        y: 0.55,
        width: 0.38,
        height: 0.35,
      },
      {
        label: "one green marble block",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.46,
        y: 0.52,
        width: 0.28,
        height: 0.3,
      },
    ],
    relationship:
      "The terrace cuts across the skyline, with the peach seating arc and marble block layered as the two jewel-toned room masses in front.",
    edgeStrategy: fullBleed,
  }),
] as const;
