import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles02bPart2 = [
  defineRestaurantArtProfile({
    slug: "eleven-madison-park",
    sourceCue:
      "A vast Art Deco dining room overlooks Madison Square while the tasting menu is built entirely around plants.",
    styleSignature: "lead-cell",
    palette: [
      { name: "city-charcoal ground", hex: "#293136" },
      { name: "limestone-cream construction", hex: "#EDE2CB" },
      { name: "park-green canopy", hex: "#496D4C" },
      { name: "aged-brass detail", hex: "#B88A3D" },
      { name: "window-blue glass", hex: "#4F7484" },
    ],
    motifs: [
      {
        label: "one vast stepped arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.49,
        width: 0.8,
        height: 0.72,
      },
      {
        label: "one Madison Square horizon",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.34,
        y: 0.54,
        width: 0.43,
        height: 0.24,
      },
      {
        label: "one tall window grid",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.7,
        y: 0.38,
        width: 0.3,
        height: 0.5,
      },
      {
        label: "one plant-like central fan",
        kind: "leaf",
        count: 1,
        colorIndex: 3,
        x: 0.52,
        y: 0.56,
        width: 0.32,
        height: 0.39,
      },
    ],
    relationship:
      "The vast arch spans the tall window and Madison Square horizon; a single plant fan stands centrally in front to identify the all-plant menu.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "francie",
    sourceCue: "A limestone building combines ash wood, mosaic flooring, exposed brick, and an open kitchen.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "brick-brown ground", hex: "#754A38" },
      { name: "limestone-cream construction", hex: "#E9DEC7" },
      { name: "ash-tan wood", hex: "#C0A276" },
      { name: "mosaic-blue floor", hex: "#496F80" },
      { name: "kitchen-charcoal opening", hex: "#303638" },
    ],
    motifs: [
      {
        label: "one limestone facade block",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.43,
        width: 0.66,
        height: 0.58,
      },
      {
        label: "one ash-wood arch",
        kind: "arch",
        count: 1,
        colorIndex: 2,
        x: 0.33,
        y: 0.47,
        width: 0.36,
        height: 0.46,
      },
      {
        label: "one mosaic floor plane",
        kind: "horizon",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.72,
        width: 0.74,
        height: 0.2,
      },
      {
        label: "one open kitchen window",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.68,
        y: 0.4,
        width: 0.29,
        height: 0.36,
      },
    ],
    relationship:
      "The ash arch and kitchen window cut into the limestone block, which rests on one broad mosaic floor plane against the brick ground.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "atomix",
    sourceCue:
      "A townhouse descends to a basement U-shaped counter where a contemporary Korean tasting menu unfolds.",
    styleSignature: "paper-layer",
    palette: [
      { name: "ink-black ground", hex: "#22292D" },
      { name: "ceramic-ivory construction", hex: "#EFE4CF" },
      { name: "townhouse-gray shell", hex: "#687278" },
      { name: "burnished-bronze stair", hex: "#A8753F" },
      { name: "deep-blue tasting", hex: "#354E68" },
    ],
    motifs: [
      {
        label: "one townhouse silhouette",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.36,
        y: 0.38,
        width: 0.38,
        height: 0.55,
      },
      {
        label: "one descending stair band",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.5,
        width: 0.5,
        height: 0.48,
      },
      {
        label: "one basement counter horseshoe",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.58,
        y: 0.65,
        width: 0.6,
        height: 0.38,
      },
      {
        label: "one tasting-course disk",
        kind: "disk",
        count: 1,
        colorIndex: 4,
        x: 0.65,
        y: 0.51,
        width: 0.24,
        height: 0.24,
      },
    ],
    relationship:
      "The stair band descends from the townhouse into the basement horseshoe, where one tasting disk marks the contemporary sequence.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "the-four-horsemen",
    sourceCue:
      "A compact wood-lined wine bar pairs natural wines with concise, highly seasonal American plates.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "walnut-brown ground", hex: "#53382D" },
      { name: "warm-cream construction", hex: "#EEE0C5" },
      { name: "grape-purple wine", hex: "#6F445B" },
      { name: "leaf-green season", hex: "#587147" },
      { name: "table-honey wood", hex: "#B9874E" },
    ],
    motifs: [
      {
        label: "one compact timber room",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.46,
        width: 0.68,
        height: 0.6,
      },
      {
        label: "one wine-glass oval",
        kind: "oval",
        count: 1,
        colorIndex: 2,
        x: 0.35,
        y: 0.39,
        width: 0.26,
        height: 0.35,
      },
      {
        label: "one seasonal leaf fan",
        kind: "leaf",
        count: 1,
        colorIndex: 3,
        x: 0.68,
        y: 0.37,
        width: 0.29,
        height: 0.4,
      },
      {
        label: "one shared-table band",
        kind: "horizon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.7,
        width: 0.7,
        height: 0.17,
      },
    ],
    relationship:
      "The wine oval and seasonal leaf sit at opposite sides of the compact room, joined by one shared-table band along its base.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "joo-ok",
    sourceCue:
      "A high-floor dining room opens to broad skyline views while the menu draws on Korean fermentation and royal-court traditions.",
    styleSignature: "lead-cell",
    palette: [
      { name: "night-navy ground", hex: "#1E3243" },
      { name: "warm-gold construction", hex: "#C39543" },
      { name: "sky-blue panorama", hex: "#5B8798" },
      { name: "celadon fermentation", hex: "#78998B" },
      { name: "plum royal pattern", hex: "#744B67" },
    ],
    motifs: [
      {
        label: "one high skyline band",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.29,
        width: 0.78,
        height: 0.2,
      },
      {
        label: "one panoramic window arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.49,
        width: 0.78,
        height: 0.68,
      },
      {
        label: "one fermentation vessel oval",
        kind: "oval",
        count: 1,
        colorIndex: 3,
        x: 0.37,
        y: 0.59,
        width: 0.28,
        height: 0.34,
      },
      {
        label: "one royal-pattern fan",
        kind: "leaf",
        count: 1,
        colorIndex: 4,
        x: 0.66,
        y: 0.58,
        width: 0.32,
        height: 0.36,
      },
    ],
    relationship:
      "The panoramic arch frames the high skyline, while fermentation vessel and royal-pattern fan share the lower menu field as distinct traditions.",
    edgeStrategy: fullBleed,
  }),
] as const;
