import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles03bPart1 = [
  defineRestaurantArtProfile({
    slug: "le-bernardin",
    sourceCue:
      "A thin sheet of yellowfin tuna over a foie-gras-topped baguette expresses the seafood kitchen's quiet French precision.",
    styleSignature: "painted-mass",
    palette: [
      { name: "formal-charcoal ground", hex: "#293034" },
      { name: "baguette-ivory construction", hex: "#F0E1C3" },
      { name: "tuna-rose veil", hex: "#C96E70" },
      { name: "seafood-blue precision", hex: "#3E6D80" },
      { name: "foie-gras gold", hex: "#C69643" },
    ],
    motifs: [
      {
        label: "one broad tuna veil",
        kind: "ribbon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.45,
        width: 0.68,
        height: 0.24,
      },
      {
        label: "one slender baguette block",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.62,
        width: 0.62,
        height: 0.16,
      },
      {
        label: "one seafood-kitchen wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.72,
        width: 0.72,
        height: 0.13,
      },
      {
        label: "one foie-gras oval",
        kind: "oval",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.53,
        width: 0.29,
        height: 0.19,
      },
    ],
    relationship:
      "The tuna veil covers the foie-gras oval and slender baguette in one precise stack, with the seafood wave held quietly below.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "the-modern",
    sourceCue: "A bright dining room opens directly toward the Museum of Modern Art's sculpture garden.",
    styleSignature: "geometric-facet",
    palette: [
      { name: "gallery-ivory ground", hex: "#ECE6D9" },
      { name: "soft-graphite construction", hex: "#454D50" },
      { name: "garden-green opening", hex: "#52724D" },
      { name: "modern-blue accent", hex: "#3F6FA0" },
      { name: "sunlit-stone sculpture", hex: "#C3B89F" },
    ],
    motifs: [
      {
        label: "one broad garden window",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.57,
        y: 0.39,
        width: 0.62,
        height: 0.45,
      },
      {
        label: "one sculptural oval",
        kind: "oval",
        count: 1,
        colorIndex: 4,
        x: 0.64,
        y: 0.46,
        width: 0.3,
        height: 0.36,
      },
      {
        label: "one bright room plane",
        kind: "horizon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.7,
        width: 0.75,
        height: 0.2,
      },
      {
        label: "one gallery-frame band",
        kind: "horizon",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.2,
        width: 0.73,
        height: 0.13,
      },
    ],
    relationship:
      "The bright room plane opens toward the garden window and sculpture, with a restrained gallery-frame band above the museum view.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "yingtao",
    sourceCue:
      "A curved chef's counter overlooks YingTao's open kitchen, where Berkshire-pork-and-tiger-prawn wontons float in broth before a coconut-forward nian gao.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "ink-black ground", hex: "#25292D" },
      { name: "porcelain-ivory wonton", hex: "#F0E4CC" },
      { name: "cherry-crimson interior accent", hex: "#A93F45" },
      { name: "broth-gold bowl", hex: "#C99B3E" },
    ],
    motifs: [
      {
        label: "one curved chef-counter crescent",
        kind: "arch",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.43,
        width: 0.78,
        height: 0.57,
      },
      {
        label: "two pleated pork-and-prawn wontons",
        kind: "triangle",
        count: 2,
        colorIndex: 1,
        x: 0.5,
        y: 0.5,
        width: 0.27,
        height: 0.24,
        spreadX: 0.29,
      },
      {
        label: "one golden broth bowl",
        kind: "oval",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.61,
        width: 0.64,
        height: 0.3,
      },
    ],
    layerOrder: [0, 2, 1],
    relationship:
      "A cherry-crimson crescent abstracts the curved counter behind a gold broth bowl and two broad pleated wonton silhouettes.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "aquavit",
    sourceCue:
      "Nordic light woods and a restrained room frame Scandinavian traditions including herring, gravlax, and preserved flavors.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "restrained-blue ground", hex: "#3E6273" },
      { name: "silver-gray construction", hex: "#A6B1B2" },
      { name: "pale-birch room", hex: "#D8C39A" },
      { name: "herring-silver fish", hex: "#738B94" },
      { name: "dill-green preserve", hex: "#5B784C" },
    ],
    motifs: [
      {
        label: "one pale timber plane",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.44,
        width: 0.68,
        height: 0.55,
      },
      {
        label: "one restrained-room horizon",
        kind: "horizon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.69,
        width: 0.75,
        height: 0.16,
      },
      {
        label: "one herring-silver crescent",
        kind: "arch",
        count: 1,
        colorIndex: 3,
        x: 0.37,
        y: 0.45,
        width: 0.4,
        height: 0.25,
      },
      {
        label: "one preserved-flavor jar arch",
        kind: "arch",
        count: 1,
        colorIndex: 4,
        x: 0.68,
        y: 0.43,
        width: 0.3,
        height: 0.43,
      },
    ],
    relationship:
      "The herring crescent and preserved-flavor jar occupy separate areas of the pale timber room above one restrained horizon.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "per-se",
    sourceCue:
      "A blue entrance door leads to a fireplace and broad Central Park views in the formal dining room.",
    styleSignature: "lead-cell",
    palette: [
      { name: "doorway-blue ground", hex: "#315B7A" },
      { name: "limestone-cream construction", hex: "#EEE2CA" },
      { name: "park-green canopy", hex: "#4D714D" },
      { name: "hearth-amber fire", hex: "#C87532" },
      { name: "formal-charcoal room", hex: "#30373A" },
    ],
    motifs: [
      {
        label: "one blue doorway arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.28,
        y: 0.45,
        width: 0.35,
        height: 0.54,
      },
      {
        label: "one fireplace block",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.58,
        width: 0.3,
        height: 0.31,
      },
      {
        label: "one park-canopy horizon",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.65,
        y: 0.48,
        width: 0.47,
        height: 0.25,
      },
      {
        label: "one tall window plane",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.72,
        y: 0.35,
        width: 0.28,
        height: 0.48,
      },
    ],
    relationship:
      "The blue doorway leads toward the fireplace, with the tall window and broad park canopy opening beside the formal room's hearth.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "masa",
    sourceCue:
      "A strikingly smooth hinoki counter creates a calm ceremonial setting for an imaginative luxury omakase.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "deep-charcoal ground", hex: "#252B2C" },
      { name: "pearl-gray construction", hex: "#B6BDB9" },
      { name: "hinoki-honey counter", hex: "#C49A5D" },
      { name: "shell-blue ceremony", hex: "#4F7485" },
      { name: "luxury-gold accent", hex: "#C5973D" },
    ],
    motifs: [
      {
        label: "one smooth hinoki counter",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.7,
        width: 0.76,
        height: 0.2,
      },
      {
        label: "one calm circular field",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.42,
        width: 0.52,
        height: 0.52,
      },
      {
        label: "one omakase plate crescent",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.42,
        y: 0.5,
        width: 0.42,
        height: 0.25,
      },
      {
        label: "one ceremonial serving wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.58,
        y: 0.59,
        width: 0.48,
        height: 0.14,
      },
    ],
    relationship:
      "The plate crescent and ceremonial wave rest in the calm circular field, all grounded by the unusually smooth hinoki counter.",
    edgeStrategy: fullBleed,
  }),
] as const;
