import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles03bPart2 = [
  defineRestaurantArtProfile({
    slug: "jean-georges",
    sourceCue:
      "A light-filled room at Central Park West frames French technique sharpened by Asian aromatics and bright acidity.",
    styleSignature: "lead-cell",
    palette: [
      { name: "soft-gray ground", hex: "#687274" },
      { name: "warm-ivory construction", hex: "#F1E6CF" },
      { name: "park-green canopy", hex: "#50734C" },
      { name: "citrus-gold acidity", hex: "#D2A02F" },
      { name: "aromatic-teal leaf", hex: "#397274" },
    ],
    motifs: [
      {
        label: "one luminous window arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.47,
        width: 0.76,
        height: 0.68,
      },
      {
        label: "one park-green canopy",
        kind: "leaf",
        count: 1,
        colorIndex: 2,
        x: 0.34,
        y: 0.55,
        width: 0.4,
        height: 0.39,
      },
      {
        label: "one citrus-gold disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.69,
        y: 0.35,
        width: 0.25,
        height: 0.25,
      },
      {
        label: "one aromatic leaf curve",
        kind: "leaf",
        count: 1,
        colorIndex: 4,
        x: 0.63,
        y: 0.58,
        width: 0.31,
        height: 0.37,
      },
    ],
    relationship:
      "The park canopy and aromatic leaf share the luminous window, sharpened by one separate citrus disk in the bright upper field.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "cafe-boulud",
    sourceCue:
      "Café Boulud's Art Deco-inspired room frames black sea bass wrapped in crispy potato, set over leek fondue with a rich red-wine sauce meurette.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "midnight-blue ground", hex: "#243A54" },
      { name: "warm-ivory Art Deco frame", hex: "#EFE0C5" },
      { name: "crispy-potato gold", hex: "#C99A3B" },
      { name: "ink-blue sea bass", hex: "#3B6577" },
      { name: "burgundy meurette", hex: "#7A3440" },
      { name: "leek-green fondue", hex: "#617749" },
    ],
    motifs: [
      {
        label: "one pointed black-sea-bass silhouette",
        kind: "fish",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.4,
        width: 0.58,
        height: 0.27,
      },
      {
        label: "two diagonal crispy-potato bands",
        kind: "stripe",
        count: 2,
        colorIndex: 2,
        x: 0.5,
        y: 0.4,
        width: 0.16,
        height: 0.26,
        spreadX: 0.21,
      },
      {
        label: "one burgundy meurette-sauce pool",
        kind: "oval",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.72,
        width: 0.6,
        height: 0.2,
      },
      {
        label: "one stepped Art Deco corner",
        kind: "corner",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.45,
        width: 0.8,
        height: 0.72,
      },
    ],
    layerOrder: [3, 2, 0, 1],
    relationship:
      "A broad stepped Art Deco corner frames the pointed fish over burgundy sauce while two diagonal potato bands cross its body without becoming microtexture.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "daniel",
    sourceCue:
      "Grand neoclassical arches and columns give the formal Upper East Side dining room a stately architectural rhythm.",
    styleSignature: "painted-mass",
    palette: [
      { name: "deep-blue ground", hex: "#2E4E6B" },
      { name: "stone-cream construction", hex: "#EDE2CB" },
      { name: "antique-gold rhythm", hex: "#B98B3E" },
      { name: "soft-plum room", hex: "#77566F" },
      { name: "floor-slate plane", hex: "#667176" },
    ],
    motifs: [
      {
        label: "three neoclassical arches",
        kind: "arch",
        count: 3,
        colorIndex: 1,
        x: 0.5,
        y: 0.38,
        width: 0.18,
        height: 0.4,
        spreadX: 0.23,
      },
      {
        label: "two broad column blocks",
        kind: "block",
        count: 2,
        colorIndex: 2,
        x: 0.5,
        y: 0.49,
        width: 0.17,
        height: 0.56,
        spreadX: 0.43,
      },
      {
        label: "one formal floor plane",
        kind: "horizon",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.74,
        width: 0.78,
        height: 0.18,
      },
      {
        label: "one architectural rhythm band",
        kind: "horizon",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.6,
        width: 0.68,
        height: 0.12,
      },
    ],
    layerOrder: [2, 3, 1, 0],
    relationship:
      "Three distinct arches repeat between two separate columns, while the rhythm band and floor plane reinforce the stately horizontal order.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "sushi-noz",
    sourceCue:
      "A cedar-lined room and hinoki counter evoke an old Kyoto setting for a rigorous Edomae omakase.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "cedar-brown ground", hex: "#604232" },
      { name: "rice-ivory construction", hex: "#F0E3C9" },
      { name: "hinoki-honey counter", hex: "#C3995D" },
      { name: "Edomae-blue tasting", hex: "#436B7C" },
      { name: "old-room amber", hex: "#A76E3F" },
    ],
    motifs: [
      {
        label: "one hinoki counter band",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.7,
        width: 0.76,
        height: 0.2,
      },
      {
        label: "one cedar room arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.48,
        width: 0.76,
        height: 0.68,
      },
      {
        label: "one old-room wall plane",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.34,
        y: 0.4,
        width: 0.34,
        height: 0.45,
      },
      {
        label: "one Edomae tasting disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.66,
        y: 0.43,
        width: 0.28,
        height: 0.28,
      },
    ],
    layerOrder: [0, 2, 1, 3],
    relationship:
      "The cedar arch and old-room plane surround the hinoki counter, with one rigorous Edomae tasting disk held clear in the service field.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "essential-by-christophe",
    sourceCue:
      "Essential's heavy iron doors, leather, brass, and beige room frame three blue prawns with genmaicha tuile, Kirby chutney, and dill-and-chive bouillon.",
    styleSignature: "painted-mass",
    palette: [
      { name: "warm-beige ground", hex: "#B49A7E" },
      { name: "soft-brass construction", hex: "#B18B43" },
      { name: "iron-black doorway", hex: "#2B3031" },
      { name: "prawn-cobalt mass", hex: "#356B8B" },
      { name: "toasted-tan genmaicha", hex: "#BE8C4D" },
      { name: "herb-green bouillon", hex: "#647B52" },
    ],
    motifs: [
      {
        label: "three broad blue-prawn curls",
        kind: "prawn",
        count: 3,
        colorIndex: 3,
        x: 0.5,
        y: 0.48,
        width: 0.22,
        height: 0.3,
        spreadX: 0.24,
      },
      {
        label: "one toasted genmaicha tuile",
        kind: "triangle",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.75,
        width: 0.25,
        height: 0.18,
      },
      {
        label: "one herb-green bouillon disk",
        kind: "disk",
        count: 1,
        colorIndex: 5,
        x: 0.5,
        y: 0.56,
        width: 0.62,
        height: 0.52,
      },
      {
        label: "one iron doorway with brass-and-beige field",
        kind: "corner",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.45,
        width: 0.8,
        height: 0.74,
      },
    ],
    layerOrder: [3, 2, 0, 1],
    relationship:
      "The iron doorway with its brass construction edge contains a green bouillon disk and three cobalt prawn curls, with one toasted tuile kept separate below.",
    edgeStrategy: fullBleed,
  }),
] as const;
