import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles03aPart1 = [
  defineRestaurantArtProfile({
    slug: "noksu",
    sourceCue:
      "A passage inside a subway station leads to a dark, theatrical twelve-seat counter facing the kitchen.",
    styleSignature: "screenprint-overlap",
    palette: [
      { name: "subway-charcoal ground", hex: "#242B2E" },
      { name: "steel-gray construction", hex: "#899599" },
      { name: "stage-amber light", hex: "#D08A34" },
      { name: "deep-navy kitchen", hex: "#263E52" },
      { name: "counter-ivory focus", hex: "#EEE1C9" },
    ],
    motifs: [
      {
        label: "one subway passage arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.31,
        y: 0.5,
        width: 0.42,
        height: 0.62,
      },
      {
        label: "one continuous counter band",
        kind: "horizon",
        count: 1,
        colorIndex: 4,
        x: 0.56,
        y: 0.67,
        width: 0.66,
        height: 0.19,
      },
      {
        label: "one theatrical light cone",
        kind: "cone",
        count: 1,
        colorIndex: 2,
        x: 0.57,
        y: 0.36,
        width: 0.34,
        height: 0.5,
      },
      {
        label: "one dark kitchen block",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.72,
        y: 0.4,
        width: 0.28,
        height: 0.4,
      },
    ],
    relationship:
      "The subway arch leads toward the continuous counter and kitchen block, with one theatrical cone isolating the service stage between them.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "oxomoco",
    sourceCue:
      "A skylit Greenpoint room filled with hanging plants supports a menu centered on wood-fired Mexican cooking.",
    styleSignature: "lead-cell",
    palette: [
      { name: "leaf-green ground", hex: "#426848" },
      { name: "stucco-cream construction", hex: "#EFE0C7" },
      { name: "sky-blue opening", hex: "#6491A0" },
      { name: "ember-amber fire", hex: "#D17B30" },
      { name: "wood-charcoal hearth", hex: "#303534" },
    ],
    motifs: [
      {
        label: "one broad skylight plane",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.18,
        width: 0.67,
        height: 0.16,
      },
      {
        label: "one hanging plant canopy",
        kind: "leaf",
        count: 1,
        colorIndex: 1,
        x: 0.33,
        y: 0.4,
        width: 0.43,
        height: 0.48,
      },
      {
        label: "one wood-fire disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.67,
        y: 0.55,
        width: 0.3,
        height: 0.3,
      },
      {
        label: "one low room arch",
        kind: "arch",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.59,
        width: 0.76,
        height: 0.5,
      },
    ],
    relationship:
      "The skylight illuminates the hanging canopy inside the low room arch, while the wood-fire disk anchors the cooking side below.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "tempura-matsui",
    sourceCue:
      "Counter seats reveal a traditional tempura sequence fried in sesame and cottonseed oils with an especially light batter.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "charcoal ground", hex: "#2A2E2D" },
      { name: "batter-ivory construction", hex: "#F2E5C9" },
      { name: "sesame-gold oil", hex: "#D09A35" },
      { name: "shiso-green accent", hex: "#56764E" },
      { name: "shrimp-coral crisp", hex: "#C76D58" },
    ],
    motifs: [
      {
        label: "one long chef counter",
        kind: "horizon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.7,
        width: 0.76,
        height: 0.19,
      },
      {
        label: "one pale batter arc",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.38,
        y: 0.44,
        width: 0.42,
        height: 0.3,
      },
      {
        label: "one sesame-gold oil wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.56,
        width: 0.6,
        height: 0.16,
      },
      {
        label: "one crisp shrimp-leg fan",
        kind: "leaf",
        count: 1,
        colorIndex: 4,
        x: 0.68,
        y: 0.39,
        width: 0.3,
        height: 0.42,
      },
    ],
    relationship:
      "The batter arc and crisp fan sit above the chef counter, joined by one broad oil wave that reads as the frying sequence.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "restaurant-yuu",
    sourceCue:
      "At service, curtains open to reveal the full kitchen team in a large warehouse-like room staged as a culinary performance.",
    styleSignature: "paper-layer",
    palette: [
      { name: "stage-charcoal ground", hex: "#242A30" },
      { name: "bright-ivory construction", hex: "#F1E6D0" },
      { name: "curtain-blue drape", hex: "#3F6280" },
      { name: "pastry-gold spotlight", hex: "#D3A03B" },
      { name: "steel-gray kitchen", hex: "#6D7A7E" },
    ],
    motifs: [
      {
        label: "two opening curtain bands",
        kind: "ribbon",
        count: 2,
        colorIndex: 2,
        x: 0.5,
        y: 0.4,
        width: 0.24,
        height: 0.62,
        spreadX: 0.4,
      },
      {
        label: "one broad kitchen stage",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.57,
        width: 0.62,
        height: 0.35,
      },
      {
        label: "one warehouse ceiling arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.48,
        width: 0.78,
        height: 0.7,
      },
      {
        label: "one spotlight disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.28,
        width: 0.23,
        height: 0.23,
      },
    ],
    relationship:
      "Two separate curtain bands open around the kitchen stage inside the warehouse arch, with one spotlight centered on the revealed team.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "chefs-table-at-brooklyn-fare",
    sourceCue:
      "A glossy walnut counter wraps around the visible brigade in a spotlighted room hidden behind a grocery store.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "deep-charcoal ground", hex: "#22292D" },
      { name: "spotlight-ivory construction", hex: "#F2E7D1" },
      { name: "walnut-brown counter", hex: "#704A35" },
      { name: "copper kitchen", hex: "#B46D3E" },
      { name: "store-slate doorway", hex: "#5C6970" },
    ],
    motifs: [
      {
        label: "one glossy walnut horseshoe",
        kind: "arch",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.61,
        width: 0.7,
        height: 0.47,
      },
      {
        label: "one central kitchen block",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.48,
        width: 0.31,
        height: 0.27,
      },
      {
        label: "one hidden-store doorway",
        kind: "arch",
        count: 1,
        colorIndex: 4,
        x: 0.27,
        y: 0.38,
        width: 0.29,
        height: 0.43,
      },
      {
        label: "one bright spotlight cone",
        kind: "cone",
        count: 1,
        colorIndex: 1,
        x: 0.58,
        y: 0.3,
        width: 0.32,
        height: 0.48,
      },
    ],
    relationship:
      "The hidden doorway leads to the walnut horseshoe around the kitchen block, while the spotlight cone isolates the visible brigade.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "sushi-sho",
    sourceCue:
      "A hinoki counter stands between towering carved-wood iceboxes as an omakase explores fermentation and preserved Edomae techniques.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "deep-charcoal ground", hex: "#252B2B" },
      { name: "ice-gray construction", hex: "#AEB7B6" },
      { name: "hinoki-honey counter", hex: "#C59658" },
      { name: "preserve-blue technique", hex: "#436C7C" },
      { name: "aged-amber fermentation", hex: "#A96A3D" },
    ],
    motifs: [
      {
        label: "one broad hinoki counter",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.69,
        width: 0.72,
        height: 0.2,
      },
      {
        label: "two towering icebox blocks",
        kind: "block",
        count: 2,
        colorIndex: 1,
        x: 0.5,
        y: 0.39,
        width: 0.23,
        height: 0.55,
        spreadX: 0.42,
      },
      {
        label: "one fermentation spiral",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.4,
        width: 0.26,
        height: 0.38,
      },
      {
        label: "one preserved-fish crescent",
        kind: "arch",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.57,
        width: 0.36,
        height: 0.22,
      },
    ],
    relationship:
      "Two individually legible iceboxes flank the fermentation spiral and preserved fish, all grounded by the broad hinoki counter.",
    edgeStrategy: fullBleed,
  }),
] as const;
