import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles02aPart1 = [
  defineRestaurantArtProfile({
    slug: "shmone",
    sourceCue:
      "A small, lively counter looks directly into the close-quarters kitchen as dishes emerge from changing market ingredients.",
    styleSignature: "relief-cut",
    palette: [
      { name: "charcoal ground", hex: "#29302E" },
      { name: "warm-cream construction", hex: "#EFE1C4" },
      { name: "warm-clay counter", hex: "#B96743" },
      { name: "olive-green market", hex: "#687447" },
      { name: "bread-gold flame", hex: "#CF9734" },
    ],
    motifs: [
      {
        label: "one compact counter arc",
        kind: "arch",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.61,
        width: 0.64,
        height: 0.4,
      },
      {
        label: "one open kitchen block",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.37,
        width: 0.42,
        height: 0.33,
      },
      {
        label: "one market-basket oval",
        kind: "oval",
        count: 1,
        colorIndex: 3,
        x: 0.3,
        y: 0.38,
        width: 0.28,
        height: 0.23,
      },
      {
        label: "one lively flame curve",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.7,
        y: 0.38,
        width: 0.24,
        height: 0.39,
      },
    ],
    relationship:
      "The compact counter opens directly toward the kitchen block, with market ingredients and one lively flame balancing its two work sides.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "tuome",
    sourceCue: "Tender octopus with pork XO sauce captures the menu's layered Asian-influenced contrasts.",
    styleSignature: "lead-cell",
    palette: [
      { name: "deep-plum ground", hex: "#49374D" },
      { name: "warm-ivory construction", hex: "#F0E0C7" },
      { name: "octopus-coral form", hex: "#C66D67" },
      { name: "xo-sauce brown", hex: "#754638" },
      { name: "ocean-blue contrast", hex: "#3A7180" },
    ],
    motifs: [
      {
        label: "one broad octopus curve",
        kind: "ribbon",
        count: 1,
        colorIndex: 2,
        x: 0.47,
        y: 0.5,
        width: 0.66,
        height: 0.42,
      },
      {
        label: "one dark sauce wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.52,
        y: 0.59,
        width: 0.6,
        height: 0.17,
      },
      {
        label: "one backlit bar block",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.71,
        width: 0.72,
        height: 0.17,
      },
      {
        label: "one bay-window arch",
        kind: "arch",
        count: 1,
        colorIndex: 4,
        x: 0.7,
        y: 0.36,
        width: 0.33,
        height: 0.42,
      },
    ],
    relationship:
      "The octopus curve overlaps the dark sauce wave above the backlit bar, while the window arch keeps the layered contrast open on one side.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "bar-miller",
    sourceCue:
      "An intimate wooden counter presents a sustainable omakase built around local seafood and carefully aged fish.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "walnut-brown ground", hex: "#54392E" },
      { name: "rice-ivory construction", hex: "#EFE3CC" },
      { name: "seafood-blue local catch", hex: "#3C6777" },
      { name: "aged-amber fish", hex: "#B47742" },
      { name: "counter-honey wood", hex: "#C19A66" },
    ],
    motifs: [
      {
        label: "one intimate wood counter",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.72,
        width: 0.8,
        height: 0.16,
      },
      {
        label: "one local-seafood wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 2,
        x: 0.55,
        y: 0.5,
        width: 0.6,
        height: 0.2,
      },
      {
        label: "one aged-fish crescent",
        kind: "arch",
        count: 1,
        colorIndex: 3,
        x: 0.68,
        y: 0.34,
        width: 0.32,
        height: 0.25,
      },
      {
        label: "one dry-aging cabinet block",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.23,
        y: 0.4,
        width: 0.22,
        height: 0.5,
      },
    ],
    layerOrder: [3, 0, 1, 2],
    relationship:
      "The aging cabinet anchors one side of the intimate counter; the local-seafood wave crosses its open work face toward the separate aged-fish crescent.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "tsukimi",
    sourceCue:
      "Illuminated ceramics, mirrored panels, and soft arches evoke the restaurant's moon-viewing name.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "midnight-blue ground", hex: "#203143" },
      { name: "silver-gray construction", hex: "#A9B4B8" },
      { name: "moon-ivory light", hex: "#F1E7D2" },
      { name: "soft-mauve arch", hex: "#9B758C" },
      { name: "mirror-blue plane", hex: "#54778A" },
    ],
    motifs: [
      {
        label: "one luminous moon disk",
        kind: "disk",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.33,
        width: 0.3,
        height: 0.3,
      },
      {
        label: "two soft room arches",
        kind: "arch",
        count: 2,
        colorIndex: 3,
        x: 0.5,
        y: 0.58,
        width: 0.3,
        height: 0.5,
        spreadX: 0.34,
      },
      {
        label: "one mirrored vertical plane",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.54,
        width: 0.18,
        height: 0.58,
      },
      {
        label: "one ceramic vessel oval",
        kind: "oval",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.68,
        width: 0.28,
        height: 0.2,
      },
    ],
    relationship:
      "Two individually legible arches flank the mirrored plane; the moon disk illuminates them above one centered ceramic vessel.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "semma",
    sourceCue:
      "A crisp gunpowder dosa wrapped around potato masala expresses the kitchen's focus on regional South Indian cooking.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "spice-brown ground", hex: "#654432" },
      { name: "coconut-cream construction", hex: "#F1E2C3" },
      { name: "turmeric-gold dosa", hex: "#D3A130" },
      { name: "potato-gold center", hex: "#C78432" },
      { name: "palm-green fan", hex: "#4F754E" },
    ],
    motifs: [
      {
        label: "one broad dosa spiral",
        kind: "ribbon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.53,
        width: 0.68,
        height: 0.42,
      },
      {
        label: "one potato-gold oval",
        kind: "oval",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.53,
        width: 0.3,
        height: 0.2,
      },
      {
        label: "one palm-leaf fan",
        kind: "leaf",
        count: 1,
        colorIndex: 4,
        x: 0.28,
        y: 0.34,
        width: 0.3,
        height: 0.38,
      },
      {
        label: "one spice-colored sun",
        kind: "disk",
        count: 1,
        colorIndex: 1,
        x: 0.71,
        y: 0.33,
        width: 0.22,
        height: 0.22,
      },
    ],
    relationship:
      "The crisp dosa spiral wraps the potato oval, balanced by one leaf fan and a separate spice disk in the upper field.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "kosaka",
    sourceCue:
      "A classic twelve-seat counter and subdued room keep attention on the measured omakase progression.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "deep-navy ground", hex: "#20313C" },
      { name: "rice-ivory construction", hex: "#F0E4CC" },
      { name: "pale-oak counter", hex: "#C9A878" },
      { name: "soft-graphite room", hex: "#555F61" },
      { name: "quiet-sea blue", hex: "#476D7A" },
    ],
    motifs: [
      {
        label: "one long counter band",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.7,
        width: 0.78,
        height: 0.19,
      },
      {
        label: "one continuous seat arcade",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.57,
        width: 0.68,
        height: 0.36,
      },
      {
        label: "one measured course disk",
        kind: "disk",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.37,
        width: 0.25,
        height: 0.25,
      },
      {
        label: "one pale ceiling plane",
        kind: "horizon",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.17,
        width: 0.76,
        height: 0.13,
      },
    ],
    relationship:
      "The seat arcade connects the long counter to the pale ceiling plane, keeping the measured course disk centered for the progression.",
    edgeStrategy: fullBleed,
  }),
] as const;
