import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles03aPart2 = [
  defineRestaurantArtProfile({
    slug: "gabriel-kreuther",
    sourceCue:
      "A cavernous Bryant Park room uses cream banquettes, fine art, and sparkling table settings for polished Alsatian-rooted dining.",
    styleSignature: "lead-cell",
    palette: [
      { name: "soft-graphite ground", hex: "#3A4245" },
      { name: "cream construction", hex: "#F0E4CF" },
      { name: "park-green horizon", hex: "#4F704E" },
      { name: "Alsatian-gold sparkle", hex: "#C89539" },
      { name: "art-blue field", hex: "#536F86" },
    ],
    motifs: [
      {
        label: "one cavernous room arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.5,
        width: 0.8,
        height: 0.72,
      },
      {
        label: "one cream banquette crescent",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.38,
        y: 0.62,
        width: 0.45,
        height: 0.28,
      },
      {
        label: "one framed art block",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.67,
        y: 0.38,
        width: 0.28,
        height: 0.35,
      },
      {
        label: "one park-green horizon",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.71,
        width: 0.72,
        height: 0.13,
      },
    ],
    relationship:
      "The cavernous arch contains the banquette and art block, while the park horizon runs beneath both as the room's polished base.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "le-pavillon",
    sourceCue:
      "Soaring ceilings, plate glass, a warm palette, and a blown-glass chandelier define the skyscraper dining room.",
    styleSignature: "lead-cell",
    palette: [
      { name: "warm-amber ground", hex: "#A3633D" },
      { name: "soft-cream construction", hex: "#EFE2C8" },
      { name: "glass-blue window", hex: "#5B8496" },
      { name: "vegetable-green accent", hex: "#5E7A4C" },
      { name: "chandelier-gold light", hex: "#D1A03A" },
    ],
    motifs: [
      {
        label: "one soaring ceiling arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.48,
        width: 0.78,
        height: 0.72,
      },
      {
        label: "one plate-glass window",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.67,
        y: 0.4,
        width: 0.34,
        height: 0.52,
      },
      {
        label: "one blown-glass chandelier",
        kind: "oval",
        count: 1,
        colorIndex: 4,
        x: 0.38,
        y: 0.32,
        width: 0.29,
        height: 0.34,
      },
      {
        label: "one skyline horizon band",
        kind: "horizon",
        count: 1,
        colorIndex: 3,
        x: 0.58,
        y: 0.67,
        width: 0.62,
        height: 0.14,
      },
    ],
    relationship:
      "The chandelier hangs inside the soaring arch opposite the plate-glass window, with the skyline horizon held broad and low.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "joji",
    sourceCue:
      "A calm counter beneath One Vanderbilt pairs Toyosu seafood with carefully vinegared blended rice and seasonal Japanese accents.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "tower-blue ground", hex: "#315A6D" },
      { name: "rice-ivory construction", hex: "#F0E4CC" },
      { name: "cypress-tan counter", hex: "#C39B67" },
      { name: "yuzu-gold season", hex: "#D0A132" },
      { name: "tower-slate base", hex: "#5D6D75" },
    ],
    motifs: [
      {
        label: "one calm counter band",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.7,
        width: 0.75,
        height: 0.19,
      },
      {
        label: "one tower-base arch",
        kind: "arch",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.45,
        width: 0.64,
        height: 0.57,
      },
      {
        label: "one blended-rice crescent",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.39,
        y: 0.49,
        width: 0.4,
        height: 0.24,
      },
      {
        label: "one Toyosu-seafood wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.6,
        y: 0.45,
        width: 0.46,
        height: 0.16,
      },
    ],
    relationship:
      "The tower-base arch shelters the calm counter, where blended rice and the Toyosu seafood wave meet as two measured forms.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "meju",
    sourceCue:
      "An eight-seat L-shaped counter hides behind a banchan shop, facing an open kitchen while decade-aged Korean ferments shape the menu.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "ink-black ground", hex: "#23292A" },
      { name: "soybean-gold construction", hex: "#C7993D" },
      { name: "earthen-brown vessel", hex: "#784D38" },
      { name: "celadon ferment", hex: "#7E9B8C" },
      { name: "shop-ivory doorway", hex: "#EEE1C9" },
    ],
    motifs: [
      {
        label: "one hidden market doorway",
        kind: "arch",
        count: 1,
        colorIndex: 4,
        x: 0.29,
        y: 0.43,
        width: 0.37,
        height: 0.53,
      },
      {
        label: "three fermentation vessel ovals",
        kind: "oval",
        count: 3,
        colorIndex: 2,
        x: 0.55,
        y: 0.52,
        width: 0.17,
        height: 0.25,
        spreadX: 0.21,
      },
      {
        label: "one cellar shelf block",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.57,
        y: 0.7,
        width: 0.65,
        height: 0.16,
      },
      {
        label: "one slow-rising spiral",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.71,
        y: 0.3,
        width: 0.22,
        height: 0.38,
      },
    ],
    relationship:
      "The hidden doorway opens onto three separate fermentation vessels above the cellar shelf, with one slow spiral marking their age.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "kochi",
    sourceCue:
      "A Korean tasting menu is organized around composed skewers, drawing inspiration from royal-court and street-food traditions.",
    styleSignature: "fiber-applique",
    palette: [
      { name: "deep-teal ground", hex: "#254F55" },
      { name: "warm-ivory construction", hex: "#EFE1C7" },
      { name: "sesame-gold skewer", hex: "#C99A38" },
      { name: "plum royal accent", hex: "#724B65" },
      { name: "grill-charcoal street", hex: "#303638" },
    ],
    motifs: [
      {
        label: "three broad skewer diagonals",
        kind: "ribbon",
        count: 3,
        colorIndex: 2,
        x: 0.5,
        y: 0.48,
        width: 0.16,
        height: 0.52,
        spreadX: 0.22,
      },
      {
        label: "one royal-fan arc",
        kind: "leaf",
        count: 1,
        colorIndex: 3,
        x: 0.28,
        y: 0.34,
        width: 0.3,
        height: 0.38,
      },
      {
        label: "one street-grill disk",
        kind: "disk",
        count: 1,
        colorIndex: 4,
        x: 0.7,
        y: 0.37,
        width: 0.25,
        height: 0.25,
      },
      {
        label: "one street-food counter band",
        kind: "horizon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.72,
        width: 0.74,
        height: 0.17,
      },
    ],
    relationship:
      "Three distinct skewers rise from the street-food counter between the royal fan and grill disk, keeping both cited traditions legible.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "mari",
    sourceCue: "A multi-course tasting sequence builds Korean flavors into carefully folded hand rolls.",
    styleSignature: "paper-layer",
    palette: [
      { name: "seaweed-green ground", hex: "#294C3D" },
      { name: "rice-ivory construction", hex: "#F0E4CC" },
      { name: "sesame-gold center", hex: "#C99B3B" },
      { name: "pickled-coral accent", hex: "#C76658" },
      { name: "tasting-blue band", hex: "#456B82" },
    ],
    motifs: [
      {
        label: "three folded seaweed cones",
        kind: "cone",
        count: 3,
        colorIndex: 1,
        x: 0.5,
        y: 0.47,
        width: 0.18,
        height: 0.4,
        spreadX: 0.22,
      },
      {
        label: "one rice-ivory wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.58,
        width: 0.62,
        height: 0.15,
      },
      {
        label: "one sesame disk",
        kind: "disk",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.3,
        width: 0.2,
        height: 0.2,
      },
      {
        label: "one tasting-course band",
        kind: "horizon",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.72,
        width: 0.74,
        height: 0.16,
      },
    ],
    relationship:
      "Three individually legible seaweed cones progress across the tasting band, linked by one rice wave beneath a centered sesame disk.",
    edgeStrategy: fullBleed,
  }),
] as const;
