import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles01aPart2 = [
  defineRestaurantArtProfile({
    slug: "bridges",
    sourceCue:
      "Cured tuna, mushrooms, and dates express the warm, contemporary bistro's preference for layered savory contrasts.",
    styleSignature: "painted-mass",
    palette: [
      { name: "warm-amber ground", hex: "#A85D3F" },
      { name: "cream construction", hex: "#F0E2CA" },
      { name: "tuna-rose layer", hex: "#C86F6E" },
      { name: "mushroom-taupe caps", hex: "#8A715D" },
      { name: "date-brown center", hex: "#5B3A32" },
    ],
    motifs: [
      {
        label: "one broad tuna crescent",
        kind: "oval",
        count: 1,
        colorIndex: 2,
        x: 0.48,
        y: 0.48,
        width: 0.62,
        height: 0.3,
      },
      {
        label: "two mushroom-cap disks",
        kind: "disk",
        count: 2,
        colorIndex: 3,
        x: 0.5,
        y: 0.31,
        width: 0.2,
        height: 0.2,
        spreadX: 0.32,
      },
      {
        label: "one date-brown oval",
        kind: "oval",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.52,
        width: 0.25,
        height: 0.18,
      },
      {
        label: "one amber room arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.53,
        width: 0.78,
        height: 0.68,
      },
    ],
    relationship:
      "The room arch contains a layered tuna crescent, two separate mushroom caps, and one dark date oval as the savory focal stack.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "yamada",
    sourceCue:
      "A pale earth-toned L-shaped counter faces ikebana and a dry garden visible through the windows.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "sand ground", hex: "#C5B28D" },
      { name: "stone-gray construction", hex: "#50595A" },
      { name: "pale-oak counter", hex: "#D9BD87" },
      { name: "sage-green ikebana", hex: "#74866C" },
      { name: "dry-garden ivory", hex: "#EEE4CE" },
    ],
    motifs: [
      {
        label: "one L-shaped pale counter",
        kind: "corner",
        count: 1,
        colorIndex: 2,
        x: 0.39,
        y: 0.67,
        width: 0.68,
        height: 0.34,
      },
      {
        label: "one raked garden field",
        kind: "horizon",
        count: 1,
        colorIndex: 4,
        x: 0.7,
        y: 0.37,
        width: 0.27,
        height: 0.18,
      },
      {
        label: "one branch-like ikebana curve",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.38,
        y: 0.4,
        width: 0.2,
        height: 0.26,
      },
      {
        label: "one square window frame",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.7,
        y: 0.35,
        width: 0.36,
        height: 0.38,
      },
    ],
    layerOrder: [3, 1, 0, 2],
    relationship:
      "The angled counter faces the framed garden field; the ikebana curve rises between the counter and window as the sole organic form.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "le-coucou",
    sourceCue:
      "An ornate bar and hand-painted murals give the lofty room an eighteenth-century French atmosphere.",
    styleSignature: "painted-mass",
    palette: [
      { name: "parchment ground", hex: "#DCCBA8" },
      { name: "walnut construction", hex: "#4D352C" },
      { name: "dusty-blue mural", hex: "#657B88" },
      { name: "antique-gold ornament", hex: "#B78A3F" },
      { name: "plaster-ivory light", hex: "#F0E5CF" },
    ],
    motifs: [
      {
        label: "one ornate bar arch",
        kind: "arch",
        count: 1,
        colorIndex: 3,
        x: 0.34,
        y: 0.56,
        width: 0.48,
        height: 0.54,
      },
      {
        label: "one broad mural field",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.62,
        y: 0.4,
        width: 0.54,
        height: 0.44,
      },
      {
        label: "one tall window block",
        kind: "block",
        count: 1,
        colorIndex: 4,
        x: 0.74,
        y: 0.37,
        width: 0.2,
        height: 0.5,
      },
      {
        label: "one sweeping chandelier curve",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.22,
        width: 0.62,
        height: 0.2,
      },
    ],
    relationship:
      "The mural and tall window establish the lofty rear plane, while the ornate bar and chandelier curve overlap in the warm foreground.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "muku",
    sourceCue:
      "Chef Manabu Asanuma's kaiseki progression moves from sashimi through steamed, charcoal-grilled, and fried courses to Yamagata soba made with his family's hometown buckwheat.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "mist-blue ground", hex: "#708999" },
      { name: "charcoal construction", hex: "#283236" },
      { name: "sashimi coral", hex: "#C77B68" },
      { name: "charcoal ember", hex: "#C08A3C" },
      { name: "buckwheat green", hex: "#526E50" },
    ],
    motifs: [
      {
        label: "one sashimi disk",
        kind: "disk",
        count: 1,
        colorIndex: 2,
        x: 0.28,
        y: 0.35,
        width: 0.27,
        height: 0.27,
      },
      {
        label: "one steamed-course oval",
        kind: "oval",
        count: 1,
        colorIndex: 1,
        x: 0.6,
        y: 0.31,
        width: 0.34,
        height: 0.22,
      },
      {
        label: "one charcoal-grill ribbon",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.48,
        y: 0.55,
        width: 0.64,
        height: 0.16,
      },
      {
        label: "one Yamagata buckwheat leaf",
        kind: "leaf",
        count: 1,
        colorIndex: 4,
        x: 0.66,
        y: 0.7,
        width: 0.28,
        height: 0.3,
      },
    ],
    relationship:
      "Sashimi and a steamed course begin the upper sequence; the charcoal ribbon leads down to the Yamagata buckwheat leaf.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "labeille",
    sourceCue:
      "Velvet seating, intimate booths, and a marble bar frame cooking shaped by French technique and Japanese influence.",
    styleSignature: "fiber-applique",
    palette: [
      { name: "deep-plum ground", hex: "#4A334A" },
      { name: "marble-cream construction", hex: "#EEE2CC" },
      { name: "honey-gold light", hex: "#C58D32" },
      { name: "ink-blue screen", hex: "#2F5064" },
      { name: "velvet-rose booth", hex: "#985B6B" },
    ],
    motifs: [
      {
        label: "one velvet booth crescent",
        kind: "arch",
        count: 1,
        colorIndex: 4,
        x: 0.34,
        y: 0.57,
        width: 0.48,
        height: 0.4,
      },
      {
        label: "one marble bar block",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.59,
        y: 0.66,
        width: 0.54,
        height: 0.18,
      },
      {
        label: "one folded screen plane",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.68,
        y: 0.39,
        width: 0.34,
        height: 0.44,
      },
      {
        label: "one honeyed light disk",
        kind: "disk",
        count: 1,
        colorIndex: 2,
        x: 0.38,
        y: 0.29,
        width: 0.2,
        height: 0.2,
      },
    ],
    relationship:
      "The booth crescent and marble bar frame the folded screen, with a single honey light bridging the intimate seating and precise counter.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "corima",
    sourceCue:
      "Northern Mexican traditions meet a live-fire tasting format, with wheat tortillas and desert ingredients as recurring anchors.",
    styleSignature: "relief-cut",
    palette: [
      { name: "charcoal ground", hex: "#2B2C28" },
      { name: "wheat-cream construction", hex: "#EAD9B8" },
      { name: "desert-ochre ingredient", hex: "#B76F3C" },
      { name: "agave-green accent", hex: "#5D7650" },
      { name: "live-fire orange", hex: "#D45D2F" },
    ],
    motifs: [
      {
        label: "one desert-ingredient oval",
        kind: "oval",
        count: 1,
        colorIndex: 2,
        x: 0.32,
        y: 0.52,
        width: 0.36,
        height: 0.27,
      },
      {
        label: "one live-fire sun disk",
        kind: "disk",
        count: 1,
        colorIndex: 4,
        x: 0.7,
        y: 0.34,
        width: 0.26,
        height: 0.26,
      },
      {
        label: "one folded tortilla crescent",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.53,
        y: 0.61,
        width: 0.52,
        height: 0.33,
      },
      {
        label: "one rising smoke ribbon",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.64,
        y: 0.31,
        width: 0.18,
        height: 0.46,
      },
    ],
    layerOrder: [2, 0, 3, 1],
    relationship:
      "The tortilla folds around the desert ingredient oval beside the live-fire disk, while one broad smoke ribbon rises through the upper field.",
    edgeStrategy: fullBleed,
  }),
] as const;
