import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import type { RestaurantGeometryMotif, RestaurantMotifKind } from "./restaurant-art-profile";

const ARTBOARD = 896;

export const washingtonDcRestaurantArtProfilesPartOne = [
  defineRestaurantArtProfile({
    slug: "the-inn-at-little-washington",
    sourceCue: "Stately maximalist décor surrounds roaming bread and cheese carts.",
    styleSignature: "lead-cell",
    palette: [
      { name: "warm-cream glass", hex: "#F1E2C6" },
      { name: "charcoal lead", hex: "#25282B" },
      { name: "deep-plum drapery", hex: "#70455F" },
      { name: "antique-gold cart", hex: "#C39138" },
      { name: "garden-green decor", hex: "#4F704B" },
      { name: "cheese-wheel ivory", hex: "#DEC691" },
    ],
    motifs: [
      motif("one stately decor arch", "arch", 1, 2, 448, 450, 700, 610, 0, 0),
      motif("one maximalist decor wedge", "triangle", 1, 1, 448, 674, 760, 230, 0, 0),
      motif("one roaming cheese-wheel oval", "oval", 1, 5, 300, 506, 260, 190, 0, 0),
      motif("one tall service-cart block", "block", 1, 3, 620, 500, 240, 330, 0, 0),
    ],
    relationship: "Stately and maximalist decor masses hold a distinct cheese wheel beside the roaming cart.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "jont",
    sourceCue: "Chefs and servers move in rhythm around a compact kitchen counter.",
    styleSignature: "relief-cut",
    palette: [
      { name: "warm-ivory paper", hex: "#F0E2C8" },
      { name: "ink-black carved line", hex: "#23292C" },
      { name: "copper counter", hex: "#AF6242" },
      { name: "sea-blue motion", hex: "#3F7180" },
      { name: "plum treasure box", hex: "#6D4962" },
    ],
    motifs: [
      motif("one sweeping chef-counter arc", "arch", 1, 2, 448, 566, 700, 320, 0, 0),
      motif("one central kitchen block", "block", 1, 1, 448, 412, 340, 280, 0, 0),
      motif("two interlocking motion ribbons", "ribbon", 2, 3, 448, 330, 440, 92, 0, 120),
      motif("one compact counter rectangle", "block", 1, 4, 448, 646, 220, 150, 0, 0),
    ],
    relationship: "Two motion ribbons cross the compact kitchen block and connect both counter forms.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "minibar-by-jose-andres",
    sourceCue: "An all-white room leads to a twelve-seat wood kitchen counter.",
    styleSignature: "geometric-facet",
    palette: [
      { name: "white-room ground", hex: "#F2E9D8" },
      { name: "graphite facet edge", hex: "#293034" },
      { name: "walnut counter", hex: "#8E593F" },
      { name: "electric-blue laboratory", hex: "#3E6F91" },
      { name: "warm-gold transition", hex: "#C59439" },
      { name: "ivory anteroom", hex: "#D8CCB4" },
    ],
    motifs: [
      motif("one white anteroom block", "block", 1, 5, 268, 394, 320, 350, 0, 0),
      motif("one warm wood counter arc", "arch", 1, 2, 526, 596, 610, 290, 0, 0),
      motif("one twelve-seat counter block", "block", 1, 3, 562, 380, 310, 300, 0, 0),
      motif("one room-to-counter passage", "ribbon", 1, 1, 430, 370, 140, 260, 0, 0),
    ],
    relationship:
      "The white anteroom passes along one route into the twelve-seat block and long wood counter.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "xiquet",
    sourceCue: "Valencian rice with rabbit and mushrooms cooks over a wood-fired hearth.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "warm-cream glaze", hex: "#F1E4CA" },
      { name: "charcoal contour", hex: "#262A2C" },
      { name: "saffron rice", hex: "#D09A31" },
      { name: "smoke gray", hex: "#687074" },
      { name: "wood-fire umber", hex: "#95533A" },
      { name: "mushroom tan", hex: "#B88D60" },
    ],
    motifs: [
      motif("one broad hearth arch", "arch", 1, 4, 448, 468, 690, 580, 0, 0),
      motif("one rising smoke ribbon", "ribbon", 1, 3, 448, 260, 440, 104, 0, 0),
      motif("one saffron rice oval", "oval", 1, 2, 448, 530, 490, 260, 0, 0),
      motif("one wood-fire horizon band", "horizon", 1, 4, 448, 688, 790, 132, 0, 0),
    ],
    relationship: "The saffron rice rests within the broad hearth while smoke rises over a wood-fire band.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "rooster-and-owl",
    sourceCue: "Pistachio olive-oil cake combines blackberry and goat-cheese mousse.",
    styleSignature: "painted-mass",
    palette: [
      { name: "cream painted ground", hex: "#F2E5CD" },
      { name: "charcoal painted edge", hex: "#2A2F31" },
      { name: "pistachio green", hex: "#70814A" },
      { name: "blackberry purple", hex: "#6A4367" },
      { name: "olive gold", hex: "#B8933D" },
      { name: "goat-cheese cream", hex: "#DCC9AC" },
    ],
    motifs: [
      motif("one low cake block", "block", 1, 4, 448, 606, 560, 220, 0, 0),
      motif("one blackberry-purple disk", "disk", 1, 3, 312, 390, 260, 260, 0, 0),
      motif("one pistachio-green wave", "ribbon", 1, 2, 448, 500, 580, 116, 0, 0),
      motif("one soft cream arc", "arch", 1, 5, 590, 400, 300, 220, 0, 0),
    ],
    relationship: "The cake block supports separate blackberry, pistachio, and goat-cheese masses.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "masseria",
    sourceCue: "A brick warehouse room joins a steel kitchen, glass cellar, and terrace.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "warm-ivory room", hex: "#F0E1C4" },
      { name: "steel-charcoal join", hex: "#30373A" },
      { name: "clay-brick wall", hex: "#A95B43" },
      { name: "glass-blue cellar", hex: "#4D7484" },
      { name: "olive-green terrace", hex: "#61744C" },
    ],
    motifs: [
      motif("one broad brick wall block", "block", 1, 2, 300, 430, 450, 470, 0, 0),
      motif("one steel kitchen rectangle", "block", 1, 1, 600, 450, 310, 310, 0, 0),
      motif("one glass cellar arch", "arch", 1, 3, 448, 382, 300, 330, 0, 0),
      motif("one open terrace plane", "horizon", 1, 4, 448, 682, 780, 150, 0, 0),
    ],
    relationship: "Brick and steel room masses meet at a glass cellar above the open terrace plane.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "omakase-at-barracks-row",
    sourceCue: "Stairway art recalls printing inked fish onto rice paper in gyotaku.",
    styleSignature: "ink-contour",
    palette: [
      { name: "rice-paper ivory", hex: "#F0E5CF" },
      { name: "sumi-black ink", hex: "#20282C" },
      { name: "ocean-blue fish", hex: "#3D7082" },
      { name: "steel-gray stair", hex: "#697177" },
      { name: "warm-tan paper", hex: "#BE966B" },
    ],
    motifs: [
      motif("one ascending stair band", "ribbon", 1, 3, 330, 500, 570, 140, 0, 0),
      motif("one bold fish silhouette", "oval", 1, 1, 542, 362, 420, 210, 0, 0),
      motif("one rice-paper rectangle", "block", 1, 4, 544, 510, 410, 340, 0, 0),
      motif("one ink-wash disk", "disk", 1, 2, 258, 278, 230, 230, 0, 0),
    ],
    relationship: "The stair band leads into a rice-paper field carrying one inked fish and one wash disk.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "the-dabney",
    sourceCue: "Exposed brick, dark wood, and an open kitchen frame a wood-fired hearth.",
    styleSignature: "relief-cut",
    palette: [
      { name: "warm-cream paper", hex: "#F0E2C8" },
      { name: "charcoal carved line", hex: "#252A2B" },
      { name: "brick-brown wall", hex: "#A45740" },
      { name: "dark-wood beam", hex: "#654337" },
      { name: "hearth amber", hex: "#D08034" },
      { name: "herb green", hex: "#58744C" },
    ],
    motifs: [
      motif("one glowing hearth arch", "arch", 1, 4, 448, 512, 590, 490, 0, 0),
      motif("one dark wood beam", "horizon", 1, 3, 448, 244, 780, 110, 0, 0),
      motif("one brick wall field", "block", 1, 2, 448, 474, 760, 500, 0, 0),
      motif("one open-kitchen window", "block", 1, 5, 646, 312, 270, 260, 0, 0),
    ],
    layerOrder: [2, 1, 0, 3],
    relationship: "A dark beam and brick field frame the glowing wood hearth and open-kitchen window.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "elcielo-washington-dc",
    sourceCue: "A Colombian tasting moves from corn broth to a chocolate finale in two rooms.",
    styleSignature: "lead-cell",
    palette: [
      { name: "warm-ivory glass", hex: "#F1E4C9" },
      { name: "charcoal lead", hex: "#252A2C" },
      { name: "maize-gold corn", hex: "#D19A32" },
      { name: "cocoa-brown finale", hex: "#784A39" },
      { name: "leaf-green accent", hex: "#55734C" },
      { name: "room-blue glass", hex: "#4D7183" },
    ],
    motifs: [
      motif("one golden corn crescent", "arch", 1, 2, 300, 450, 320, 240, 0, 0),
      motif("one cocoa-colored wave", "ribbon", 1, 3, 448, 604, 630, 128, 0, 0),
      motif("two paired room arches", "arch", 2, 5, 448, 364, 260, 350, 280, 0),
      motif("one corn-broth horizon band", "horizon", 1, 2, 448, 708, 790, 120, 0, 0),
    ],
    relationship: "Two room arches carry a corn crescent and broth band toward the final cocoa wave.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "oyster-oyster",
    sourceCue: "The vegetable kitchen centers regenerative farms, reuse, and seasonality.",
    styleSignature: "fiber-applique",
    palette: [
      { name: "mushroom-cream textile", hex: "#F0E2C7" },
      { name: "night-blue stitch", hex: "#29394B" },
      { name: "leaf-green farm", hex: "#50734B" },
      { name: "soil-brown reuse", hex: "#806047" },
      { name: "sunflower gold", hex: "#CF9B35" },
      { name: "seasonal-produce beige", hex: "#D7C5A3" },
    ],
    motifs: [
      motif("one broad leaf oval", "leaf", 1, 2, 300, 414, 350, 300, 0, 0),
      motif("one seasonal produce dome", "arch", 1, 5, 594, 424, 320, 240, 0, 0),
      motif("one regenerative-farm disk", "disk", 1, 4, 448, 250, 220, 220, 0, 0),
      motif("one circular reuse band", "arch", 1, 3, 448, 536, 700, 520, 0, 0),
    ],
    relationship: "Vegetable, seasonal-produce, and regenerative-farm forms circulate within one reuse band.",
    edgeStrategy: "full-bleed",
  }),
  defineRestaurantArtProfile({
    slug: "pineapple-and-pearls",
    sourceCue: "Balloons, velvet jackets, pop music, and tableside theater evoke a lavish party.",
    styleSignature: "geometric-facet",
    palette: [
      { name: "warm-ivory light", hex: "#F2E4C8" },
      { name: "midnight-blue facet", hex: "#29384F" },
      { name: "velvet-plum lapel", hex: "#70465F" },
      { name: "champagne-gold glow", hex: "#C79A40" },
      { name: "teal party ribbon", hex: "#3F7774" },
    ],
    motifs: [
      motif("one large balloon disk", "disk", 1, 3, 300, 330, 310, 310, 0, 0),
      motif("one velvet lapel chevron", "triangle", 1, 2, 598, 396, 310, 350, 0, 0),
      motif("one tableside-theater circle", "disk", 1, 3, 594, 624, 190, 190, 0, 0),
      motif("one sweeping party ribbon", "ribbon", 1, 4, 448, 550, 700, 126, 0, 0),
    ],
    relationship:
      "A balloon and velvet lapel sit beside tableside theater while the party ribbon sweeps through.",
    edgeStrategy: "full-bleed",
  }),
] as const;

function motif(
  label: string,
  kind: RestaurantMotifKind,
  count: 1 | 2 | 3,
  colorIndex: number,
  x: number,
  y: number,
  width: number,
  height: number,
  spreadX: number,
  spreadY: number,
): RestaurantGeometryMotif {
  return {
    label,
    kind,
    count,
    colorIndex,
    x: x / ARTBOARD,
    y: y / ARTBOARD,
    width: width / ARTBOARD,
    height: height / ARTBOARD,
    spreadX: spreadX / ARTBOARD,
    spreadY: spreadY / ARTBOARD,
  };
}
