import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles01bPart2 = [
  defineRestaurantArtProfile({
    slug: "sixty-three-clinton",
    sourceCue:
      "A playful breakfast taco has become a signature within the understated Lower East Side tasting sequence.",
    styleSignature: "paper-layer",
    palette: [
      { name: "city-charcoal ground", hex: "#2D3234" },
      { name: "soft-cream construction", hex: "#F1E3C7" },
      { name: "corn-gold taco", hex: "#D0A13D" },
      { name: "sunrise-peach play", hex: "#D98567" },
      { name: "chili-red accent", hex: "#A84B37" },
    ],
    motifs: [
      {
        label: "one folded taco crescent",
        kind: "arch",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.53,
        width: 0.58,
        height: 0.36,
      },
      {
        label: "one rising sun disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.69,
        y: 0.29,
        width: 0.22,
        height: 0.22,
      },
      {
        label: "one low city-block band",
        kind: "horizon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.72,
        width: 0.76,
        height: 0.17,
      },
      {
        label: "one soft egg oval",
        kind: "oval",
        count: 1,
        colorIndex: 1,
        x: 0.47,
        y: 0.48,
        width: 0.24,
        height: 0.18,
      },
    ],
    relationship:
      "The egg oval rests inside the folded taco above the low city band, with one playful sunrise disk offset behind it.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "sushi-nakazawa-new-york",
    sourceCue:
      "A sleek ten-seat counter frames tender fish, seasoned rice, wasabi, and a restrained brush of nikiri.",
    styleSignature: "lead-cell",
    palette: [
      { name: "deep-charcoal ground", hex: "#1F292E" },
      { name: "rice-ivory construction", hex: "#F0E5D0" },
      { name: "ocean-blue fish", hex: "#3D6E7E" },
      { name: "wasabi-green accent", hex: "#6C824D" },
      { name: "nikiri-amber brush", hex: "#BD7139" },
    ],
    motifs: [
      {
        label: "one sleek counter band",
        kind: "horizon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.7,
        width: 0.78,
        height: 0.18,
      },
      {
        label: "one continuous seat arcade",
        kind: "arch",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.57,
        width: 0.68,
        height: 0.36,
      },
      {
        label: "one tender fish crescent",
        kind: "arch",
        count: 1,
        colorIndex: 2,
        x: 0.42,
        y: 0.38,
        width: 0.4,
        height: 0.24,
      },
      {
        label: "one brushed sauce wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.56,
        y: 0.48,
        width: 0.46,
        height: 0.12,
      },
    ],
    relationship:
      "The continuous seat arcade rises from the sleek counter; fish and one restrained nikiri brush remain the only forms above it.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "family-meal-at-blue-hill",
    sourceCue:
      "Family-style courses center seasonal vegetables and grains connected to the restaurant's upstate farm network.",
    styleSignature: "fiber-applique",
    palette: [
      { name: "earth-brown ground", hex: "#5B4535" },
      { name: "warm-cream construction", hex: "#EEE2C7" },
      { name: "field-green farm", hex: "#55724A" },
      { name: "grain-gold harvest", hex: "#CDA141" },
      { name: "river-blue accent", hex: "#3F7180" },
    ],
    motifs: [
      {
        label: "one broad farm field",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.69,
        width: 0.78,
        height: 0.25,
      },
      {
        label: "one shared-table oval",
        kind: "oval",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.5,
        width: 0.6,
        height: 0.3,
      },
      {
        label: "one grain-sheaf arc",
        kind: "leaf",
        count: 1,
        colorIndex: 3,
        x: 0.3,
        y: 0.34,
        width: 0.3,
        height: 0.4,
      },
      {
        label: "one seasonal vegetable fan",
        kind: "leaf",
        count: 1,
        colorIndex: 4,
        x: 0.7,
        y: 0.35,
        width: 0.3,
        height: 0.4,
      },
    ],
    relationship:
      "The shared-table oval spans the farm field, with grain and seasonal produce fanning up at opposite ends of the family-style setting.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "jeju-noodle-bar",
    sourceCue: "Gochu ramyun brings curly noodles and pork broth together in a deeply savory Korean bowl.",
    styleSignature: "ceramic-roundel",
    palette: [
      { name: "savory-charcoal ground", hex: "#262B2B" },
      { name: "noodle-ivory construction", hex: "#F0DDB0" },
      { name: "broth-amber bowl", hex: "#A96332" },
      { name: "chili-coral heat", hex: "#C7523E" },
      { name: "pork-brown savor", hex: "#71483B" },
    ],
    motifs: [
      {
        label: "one broad broth bowl",
        kind: "oval",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.59,
        width: 0.7,
        height: 0.38,
      },
      {
        label: "one curling noodle spiral",
        kind: "ribbon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.49,
        width: 0.52,
        height: 0.32,
      },
      {
        label: "one pork-broth oval",
        kind: "oval",
        count: 1,
        colorIndex: 4,
        x: 0.49,
        y: 0.52,
        width: 0.26,
        height: 0.18,
      },
      {
        label: "one steam ribbon",
        kind: "ribbon",
        count: 1,
        colorIndex: 3,
        x: 0.63,
        y: 0.28,
        width: 0.22,
        height: 0.34,
      },
    ],
    relationship:
      "The noodle spiral and pork oval sit inside the broad broth bowl, with one chili-colored steam ribbon rising clear of the rim.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "frevo",
    sourceCue:
      "A rotating art panel conceals the entrance to an intimate chef counter tucked behind a gallery.",
    styleSignature: "geometric-facet",
    palette: [
      { name: "midnight-blue ground", hex: "#213344" },
      { name: "gallery-ivory construction", hex: "#F0E8D8" },
      { name: "burnished-brass pivot", hex: "#B8883E" },
      { name: "plum color field", hex: "#70485F" },
      { name: "counter-teal shadow", hex: "#35666A" },
    ],
    motifs: [
      {
        label: "one rotating gallery panel",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.43,
        y: 0.44,
        width: 0.44,
        height: 0.58,
      },
      {
        label: "one hidden doorway arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.65,
        y: 0.52,
        width: 0.38,
        height: 0.52,
      },
      {
        label: "one intimate counter curve",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.56,
        y: 0.69,
        width: 0.6,
        height: 0.16,
      },
      {
        label: "one framed color field",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.32,
        y: 0.34,
        width: 0.24,
        height: 0.34,
      },
    ],
    relationship:
      "The rotating panel overlaps the hidden arch; behind it, the intimate counter curves beneath a single framed gallery field.",
    edgeStrategy: fullBleed,
  }),
] as const;
