import { defineRestaurantArtProfile } from "./restaurant-art-profile";
import { NEW_YORK_CITY_RESTAURANT_FULL_BLEED_EDGE_STRATEGY as fullBleed } from "./restaurant-art-profiles-nyc-shared";

export const newYorkCityRestaurantArtProfiles01bPart1 = [
  defineRestaurantArtProfile({
    slug: "dirt-candy",
    sourceCue:
      "Seasonal vegetables appear raw, cooked, pickled, and preserved, making changing produce the tasting menu's central subject.",
    styleSignature: "fiber-applique",
    palette: [
      { name: "earth-brown ground", hex: "#5A4436" },
      { name: "garden-ivory construction", hex: "#EEE4C9" },
      { name: "leaf-green produce", hex: "#4F794A" },
      { name: "beet-purple root", hex: "#74435E" },
      { name: "squash-gold preserve", hex: "#D39A35" },
    ],
    motifs: [
      {
        label: "one broad leaf fan",
        kind: "leaf",
        count: 1,
        colorIndex: 2,
        x: 0.33,
        y: 0.4,
        width: 0.42,
        height: 0.45,
      },
      {
        label: "one root-vegetable oval",
        kind: "oval",
        count: 1,
        colorIndex: 3,
        x: 0.62,
        y: 0.57,
        width: 0.3,
        height: 0.38,
      },
      {
        label: "one pickling-jar arch",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.64,
        y: 0.37,
        width: 0.34,
        height: 0.42,
      },
      {
        label: "one preserved-produce disk",
        kind: "disk",
        count: 1,
        colorIndex: 4,
        x: 0.34,
        y: 0.67,
        width: 0.24,
        height: 0.24,
      },
    ],
    relationship:
      "Raw leaf and root forms flank the pickling arch, while the preserved-produce disk completes the seasonal cycle below.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "cesar",
    sourceCue:
      "A simple, clean room gives every table a clear view of the kitchen preparing a seasonal seafood-forward tasting menu.",
    styleSignature: "geometric-facet",
    palette: [
      { name: "ocean-blue ground", hex: "#315D70" },
      { name: "graphite construction", hex: "#293237" },
      { name: "warm-ivory room", hex: "#F0E5CF" },
      { name: "pearl-gray seafood", hex: "#AAB4B1" },
      { name: "clear-water teal", hex: "#4B8990" },
    ],
    motifs: [
      {
        label: "one open kitchen rectangle",
        kind: "block",
        count: 1,
        colorIndex: 2,
        x: 0.65,
        y: 0.39,
        width: 0.42,
        height: 0.36,
      },
      {
        label: "one broad viewing arc",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.55,
        width: 0.74,
        height: 0.62,
      },
      {
        label: "one seafood-blue wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.5,
        y: 0.69,
        width: 0.72,
        height: 0.16,
      },
      {
        label: "one high ceiling plane",
        kind: "horizon",
        count: 1,
        colorIndex: 3,
        x: 0.5,
        y: 0.18,
        width: 0.76,
        height: 0.13,
      },
    ],
    relationship:
      "The viewing arc opens toward the kitchen rectangle under the high ceiling, with one seafood wave carrying the eye across the foreground.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "torrisi",
    sourceCue:
      "New York Italian-American pantry and deli traditions are reworked into polished contemporary dishes in Nolita.",
    styleSignature: "screenprint-overlap",
    palette: [
      { name: "city-charcoal ground", hex: "#293035" },
      { name: "warm-cream construction", hex: "#F0DEC0" },
      { name: "olive-green pantry", hex: "#667344" },
      { name: "tomato-coral deli", hex: "#C7634F" },
      { name: "bread-gold polish", hex: "#C7953F" },
    ],
    motifs: [
      {
        label: "one deli-counter block",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.67,
        width: 0.72,
        height: 0.2,
      },
      {
        label: "one arched pasta ribbon",
        kind: "ribbon",
        count: 1,
        colorIndex: 4,
        x: 0.38,
        y: 0.43,
        width: 0.44,
        height: 0.38,
      },
      {
        label: "one city-window grid",
        kind: "block",
        count: 1,
        colorIndex: 3,
        x: 0.7,
        y: 0.34,
        width: 0.3,
        height: 0.38,
      },
      {
        label: "one olive-green oval",
        kind: "oval",
        count: 1,
        colorIndex: 2,
        x: 0.65,
        y: 0.61,
        width: 0.28,
        height: 0.18,
      },
    ],
    relationship:
      "The pasta ribbon rises from the deli counter toward the city grid; the olive oval sits as the compact pantry anchor.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "estela",
    sourceCue:
      "Ink-dark arroz negro with squid and hazelnut captures the kitchen's layered, high-contrast approach to familiar ingredients.",
    styleSignature: "screenprint-overlap",
    palette: [
      { name: "ink-black ground", hex: "#1D2528" },
      { name: "shell-ivory construction", hex: "#F0E5D0" },
      { name: "hazelnut-brown ingredient", hex: "#8A5A39" },
      { name: "citrus-gold sauce", hex: "#D6A12F" },
      { name: "coastal-blue accent", hex: "#3C7180" },
    ],
    motifs: [
      {
        label: "one ink-dark rice oval",
        kind: "oval",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.54,
        width: 0.65,
        height: 0.42,
      },
      {
        label: "one pale squid arc",
        kind: "arch",
        count: 1,
        colorIndex: 1,
        x: 0.43,
        y: 0.4,
        width: 0.44,
        height: 0.36,
      },
      {
        label: "one hazelnut disk",
        kind: "disk",
        count: 1,
        colorIndex: 2,
        x: 0.68,
        y: 0.4,
        width: 0.2,
        height: 0.2,
      },
      {
        label: "one bright sauce crescent",
        kind: "arch",
        count: 1,
        colorIndex: 3,
        x: 0.52,
        y: 0.66,
        width: 0.46,
        height: 0.2,
      },
    ],
    relationship:
      "The pale squid arc and hazelnut disk sit on the dark rice oval, cut by one bright sauce crescent for the intended high contrast.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "torien",
    sourceCue:
      "A counter-side yakitori sequence uses binchotan charcoal to shape each skewered cut of chicken.",
    styleSignature: "relief-cut",
    palette: [
      { name: "charcoal ground", hex: "#222725" },
      { name: "smoke-gray construction", hex: "#A4AAA4" },
      { name: "ember-amber fire", hex: "#D17A2D" },
      { name: "cypress-tan counter", hex: "#B88F5D" },
      { name: "grilled-brown skewer", hex: "#7A4733" },
    ],
    motifs: [
      {
        label: "one charcoal hearth block",
        kind: "block",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.7,
        width: 0.7,
        height: 0.2,
      },
      {
        label: "three broad skewer diagonals",
        kind: "ribbon",
        count: 3,
        colorIndex: 4,
        x: 0.5,
        y: 0.46,
        width: 0.16,
        height: 0.5,
        spreadX: 0.22,
      },
      {
        label: "one rising smoke spiral",
        kind: "ribbon",
        count: 1,
        colorIndex: 1,
        x: 0.67,
        y: 0.28,
        width: 0.22,
        height: 0.36,
      },
      {
        label: "one amber ember disk",
        kind: "disk",
        count: 1,
        colorIndex: 2,
        x: 0.31,
        y: 0.3,
        width: 0.22,
        height: 0.22,
      },
    ],
    relationship:
      "Three separate skewers cross above the hearth block; the ember disk and smoke spiral mark the charcoal heat on opposite sides.",
    edgeStrategy: fullBleed,
  }),
  defineRestaurantArtProfile({
    slug: "yoshino",
    sourceCue:
      "A hinoki counter cut from a centuries-old tree anchors an omakase known for warm saba maki and precise nigiri.",
    styleSignature: "marquetry-strata",
    palette: [
      { name: "deep-charcoal ground", hex: "#252A2B" },
      { name: "rice-ivory construction", hex: "#F1E6CF" },
      { name: "hinoki-honey counter", hex: "#C89959" },
      { name: "mackerel-blue fish", hex: "#496A7D" },
      { name: "warm-saba copper", hex: "#B86B3D" },
    ],
    motifs: [
      {
        label: "one ancient-tree counter",
        kind: "horizon",
        count: 1,
        colorIndex: 2,
        x: 0.5,
        y: 0.68,
        width: 0.76,
        height: 0.21,
      },
      {
        label: "one warm mackerel crescent",
        kind: "arch",
        count: 1,
        colorIndex: 4,
        x: 0.36,
        y: 0.43,
        width: 0.38,
        height: 0.25,
      },
      {
        label: "one cypress grain wave",
        kind: "ribbon",
        count: 1,
        colorIndex: 1,
        x: 0.5,
        y: 0.57,
        width: 0.66,
        height: 0.12,
      },
      {
        label: "one precise nigiri disk",
        kind: "disk",
        count: 1,
        colorIndex: 3,
        x: 0.69,
        y: 0.35,
        width: 0.24,
        height: 0.24,
      },
    ],
    relationship:
      "The old hinoki counter spans the base, crossed once by its grain wave; warm mackerel and the precise nigiri disk balance above it.",
    edgeStrategy: fullBleed,
  }),
] as const;
