import { defineUsState } from "./us-state-record";

export const usStatesAlabamaThroughMissouri = [
  defineUsState({
    censusStateFips: "01",
    postalCode: "AL",
    slug: "alabama",
    name: "Alabama",
    signature: "longleaf pines opening onto the braided wetlands of the Mobile-Tensaw Delta",
    symbol: "river channels gathering toward the Gulf",
    terrain: "forested uplands descending through a broad coastal plain",
    palette: ["pine green", "river blue", "marsh gold", "clay red"],
    styles: ["pixel-cluster-landscape", "watercolor-naturalist-study", "thread-painted-embroidery"],
  }),
  defineUsState({
    censusStateFips: "02",
    postalCode: "AK",
    slug: "alaska",
    name: "Alaska",
    signature: "Denali rising above braided tundra rivers and dark spruce",
    symbol: "immense northern distance held beneath a low luminous sky",
    terrain: "glaciated ranges, tundra, boreal forest, and braided water",
    palette: ["snow white", "glacier blue", "spruce black", "tundra russet", "aurora green"],
    styles: ["thread-painted-embroidery", "scratchboard-nocturne", "aquatint-atmosphere"],
  }),
  defineUsState({
    censusStateFips: "04",
    postalCode: "AZ",
    slug: "arizona",
    name: "Arizona",
    signature: "the Colorado River winding through the layered walls of the Grand Canyon",
    symbol: "geologic time revealed as bands of desert color",
    terrain: "high plateau cut by immense canyons and dry tributaries",
    palette: ["sandstone red", "ochre", "violet shadow", "river green", "sky cobalt"],
    styles: ["plein-air-broken-color", "relief-blockprint", "cut-paper-strata"],
  }),
  defineUsState({
    censusStateFips: "05",
    postalCode: "AR",
    slug: "arkansas",
    name: "Arkansas",
    signature: "the Buffalo National River beneath pale Ozark limestone bluffs",
    symbol: "clear water carrying autumn color around a quiet bend",
    terrain: "wooded plateaus, river valleys, springs, and folded ridges",
    palette: ["limestone cream", "river teal", "oak copper", "moss green"],
    styles: ["relief-blockprint", "watercolor-naturalist-study", "contour-atlas-ink"],
  }),
  defineUsState({
    censusStateFips: "06",
    postalCode: "CA",
    slug: "california",
    name: "California",
    signature: "coastal redwoods framing Pacific light with Sierra granite beyond",
    symbol: "one long horizon joining forest, ocean, and mountain",
    terrain: "coast ranges, central valleys, high granite, and desert basins",
    palette: ["redwood umber", "Pacific blue", "granite silver", "poppy orange", "chaparral green"],
    styles: ["stained-glass-field", "plein-air-broken-color", "luminous-ligne-claire"],
  }),
  defineUsState({
    censusStateFips: "08",
    postalCode: "CO",
    slug: "colorado",
    name: "Colorado",
    signature: "a snow-lined Rocky Mountain ridge above golden aspen",
    symbol: "a high pass opening into clear alpine distance",
    terrain: "continental-divide peaks, parks, mesas, and river headwaters",
    palette: ["alpine blue", "snow white", "aspen gold", "granite gray", "spruce green"],
    styles: ["monoprint-ink-wash", "mineral-line-engraving", "contour-atlas-ink"],
  }),
  defineUsState({
    censusStateFips: "09",
    postalCode: "CT",
    slug: "connecticut",
    name: "Connecticut",
    signature: "the Connecticut River passing autumn hardwoods and old fieldstone walls",
    symbol: "a narrow waterway linking inland towns to the Sound",
    terrain: "rolling forest, river valleys, rocky ridges, and tidal coast",
    palette: ["maple red", "oak gold", "river slate", "fieldstone gray"],
    styles: ["contour-atlas-ink", "wood-marquetry-landscape", "matte-gouache-editorial"],
  }),
  defineUsState({
    censusStateFips: "10",
    postalCode: "DE",
    slug: "delaware",
    name: "Delaware",
    signature: "Atlantic dunes meeting the salt marshes of Delaware Bay",
    symbol: "a tidal creek reflecting an open coastal sky",
    terrain: "low coastal plain, barrier beaches, marsh, and estuary",
    palette: ["dune cream", "marsh green", "bay blue", "shell pink"],
    styles: ["mineral-line-engraving", "cyanotype-field-study", "watercolor-naturalist-study"],
  }),
  defineUsState({
    censusStateFips: "12",
    postalCode: "FL",
    slug: "florida",
    name: "Florida",
    signature: "Everglades sawgrass opening around mangrove islands and a roseate spoonbill",
    symbol: "fresh water moving almost invisibly toward the sea",
    terrain: "wet prairie, limestone keys, mangrove coast, and shallow reef",
    palette: ["sawgrass green", "mangrove black", "spoonbill pink", "turquoise", "sun gold"],
    styles: ["aquatint-atmosphere", "stained-glass-field", "watercolor-naturalist-study"],
  }),
  defineUsState({
    censusStateFips: "13",
    postalCode: "GA",
    slug: "georgia",
    name: "Georgia",
    signature: "live oaks and salt-marsh grass along the Georgia coast",
    symbol: "golden tidal channels threading beneath broad shade",
    terrain: "Blue Ridge headwaters, Piedmont, coastal plain, and barrier islands",
    palette: ["marsh gold", "live-oak green", "tidal blue", "clay red"],
    styles: ["risograph-overprint", "woven-tapestry-field", "ceramic-underglaze"],
  }),
  defineUsState({
    censusStateFips: "15",
    postalCode: "HI",
    slug: "hawaii",
    name: "Hawaii",
    signature: "dark volcanic slopes meeting the Pacific beside red ʻōhiʻa lehua blossoms",
    symbol: "new land cooling at the edge of an immense ocean",
    terrain: "shield volcanoes, rain forest, dry leeward slopes, and coral coast",
    palette: ["lava black", "ocean cobalt", "lehua red", "fern green", "cloud white"],
    styles: ["matte-gouache-editorial", "fresco-mineral-pigment", "ceramic-underglaze"],
  }),
  defineUsState({
    censusStateFips: "16",
    postalCode: "ID",
    slug: "idaho",
    name: "Idaho",
    signature: "the jagged Sawtooth Range reflected in a clear alpine lake",
    symbol: "a cold headwater beginning beneath granite peaks",
    terrain: "mountain ranges, deep river canyons, forest, and volcanic plain",
    palette: ["granite gray", "lake blue", "pine green", "snow white", "sage"],
    styles: ["woven-tapestry-field", "wood-marquetry-landscape", "mineral-line-engraving"],
  }),
  defineUsState({
    censusStateFips: "17",
    postalCode: "IL",
    slug: "illinois",
    name: "Illinois",
    signature: "Chicago's lakefront skyline rising beyond the blue plane of Lake Michigan",
    symbol: "prairie lines converging on a city of vertical light",
    terrain: "tallgrass plain, great rivers, glacial hills, and freshwater shore",
    palette: ["lake blue", "steel gray", "prairie gold", "brick red"],
    styles: ["cut-paper-strata", "risograph-overprint", "prismatic-geometric-symbolism"],
  }),
  defineUsState({
    censusStateFips: "18",
    postalCode: "IN",
    slug: "indiana",
    name: "Indiana",
    signature: "marram grass bending across the dunes of Lake Michigan",
    symbol: "wind-written sand opening toward a freshwater horizon",
    terrain: "glacial plain, hardwood forest, river lowlands, and lake dunes",
    palette: ["dune cream", "lake blue", "marram green", "cloud silver"],
    styles: ["cyanotype-field-study", "watercolor-naturalist-study", "thread-painted-embroidery"],
  }),
  defineUsState({
    censusStateFips: "19",
    postalCode: "IA",
    slug: "iowa",
    name: "Iowa",
    signature: "the Loess Hills rising above patchwork farms near the Missouri River",
    symbol: "patient field lines following wind-shaped ridges",
    terrain: "rolling prairie, glacial plains, river valleys, and loess bluffs",
    palette: ["corn gold", "prairie green", "soil umber", "river blue"],
    styles: ["watercolor-naturalist-study", "wood-marquetry-landscape", "risograph-overprint"],
  }),
  defineUsState({
    censusStateFips: "20",
    postalCode: "KS",
    slug: "kansas",
    name: "Kansas",
    signature: "Flint Hills tallgrass rolling beneath a summer thunderstorm",
    symbol: "one luminous horizon holding weather and open distance",
    terrain: "high plains, prairie uplands, river valleys, and chalk bluffs",
    palette: ["grass green", "storm violet", "limestone cream", "lightning gold"],
    styles: ["charcoal-pastel-weather", "screenprint-night", "plein-air-broken-color"],
  }),
  defineUsState({
    censusStateFips: "21",
    postalCode: "KY",
    slug: "kentucky",
    name: "Kentucky",
    signature: "a lantern revealing the broad limestone passages of Mammoth Cave",
    symbol: "a small warm light entering a vast hidden landscape",
    terrain: "karst plateau, wooded knobs, bluegrass uplands, and river valleys",
    palette: ["cave black", "lantern amber", "limestone gray", "bluegrass green"],
    styles: ["screenprint-night", "aquatint-atmosphere", "scratchboard-nocturne"],
    excludedMotifs: ["fantasy crystals", "daylight cave opening"],
  }),
  defineUsState({
    censusStateFips: "22",
    postalCode: "LA",
    slug: "louisiana",
    name: "Louisiana",
    signature: "bald cypress and knees standing in a quiet bayou",
    symbol: "reflected branches turning water into a second forest",
    terrain: "delta plain, natural levees, wetlands, bayous, and Gulf marsh",
    palette: ["cypress green", "water black", "Spanish-moss silver", "egret white", "mud ochre"],
    styles: ["mosaic-tesserae-field", "monoprint-ink-wash", "watercolor-naturalist-study"],
  }),
  defineUsState({
    censusStateFips: "23",
    postalCode: "ME",
    slug: "maine",
    name: "Maine",
    signature: "a granite Atlantic headland with spruce islands and a working lighthouse",
    symbol: "a steady beam crossing cold coastal weather",
    terrain: "rocky coast, forested interior, lakes, and rounded mountains",
    palette: ["granite gray", "spruce green", "Atlantic navy", "beacon gold"],
    styles: ["fresco-mineral-pigment", "pixel-cluster-landscape", "cyanotype-field-study"],
  }),
  defineUsState({
    censusStateFips: "24",
    postalCode: "MD",
    slug: "maryland",
    name: "Maryland",
    signature: "a Chesapeake Bay skipjack crossing among tidal creeks and blue herons",
    symbol: "many tributaries joining one wide estuary",
    terrain: "Appalachian ridge, Piedmont rivers, coastal plain, and tidal bay",
    palette: ["bay blue", "marsh green", "sail cream", "heron gray", "sunset copper"],
    styles: ["prismatic-geometric-symbolism", "mosaic-tesserae-field", "contour-atlas-ink"],
  }),
  defineUsState({
    censusStateFips: "25",
    postalCode: "MA",
    slug: "massachusetts",
    name: "Massachusetts",
    signature: "Cape Cod dunes curving around a lighthouse and broad Atlantic water",
    symbol: "a hooked shoreline holding centuries of ocean passage",
    terrain: "rocky uplands, river valley, glacial ponds, and sandy cape",
    palette: ["dune cream", "Atlantic blue", "cranberry red", "weathered gray"],
    styles: ["ceramic-underglaze", "relief-blockprint", "cyanotype-field-study"],
  }),
  defineUsState({
    censusStateFips: "26",
    postalCode: "MI",
    slug: "michigan",
    name: "Michigan",
    signature: "Pictured Rocks cliffs glowing above the clear water of Lake Superior",
    symbol: "two peninsulas surrounded by freshwater horizons",
    terrain: "Great Lakes shore, forest, dunes, wetlands, and glacial plain",
    palette: ["lake turquoise", "sandstone copper", "pine green", "ice blue"],
    styles: ["wood-marquetry-landscape", "ceramic-underglaze", "mosaic-tesserae-field"],
  }),
  defineUsState({
    censusStateFips: "27",
    postalCode: "MN",
    slug: "minnesota",
    name: "Minnesota",
    signature: "Boundary Waters lakes reflecting boreal pines beneath northern light",
    symbol: "a chain of quiet water leading into wilderness",
    terrain: "lake country, boreal forest, prairie, and North Shore bedrock",
    palette: ["lake black", "pine green", "aurora teal", "granite gray", "snow blue"],
    styles: ["scratchboard-nocturne", "screenprint-night", "pixel-cluster-landscape"],
  }),
  defineUsState({
    censusStateFips: "28",
    postalCode: "MS",
    slug: "mississippi",
    name: "Mississippi",
    signature: "cypress wetlands and an oxbow lake across the Mississippi Delta plain",
    symbol: "a slow river memory bending away from its former course",
    terrain: "alluvial delta, loess bluffs, pine hills, and Gulf coast",
    palette: ["cypress green", "river brown", "mist blue", "cotton white"],
    styles: ["luminous-ligne-claire", "monoprint-ink-wash", "contour-atlas-ink"],
  }),
  defineUsState({
    censusStateFips: "29",
    postalCode: "MO",
    slug: "missouri",
    name: "Missouri",
    signature: "a clear Ozark spring flowing beneath wooded limestone bluffs",
    symbol: "two great rivers meeting beyond a maze of upland streams",
    terrain: "Ozark plateau, prairie plain, limestone caves, and broad rivers",
    palette: ["spring blue", "limestone cream", "oak green", "river silt"],
    styles: ["pixel-cluster-landscape", "relief-blockprint", "watercolor-naturalist-study"],
  }),
] as const;
