import { defineUsState } from "./us-state-record";

export const usStatesMontanaThroughWyoming = [
  defineUsState({
    censusStateFips: "30",
    postalCode: "MT",
    slug: "montana",
    name: "Montana",
    signature: "glaciated peaks rising beyond open prairie beneath a vast sky",
    symbol: "one clear river carrying mountain snow toward the plains",
    terrain: "northern Rockies, intermontane valleys, prairie, and badlands",
    palette: ["sky blue", "snow white", "prairie gold", "pine green", "stone gray"],
    styles: ["thread-painted-embroidery", "mineral-line-engraving", "woven-tapestry-field"],
  }),
  defineUsState({
    censusStateFips: "31",
    postalCode: "NE",
    slug: "nebraska",
    name: "Nebraska",
    signature: "sandhill cranes gathering along the braided Platte River",
    symbol: "a moving flock joining water, grass, and open sky",
    terrain: "Sandhills grassland, river valleys, loess plains, and High Plains",
    palette: ["prairie gold", "river silver", "crane gray", "dawn rose"],
    styles: ["plein-air-broken-color", "risograph-overprint", "watercolor-naturalist-study"],
  }),
  defineUsState({
    censusStateFips: "32",
    postalCode: "NV",
    slug: "nevada",
    name: "Nevada",
    signature: "Basin and Range ridges repeating across a bright desert playa",
    symbol: "successive mountain silhouettes measuring immense dry distance",
    terrain: "parallel fault-block ranges, desert basins, playas, and alpine islands",
    palette: ["playa cream", "sage green", "mountain violet", "rust red", "cobalt sky"],
    styles: ["relief-blockprint", "screenprint-night", "prismatic-geometric-symbolism"],
  }),
  defineUsState({
    censusStateFips: "33",
    postalCode: "NH",
    slug: "new-hampshire",
    name: "New Hampshire",
    signature: "Mount Washington above layered White Mountain forest in autumn",
    symbol: "weather moving quickly across a high granite ridge",
    terrain: "White Mountains, lake country, forested hills, and short Atlantic coast",
    palette: ["maple red", "birch gold", "granite gray", "fir green", "cloud blue"],
    styles: ["stained-glass-field", "matte-gouache-editorial", "wood-marquetry-landscape"],
  }),
  defineUsState({
    censusStateFips: "34",
    postalCode: "NJ",
    slug: "new-jersey",
    name: "New Jersey",
    signature: "tea-dark Pine Barrens water flowing through Atlantic white cedar",
    symbol: "a quiet wild corridor held between coast and city",
    terrain: "ridge and valley, Piedmont, pine barrens, wetlands, and barrier shore",
    palette: ["cedar green", "tea brown", "sand cream", "cranberry red"],
    styles: ["monoprint-ink-wash", "cyanotype-field-study", "woven-tapestry-field"],
  }),
  defineUsState({
    censusStateFips: "35",
    postalCode: "NM",
    slug: "new-mexico",
    name: "New Mexico",
    signature: "white gypsum dunes folding beneath the blue San Andres Mountains",
    symbol: "wind drawing new curves across an ancient basin",
    terrain: "high desert basins, mesas, volcanic fields, and mountain ranges",
    palette: ["gypsum white", "sky cobalt", "adobe red", "sage green", "violet shadow"],
    styles: ["contour-atlas-ink", "cut-paper-strata", "ceramic-underglaze"],
  }),
  defineUsState({
    censusStateFips: "36",
    postalCode: "NY",
    slug: "new-york",
    name: "New York",
    signature:
      "the low broad American Falls beside the slender Bridal Veil Falls, separated by wooded Luna Island, with a distant city skyline on a flat Great Lakes horizon",
    symbol: "Great Lakes water gathering into one luminous edge above the Niagara River gorge",
    terrain: "the flat Niagara River corridor and urban Great Lakes plain at Niagara Falls",
    palette: ["water white", "river teal", "gorge gray", "maple copper"],
    styles: ["mineral-line-engraving", "risograph-overprint", "luminous-ligne-claire"],
    excludedMotifs: ["mountains, hills, or wilderness peaks anywhere in the scene"],
    artBriefSourceUrls: ["https://parks.ny.gov/visit/state-parks/niagara-falls-state-park"],
  }),
  defineUsState({
    censusStateFips: "37",
    postalCode: "NC",
    slug: "north-carolina",
    name: "North Carolina",
    signature: "layered Blue Ridge summits with blooming rhododendron in the foreground",
    symbol: "successive blue horizons descending toward the coastal plain",
    terrain: "Appalachian ridges, Piedmont rivers, pocosins, and barrier islands",
    palette: ["ridge blue", "rhododendron pink", "forest green", "mist silver"],
    styles: ["aquatint-atmosphere", "plein-air-broken-color", "thread-painted-embroidery"],
  }),
  defineUsState({
    censusStateFips: "38",
    postalCode: "ND",
    slug: "north-dakota",
    name: "North Dakota",
    signature: "painted badlands rising behind bison and mixed-grass prairie",
    symbol: "one dark animal crossing bands of ancient earth",
    terrain: "northern prairie, Missouri Plateau, badlands, and glacial lake plain",
    palette: ["prairie gold", "clay rose", "sage green", "bison brown", "sky blue"],
    styles: ["risograph-overprint", "fresco-mineral-pigment", "relief-blockprint"],
  }),
  defineUsState({
    censusStateFips: "39",
    postalCode: "OH",
    slug: "ohio",
    name: "Ohio",
    signature: "a Hocking Hills sandstone recess beneath beech and maple forest",
    symbol: "water and roots opening a hidden room in stone",
    terrain: "glacial till plain, Appalachian plateau, river valleys, and Lake Erie shore",
    palette: ["sandstone ochre", "beech gold", "moss green", "water blue"],
    styles: ["matte-gouache-editorial", "wood-marquetry-landscape", "watercolor-naturalist-study"],
  }),
  defineUsState({
    censusStateFips: "40",
    postalCode: "OK",
    slug: "oklahoma",
    name: "Oklahoma",
    signature: "rounded Wichita Mountains granite above prairie and a grazing bison",
    symbol: "old red stone holding firm above moving grass",
    terrain: "prairie plains, cross timbers, red-bed hills, and low granite mountains",
    palette: ["granite rose", "prairie gold", "bison brown", "storm blue"],
    styles: ["woven-tapestry-field", "screenprint-night", "ceramic-underglaze"],
  }),
  defineUsState({
    censusStateFips: "41",
    postalCode: "OR",
    slug: "oregon",
    name: "Oregon",
    signature: "Pacific sea stacks beyond a wind-shaped Douglas-fir coast",
    symbol: "mist joining dark forest to bright ocean",
    terrain: "volcanic Cascades, forested coast, high desert, and river gorge",
    palette: ["fir green", "ocean blue", "basalt black", "mist gray", "sunset coral"],
    styles: ["cut-paper-strata", "cyanotype-field-study", "luminous-ligne-claire"],
  }),
  defineUsState({
    censusStateFips: "42",
    postalCode: "PA",
    slug: "pennsylvania",
    name: "Pennsylvania",
    signature: "the Susquehanna River turning between long forested Appalachian ridges",
    symbol: "parallel mountains parting for one broad watercourse",
    terrain: "ridge and valley, Allegheny Plateau, Piedmont, and major river gaps",
    palette: ["forest green", "river blue", "shale gray", "autumn copper"],
    styles: ["cyanotype-field-study", "mineral-line-engraving", "matte-gouache-editorial"],
  }),
  defineUsState({
    censusStateFips: "44",
    postalCode: "RI",
    slug: "rhode-island",
    name: "Rhode Island",
    signature: "a rocky Narragansett Bay shore opening around islands and a white sail",
    symbol: "many sheltered coves gathered inside one ocean horizon",
    terrain: "coastal lowland, tidal bay, rocky headlands, and wooded uplands",
    palette: ["bay blue", "granite gray", "sail white", "beach-rose pink"],
    styles: ["watercolor-naturalist-study", "ceramic-underglaze", "mosaic-tesserae-field"],
  }),
  defineUsState({
    censusStateFips: "45",
    postalCode: "SC",
    slug: "south-carolina",
    name: "South Carolina",
    signature: "cypress knees and tupelo reflected in a blackwater river",
    symbol: "tea-dark water carrying forest light toward the coast",
    terrain: "Blue Ridge edge, Piedmont, sandhills, coastal plain, and sea islands",
    palette: ["water black", "cypress green", "tupelo gold", "mist silver"],
    styles: ["charcoal-pastel-weather", "monoprint-ink-wash", "scratchboard-nocturne"],
  }),
  defineUsState({
    censusStateFips: "46",
    postalCode: "SD",
    slug: "south-dakota",
    name: "South Dakota",
    signature: "striped Badlands pinnacles opening abruptly from mixed-grass prairie",
    symbol: "eroded towers catching the last warm light",
    terrain: "prairie plains, Missouri breaks, Black Hills, and badlands",
    palette: ["clay rose", "prairie gold", "sage green", "violet shadow"],
    styles: ["screenprint-night", "relief-blockprint", "fresco-mineral-pigment"],
  }),
  defineUsState({
    censusStateFips: "47",
    postalCode: "TN",
    slug: "tennessee",
    name: "Tennessee",
    signature: "blue Great Smoky Mountain ridges rising behind flowering rhododendron",
    symbol: "layer after layer of forest dissolving into warm haze",
    terrain: "Appalachian mountains, ridge and valley, central basin, and Mississippi plain",
    palette: ["smoky blue", "forest green", "rhododendron pink", "haze gold"],
    styles: ["mosaic-tesserae-field", "plein-air-broken-color", "woven-tapestry-field"],
  }),
  defineUsState({
    censusStateFips: "48",
    postalCode: "TX",
    slug: "texas",
    name: "Texas",
    signature: "the Rio Grande curving through the sheer walls of Santa Elena Canyon",
    symbol: "one river drawing a bright line across immense desert stone",
    terrain: "Gulf plain, prairie, hill country, desert basins, and mountain ranges",
    palette: ["adobe red", "river teal", "desert gold", "cactus green", "sky cobalt"],
    styles: ["fresco-mineral-pigment", "relief-blockprint", "contour-atlas-ink"],
  }),
  defineUsState({
    censusStateFips: "49",
    postalCode: "UT",
    slug: "utah",
    name: "Utah",
    signature: "a sandstone arch framing fins, canyon plateaus, and desert sky",
    symbol: "open stone holding a window onto deep geologic distance",
    terrain: "Colorado Plateau canyons, Great Basin ranges, salt flats, and Wasatch peaks",
    palette: ["sandstone orange", "cream", "sage green", "indigo", "sun gold"],
    styles: ["prismatic-geometric-symbolism", "cut-paper-strata", "stained-glass-field"],
  }),
  defineUsState({
    censusStateFips: "50",
    postalCode: "VT",
    slug: "vermont",
    name: "Vermont",
    signature: "a covered bridge crossing a clear river beneath autumn Green Mountains",
    symbol: "a small passage joining two wooded banks",
    terrain: "Green Mountain spine, river valleys, hardwood forest, and lake shore",
    palette: ["maple red", "forest green", "bridge white", "river blue", "gold"],
    styles: ["ceramic-underglaze", "wood-marquetry-landscape", "thread-painted-embroidery"],
  }),
  defineUsState({
    censusStateFips: "51",
    postalCode: "VA",
    slug: "virginia",
    name: "Virginia",
    signature: "Shenandoah Valley fields held between long blue mountain ridges",
    symbol: "a river valley opening east from the Appalachian wall",
    terrain: "ridge and valley, Blue Ridge, Piedmont rivers, and Chesapeake plain",
    palette: ["ridge blue", "field green", "river silver", "autumn copper"],
    styles: ["wood-marquetry-landscape", "mineral-line-engraving", "matte-gouache-editorial"],
  }),
  defineUsState({
    censusStateFips: "53",
    postalCode: "WA",
    slug: "washington",
    name: "Washington",
    signature: "Mount Rainier above dark evergreen forest and subalpine wildflowers",
    symbol: "one ice-covered summit gathering cloud and river headwaters",
    terrain: "Pacific coast, Olympic rainforest, Cascade volcanoes, and dry plateau",
    palette: ["glacier white", "fir green", "sky blue", "wildflower magenta", "basalt gray"],
    styles: ["scratchboard-nocturne", "luminous-ligne-claire", "watercolor-naturalist-study"],
  }),
  defineUsState({
    censusStateFips: "54",
    postalCode: "WV",
    slug: "west-virginia",
    name: "West Virginia",
    signature: "the steel arch of New River Gorge Bridge spanning a forested canyon",
    symbol: "a single curve joining steep Appalachian walls",
    terrain: "dissected plateau, narrow valleys, sandstone gorges, and forested ridges",
    palette: ["forest green", "steel rust", "river blue", "sandstone gray", "autumn gold"],
    styles: ["luminous-ligne-claire", "aquatint-atmosphere", "contour-atlas-ink"],
  }),
  defineUsState({
    censusStateFips: "55",
    postalCode: "WI",
    slug: "wisconsin",
    name: "Wisconsin",
    signature: "Apostle Islands sandstone sea caves opening onto Lake Superior",
    symbol: "freshwater waves carving rooms into red rock",
    terrain: "glacial lake country, northern forest, driftless hills, and Great Lakes shore",
    palette: ["sandstone red", "lake blue", "ice white", "pine green"],
    styles: ["pixel-cluster-landscape", "ceramic-underglaze", "cyanotype-field-study"],
  }),
  defineUsState({
    censusStateFips: "56",
    postalCode: "WY",
    slug: "wyoming",
    name: "Wyoming",
    signature: "the Grand Teton rising above sagebrush and the winding Snake River",
    symbol: "a sharp mountain silhouette anchoring an open basin",
    terrain: "high basins, mountain ranges, volcanic plateau, and grassland",
    palette: ["granite gray", "sage green", "river blue", "snow white", "sunrise rose"],
    styles: ["thread-painted-embroidery", "plein-air-broken-color", "mineral-line-engraving"],
  }),
] as const;
