import type { VideoGameSeed } from "./video-game-record";

export const earlyVideoGameSeeds = [
  {
    slug: "pong",
    gameTitle: "Pong",
    category: "arcade",
    completionCriterion: "Complete one full match of Pong.",
    forms: ["two opposed shore planes", "one curved traveling pulse", "a wide central interval"],
    relationship: "the two shore planes exchange the single pulse across open space",
    palette: ["bone white", "charcoal", "muted coral"],
    styles: ["prismatic-geometric-symbolism", "relief-blockprint", "risograph-overprint"],
  },
  {
    slug: "space-invaders",
    gameTitle: "Space Invaders",
    category: "arcade",
    completionCriterion: "Clear the first wave in Space Invaders.",
    forms: ["a descending stepped weather band", "one narrow ascending beam", "a deep open field"],
    relationship: "the beam rises as the weather band descends",
    palette: ["midnight navy", "pale citron", "dusty magenta"],
    styles: ["screenprint-night", "luminous-ligne-claire", "pixel-cluster-landscape"],
  },
  {
    slug: "pac-man",
    gameTitle: "PAC-MAN",
    category: "arcade",
    completionCriterion: "Clear the first maze in PAC-MAN.",
    forms: ["four receding pressure arcs", "one traveling warm disk", "a dark breathing field"],
    relationship: "the arcs open ahead of the disk and close gently behind it",
    palette: ["saffron", "ink blue", "soft vermilion"],
    styles: ["relief-blockprint", "matte-gouache-editorial", "screenprint-night"],
  },
  {
    slug: "tetris",
    gameTitle: "Tetris",
    category: "puzzle",
    completionCriterion: "Clear 100 lines in a single Tetris session.",
    forms: ["irregular mineral slabs", "a calm horizontal foundation", "one descending translucent plane"],
    relationship: "the varied slabs settle into a level foundation as the open plane descends",
    palette: ["slate blue", "ochre", "mineral green"],
    styles: ["mosaic-tesserae-field", "thread-painted-embroidery", "mineral-line-engraving"],
  },
  {
    slug: "super-mario-bros",
    gameTitle: "Super Mario Bros.",
    category: "platformer",
    completionCriterion: "Defeat Bowser and finish Super Mario Bros.",
    forms: ["one springing path", "three terraced ledges", "a broad dawn field"],
    relationship: "the path bounds across the ledges toward dawn",
    palette: ["tomato red", "sky teal", "warm cream"],
    styles: ["cut-paper-strata", "prismatic-geometric-symbolism", "plein-air-broken-color"],
  },
  {
    slug: "the-legend-of-zelda",
    gameTitle: "The Legend of Zelda",
    category: "action-adventure",
    completionCriterion: "Defeat Ganon and finish The Legend of Zelda.",
    forms: ["a woodland cleft", "one winding path", "a distant amber light"],
    relationship: "the path passes through the woodland cleft toward the distant light",
    palette: ["moss green", "walnut brown", "amber"],
    styles: ["wood-marquetry-landscape", "monoprint-ink-wash", "woven-tapestry-field"],
  },
  {
    slug: "metroid",
    gameTitle: "Metroid",
    category: "action-adventure",
    completionCriterion: "Defeat Mother Brain and escape in Metroid.",
    forms: ["one warm nucleus", "three concentric cavern chambers", "a narrow return seam"],
    relationship: "the nucleus passes through the chambers and finds the return seam",
    palette: ["deep graphite", "ember orange", "cool violet"],
    styles: ["scratchboard-nocturne", "contour-atlas-ink", "cut-paper-strata"],
  },
  {
    slug: "dragon-quest",
    gameTitle: "Dragon Quest",
    category: "role-playing",
    completionCriterion: "Defeat the Dragonlord and finish Dragon Quest.",
    forms: ["one small trail", "three broad realm fields", "a sunrise gate"],
    relationship: "the trail crosses all three realms toward the sunrise gate",
    palette: ["clay red", "river blue", "sunlit gold"],
    styles: ["fresco-mineral-pigment", "plein-air-broken-color", "aquatint-atmosphere"],
  },
  {
    slug: "simcity",
    gameTitle: "SimCity",
    category: "simulation",
    completionCriterion: "Build a SimCity city with a population of at least 100,000.",
    forms: ["a branching river", "three expanding civic masses", "one green clearing"],
    relationship: "the civic masses grow around the river while preserving the clearing",
    palette: ["blue gray", "brick umber", "park green"],
    styles: ["contour-atlas-ink", "cyanotype-field-study", "prismatic-geometric-symbolism"],
  },
  {
    slug: "prince-of-persia",
    gameTitle: "Prince of Persia",
    category: "platformer",
    completionCriterion: "Rescue the princess and finish Prince of Persia.",
    forms: ["one flowing motion ribbon", "two high stone ledges", "a narrowing sand arc"],
    relationship: "the ribbon leaps between the ledges before the sand arc closes",
    palette: ["sandstone", "indigo shadow", "pale turquoise"],
    styles: ["mineral-line-engraving", "luminous-ligne-claire", "watercolor-naturalist-study"],
  },
] as const satisfies readonly VideoGameSeed[];
