import type { VideoGameSeed } from "./video-game-record";

export const contemporaryVideoGameSeeds = [
  {
    slug: "never-alone",
    gameTitle: "Never Alone",
    category: "platformer",
    completionCriterion: "Complete the main story of Never Alone.",
    forms: ["two parallel traveling tracks", "one broad winter field", "an aurora aperture"],
    relationship: "the two tracks cross the winter field together toward the aurora aperture",
    palette: ["snow white", "storm blue", "soft aurora green"],
    styles: ["watercolor-naturalist-study", "luminous-ligne-claire", "wood-marquetry-landscape"],
  },
  {
    slug: "rocket-league",
    gameTitle: "Rocket League",
    category: "sports",
    completionCriterion: "Win one complete match of Rocket League.",
    forms: ["one high kinetic curve", "a blank floating sphere", "two opposed field wedges"],
    relationship: "the kinetic curve lifts the sphere between the opposed field wedges",
    palette: ["cobalt", "copper orange", "smoky white"],
    styles: ["stained-glass-field", "woven-tapestry-field", "mosaic-tesserae-field"],
  },
  {
    slug: "stardew-valley",
    gameTitle: "Stardew Valley",
    category: "simulation",
    completionCriterion: "Complete the Community Center or Joja development in Stardew Valley.",
    forms: ["four seasonal field bands", "one warm homestead light", "a slow circular path"],
    relationship: "the seasonal bands meet around the homestead light as the path returns",
    palette: ["leaf green", "harvest gold", "plum shadow"],
    styles: ["thread-painted-embroidery", "aquatint-atmosphere", "watercolor-naturalist-study"],
  },
  {
    slug: "the-legend-of-zelda-breath-of-the-wild",
    gameTitle: "The Legend of Zelda: Breath of the Wild",
    category: "action-adventure",
    completionCriterion:
      "Defeat Calamity Ganon and see the credits in The Legend of Zelda: Breath of the Wild.",
    forms: ["one broad wind path", "three receding terrain layers", "an immense open sky"],
    relationship: "the wind path rises through the terrain layers into open sky",
    palette: ["luminous sky blue", "sage", "warm limestone"],
    styles: ["luminous-ligne-claire", "ceramic-underglaze", "monoprint-ink-wash"],
  },
  {
    slug: "hollow-knight",
    gameTitle: "Hollow Knight",
    category: "action-adventure",
    completionCriterion: "Reach an ending in Hollow Knight.",
    forms: ["one pale descending seed", "three cavern bell forms", "a dark root basin"],
    relationship: "the seed descends through the cavern bells toward the root basin",
    palette: ["ink black", "bone white", "muted blue"],
    styles: ["monoprint-ink-wash", "cut-paper-strata", "fresco-mineral-pigment"],
  },
  {
    slug: "celeste",
    gameTitle: "Celeste",
    category: "platformer",
    completionCriterion: "Reach the summit and finish Celeste’s main story.",
    forms: ["one diagonal ascent", "three broad weather bands", "a warm summit disk"],
    relationship: "the ascent crosses every weather band toward the summit disk",
    palette: ["dusk violet", "ice blue", "sunrise coral"],
    styles: ["pixel-cluster-landscape", "mineral-line-engraving", "cyanotype-field-study"],
  },
  {
    slug: "beat-saber",
    gameTitle: "Beat Saber",
    category: "rhythm",
    completionCriterion: "Clear one Beat Saber track on Expert difficulty.",
    forms: ["two crossing motion bands", "three staggered pulse planes", "one dark depth field"],
    relationship: "the motion bands cross as the pulse planes advance through the field",
    palette: ["acid yellow", "electric violet", "midnight blue"],
    styles: ["screenprint-night", "pixel-cluster-landscape", "contour-atlas-ink"],
  },
  {
    slug: "hades",
    gameTitle: "Hades",
    category: "action-adventure",
    completionCriterion: "Escape the Underworld for the first time in Hades.",
    forms: ["one ember-red rising path", "three dark mineral gates", "a cool upper aperture"],
    relationship: "the ember path breaks through each mineral gate toward the aperture",
    palette: ["black clay", "ember red", "cool turquoise"],
    styles: ["ceramic-underglaze", "stained-glass-field", "matte-gouache-editorial"],
  },
  {
    slug: "elden-ring",
    gameTitle: "Elden Ring",
    category: "role-playing",
    completionCriterion: "Reach an ending in Elden Ring.",
    forms: ["three fractured land bands", "one empty dawn field", "a narrow entering path"],
    relationship: "the land bands circle the empty dawn as the path enters",
    palette: ["fog gray", "tarnished ochre", "deep moss"],
    styles: ["aquatint-atmosphere", "charcoal-pastel-weather", "wood-marquetry-landscape"],
  },
  {
    slug: "baldurs-gate-3",
    gameTitle: "Baldur’s Gate 3",
    category: "role-playing",
    completionCriterion: "Reach the ending credits in Baldur’s Gate 3.",
    forms: ["four distinct colored routes", "one shared bridge", "a broad open chasm"],
    relationship: "the four routes meet to make one bridge across the chasm",
    palette: ["luminous cobalt", "warm ochre", "soft magenta"],
    styles: ["luminous-ligne-claire", "relief-blockprint", "woven-tapestry-field"],
  },
] as const satisfies readonly VideoGameSeed[];
