import {
  defineVideoGameArtProfile,
  type CodeNativeVideoGameArtProfile,
  type VideoGameArtProfileSpec,
} from "./code-native-video-game-profile";

const profile = (
  slug: string,
  layoutId: VideoGameArtProfileSpec["layoutId"],
  paletteId: number,
  motifKinds: VideoGameArtProfileSpec["motifKinds"],
  variant: number,
): CodeNativeVideoGameArtProfile =>
  defineVideoGameArtProfile({ slug, layoutId, paletteId, motifKinds, variant });

export const codeNativeVideoGameArtProfiles = [
  profile("pong", "exchange", 0, ["horizon", "horizon", "ribbon"], 0),
  profile("space-invaders", "ascent", 1, ["stripe", "triangle", "horizon"], 1),
  profile("pac-man", "radial", 2, ["ring", "ring", "disk"], 2),
  profile("tetris", "terraced", 3, ["block", "block", "stripe"], 3),
  profile("super-mario-bros", "ascent", 4, ["ribbon", "block", "disk"], 4),
  profile("the-legend-of-zelda", "cleft", 5, ["triangle", "ribbon", "disk"], 0),
  profile("metroid", "orbit", 6, ["disk", "ring", "ring"], 1),
  profile("dragon-quest", "diagonal", 7, ["ribbon", "horizon", "arch"], 2),
  profile("simcity", "fork", 8, ["ribbon", "block", "oval"], 3),
  profile("prince-of-persia", "diagonal", 9, ["ribbon", "block", "arch"], 4),
  profile("the-secret-of-monkey-island", "orbit", 10, ["oval", "stripe", "ring"], 0),
  profile("sonic-the-hedgehog", "radial", 11, ["ribbon", "horizon", "stripe"], 1),
  profile("street-fighter-ii", "exchange", 1, ["arch", "arch", "disk"], 2),
  profile("doom", "cleft", 2, ["stripe", "block", "triangle"], 3),
  profile("myst", "threshold", 3, ["corner", "block", "oval"], 4),
  profile("chrono-trigger", "orbit", 4, ["ribbon", "disk", "horizon"], 0),
  profile("pokemon-red-version", "fork", 5, ["stripe", "horizon", "disk"], 1),
  profile("super-mario-64", "ascent", 6, ["block", "ring", "stripe"], 2),
  profile("tomb-raider", "threshold", 7, ["ribbon", "arch", "oval"], 3),
  profile("final-fantasy-vii", "radial", 8, ["ribbon", "ring", "disk"], 4),
  profile("castlevania-symphony-of-the-night", "exchange", 9, ["block", "corner", "disk"], 0),
  profile("half-life", "diagonal", 10, ["ribbon", "block", "stripe"], 1),
  profile("starcraft", "radial", 11, ["triangle", "block", "ring"], 2),
  profile("tony-hawks-pro-skater-2", "ascent", 0, ["arch", "triangle", "stripe"], 3),
  profile("the-sims", "threshold", 2, ["block", "corner", "disk"], 4),
  profile("halo-combat-evolved", "horizon", 3, ["disk", "ribbon", "arch"], 0),
  profile("the-elder-scrolls-iii-morrowind", "diagonal", 4, ["horizon", "stripe", "ribbon"], 1),
  profile("katamari-damacy", "radial", 5, ["disk", "block", "triangle"], 2),
  profile("shadow-of-the-colossus", "horizon", 6, ["disk", "horizon", "arch"], 3),
  profile("resident-evil-4", "diagonal", 7, ["disk", "ribbon", "block"], 4),
  profile("wii-sports", "exchange", 8, ["arch", "ribbon", "disk"], 0),
  profile("portal", "threshold", 9, ["arch", "ribbon", "triangle"], 1),
  profile("bioshock", "horizon", 10, ["stripe", "horizon", "disk"], 2),
  profile("mass-effect", "fork", 11, ["ribbon", "stripe", "disk"], 3),
  profile("braid", "exchange", 0, ["ribbon", "block", "arch"], 4),
  profile("minecraft", "terraced", 1, ["horizon", "arch", "disk"], 0),
  profile("dark-souls", "ascent", 3, ["disk", "arch", "corner"], 1),
  profile("journey", "diagonal", 4, ["ribbon", "horizon", "triangle"], 2),
  profile("papers-please", "cleft", 5, ["block", "block", "corner"], 3),
  profile("monument-valley", "orbit", 6, ["block", "corner", "stripe"], 4),
  profile("never-alone", "horizon", 7, ["stripe", "horizon", "arch"], 0),
  profile("rocket-league", "exchange", 8, ["ribbon", "disk", "triangle"], 1),
  profile("stardew-valley", "terraced", 9, ["stripe", "horizon", "disk"], 2),
  profile("the-legend-of-zelda-breath-of-the-wild", "ascent", 10, ["ribbon", "horizon", "arch"], 3),
  profile("hollow-knight", "cleft", 11, ["disk", "arch", "oval"], 4),
  profile("celeste", "diagonal", 0, ["ribbon", "stripe", "disk"], 0),
  profile("beat-saber", "exchange", 2, ["stripe", "ribbon", "block"], 1),
  profile("hades", "ascent", 3, ["disk", "ribbon", "corner"], 2),
  profile("elden-ring", "radial", 4, ["stripe", "disk", "ribbon"], 3),
  profile("baldurs-gate-3", "cleft", 5, ["ribbon", "stripe", "arch"], 4),
] as const;
