import type { VideoGameSeed } from "./video-game-record";

export const foundationalVideoGameSeeds = [
  {
    slug: "the-secret-of-monkey-island",
    gameTitle: "The Secret of Monkey Island",
    category: "adventure",
    completionCriterion: "Complete the story of The Secret of Monkey Island.",
    forms: ["one curved island mass", "a crooked mast line", "a moonlit question spiral"],
    relationship: "the mast and spiral lean toward opposite shores of the island",
    palette: ["ink black", "sea green", "moonlit peach"],
    styles: ["monoprint-ink-wash", "cut-paper-strata", "fresco-mineral-pigment"],
  },
  {
    slug: "sonic-the-hedgehog",
    gameTitle: "Sonic the Hedgehog",
    category: "platformer",
    completionCriterion: "Defeat the final boss and finish Sonic the Hedgehog.",
    forms: ["one kinetic looping ribbon", "three broad terrain masses", "an open horizon"],
    relationship: "the ribbon loops around the terrain and releases into the horizon",
    palette: ["electric teal", "warm chartreuse", "raspberry"],
    styles: ["risograph-overprint", "luminous-ligne-claire", "screenprint-night"],
  },
  {
    slug: "street-fighter-ii",
    gameTitle: "Street Fighter II",
    category: "fighting",
    completionCriterion: "Finish Arcade Mode with one fighter in Street Fighter II.",
    forms: ["two opposed force arcs", "one grounded circle", "a vertical field seam"],
    relationship: "the force arcs meet above the grounded circle without crossing the seam",
    palette: ["cobalt", "burnt orange", "smoky cream"],
    styles: ["stained-glass-field", "woven-tapestry-field", "mosaic-tesserae-field"],
  },
  {
    slug: "doom",
    gameTitle: "DOOM",
    category: "shooter",
    completionCriterion: "Complete all three original episodes of DOOM (1993).",
    forms: ["one hot fissure", "two dark monolith fields", "a pale advancing wedge"],
    relationship: "the pale wedge advances as the fissure opens between the monoliths",
    palette: ["coal black", "oxide red", "ash white"],
    styles: ["relief-blockprint", "matte-gouache-editorial", "screenprint-night"],
  },
  {
    slug: "myst",
    gameTitle: "Myst",
    category: "adventure",
    completionCriterion: "Reach an ending in Myst (1993).",
    forms: ["three impossible threshold planes", "one quiet aperture", "a distant mist field"],
    relationship: "the threshold planes align briefly around the aperture",
    palette: ["fog blue", "weathered copper", "violet gray"],
    styles: ["aquatint-atmosphere", "luminous-ligne-claire", "charcoal-pastel-weather"],
  },
  {
    slug: "chrono-trigger",
    gameTitle: "Chrono Trigger",
    category: "role-playing",
    completionCriterion: "Reach an ending in Chrono Trigger.",
    forms: ["one looped time river", "three overlapping era disks", "a green horizon"],
    relationship: "the river threads every era disk before returning to the horizon",
    palette: ["luminous cyan", "fern green", "sunset amber"],
    styles: ["luminous-ligne-claire", "charcoal-pastel-weather", "pixel-cluster-landscape"],
  },
  {
    slug: "pokemon-red-version",
    gameTitle: "Pokémon Red Version",
    category: "role-playing",
    completionCriterion: "Enter the Hall of Fame in Pokémon Red Version.",
    forms: ["three distinct habitat bands", "one companion-light seed", "a converging trail"],
    relationship: "the habitat bands converge as the companion-light follows the trail",
    palette: ["terracotta", "sage green", "deep blue"],
    styles: ["ceramic-underglaze", "stained-glass-field", "matte-gouache-editorial"],
  },
  {
    slug: "super-mario-64",
    gameTitle: "Super Mario 64",
    category: "platformer",
    completionCriterion: "Defeat the final Bowser encounter and see the credits in Super Mario 64.",
    forms: ["three floating planes", "one clear vertical axis", "an ascending spiral route"],
    relationship: "the planes spiral upward around the clear axis",
    palette: ["bright vermilion", "azure", "warm limestone"],
    styles: ["prismatic-geometric-symbolism", "relief-blockprint", "risograph-overprint"],
  },
  {
    slug: "tomb-raider",
    gameTitle: "Tomb Raider",
    category: "action-adventure",
    completionCriterion: "Complete the main story of Tomb Raider (1996).",
    forms: ["one solitary descending route", "three monumental stone apertures", "a blue cavern field"],
    relationship: "the route descends through the stone apertures toward the blue cavern",
    palette: ["charcoal", "weathered ochre", "cold cyan"],
    styles: ["charcoal-pastel-weather", "luminous-ligne-claire", "scratchboard-nocturne"],
  },
  {
    slug: "final-fantasy-vii",
    gameTitle: "Final Fantasy VII",
    category: "role-playing",
    completionCriterion: "Complete the main story of Final Fantasy VII.",
    forms: ["one pale life river", "a dark industrial ring", "one quiet flower disk"],
    relationship: "the life river rises through the industrial ring toward the flower disk",
    palette: ["near black", "phosphor green", "dusty rose"],
    styles: ["screenprint-night", "pixel-cluster-landscape", "contour-atlas-ink"],
  },
] as const satisfies readonly VideoGameSeed[];
