import type { VideoGameSeed } from "./video-game-record";

export const expansionVideoGameSeeds = [
  {
    slug: "castlevania-symphony-of-the-night",
    gameTitle: "Castlevania: Symphony of the Night",
    category: "action-adventure",
    completionCriterion: "Reach an ending in Castlevania: Symphony of the Night.",
    forms: ["two mirrored architectural masses", "one moonlit midpoint", "a folding vertical seam"],
    relationship: "the masses fold above and below the moonlit midpoint",
    palette: ["velvet black", "silver", "wine red"],
    styles: ["scratchboard-nocturne", "contour-atlas-ink", "cut-paper-strata"],
  },
  {
    slug: "half-life",
    gameTitle: "Half-Life",
    category: "shooter",
    completionCriterion: "Complete the story of Half-Life.",
    forms: ["one orange resonance wave", "three pale laboratory planes", "a fractured boundary"],
    relationship: "the resonance wave crosses the planes and fractures their shared boundary",
    palette: ["cyanotype blue", "safety orange", "paper white"],
    styles: ["cyanotype-field-study", "ceramic-underglaze", "relief-blockprint"],
  },
  {
    slug: "starcraft",
    gameTitle: "StarCraft",
    category: "strategy",
    completionCriterion: "Complete all three campaigns in StarCraft.",
    forms: ["three asymmetric cosmic territories", "one empty central star", "a branching frontier seam"],
    relationship: "the three territories converge around the empty star without merging",
    palette: ["ultramarine", "mineral violet", "antique gold"],
    styles: ["mosaic-tesserae-field", "thread-painted-embroidery", "mineral-line-engraving"],
  },
  {
    slug: "tony-hawks-pro-skater-2",
    gameTitle: "Tony Hawk’s Pro Skater 2",
    category: "sports",
    completionCriterion: "Complete Career Mode with one skater in Tony Hawk’s Pro Skater 2.",
    forms: ["one broad flight arc", "two abstract inclined masses", "a grounded offset shadow"],
    relationship: "the flight arc bridges both inclined masses above the offset shadow",
    palette: ["fluorescent coral", "royal purple", "concrete gray"],
    styles: ["risograph-overprint", "screenprint-night", "scratchboard-nocturne"],
  },
  {
    slug: "the-sims",
    gameTitle: "The Sims",
    category: "simulation",
    completionCriterion: "Grow one household’s net worth to 100,000 simoleons in The Sims.",
    forms: ["four domestic planes", "one shared warm center", "a slowly widening orbit"],
    relationship: "the domestic planes pivot independently around the shared center",
    palette: ["sage", "warm apricot", "slate blue"],
    styles: ["matte-gouache-editorial", "mosaic-tesserae-field", "pixel-cluster-landscape"],
  },
  {
    slug: "halo-combat-evolved",
    gameTitle: "Halo: Combat Evolved",
    category: "shooter",
    completionCriterion: "Complete the campaign of Halo: Combat Evolved.",
    forms: ["one small explorer-light", "a long terrain seam", "an immense interrupted sky arc"],
    relationship: "the explorer-light follows the terrain seam beneath the interrupted sky arc",
    palette: ["luminous jade", "deep indigo", "pale sand"],
    styles: ["luminous-ligne-claire", "plein-air-broken-color", "matte-gouache-editorial"],
  },
  {
    slug: "the-elder-scrolls-iii-morrowind",
    gameTitle: "The Elder Scrolls III: Morrowind",
    category: "role-playing",
    completionCriterion: "Complete the main quest of The Elder Scrolls III: Morrowind.",
    forms: ["one broad ash plain", "a weathered mineral pillar", "a quiet saline shore"],
    relationship: "a winding path connects the ash plain, mineral pillar, and shore",
    palette: ["ash gray", "rust ochre", "saline blue"],
    styles: ["fresco-mineral-pigment", "plein-air-broken-color", "aquatint-atmosphere"],
  },
  {
    slug: "katamari-damacy",
    gameTitle: "Katamari Damacy",
    category: "puzzle",
    completionCriterion: "Complete Make the Moon in Katamari Damacy (2004).",
    forms: ["one growing plain sphere", "three abstract color fields", "an outward radial burst"],
    relationship: "the sphere gathers the color fields into the radial burst",
    palette: ["leaf green", "coral", "cobalt"],
    styles: ["stained-glass-field", "woven-tapestry-field", "mosaic-tesserae-field"],
  },
  {
    slug: "shadow-of-the-colossus",
    gameTitle: "Shadow of the Colossus",
    category: "action-adventure",
    completionCriterion: "Defeat all sixteen colossi and finish Shadow of the Colossus (2005).",
    forms: ["one tiny traveling light", "a vast quiet plain", "one colossal weathered arch"],
    relationship: "the tiny light crosses the plain toward the weathered arch",
    palette: ["weathered green", "stone gray", "pale gold"],
    styles: ["plein-air-broken-color", "luminous-ligne-claire", "risograph-overprint"],
  },
  {
    slug: "resident-evil-4",
    gameTitle: "Resident Evil 4",
    category: "action-adventure",
    completionCriterion: "Complete the main story of Resident Evil 4 (2005).",
    forms: ["one amber lantern path", "two dark settlement masses", "a cold forest field"],
    relationship: "the lantern path bends between the settlement masses and enters the forest",
    palette: ["soot black", "lantern amber", "cold pine"],
    styles: ["charcoal-pastel-weather", "scratchboard-nocturne", "monoprint-ink-wash"],
  },
] as const satisfies readonly VideoGameSeed[];
