import type { VideoGameSeed } from "./video-game-record";

export const modernVideoGameSeeds = [
  {
    slug: "wii-sports",
    gameTitle: "Wii Sports",
    category: "sports",
    completionCriterion: "Complete one full event in each of the five Wii Sports disciplines.",
    forms: ["five broad gesture arcs", "one pale shared center", "a soft circular ground"],
    relationship: "the five gesture arcs return to the shared center",
    palette: ["linen white", "soft aqua", "tangerine"],
    styles: ["thread-painted-embroidery", "aquatint-atmosphere", "watercolor-naturalist-study"],
  },
  {
    slug: "portal",
    gameTitle: "Portal",
    category: "puzzle",
    completionCriterion: "Complete the story of Portal.",
    forms: ["two differently shaped thresholds", "one white traveling path", "a folded neutral plane"],
    relationship: "the white path passes through both thresholds across the folded plane",
    palette: ["warm white", "deep plum", "muted turquoise"],
    styles: ["prismatic-geometric-symbolism", "relief-blockprint", "risograph-overprint"],
  },
  {
    slug: "bioshock",
    gameTitle: "BioShock",
    category: "shooter",
    completionCriterion: "Complete the main story of BioShock.",
    forms: ["three bowed brass pressure bands", "one dark sea field", "a single rising bubble"],
    relationship: "the pressure bands bow beneath the sea while the bubble rises",
    palette: ["deep teal", "aged brass", "ivory"],
    styles: ["ceramic-underglaze", "stained-glass-field", "matte-gouache-editorial"],
  },
  {
    slug: "mass-effect",
    gameTitle: "Mass Effect",
    category: "role-playing",
    completionCriterion: "Complete the main story of Mass Effect.",
    forms: ["three diverging star routes", "one quiet decision point", "a dark cosmic basin"],
    relationship: "the star routes diverge and return to the same decision point",
    palette: ["luminous cyan", "deep violet", "warm white"],
    styles: ["luminous-ligne-claire", "matte-gouache-editorial", "fresco-mineral-pigment"],
  },
  {
    slug: "braid",
    gameTitle: "Braid",
    category: "puzzle",
    completionCriterion: "Complete the main story of Braid (2008).",
    forms: ["one woven time ribbon", "three broad landscape blocks", "a distant threshold"],
    relationship: "the ribbon reverses around the landscape blocks before crossing the threshold",
    palette: ["mulberry", "meadow green", "aged cream"],
    styles: ["woven-tapestry-field", "fresco-mineral-pigment", "thread-painted-embroidery"],
  },
  {
    slug: "minecraft",
    gameTitle: "Minecraft",
    category: "sandbox",
    completionCriterion: "Defeat the Ender Dragon in Minecraft.",
    forms: ["three large irregular mineral strata", "one sheltering canopy", "a warm interior light"],
    relationship: "the mineral strata transform into the canopy around the interior light",
    palette: ["granite gray", "lichen green", "hearth amber"],
    styles: ["pixel-cluster-landscape", "mineral-line-engraving", "cyanotype-field-study"],
  },
  {
    slug: "dark-souls",
    gameTitle: "Dark Souls",
    category: "role-playing",
    completionCriterion: "Reach an ending in Dark Souls (2011).",
    forms: ["one solitary ember", "three ascending shadow gates", "a worn mineral path"],
    relationship: "the ember rests before the gates while the path continues upward",
    palette: ["charcoal", "ember orange", "iron gray"],
    styles: ["mineral-line-engraving", "watercolor-naturalist-study", "ceramic-underglaze"],
  },
  {
    slug: "journey",
    gameTitle: "Journey",
    category: "adventure",
    completionCriterion: "Reach the mountain and finish Journey.",
    forms: ["one flowing sand ribbon", "three broad dune masses", "a split mountain light"],
    relationship: "the sand ribbon climbs the dunes toward the split mountain light",
    palette: ["rose sand", "deep teal", "pale lemon"],
    styles: ["cut-paper-strata", "luminous-ligne-claire", "prismatic-geometric-symbolism"],
  },
  {
    slug: "papers-please",
    gameTitle: "Papers, Please",
    category: "simulation",
    completionCriterion: "Reach an ending in Papers, Please.",
    forms: ["three blank document planes", "one narrow open passage", "a heavy horizontal pressure bar"],
    relationship: "the document planes press against the passage beneath the pressure bar",
    palette: ["paper gray", "brick red", "faded olive"],
    styles: ["relief-blockprint", "matte-gouache-editorial", "screenprint-night"],
  },
  {
    slug: "monument-valley",
    gameTitle: "Monument Valley",
    category: "puzzle",
    completionCriterion: "Complete all ten chapters of Monument Valley.",
    forms: ["three generic impossible planes", "one floating stair", "an open color field"],
    relationship: "the impossible planes turn around the floating stair",
    palette: ["dusty lilac", "desert peach", "deep turquoise"],
    styles: ["matte-gouache-editorial", "mosaic-tesserae-field", "pixel-cluster-landscape"],
  },
] as const satisfies readonly VideoGameSeed[];
