import type { FixtureCollection, PublishedBadgeFixture } from "./types";

const starterPackRef = {
  packId: "badge.catalogue.starter",
  version: "1.0.0-alpha.3",
  packDigest: "5b7135a70477130907050a9921da342e927980838ee9b1ae03a4d41809c6ffe3",
} as const;

export const starterBadges: readonly PublishedBadgeFixture[] = [
  {
    definitionId: "visited-yosemite",
    collectionId: "us-national-parks",
    title: "Yosemite",
    shortTitle: "Yosemite",
    criterion: "Visit Yosemite National Park",
    description: "Granite, river, and wonder—kept as one honest memory.",
    accessibleDescription: "An engraved Yosemite valley with El Capitan and a turquoise river.",
    sourceAssetHash: "21173941d3ad44ff0f245dcef0f1bbf2606b39163442afcc24777d442dda2ece",
    sourceUrl: "/yosemite-literal.png",
    visualEditionId: "visual.yosemite.literal.png.v1",
    renderRecipe: {
      version: 1,
      shape: "circle",
      material: "metal",
      borderColor: "#8f806c",
      borderWidth: 0.075,
      thickness: 0.13,
      relief: 0.032,
      crop: { x: 0.5, y: 0.5, scale: 1.03 },
    },
    packRef: starterPackRef,
    initialLifecycle: "planned",
    sayingSuggestions: [
      "Worth every switchback.",
      "Granite keeps the long view.",
      "The valley made time feel wide.",
    ],
  },
  {
    definitionId: "read-sapiens",
    collectionId: "books-read",
    title: "Read Sapiens",
    shortTitle: "Sapiens",
    criterion: "Finish reading Sapiens",
    description: "A long view of the stories people build together.",
    accessibleDescription: "Layered human silhouettes and paths flowing toward a distant horizon.",
    sourceAssetHash: "296c08b967b50dfbefdb8c8187f48943c11b3d3976d4d724fd248be335431729",
    sourceUrl: "/sapiens.png",
    visualEditionId: "visual.sapiens.journey.png.v1",
    renderRecipe: {
      version: 1,
      shape: "rectangle",
      material: "wool",
      borderColor: "#a65c3e",
      borderWidth: 0.055,
      thickness: 0.075,
      relief: 0.018,
      crop: { x: 0.5, y: 0.52, scale: 1.05 },
    },
    packRef: starterPackRef,
    initialLifecycle: "suggested",
    sayingSuggestions: ["One species, countless stories.", "A longer view of us.", "History got personal."],
  },
  {
    definitionId: "finished-bachelors-degree",
    collectionId: "life-milestones",
    title: "Bachelor's degree",
    shortTitle: "Degree",
    criterion: "Complete a bachelor's degree",
    description: "Years of patient work resolving into an open threshold.",
    accessibleDescription: "Ascending stone planes lead to a bright open doorway.",
    sourceAssetHash: "2af87c6a64740642f85ae37bc702a206c8c817531acb9d5aaf44269c5369a737",
    sourceUrl: "/bachelors-degree.png",
    visualEditionId: "visual.degree.threshold.png.v1",
    renderRecipe: {
      version: 1,
      shape: "shield",
      material: "enamel",
      borderColor: "#b8aa8e",
      borderWidth: 0.065,
      thickness: 0.11,
      relief: 0.026,
      crop: { x: 0.5, y: 0.48, scale: 1.08 },
    },
    packRef: starterPackRef,
    initialLifecycle: "suggested",
    sayingSuggestions: ["The door was built one day at a time.", "Long work, open horizon."],
  },
  {
    definitionId: "visited-all-us-national-parks",
    collectionId: "us-national-parks",
    title: "Every national park",
    shortTitle: "All parks",
    criterion: "Visit every park in the active U.S. National Parks catalogue",
    description: "A composite journey whose final picture was published before the last activation.",
    accessibleDescription: "Many American landscapes connected by one fine trail across a topographic field.",
    sourceAssetHash: "0b2ec88a2ee72eb85de9525020bfdc419fada5f1dfc6a6ea381df3ff32fa3c6c",
    sourceUrl: "/all-parks.png",
    visualEditionId: "visual.all-parks.constellation.png.v1",
    renderRecipe: {
      version: 1,
      shape: "circle",
      material: "enamel",
      borderColor: "#6f6657",
      borderWidth: 0.09,
      thickness: 0.14,
      relief: 0.035,
      crop: { x: 0.5, y: 0.5, scale: 1.02 },
    },
    packRef: starterPackRef,
    initialLifecycle: "suggested",
    sayingSuggestions: ["One country, a lifetime of wild places.", "The long way was the point."],
  },
] as const;

export const starterCollection: FixtureCollection = {
  collectionId: "personal-field-archive",
  title: "The Field Archive",
  eyebrow: "A private collection of places, pages, and passages",
  description: "Four finished artifacts to begin with. Only you decide when they become memories.",
  badges: starterBadges,
};

export type { FixtureCollection, PublishedBadgeFixture } from "./types";
