import type { FixtureCollection, PublishedBadgeFixture } from "./types";

export const STARTER_PACK_ID = "badge.catalogue.starter";

const starterPackRef = {
  packId: STARTER_PACK_ID,
  version: "1.0.0-alpha.3",
  packDigest: "5b7135a70477130907050a9921da342e927980838ee9b1ae03a4d41809c6ffe3",
} as const;

export const starterBadges: readonly PublishedBadgeFixture[] = [
  {
    definitionId: "visited-yosemite",
    collectionId: "us-national-parks",
    title: "Yosemite",
    shortTitle: "Yosemite",
    criterion: "Visit Yosemite National Park",
    description: "Granite, river, and wonder—kept as one honest memory.",
    accessibleDescription: "An engraved Yosemite valley with El Capitan and a turquoise river.",
    sourceAssetHash: "21173941d3ad44ff0f245dcef0f1bbf2606b39163442afcc24777d442dda2ece",
    sourceUrl: "/yosemite-literal.png",
    visualEditionId: "visual.yosemite.literal.png.v1",
    renderRecipe: {
      version: 1,
      shape: "circle",
      material: "metal",
      borderColor: "#8f806c",
      borderWidth: 0.075,
      thickness: 0.13,
      relief: 0.032,
      crop: { x: 0.5, y: 0.5, scale: 1.03 },
    },
    packRef: starterPackRef,
    initialLifecycle: "planned",
    defaultQuotationId: "john-muir-yosemite-temple-1868",
    historicalQuotations: [
      {
        id: "john-muir-yosemite-temple-1868",
        text: "It is by far the grandest of all the special temples of Nature I was ever permitted to enter.",
        person: "John Muir",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/John_Muir",
        sourceTitle: "Letters to a Friend, July 26, 1868",
        sourceUrl: "https://www.nps.gov/jomu/learn/historyculture/john-muir-quotes.htm",
      },
      {
        id: "john-muir-mountaineers-steep-trails",
        text: "Therefore we are all, in some sense, mountaineers, and going to the mountains is going home.",
        person: "John Muir",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/John_Muir",
        sourceTitle: "Steep Trails",
        sourceUrl: "https://www.nps.gov/jomu/learn/historyculture/john-muir-quotes.htm",
      },
      {
        id: "john-muir-mountains-calling-1873",
        text: "The mountains are calling and I must go.",
        person: "John Muir",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/John_Muir",
        sourceTitle: "Letter to Sarah Muir Galloway, September 3, 1873",
        sourceUrl: "https://www.nps.gov/jomu/learn/historyculture/john-muir-quotes.htm",
      },
    ],
  },
  {
    definitionId: "read-sapiens",
    collectionId: "books-read",
    title: "Read Sapiens",
    shortTitle: "Sapiens",
    criterion: "Finish reading Sapiens",
    description: "A long view of the stories people build together.",
    accessibleDescription: "Layered human silhouettes and paths flowing toward a distant horizon.",
    sourceAssetHash: "296c08b967b50dfbefdb8c8187f48943c11b3d3976d4d724fd248be335431729",
    sourceUrl: "/sapiens.png",
    visualEditionId: "visual.sapiens.journey.png.v1",
    renderRecipe: {
      version: 1,
      shape: "rectangle",
      material: "wool",
      borderColor: "#a65c3e",
      borderWidth: 0.055,
      thickness: 0.075,
      relief: 0.018,
      crop: { x: 0.5, y: 0.52, scale: 1.05 },
    },
    packRef: starterPackRef,
    initialLifecycle: "suggested",
    defaultQuotationId: "francis-bacon-reading-full-man",
    historicalQuotations: [
      {
        id: "francis-bacon-reading-full-man",
        text: "Reading maketh a full man; conference a ready man; and writing an exact man.",
        person: "Francis Bacon",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/Francis_Bacon",
        sourceTitle: "Of Studies",
        sourceUrl: "https://en.wikisource.org/wiki/The_Essays_of_Francis_Bacon/L_Of_Studies",
      },
      {
        id: "francis-bacon-histories-wise",
        text: "Histories make men wise; poets witty; the mathematics subtile; natural philosophy deep; moral grave; logic and rhetoric able to contend.",
        person: "Francis Bacon",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/Francis_Bacon",
        sourceTitle: "Of Studies",
        sourceUrl: "https://en.wikisource.org/wiki/The_Essays_of_Francis_Bacon/L_Of_Studies",
      },
      {
        id: "thomas-jefferson-cannot-live-books-1815",
        text: "I cannot live without books; but fewer will suffice where amusement, and not use, is the only future object.",
        person: "Thomas Jefferson",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/Thomas_Jefferson",
        sourceTitle: "Thomas Jefferson to John Adams, 10 June 1815",
        sourceUrl: "https://founders.archives.gov/documents/Jefferson/03-08-02-0425",
      },
    ],
  },
  {
    definitionId: "finished-bachelors-degree",
    collectionId: "life-milestones",
    title: "Bachelor's degree",
    shortTitle: "Degree",
    criterion: "Complete a bachelor's degree",
    description: "Years of patient work resolving into an open threshold.",
    accessibleDescription: "Ascending stone planes lead to a bright open doorway.",
    sourceAssetHash: "2af87c6a64740642f85ae37bc702a206c8c817531acb9d5aaf44269c5369a737",
    sourceUrl: "/bachelors-degree.png",
    visualEditionId: "visual.degree.threshold.png.v1",
    renderRecipe: {
      version: 1,
      shape: "shield",
      material: "enamel",
      borderColor: "#b8aa8e",
      borderWidth: 0.065,
      thickness: 0.11,
      relief: 0.026,
      crop: { x: 0.5, y: 0.48, scale: 1.08 },
    },
    packRef: starterPackRef,
    initialLifecycle: "suggested",
    defaultQuotationId: "frederick-douglass-no-struggle-1857",
    historicalQuotations: [
      {
        id: "frederick-douglass-no-struggle-1857",
        text: "If there is no struggle, there is no progress.",
        person: "Frederick Douglass",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/Frederick_Douglass",
        sourceTitle: "West India Emancipation address, August 3, 1857",
        sourceUrl: "https://www.archives.gov/exhibits/documented-rights/exhibit/section2/index.html",
      },
      {
        id: "booker-t-washington-success-obstacles-1901",
        text: "I have learned that success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome while trying to succeed.",
        person: "Booker T. Washington",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/Booker_T._Washington",
        sourceTitle: "Up From Slavery, Chapter II: Boyhood Days",
        sourceUrl: "https://en.wikisource.org/wiki/Up_From_Slavery/Chapter_2",
      },
      {
        id: "theodore-roosevelt-hard-to-fail-1899",
        text: "It is hard to fail, but it is worse never to have tried to succeed.",
        person: "Theodore Roosevelt",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/Theodore_Roosevelt",
        sourceTitle: "The Strenuous Life, Hamilton Club speech, April 10, 1899",
        sourceUrl: "https://www.gutenberg.org/files/58821/58821-h/58821-h.htm",
      },
    ],
  },
  {
    definitionId: "visited-all-us-national-parks",
    collectionId: "us-national-parks",
    title: "Every national park",
    shortTitle: "All parks",
    criterion: "Visit every park in the active U.S. National Parks catalogue",
    description: "A composite journey whose final picture was published before the last activation.",
    accessibleDescription: "Many American landscapes connected by one fine trail across a topographic field.",
    sourceAssetHash: "0b2ec88a2ee72eb85de9525020bfdc419fada5f1dfc6a6ea381df3ff32fa3c6c",
    sourceUrl: "/all-parks.png",
    visualEditionId: "visual.all-parks.constellation.png.v1",
    renderRecipe: {
      version: 1,
      shape: "circle",
      material: "enamel",
      borderColor: "#6f6657",
      borderWidth: 0.09,
      thickness: 0.14,
      relief: 0.035,
      crop: { x: 0.5, y: 0.5, scale: 1.02 },
    },
    packRef: starterPackRef,
    initialLifecycle: "suggested",
    defaultQuotationId: "john-muir-every-walk-nature",
    historicalQuotations: [
      {
        id: "john-muir-every-walk-nature",
        text: "But in every walk with Nature one receives far more than he seeks.",
        person: "John Muir",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/John_Muir",
        sourceTitle: "Steep Trails",
        sourceUrl: "https://www.nps.gov/jomu/learn/historyculture/john-muir-quotes.htm",
      },
      {
        id: "fdr-american-national-parks-1934",
        text: "There is nothing so American as our national parks.",
        person: "Franklin D. Roosevelt",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/Franklin_D._Roosevelt",
        sourceTitle: "Radio Address from Two Medicine Chalet, August 5, 1934",
        sourceUrl: "https://www.nps.gov/glac/learn/historyculture/fdr-radio-address.htm",
      },
      {
        id: "john-wesley-powell-naked-rock-1869",
        text: "The whole country is a region of naked rock of many colors, with cliffs and buttes about us and towering mountains in the distance.",
        person: "John Wesley Powell",
        personWikipediaUrl: "https://en.wikipedia.org/wiki/John_Wesley_Powell",
        sourceTitle: "Journal entry, July 28, 1869",
        sourceUrl: "https://www.nps.gov/care/learn/historyculture/explorers-and-surveyors.htm",
      },
    ],
  },
] as const;

export const starterCollection: FixtureCollection = {
  collectionId: "personal-field-archive",
  title: "The Field Archive",
  eyebrow: "A private collection of places, pages, and passages",
  description: "Four finished artifacts to begin with. Only you decide when they become memories.",
  badges: starterBadges,
};

export type { FixtureCollection, FixtureHistoricalQuotation, PublishedBadgeFixture } from "./types";
