// Generated by scripts/write-catalogue-pack-fixtures.mjs — do not edit by hand.
import { defineCataloguePackBadges } from "./catalogue-pack-types.js";

export const cataloguePackEducation = defineCataloguePackBadges(
  [
    [
      "finished-masters-degree",
      "Master's degree",
      "Complete a master's degree",
      "Honor the sustained study behind a master's degree with a spare threshold-and-horizon composition.",
      "Four broad underglaze-style forms show a stepped path leading through an open doorway toward a rising sun and a calm horizon.",
      "masters-degree.jpg",
      "4cb08d32e32de42443a099ee6e18fcc6826c58b78a74dd1d3129ee0f1234c131",
      "frederick-douglass-no-struggle-1857",
    ],
    [
      "earned-unl-degree",
      "University of Nebraska–Lincoln degree",
      "Complete a degree from the University of Nebraska–Lincoln",
      "Remember a University of Nebraska–Lincoln degree through two campus landmarks joined by the mall, without using university branding.",
      "Large stained-glass-style fields pair Mueller Tower with Love Library's white cupola across a broad campus mall and prairie sky.",
      "university-nebraska-lincoln-degree.jpg",
      "674fb3f45405860199335afe8c293c70348f88955b28b213d7cd52cb02c6b0cc",
      "theodore-roosevelt-hard-to-fail-1899",
    ],
  ],
  {
    setId: "life-milestones",
    assetDirectory: "life-milestones",
  },
);
