// Generated by scripts/write-catalogue-pack-fixtures.mjs — do not edit by hand.
import type { PackRef } from "@badge/pack-contract";

import { cataloguePackParksAThroughG } from "./catalogue-pack-parks-01.js";
import { cataloguePackParksHThroughZ } from "./catalogue-pack-parks-02.js";
import { cataloguePackStatesAThroughM } from "./catalogue-pack-states-01.js";
import { cataloguePackStatesNThroughZ } from "./catalogue-pack-states-02.js";
import { cataloguePackBooks01 } from "./catalogue-pack-books-01.js";
import { cataloguePackBooks02 } from "./catalogue-pack-books-02.js";
import { cataloguePackEducation } from "./catalogue-pack-education.js";
import { cataloguePackDiningBayArea } from "./catalogue-pack-dining-bay-area.js";
import { cataloguePackDiningNewYorkCity01 } from "./catalogue-pack-dining-nyc-01.js";
import { cataloguePackDiningNewYorkCity02 } from "./catalogue-pack-dining-nyc-02.js";
import { cataloguePackDiningWashingtonDc } from "./catalogue-pack-dining-dc.js";
import { CATALOGUE_PACK_ID, type CataloguePackBadgeFixture } from "./catalogue-pack-types.js";

export const cataloguePackBadges: readonly CataloguePackBadgeFixture[] = [
  ...cataloguePackParksAThroughG,
  ...cataloguePackParksHThroughZ,
  ...cataloguePackStatesAThroughM,
  ...cataloguePackStatesNThroughZ,
  ...cataloguePackBooks01,
  ...cataloguePackBooks02,
  ...cataloguePackEducation,
  ...cataloguePackDiningBayArea,
  ...cataloguePackDiningNewYorkCity01,
  ...cataloguePackDiningNewYorkCity02,
  ...cataloguePackDiningWashingtonDc,
];

export const cataloguePackRef: PackRef = {
  packId: CATALOGUE_PACK_ID,
  version: "1.0.0-alpha.1",
  packDigest: "e65bd849f8ef4e22745598a70e847bd32c9406fb06741368e43fd6851628ba46",
};

export {
  CATALOGUE_PACK_ID,
  CATALOGUE_RECORD_ID_PREFIX,
  defineCataloguePackBadges,
  catalogueRenderRecipeForSet,
} from "./catalogue-pack-types.js";
export type { CataloguePackBadgeFixture, CataloguePackBadgeRow } from "./catalogue-pack-types.js";
export { catalogueQuotationBanksBySetId } from "./catalogue-quotations.js";
