// Generated by scripts/write-new-discovery-fixtures.mjs from two bounded New York City partitions.
import { discoveryMichelinDiningNycPartOne } from "./discovery-michelin-dining-nyc-01.js";
import { discoveryMichelinDiningNycPartTwo } from "./discovery-michelin-dining-nyc-02.js";

export const discoveryMichelinDiningNyc = [
  ...discoveryMichelinDiningNycPartOne,
  ...discoveryMichelinDiningNycPartTwo,
] as const;
