// Generated by scripts/write-new-discovery-fixtures.mjs from the two education milestone authoring records.
// This Archive-safe file intentionally excludes prompts, source hashes, quotations, and authoring internals.
import { defineSourceStudyBadges } from "./discovery-source-studies.js";

export const discoveryEducationMilestones = defineSourceStudyBadges(
  [
    [
      "finished-masters-degree",
      "Master's degree",
      "Complete a master's degree",
      "Graduate education · advanced degree",
      "masters-degree.jpg",
      "Four broad underglaze-style forms show a stepped path leading through an open doorway toward a rising sun and a calm horizon.",
      [
        "master's degree",
        "master’s degree",
        "master degree",
        "graduate degree",
        "postgraduate degree",
        "MA",
        "MS",
        "MSc",
        "MBA",
      ],
    ],
    [
      "earned-unl-degree",
      "University of Nebraska–Lincoln degree",
      "Complete a degree from the University of Nebraska–Lincoln",
      "Lincoln, Nebraska · higher education",
      "university-nebraska-lincoln-degree.jpg",
      "Large stained-glass-style fields pair Mueller Tower with Love Library's white cupola across a broad campus mall and prairie sky.",
      [
        "UNL degree",
        "University of Nebraska Lincoln degree",
        "Nebraska degree",
        "University of Nebraska–Lincoln",
        "Lincoln campus degree",
      ],
    ],
  ],
  { setId: "life-milestones", assetDirectory: "life-milestones" },
);
