// Generated by scripts/write-new-discovery-fixtures.mjs from two bounded video-game partitions.
import { discoveryVideoGamesPartOne } from "./discovery-video-games-01.js";
import { discoveryVideoGamesPartTwo } from "./discovery-video-games-02.js";

export const discoveryVideoGames = [...discoveryVideoGamesPartOne, ...discoveryVideoGamesPartTwo] as const;
