// Generated by scripts/write-new-discovery-fixtures.mjs from the three source-checked regional restaurant editions.
import { discoveryMichelinDiningBayArea } from "./discovery-michelin-dining-bay-area.js";
import { discoveryMichelinDiningDc } from "./discovery-michelin-dining-dc.js";
import { discoveryMichelinDiningNyc } from "./discovery-michelin-dining-nyc.js";

export const discoveryMichelinDining = [
  ...discoveryMichelinDiningBayArea,
  ...discoveryMichelinDiningNyc,
  ...discoveryMichelinDiningDc,
] as const;
