import { defineSourceStudyBadges } from "./discovery-source-studies.js";

export const discoveryParksHThroughM = defineSourceStudyBadges([
  [
    "visited-haleakala",
    "Haleakalā",
    "Visit Haleakalā National Park",
    "Hawaii",
    "haleakala.jpg",
    "An original stained-glass field source study showing silversword plants inside the vast volcanic summit crater at sunrise.",
  ],
  [
    "visited-hawaii-volcanoes",
    "Hawai‘i Volcanoes",
    "Visit Hawai'i Volcanoes National Park",
    "Hawaii",
    "hawaii-volcanoes.jpg",
    "An original monoprint ink wash source study showing orange lava meeting black land beneath a rainforest edge.",
  ],
  [
    "visited-hot-springs",
    "Hot Springs",
    "Visit Hot Springs National Park",
    "Arkansas",
    "hot-springs.jpg",
    "An original contour atlas ink source study showing the real brick and stucco Bathhouse Row streetscape fronting a dry formal Central Avenue promenade, with wooded Hot Springs Mountain behind.",
  ],
  [
    "visited-indiana-dunes",
    "Indiana Dunes",
    "Visit Indiana Dunes National Park",
    "Indiana",
    "indiana-dunes.jpg",
    "An original mineral line engraving source study showing marram grass bending above Lake Michigan dunes at sunset.",
  ],
  [
    "visited-isle-royale",
    "Isle Royale",
    "Visit Isle Royale National Park",
    "Michigan",
    "isle-royale.jpg",
    "An original aquatint atmosphere source study showing a moose wading between boreal islands in cold Lake Superior dawn.",
  ],
  [
    "visited-joshua-tree",
    "Joshua Tree",
    "Visit Joshua Tree National Park",
    "California",
    "joshua-tree.jpg",
    "An original scratchboard nocturne source study showing Joshua trees and rounded boulders beneath a violet desert sky.",
  ],
  [
    "visited-katmai",
    "Katmai",
    "Visit Katmai National Park",
    "Alaska",
    "katmai.jpg",
    "An original matte gouache editorial source study showing a brown bear fishing from the broad low roughly six-foot horizontal lip of Brooks Falls as sockeye salmon leap.",
  ],
  [
    "visited-kenai-fjords",
    "Kenai Fjords",
    "Visit Kenai Fjords National Park",
    "Alaska",
    "kenai-fjords.jpg",
    "An original woven tapestry field source study showing ice flowing from Harding Icefield into a whale-filled fjord.",
  ],
  [
    "visited-kings-canyon",
    "Kings Canyon",
    "Visit Kings Canyon National Park",
    "California",
    "kings-canyon.jpg",
    "An original cut-paper strata source study showing the South Fork Kings River beneath immense granite canyon walls.",
  ],
  [
    "visited-kobuk-valley",
    "Kobuk Valley",
    "Visit Kobuk Valley National Park",
    "Alaska",
    "kobuk-valley.jpg",
    "An original cyanotype field study source study showing caribou crossing immense Arctic sand dunes under a low sun.",
  ],
  [
    "visited-lake-clark",
    "Lake Clark",
    "Visit Lake Clark National Park",
    "Alaska",
    "lake-clark.jpg",
    "An original fresco mineral pigment source study showing turquoise Lake Clark below smoking volcanoes and red tundra.",
  ],
  [
    "visited-lassen-volcanic",
    "Lassen Volcanic",
    "Visit Lassen Volcanic National Park",
    "California",
    "lassen-volcanic.jpg",
    "An original prismatic geometric symbolism source study showing Lassen Peak above steaming hydrothermal pools and mountain lake.",
  ],
  [
    "visited-mammoth-cave",
    "Mammoth Cave",
    "Visit Mammoth Cave National Park",
    "Kentucky",
    "mammoth-cave.jpg",
    "An original ceramic underglaze painting source study showing a historic lantern lighting one immense dry, broad limestone passage disappearing into darkness.",
  ],
  [
    "visited-mesa-verde",
    "Mesa Verde",
    "Visit Mesa Verde National Park",
    "Colorado",
    "mesa-verde.jpg",
    "An original wood marquetry landscape source study showing Cliff Palace held beneath a great sandstone alcove.",
  ],
  [
    "visited-mount-rainier",
    "Mount Rainier",
    "Visit Mount Rainier National Park",
    "Washington",
    "mount-rainier.jpg",
    "An original luminous ligne claire source study showing Mount Rainier above a meadow blazing with summer wildflowers.",
  ],
]);
