import { defineSourceStudyBadges } from "./discovery-source-studies.js";

export const discoveryParksNThroughZ = defineSourceStudyBadges([
  [
    "visited-national-park-american-samoa",
    "American Samoa",
    "Visit National Park of American Samoa",
    "American Samoa",
    "national-park-american-samoa.jpg",
    "An original pixel cluster landscape source study showing a flying fox crossing a steep rainforest island above coral water.",
  ],
  [
    "visited-new-river-gorge",
    "New River Gorge",
    "Visit New River Gorge National Park and Preserve",
    "West Virginia",
    "new-river-gorge.jpg",
    "An original thread-painted embroidery source study showing the New River Gorge Bridge spanning autumn forest and whitewater.",
  ],
  [
    "visited-north-cascades",
    "North Cascades",
    "Visit North Cascades National Park",
    "Washington",
    "north-cascades.jpg",
    "An original plein-air broken color source study showing jagged glacier peaks above a turquoise alpine lake.",
  ],
  [
    "visited-olympic",
    "Olympic",
    "Visit Olympic National Park",
    "Washington",
    "olympic.jpg",
    "An original relief block print source study showing moss-draped rainforest opening onto wild sea stacks and snowy peaks.",
  ],
  [
    "visited-petrified-forest",
    "Petrified Forest",
    "Visit Petrified Forest National Park",
    "Arizona",
    "petrified-forest.jpg",
    "An original stained-glass field source study showing rainbow petrified logs scattered across painted desert badlands.",
  ],
  [
    "visited-pinnacles",
    "Pinnacles",
    "Visit Pinnacles National Park",
    "California",
    "pinnacles.jpg",
    "An original monoprint ink wash source study showing a California condor soaring between volcanic spires at sunset.",
  ],
  [
    "visited-redwood",
    "Redwood",
    "Visit Redwood National Park",
    "California",
    "redwood.jpg",
    "An original contour atlas ink source study showing sunbeams descending through immense coast redwoods and fern.",
  ],
  [
    "visited-rocky-mountain",
    "Rocky Mountain",
    "Visit Rocky Mountain National Park",
    "Colorado",
    "rocky-mountain.jpg",
    "An original mineral line engraving source study showing elk crossing a golden alpine meadow beneath Longs Peak.",
  ],
  [
    "visited-saguaro",
    "Saguaro",
    "Visit Saguaro National Park",
    "Arizona",
    "saguaro.jpg",
    "An original aquatint atmosphere source study showing giant saguaros beneath a monsoon sunset and lightning.",
  ],
  [
    "visited-sequoia",
    "Sequoia",
    "Visit Sequoia National Park",
    "California",
    "sequoia.jpg",
    "An original scratchboard nocturne source study showing the living General Sherman sequoia, its extraordinarily massive fluted cinnamon trunk staying broad far upward and continuing visibly into an irregular high conifer crown of huge ascending limbs with fine scale-like evergreen sprays.",
  ],
  [
    "visited-shenandoah",
    "Shenandoah",
    "Visit Shenandoah National Park",
    "Virginia",
    "shenandoah.jpg",
    "An original matte gouache editorial source study showing Blue Ridge layers seen from Skyline Drive through autumn leaves.",
  ],
  [
    "visited-theodore-roosevelt",
    "Theodore Roosevelt",
    "Visit Theodore Roosevelt National Park",
    "North Dakota",
    "theodore-roosevelt.jpg",
    "An original woven tapestry field source study showing bison moving through Little Missouri badlands beneath a huge sky.",
  ],
  [
    "visited-virgin-islands",
    "Virgin Islands",
    "Visit Virgin Islands National Park",
    "Virgin Islands",
    "virgin-islands.jpg",
    "An original cut-paper strata source study showing a green hillside descending into Trunk Bay's clear reef water.",
  ],
  [
    "visited-voyageurs",
    "Voyageurs",
    "Visit Voyageurs National Park",
    "Minnesota",
    "voyageurs.jpg",
    "An original cyanotype field study source study showing a canoe threading pine islands beneath northern lights.",
  ],
  [
    "visited-white-sands",
    "White Sands",
    "Visit White Sands National Park",
    "New Mexico",
    "white-sands.jpg",
    "An original fresco mineral pigment source study showing white gypsum dunes curving beneath a pink-blue twilight.",
  ],
  [
    "visited-wind-cave",
    "Wind Cave",
    "Visit Wind Cave National Park",
    "South Dakota",
    "wind-cave.jpg",
    "An original prismatic geometric symbolism source study showing delicate honeycomb boxwork fins coating limestone walls below a sunlit bison prairie.",
  ],
  [
    "visited-wrangell-st-elias",
    "Wrangell–St. Elias",
    "Visit Wrangell-St. Elias National Park",
    "Alaska",
    "wrangell-st-elias.jpg",
    "An original ceramic underglaze painting source study showing vast icefields flowing between volcanic peaks toward a tiny historic mill.",
  ],
  [
    "visited-yellowstone",
    "Yellowstone",
    "Visit Yellowstone National Park",
    "Idaho, Montana, and Wyoming",
    "yellowstone.jpg",
    "An original wood marquetry landscape source study showing Grand Prismatic Spring glowing beyond a lone bison in steam.",
  ],
  [
    "visited-zion",
    "Zion",
    "Visit Zion National Park",
    "Utah",
    "zion.jpg",
    "An original pixel cluster landscape source study showing the Virgin River winding below towering red-and-cream canyon walls.",
  ],
]);
