// Generated by scripts/write-new-discovery-fixtures.mjs from two bounded Bay Area partitions.
import { discoveryMichelinDiningBayAreaPartOne } from "./discovery-michelin-dining-bay-area-01.js";
import { discoveryMichelinDiningBayAreaPartTwo } from "./discovery-michelin-dining-bay-area-02.js";

export const discoveryMichelinDiningBayArea = [
  ...discoveryMichelinDiningBayAreaPartOne,
  ...discoveryMichelinDiningBayAreaPartTwo,
] as const;
