import { defineSourceStudyBadges } from "./discovery-source-studies.js";

export const discoveryParksAThroughG = defineSourceStudyBadges([
  [
    "visited-acadia",
    "Acadia",
    "Visit Acadia National Park",
    "Maine",
    "acadia.jpg",
    "An original pixel cluster landscape source study showing dawn over Cadillac Mountain, granite ledges, spruce, and Atlantic islands.",
  ],
  [
    "visited-arches",
    "Arches",
    "Visit Arches National Park",
    "Utah",
    "arches.jpg",
    "An original thread-painted embroidery source study showing Delicate Arch above red fins at blue hour.",
  ],
  [
    "visited-badlands",
    "Badlands",
    "Visit Badlands National Park",
    "South Dakota",
    "badlands.jpg",
    "An original plein-air broken color source study showing striped pinnacles and mixed-grass prairie after a summer storm.",
  ],
  [
    "visited-big-bend",
    "Big Bend",
    "Visit Big Bend National Park",
    "Texas",
    "big-bend.jpg",
    "An original relief block print source study showing the Rio Grande bending through Santa Elena Canyon beneath stars.",
  ],
  [
    "visited-biscayne",
    "Biscayne",
    "Visit Biscayne National Park",
    "Florida",
    "biscayne.jpg",
    "An original stained-glass field source study showing a sea turtle gliding over coral gardens and seagrass.",
  ],
  [
    "visited-black-canyon-gunnison",
    "Black Canyon",
    "Visit Black Canyon of the Gunnison National Park",
    "Colorado",
    "black-canyon-gunnison.jpg",
    "An original monoprint ink wash source study showing a thin silver Gunnison River far below sheer dark walls.",
  ],
  [
    "visited-bryce-canyon",
    "Bryce Canyon",
    "Visit Bryce Canyon National Park",
    "Utah",
    "bryce-canyon.jpg",
    "An original contour atlas ink source study showing a sunrise amphitheater crowded with orange hoodoos.",
  ],
  [
    "visited-canyonlands",
    "Canyonlands",
    "Visit Canyonlands National Park",
    "Utah",
    "canyonlands.jpg",
    "An original mineral line engraving source study showing Mesa Arch framing a maze of canyons at first light.",
  ],
  [
    "visited-capitol-reef",
    "Capitol Reef",
    "Visit Capitol Reef National Park",
    "Utah",
    "capitol-reef.jpg",
    "An original aquatint atmosphere source study showing the Waterpocket Fold rolling past pale domes and orchard trees.",
  ],
  [
    "visited-carlsbad-caverns",
    "Carlsbad Caverns",
    "Visit Carlsbad Caverns National Park",
    "New Mexico",
    "carlsbad-caverns.jpg",
    "An original scratchboard nocturne source study showing the Big Room's immense mineral columns descending into darkness.",
  ],
  [
    "visited-channel-islands",
    "Channel Islands",
    "Visit Channel Islands National Park",
    "California",
    "channel-islands.jpg",
    "An original matte gouache editorial source study showing sea cliffs, kelp forest, and an island fox above clear Pacific water.",
  ],
  [
    "visited-congaree",
    "Congaree",
    "Visit Congaree National Park",
    "South Carolina",
    "congaree.jpg",
    "An original woven tapestry field source study showing a flooded old-growth forest mirrored in blackwater.",
  ],
  [
    "visited-crater-lake",
    "Crater Lake",
    "Visit Crater Lake National Park",
    "Oregon",
    "crater-lake.jpg",
    "An original cut-paper strata source study showing Wizard Island inside an impossibly blue caldera under snow.",
  ],
  [
    "visited-cuyahoga-valley",
    "Cuyahoga Valley",
    "Visit Cuyahoga Valley National Park",
    "Ohio",
    "cuyahoga-valley.jpg",
    "An original cyanotype field study source study showing Brandywine Falls' tall sixty-foot bridal-veil cascade dropping over a hard Berea Sandstone cap and Bedford and Cleveland shale into a narrow deciduous gorge.",
  ],
  [
    "visited-death-valley",
    "Death Valley",
    "Visit Death Valley National Park",
    "California and Nevada",
    "death-valley.jpg",
    "An original fresco mineral pigment source study showing Mesquite dunes and salt polygons beneath a violet mountain dusk.",
  ],
  [
    "visited-denali",
    "Denali",
    "Visit Denali National Park",
    "Alaska",
    "denali.jpg",
    "An original charcoal and pastel weather source study showing Denali rising above braided tundra rivers and autumn taiga.",
  ],
  [
    "visited-dry-tortugas",
    "Dry Tortugas",
    "Visit Dry Tortugas National Park",
    "Florida",
    "dry-tortugas.jpg",
    "An original screenprint night source study showing Fort Jefferson floating in turquoise water beneath circling frigatebirds.",
  ],
  [
    "visited-everglades",
    "Everglades",
    "Visit Everglades National Park",
    "Florida",
    "everglades.jpg",
    "An original mosaic tesserae field source study showing an alligator gliding through sawgrass under a roseate sky.",
  ],
  [
    "visited-gates-of-the-arctic",
    "Gates of the Arctic",
    "Visit Gates of the Arctic National Park",
    "Alaska",
    "gates-of-the-arctic.jpg",
    "An original fresco mineral pigment source study showing the Arrigetch peaks beyond a winding tundra river with no road in sight.",
  ],
  [
    "visited-gateway-arch",
    "Gateway Arch",
    "Visit Gateway Arch National Park",
    "Missouri and Illinois",
    "gateway-arch.jpg",
    "An original prismatic geometric symbolism source study showing the stainless arc rising over the Mississippi at blue hour.",
  ],
  [
    "visited-glacier-bay",
    "Glacier Bay",
    "Visit Glacier Bay National Park",
    "Alaska",
    "glacier-bay.jpg",
    "An original ceramic underglaze painting source study showing a tidewater glacier calving beyond a humpback whale's fluke.",
  ],
  [
    "visited-glacier",
    "Glacier",
    "Visit Glacier National Park",
    "Montana",
    "glacier.jpg",
    "An original wood marquetry landscape source study showing Hidden Lake below sharp peaks with a mountain goat on the overlook.",
  ],
  [
    "visited-grand-canyon",
    "Grand Canyon",
    "Visit Grand Canyon National Park",
    "Arizona",
    "grand-canyon.jpg",
    "An original scratchboard nocturne source study showing layer after layer of canyon opening around a distant Colorado River.",
  ],
  [
    "visited-grand-teton",
    "Grand Teton",
    "Visit Grand Teton National Park",
    "Wyoming",
    "grand-teton.jpg",
    "An original luminous ligne claire source study showing the Teton skyline reflected in still Snake River water.",
  ],
  [
    "visited-great-basin",
    "Great Basin",
    "Visit Great Basin National Park",
    "Nevada",
    "great-basin.jpg",
    "An original pixel cluster landscape source study showing ancient bristlecone pines twisting beneath the Milky Way.",
  ],
  [
    "visited-great-sand-dunes",
    "Great Sand Dunes",
    "Visit Great Sand Dunes National Park",
    "Colorado",
    "great-sand-dunes.jpg",
    "An original thread-painted embroidery source study showing wind-rippled dunes rising before snowbound Sangre de Cristo peaks.",
  ],
  [
    "visited-great-smoky-mountains",
    "Great Smoky Mountains",
    "Visit Great Smoky Mountains National Park",
    "North Carolina and Tennessee",
    "great-smoky-mountains.jpg",
    "An original plein-air broken color source study showing blue ridges dissolving through mist above a flame-azalea forest.",
  ],
  [
    "visited-guadalupe-mountains",
    "Guadalupe Mountains",
    "Visit Guadalupe Mountains National Park",
    "Texas",
    "guadalupe-mountains.jpg",
    "An original relief block print source study showing El Capitan's connected limestone reef escarpment forming a prow-like triangular sloping profile above Chihuahuan Desert flats under migrating clouds.",
  ],
]);
